;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 08/06/2021 22:27:49
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2872			GOTO	_main
$00A6	$	_init:
;Segment.ppas,4 :: 		begin
;Segment.ppas,5 :: 		TRISA:=$FF;
$00A6	$30FF			MOVLW	255
$00A7	$1303			BCF	STATUS, RP1
$00A8	$1683			BSF	STATUS, RP0
$00A9	$0085			MOVWF	TRISA
;Segment.ppas,6 :: 		TRISC:=$00;
$00AA	$0187			CLRF	TRISC, 1
;Segment.ppas,7 :: 		PORTC:=$3F;
$00AB	$303F			MOVLW	63
$00AC	$1283			BCF	STATUS, RP0
$00AD	$0087			MOVWF	PORTC
;Segment.ppas,8 :: 		ADCON1:=$06;
$00AE	$3006			MOVLW	6
$00AF	$1683			BSF	STATUS, RP0
$00B0	$009F			MOVWF	ADCON1
$00B1	$	Segment_L_0:
;Segment.ppas,9 :: 		end;
$00B1	$0008			RETURN
$0004	$	_masque:
;Segment.ppas,11 :: 		begin
;Segment.ppas,13 :: 		1: Masque:=$06;
$0004	$	Segment_L_4:
$0004	$1303			BCF	STATUS, RP1
$0005	$1283			BCF	STATUS, RP0
$0006	$0821			MOVF	FARG_Masque, 0
$0007	$3A01			XORLW	1
$0008	$1D03			BTFSS	STATUS, Z
$0009	$280D			GOTO	Segment_L_5
$000A	$	Segment_L_3:
$000A	$3006			MOVLW	6
$000B	$00A2			MOVWF	_masque_local_result
$000C	$286F			GOTO	Segment_L_2
$000D	$	Segment_L_5:
;Segment.ppas,14 :: 		2: Masque:=$5B;
$000D	$	Segment_L_7:
$000D	$0821			MOVF	FARG_Masque, 0
$000E	$3A02			XORLW	2
$000F	$1D03			BTFSS	STATUS, Z
$0010	$2814			GOTO	Segment_L_8
$0011	$	Segment_L_6:
$0011	$305B			MOVLW	91
$0012	$00A2			MOVWF	_masque_local_result
$0013	$286F			GOTO	Segment_L_2
$0014	$	Segment_L_8:
;Segment.ppas,15 :: 		3: Masque:=$4F;
$0014	$	Segment_L_10:
$0014	$0821			MOVF	FARG_Masque, 0
$0015	$3A03			XORLW	3
$0016	$1D03			BTFSS	STATUS, Z
$0017	$281B			GOTO	Segment_L_11
$0018	$	Segment_L_9:
$0018	$304F			MOVLW	79
$0019	$00A2			MOVWF	_masque_local_result
$001A	$286F			GOTO	Segment_L_2
$001B	$	Segment_L_11:
;Segment.ppas,16 :: 		4: Masque:=$66;
$001B	$	Segment_L_13:
$001B	$0821			MOVF	FARG_Masque, 0
$001C	$3A04			XORLW	4
$001D	$1D03			BTFSS	STATUS, Z
$001E	$2822			GOTO	Segment_L_14
$001F	$	Segment_L_12:
$001F	$3066			MOVLW	102
$0020	$00A2			MOVWF	_masque_local_result
$0021	$286F			GOTO	Segment_L_2
$0022	$	Segment_L_14:
;Segment.ppas,17 :: 		5 :Masque:=$6D;
$0022	$	Segment_L_16:
$0022	$0821			MOVF	FARG_Masque, 0
$0023	$3A05			XORLW	5
$0024	$1D03			BTFSS	STATUS, Z
$0025	$2829			GOTO	Segment_L_17
$0026	$	Segment_L_15:
$0026	$306D			MOVLW	109
$0027	$00A2			MOVWF	_masque_local_result
$0028	$286F			GOTO	Segment_L_2
$0029	$	Segment_L_17:
;Segment.ppas,18 :: 		6 :Masque:=$7D;
$0029	$	Segment_L_19:
$0029	$0821			MOVF	FARG_Masque, 0
$002A	$3A06			XORLW	6
$002B	$1D03			BTFSS	STATUS, Z
$002C	$2830			GOTO	Segment_L_20
$002D	$	Segment_L_18:
$002D	$307D			MOVLW	125
$002E	$00A2			MOVWF	_masque_local_result
$002F	$286F			GOTO	Segment_L_2
$0030	$	Segment_L_20:
;Segment.ppas,19 :: 		7 :Masque:=$07;
$0030	$	Segment_L_22:
$0030	$0821			MOVF	FARG_Masque, 0
$0031	$3A07			XORLW	7
$0032	$1D03			BTFSS	STATUS, Z
$0033	$2837			GOTO	Segment_L_23
$0034	$	Segment_L_21:
$0034	$3007			MOVLW	7
$0035	$00A2			MOVWF	_masque_local_result
$0036	$286F			GOTO	Segment_L_2
$0037	$	Segment_L_23:
;Segment.ppas,20 :: 		8 :Masque:=$7F;
$0037	$	Segment_L_25:
$0037	$0821			MOVF	FARG_Masque, 0
$0038	$3A08			XORLW	8
$0039	$1D03			BTFSS	STATUS, Z
$003A	$283E			GOTO	Segment_L_26
$003B	$	Segment_L_24:
$003B	$307F			MOVLW	127
$003C	$00A2			MOVWF	_masque_local_result
$003D	$286F			GOTO	Segment_L_2
$003E	$	Segment_L_26:
;Segment.ppas,21 :: 		9 :Masque:=$6F;
$003E	$	Segment_L_28:
$003E	$0821			MOVF	FARG_Masque, 0
$003F	$3A09			XORLW	9
$0040	$1D03			BTFSS	STATUS, Z
$0041	$2845			GOTO	Segment_L_29
$0042	$	Segment_L_27:
$0042	$306F			MOVLW	111
$0043	$00A2			MOVWF	_masque_local_result
$0044	$286F			GOTO	Segment_L_2
$0045	$	Segment_L_29:
;Segment.ppas,22 :: 		10:Masque:=$77;
$0045	$	Segment_L_31:
$0045	$0821			MOVF	FARG_Masque, 0
$0046	$3A0A			XORLW	10
$0047	$1D03			BTFSS	STATUS, Z
$0048	$284C			GOTO	Segment_L_32
$0049	$	Segment_L_30:
$0049	$3077			MOVLW	119
$004A	$00A2			MOVWF	_masque_local_result
$004B	$286F			GOTO	Segment_L_2
$004C	$	Segment_L_32:
;Segment.ppas,23 :: 		11:Masque:=$7C;
$004C	$	Segment_L_34:
$004C	$0821			MOVF	FARG_Masque, 0
$004D	$3A0B			XORLW	11
$004E	$1D03			BTFSS	STATUS, Z
$004F	$2853			GOTO	Segment_L_35
$0050	$	Segment_L_33:
$0050	$307C			MOVLW	124
$0051	$00A2			MOVWF	_masque_local_result
$0052	$286F			GOTO	Segment_L_2
$0053	$	Segment_L_35:
;Segment.ppas,24 :: 		12:Masque:=$58;
$0053	$	Segment_L_37:
$0053	$0821			MOVF	FARG_Masque, 0
$0054	$3A0C			XORLW	12
$0055	$1D03			BTFSS	STATUS, Z
$0056	$285A			GOTO	Segment_L_38
$0057	$	Segment_L_36:
$0057	$3058			MOVLW	88
$0058	$00A2			MOVWF	_masque_local_result
$0059	$286F			GOTO	Segment_L_2
$005A	$	Segment_L_38:
;Segment.ppas,25 :: 		13:Masque:=$5E;
$005A	$	Segment_L_40:
$005A	$0821			MOVF	FARG_Masque, 0
$005B	$3A0D			XORLW	13
$005C	$1D03			BTFSS	STATUS, Z
$005D	$2861			GOTO	Segment_L_41
$005E	$	Segment_L_39:
$005E	$305E			MOVLW	94
$005F	$00A2			MOVWF	_masque_local_result
$0060	$286F			GOTO	Segment_L_2
$0061	$	Segment_L_41:
;Segment.ppas,26 :: 		14:Masque:=$79;
$0061	$	Segment_L_43:
$0061	$0821			MOVF	FARG_Masque, 0
$0062	$3A0E			XORLW	14
$0063	$1D03			BTFSS	STATUS, Z
$0064	$2868			GOTO	Segment_L_44
$0065	$	Segment_L_42:
$0065	$3079			MOVLW	121
$0066	$00A2			MOVWF	_masque_local_result
$0067	$286F			GOTO	Segment_L_2
$0068	$	Segment_L_44:
;Segment.ppas,27 :: 		15:Masque:=$71;
$0068	$	Segment_L_46:
$0068	$0821			MOVF	FARG_Masque, 0
$0069	$3A0F			XORLW	15
$006A	$1D03			BTFSS	STATUS, Z
$006B	$286F			GOTO	Segment_L_47
$006C	$	Segment_L_45:
$006C	$3071			MOVLW	113
$006D	$00A2			MOVWF	_masque_local_result
$006E	$286F			GOTO	Segment_L_2
$006F	$	Segment_L_47:
$006F	$	Segment_L_2:
;Segment.ppas,28 :: 		end;
$006F	$	Segment_L_1:
;Segment.ppas,29 :: 		end;
$006F	$0822			MOVF	_masque_local_result, 0
$0070	$00F0			MOVWF	STACK_0
$0071	$0008			RETURN
$0072	$	_main:
;Segment.ppas,31 :: 		begin
;Segment.ppas,32 :: 		Init();
$0072	$20A6			CALL	_init
;Segment.ppas,33 :: 		i:=1;
$0073	$3001			MOVLW	1
$0074	$1283			BCF	STATUS, RP0
$0075	$00A0			MOVWF	_i
;Segment.ppas,34 :: 		while(1) do
$0076	$	Segment_L_50:
;Segment.ppas,37 :: 		if(PORTA.1=0) then
$0076	$0805			MOVF	PORTA, 0
$0077	$00F1			MOVWF	STACK_1
$0078	$3000			MOVLW	0
$0079	$18F1			BTFSC	STACK_1, 1
$007A	$3001			MOVLW	1
$007B	$00F1			MOVWF	STACK_1
$007C	$0871			MOVF	STACK_1, 0
$007D	$3A00			XORLW	0
$007E	$1D03			BTFSS	STATUS, Z
$007F	$28A4			GOTO	Segment_L_55
$0080	$	Segment_L_54:
;Segment.ppas,40 :: 		PORTC:=Masque(i);
$0080	$0820			MOVF	_i, 0
$0081	$00A1			MOVWF	FARG_Masque
$0082	$2004			CALL	_masque
$0083	$0870			MOVF	STACK_0, 0
$0084	$0087			MOVWF	PORTC
;Segment.ppas,42 :: 		delay_ms(1000);
$0085	$300B			MOVLW	11
$0086	$00FC			MOVWF	STACK_12
$0087	$30FF			MOVLW	255
$0088	$00FB			MOVWF	STACK_11
$0089	$30FF			MOVLW	255
$008A	$00FA			MOVWF	STACK_10
$008B	$0BFC			DECFSZ	STACK_12, F
$008C	$288E			GOTO	$+2
$008D	$2895			GOTO	$+8
$008E	$0BFB			DECFSZ	STACK_11, F
$008F	$2891			GOTO	$+2
$0090	$2894			GOTO	$+4
$0091	$0BFA			DECFSZ	STACK_10, F
$0092	$2891			GOTO	$-1
$0093	$288E			GOTO	$-5
$0094	$288B			GOTO	$-9
$0095	$3033			MOVLW	51
$0096	$00FB			MOVWF	STACK_11
$0097	$30FF			MOVLW	255
$0098	$00FA			MOVWF	STACK_10
$0099	$0BFB			DECFSZ	STACK_11, F
$009A	$289C			GOTO	$+2
$009B	$289F			GOTO	$+4
$009C	$0BFA			DECFSZ	STACK_10, F
$009D	$289C			GOTO	$-1
$009E	$2899			GOTO	$-5
$009F	$3088			MOVLW	136
$00A0	$00FA			MOVWF	STACK_10
$00A1	$0BFA			DECFSZ	STACK_10, F
$00A2	$28A1			GOTO	$-1
;Segment.ppas,43 :: 		i:=i+1;
$00A3	$0AA0			INCF	_i, 1
;Segment.ppas,44 :: 		end;
$00A4	$	Segment_L_55:
$00A4	$	Segment_L_56:
;Segment.ppas,45 :: 		end;
$00A4	$2876			GOTO	Segment_L_50
;Segment.ppas,46 :: 		end.
$00A5	$28A5			GOTO	$
