;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 06/06/2021 10:38:07
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$06CF	$	_delay_1us:
;delays.ppas,11 :: 		begin
;delays.ppas,12 :: 		Delay_us(1);
$06CF	$0000			NOP
$06D0	$0000			NOP
$06D1	$	delays_L_1:
;delays.ppas,13 :: 		end;
$06D1	$0008			RETURN
$0697	$	_delay_5500us:
;delays.ppas,41 :: 		begin
;delays.ppas,42 :: 		Delay_us(5500);
$0697	$300F			MOVLW	15
$0698	$1303			BCF	STATUS, RP1
$0699	$1283			BCF	STATUS, RP0
$069A	$00FB			MOVWF	STACK_11
$069B	$30FF			MOVLW	255
$069C	$00FA			MOVWF	STACK_10
$069D	$0BFB			DECFSZ	STACK_11, F
$069E	$2EA0			GOTO	$+2
$069F	$2EA3			GOTO	$+4
$06A0	$0BFA			DECFSZ	STACK_10, F
$06A1	$2EA0			GOTO	$-1
$06A2	$2E9D			GOTO	$-5
$06A3	$303E			MOVLW	62
$06A4	$00FA			MOVWF	STACK_10
$06A5	$0BFA			DECFSZ	STACK_10, F
$06A6	$2EA5			GOTO	$-1
$06A7	$0000			NOP
$06A8	$	delays_L_7:
;delays.ppas,43 :: 		end;
$06A8	$0008			RETURN
$06C8	$	_delay_50us:
;delays.ppas,26 :: 		begin
;delays.ppas,27 :: 		Delay_us(50);
$06C8	$3021			MOVLW	33
$06C9	$1303			BCF	STATUS, RP1
$06CA	$1283			BCF	STATUS, RP0
$06CB	$00FA			MOVWF	STACK_10
$06CC	$0BFA			DECFSZ	STACK_10, F
$06CD	$2ECC			GOTO	$-1
$06CE	$	delays_L_4:
;delays.ppas,28 :: 		end;
$06CE	$0008			RETURN
$0364	$	_lcd_cmd:
;lcd.ppas,19 :: 		
;lcd.ppas,20 :: 		
$0364	$1303			BCF	STATUS, RP1
$0365	$1283			BCF	STATUS, RP0
$0366	$0821			MOVF	lcd_ctrlport_address, 0
$0367	$0084			MOVWF	FSR
;lcd.ppas,22 :: 		
$0368	$0922			COMF	lcd____menable, W
$0369	$00F0			MOVWF	STACK_0
$036A	$0870			MOVF	STACK_0, 0
$036B	$0580			ANDWF	INDF, 1
;lcd.ppas,23 :: 		
$036C	$0923			COMF	lcd____mrs, W
$036D	$00F0			MOVWF	STACK_0
$036E	$0870			MOVF	STACK_0, 0
$036F	$0580			ANDWF	INDF, 1
;lcd.ppas,25 :: 		
$0370	$0824			MOVF	lcd_dataport_address, 0
$0371	$0084			MOVWF	FSR
;lcd.ppas,26 :: 		
$0372	$0826			MOVF	lcd____mdb6, 0
$0373	$0425			IORWF	lcd____mdb7, 0
$0374	$00F0			MOVWF	STACK_0
$0375	$0827			MOVF	lcd____mdb5, 0
$0376	$04F0			IORWF	STACK_0, 1
$0377	$0828			MOVF	lcd____mdb4, 0
$0378	$04F0			IORWF	STACK_0, 1
$0379	$09F0			COMF	STACK_0, F
$037A	$0870			MOVF	STACK_0, 0
$037B	$0580			ANDWF	INDF, 1
;lcd.ppas,28 :: 		
$037C	$3000			MOVLW	0
$037D	$1BE1			BTFSC	FARG_Lcd_Cmd, 7
$037E	$3001			MOVLW	1
$037F	$00F1			MOVWF	STACK_1
$0380	$0871			MOVF	STACK_1, 0
$0381	$3A01			XORLW	1
$0382	$1D03			BTFSS	STATUS, Z
$0383	$2B86			GOTO	lcd_L_2
$0384	$	lcd_L_1:
;lcd.ppas,29 :: 		
$0384	$0825			MOVF	lcd____mdb7, 0
$0385	$0480			IORWF	INDF, 1
$0386	$	lcd_L_2:
$0386	$	lcd_L_3:
;lcd.ppas,30 :: 		
$0386	$3000			MOVLW	0
$0387	$1B61			BTFSC	FARG_Lcd_Cmd, 6
$0388	$3001			MOVLW	1
$0389	$00F1			MOVWF	STACK_1
$038A	$0871			MOVF	STACK_1, 0
$038B	$3A01			XORLW	1
$038C	$1D03			BTFSS	STATUS, Z
$038D	$2B90			GOTO	lcd_L_5
$038E	$	lcd_L_4:
;lcd.ppas,31 :: 		
$038E	$0826			MOVF	lcd____mdb6, 0
$038F	$0480			IORWF	INDF, 1
$0390	$	lcd_L_5:
$0390	$	lcd_L_6:
;lcd.ppas,32 :: 		
$0390	$3000			MOVLW	0
$0391	$1AE1			BTFSC	FARG_Lcd_Cmd, 5
$0392	$3001			MOVLW	1
$0393	$00F1			MOVWF	STACK_1
$0394	$0871			MOVF	STACK_1, 0
$0395	$3A01			XORLW	1
$0396	$1D03			BTFSS	STATUS, Z
$0397	$2B9A			GOTO	lcd_L_8
$0398	$	lcd_L_7:
;lcd.ppas,33 :: 		
$0398	$0827			MOVF	lcd____mdb5, 0
$0399	$0480			IORWF	INDF, 1
$039A	$	lcd_L_8:
$039A	$	lcd_L_9:
;lcd.ppas,34 :: 		
$039A	$3000			MOVLW	0
$039B	$1A61			BTFSC	FARG_Lcd_Cmd, 4
$039C	$3001			MOVLW	1
$039D	$00F1			MOVWF	STACK_1
$039E	$0871			MOVF	STACK_1, 0
$039F	$3A01			XORLW	1
$03A0	$1D03			BTFSS	STATUS, Z
$03A1	$2BA4			GOTO	lcd_L_11
$03A2	$	lcd_L_10:
;lcd.ppas,35 :: 		
$03A2	$0828			MOVF	lcd____mdb4, 0
$03A3	$0480			IORWF	INDF, 1
$03A4	$	lcd_L_11:
$03A4	$	lcd_L_12:
;lcd.ppas,37 :: 		
$03A4	$0821			MOVF	lcd_ctrlport_address, 0
$03A5	$0084			MOVWF	FSR
;lcd.ppas,38 :: 		
$03A6	$0829			MOVF	lcd_lcdcmd_status, 0
$03A7	$3A01			XORLW	1
$03A8	$1D03			BTFSS	STATUS, Z
$03A9	$2BAF			GOTO	lcd_L_14
$03AA	$	lcd_L_13:
;lcd.ppas,39 :: 		
$03AA	$0923			COMF	lcd____mrs, W
$03AB	$00F0			MOVWF	STACK_0
$03AC	$0870			MOVF	STACK_0, 0
$03AD	$0580			ANDWF	INDF, 1
$03AE	$2BB1			GOTO	lcd_L_15
;lcd.ppas,40 :: 		
$03AF	$	lcd_L_14:
;lcd.ppas,41 :: 		
$03AF	$0823			MOVF	lcd____mrs, 0
$03B0	$0480			IORWF	INDF, 1
$03B1	$	lcd_L_15:
;lcd.ppas,43 :: 		
$03B1	$0822			MOVF	lcd____menable, 0
$03B2	$0480			IORWF	INDF, 1
;lcd.ppas,44 :: 		
$03B3	$26CF			CALL	_delay_1us
;lcd.ppas,45 :: 		
$03B4	$0922			COMF	lcd____menable, W
$03B5	$00F0			MOVWF	STACK_0
$03B6	$0870			MOVF	STACK_0, 0
$03B7	$0580			ANDWF	INDF, 1
;lcd.ppas,47 :: 		
$03B8	$0923			COMF	lcd____mrs, W
$03B9	$00F0			MOVWF	STACK_0
$03BA	$0870			MOVF	STACK_0, 0
$03BB	$0580			ANDWF	INDF, 1
;lcd.ppas,49 :: 		
$03BC	$0824			MOVF	lcd_dataport_address, 0
$03BD	$0084			MOVWF	FSR
;lcd.ppas,50 :: 		
$03BE	$0826			MOVF	lcd____mdb6, 0
$03BF	$0425			IORWF	lcd____mdb7, 0
$03C0	$00F0			MOVWF	STACK_0
$03C1	$0827			MOVF	lcd____mdb5, 0
$03C2	$04F0			IORWF	STACK_0, 1
$03C3	$0828			MOVF	lcd____mdb4, 0
$03C4	$04F0			IORWF	STACK_0, 1
$03C5	$09F0			COMF	STACK_0, F
$03C6	$0870			MOVF	STACK_0, 0
$03C7	$0580			ANDWF	INDF, 1
;lcd.ppas,52 :: 		
$03C8	$3000			MOVLW	0
$03C9	$19E1			BTFSC	FARG_Lcd_Cmd, 3
$03CA	$3001			MOVLW	1
$03CB	$00F1			MOVWF	STACK_1
$03CC	$0871			MOVF	STACK_1, 0
$03CD	$3A01			XORLW	1
$03CE	$1D03			BTFSS	STATUS, Z
$03CF	$2BD2			GOTO	lcd_L_17
$03D0	$	lcd_L_16:
;lcd.ppas,53 :: 		
$03D0	$0825			MOVF	lcd____mdb7, 0
$03D1	$0480			IORWF	INDF, 1
$03D2	$	lcd_L_17:
$03D2	$	lcd_L_18:
;lcd.ppas,54 :: 		
$03D2	$3000			MOVLW	0
$03D3	$1961			BTFSC	FARG_Lcd_Cmd, 2
$03D4	$3001			MOVLW	1
$03D5	$00F1			MOVWF	STACK_1
$03D6	$0871			MOVF	STACK_1, 0
$03D7	$3A01			XORLW	1
$03D8	$1D03			BTFSS	STATUS, Z
$03D9	$2BDC			GOTO	lcd_L_20
$03DA	$	lcd_L_19:
;lcd.ppas,55 :: 		
$03DA	$0826			MOVF	lcd____mdb6, 0
$03DB	$0480			IORWF	INDF, 1
$03DC	$	lcd_L_20:
$03DC	$	lcd_L_21:
;lcd.ppas,56 :: 		
$03DC	$3000			MOVLW	0
$03DD	$18E1			BTFSC	FARG_Lcd_Cmd, 1
$03DE	$3001			MOVLW	1
$03DF	$00F1			MOVWF	STACK_1
$03E0	$0871			MOVF	STACK_1, 0
$03E1	$3A01			XORLW	1
$03E2	$1D03			BTFSS	STATUS, Z
$03E3	$2BE6			GOTO	lcd_L_23
$03E4	$	lcd_L_22:
;lcd.ppas,57 :: 		
$03E4	$0827			MOVF	lcd____mdb5, 0
$03E5	$0480			IORWF	INDF, 1
$03E6	$	lcd_L_23:
$03E6	$	lcd_L_24:
;lcd.ppas,58 :: 		
$03E6	$3001			MOVLW	1
$03E7	$0561			ANDWF	FARG_Lcd_Cmd, 0
$03E8	$00F1			MOVWF	STACK_1
$03E9	$0871			MOVF	STACK_1, 0
$03EA	$3A01			XORLW	1
$03EB	$1D03			BTFSS	STATUS, Z
$03EC	$2BEF			GOTO	lcd_L_26
$03ED	$	lcd_L_25:
;lcd.ppas,59 :: 		
$03ED	$0828			MOVF	lcd____mdb4, 0
$03EE	$0480			IORWF	INDF, 1
$03EF	$	lcd_L_26:
$03EF	$	lcd_L_27:
;lcd.ppas,61 :: 		
$03EF	$0821			MOVF	lcd_ctrlport_address, 0
$03F0	$0084			MOVWF	FSR
;lcd.ppas,62 :: 		
$03F1	$0829			MOVF	lcd_lcdcmd_status, 0
$03F2	$3A01			XORLW	1
$03F3	$1D03			BTFSS	STATUS, Z
$03F4	$2BFA			GOTO	lcd_L_29
$03F5	$	lcd_L_28:
;lcd.ppas,63 :: 		
$03F5	$0923			COMF	lcd____mrs, W
$03F6	$00F0			MOVWF	STACK_0
$03F7	$0870			MOVF	STACK_0, 0
$03F8	$0580			ANDWF	INDF, 1
$03F9	$2BFC			GOTO	lcd_L_30
;lcd.ppas,64 :: 		
$03FA	$	lcd_L_29:
;lcd.ppas,65 :: 		
$03FA	$0823			MOVF	lcd____mrs, 0
$03FB	$0480			IORWF	INDF, 1
$03FC	$	lcd_L_30:
;lcd.ppas,67 :: 		
$03FC	$0822			MOVF	lcd____menable, 0
$03FD	$0480			IORWF	INDF, 1
;lcd.ppas,68 :: 		
$03FE	$26CF			CALL	_delay_1us
;lcd.ppas,69 :: 		
$03FF	$0922			COMF	lcd____menable, W
$0400	$00F0			MOVWF	STACK_0
$0401	$0870			MOVF	STACK_0, 0
$0402	$0580			ANDWF	INDF, 1
;lcd.ppas,71 :: 		
$0403	$0829			MOVF	lcd_lcdcmd_status, 0
$0404	$3A01			XORLW	1
$0405	$1D03			BTFSS	STATUS, Z
$0406	$2C09			GOTO	lcd_L_32
$0407	$	lcd_L_31:
;lcd.ppas,72 :: 		
$0407	$2697			CALL	_delay_5500us
$0408	$2C0A			GOTO	lcd_L_33
;lcd.ppas,73 :: 		
$0409	$	lcd_L_32:
;lcd.ppas,74 :: 		
$0409	$26C8			CALL	_delay_50us
$040A	$	lcd_L_33:
$040A	$	lcd_L_0:
;lcd.ppas,75 :: 		
$040A	$0008			RETURN
$0117	$	_lcd_config:
;lcd.ppas,115 :: 		
;lcd.ppas,116 :: 		
$0117	$2697			CALL	_delay_5500us
;lcd.ppas,117 :: 		
$0118	$2697			CALL	_delay_5500us
;lcd.ppas,118 :: 		
$0119	$2697			CALL	_delay_5500us
;lcd.ppas,120 :: 		
$011A	$0859			MOVF	FARG_Lcd_Config+1, 0
$011B	$00F0			MOVWF	STACK_0
$011C	$3001			MOVLW	1
$011D	$00F4			MOVWF	STACK_4
$011E	$0870			MOVF	STACK_0, 0
$011F	$	L_Lcd_Config_0:
$011F	$1903			BTFSC	STATUS, Z
$0120	$2925			GOTO	L_Lcd_Config_1
$0121	$0DF4			RLF	STACK_4, 1
$0122	$1074			BCF	STACK_4, 0
$0123	$3FFF			ADDLW	255
$0124	$291F			GOTO	L_Lcd_Config_0
$0125	$	L_Lcd_Config_1:
$0125	$0874			MOVF	STACK_4, 0
$0126	$00A5			MOVWF	lcd____mdb7
;lcd.ppas,121 :: 		
$0127	$085A			MOVF	FARG_Lcd_Config+2, 0
$0128	$00F0			MOVWF	STACK_0
$0129	$3001			MOVLW	1
$012A	$00F3			MOVWF	STACK_3
$012B	$0870			MOVF	STACK_0, 0
$012C	$	L_Lcd_Config_2:
$012C	$1903			BTFSC	STATUS, Z
$012D	$2932			GOTO	L_Lcd_Config_3
$012E	$0DF3			RLF	STACK_3, 1
$012F	$1073			BCF	STACK_3, 0
$0130	$3FFF			ADDLW	255
$0131	$292C			GOTO	L_Lcd_Config_2
$0132	$	L_Lcd_Config_3:
$0132	$0873			MOVF	STACK_3, 0
$0133	$00A6			MOVWF	lcd____mdb6
;lcd.ppas,122 :: 		
$0134	$085B			MOVF	FARG_Lcd_Config+3, 0
$0135	$00F0			MOVWF	STACK_0
$0136	$3001			MOVLW	1
$0137	$00F2			MOVWF	STACK_2
$0138	$0870			MOVF	STACK_0, 0
$0139	$	L_Lcd_Config_4:
$0139	$1903			BTFSC	STATUS, Z
$013A	$293F			GOTO	L_Lcd_Config_5
$013B	$0DF2			RLF	STACK_2, 1
$013C	$1072			BCF	STACK_2, 0
$013D	$3FFF			ADDLW	255
$013E	$2939			GOTO	L_Lcd_Config_4
$013F	$	L_Lcd_Config_5:
$013F	$0872			MOVF	STACK_2, 0
$0140	$00A7			MOVWF	lcd____mdb5
;lcd.ppas,123 :: 		
$0141	$085C			MOVF	FARG_Lcd_Config+4, 0
$0142	$00F0			MOVWF	STACK_0
$0143	$3001			MOVLW	1
$0144	$00F1			MOVWF	STACK_1
$0145	$0870			MOVF	STACK_0, 0
$0146	$	L_Lcd_Config_6:
$0146	$1903			BTFSC	STATUS, Z
$0147	$294C			GOTO	L_Lcd_Config_7
$0148	$0DF1			RLF	STACK_1, 1
$0149	$1071			BCF	STACK_1, 0
$014A	$3FFF			ADDLW	255
$014B	$2946			GOTO	L_Lcd_Config_6
$014C	$	L_Lcd_Config_7:
$014C	$0871			MOVF	STACK_1, 0
$014D	$00A8			MOVWF	lcd____mdb4
;lcd.ppas,124 :: 		
$014E	$085E			MOVF	FARG_Lcd_Config+6, 0
$014F	$00F0			MOVWF	STACK_0
$0150	$3001			MOVLW	1
$0151	$00A3			MOVWF	lcd____mrs
$0152	$0870			MOVF	STACK_0, 0
$0153	$	L_Lcd_Config_8:
$0153	$1903			BTFSC	STATUS, Z
$0154	$2959			GOTO	L_Lcd_Config_9
$0155	$0DA3			RLF	lcd____mrs, 1
$0156	$1023			BCF	lcd____mrs, 0
$0157	$3FFF			ADDLW	255
$0158	$2953			GOTO	L_Lcd_Config_8
$0159	$	L_Lcd_Config_9:
;lcd.ppas,125 :: 		
$0159	$085F			MOVF	FARG_Lcd_Config+7, 0
$015A	$00F0			MOVWF	STACK_0
$015B	$3001			MOVLW	1
$015C	$00AA			MOVWF	lcd____mrw
$015D	$0870			MOVF	STACK_0, 0
$015E	$	L_Lcd_Config_10:
$015E	$1903			BTFSC	STATUS, Z
$015F	$2964			GOTO	L_Lcd_Config_11
$0160	$0DAA			RLF	lcd____mrw, 1
$0161	$102A			BCF	lcd____mrw, 0
$0162	$3FFF			ADDLW	255
$0163	$295E			GOTO	L_Lcd_Config_10
$0164	$	L_Lcd_Config_11:
;lcd.ppas,126 :: 		
$0164	$0860			MOVF	FARG_Lcd_Config+8, 0
$0165	$00F0			MOVWF	STACK_0
$0166	$3001			MOVLW	1
$0167	$00A2			MOVWF	lcd____menable
$0168	$0870			MOVF	STACK_0, 0
$0169	$	L_Lcd_Config_12:
$0169	$1903			BTFSC	STATUS, Z
$016A	$296F			GOTO	L_Lcd_Config_13
$016B	$0DA2			RLF	lcd____menable, 1
$016C	$1022			BCF	lcd____menable, 0
$016D	$3FFF			ADDLW	255
$016E	$2969			GOTO	L_Lcd_Config_12
$016F	$	L_Lcd_Config_13:
;lcd.ppas,128 :: 		
$016F	$0858			MOVF	FARG_Lcd_Config, 0
$0170	$00A4			MOVWF	lcd_dataport_address
;lcd.ppas,129 :: 		
$0171	$085D			MOVF	FARG_Lcd_Config+5, 0
$0172	$00A1			MOVWF	lcd_ctrlport_address
;lcd.ppas,131 :: 		
$0173	$0858			MOVF	FARG_Lcd_Config, 0
$0174	$0084			MOVWF	FSR
;lcd.ppas,133 :: 		
$0175	$0873			MOVF	STACK_3, 0
$0176	$0474			IORWF	STACK_4, 0
$0177	$00F0			MOVWF	STACK_0
$0178	$0872			MOVF	STACK_2, 0
$0179	$04F0			IORWF	STACK_0, 1
$017A	$0871			MOVF	STACK_1, 0
$017B	$04F0			IORWF	STACK_0, 1
$017C	$09F0			COMF	STACK_0, F
$017D	$0870			MOVF	STACK_0, 0
$017E	$0580			ANDWF	INDF, 1
;lcd.ppas,134 :: 		
$017F	$	lcd_L_56:
$017F	$1784			BSF	FSR, 7
$0180	$	lcd_L_57:
;lcd.ppas,135 :: 		
$0180	$0826			MOVF	lcd____mdb6, 0
$0181	$0425			IORWF	lcd____mdb7, 0
$0182	$00F0			MOVWF	STACK_0
$0183	$0827			MOVF	lcd____mdb5, 0
$0184	$04F0			IORWF	STACK_0, 1
$0185	$0828			MOVF	lcd____mdb4, 0
$0186	$04F0			IORWF	STACK_0, 1
$0187	$09F0			COMF	STACK_0, F
$0188	$0870			MOVF	STACK_0, 0
$0189	$0580			ANDWF	INDF, 1
;lcd.ppas,136 :: 		
$018A	$1384			BCF	FSR, 7
$018B	$	lcd_L_59:
;lcd.ppas,139 :: 		
$018B	$0821			MOVF	lcd_ctrlport_address, 0
$018C	$0084			MOVWF	FSR
;lcd.ppas,141 :: 		
$018D	$082A			MOVF	lcd____mrw, 0
$018E	$0423			IORWF	lcd____mrs, 0
$018F	$00F0			MOVWF	STACK_0
$0190	$0822			MOVF	lcd____menable, 0
$0191	$04F0			IORWF	STACK_0, 1
$0192	$09F0			COMF	STACK_0, F
$0193	$0870			MOVF	STACK_0, 0
$0194	$0580			ANDWF	INDF, 1
;lcd.ppas,142 :: 		
$0195	$	lcd_L_60:
$0195	$1784			BSF	FSR, 7
$0196	$	lcd_L_61:
;lcd.ppas,143 :: 		
$0196	$082A			MOVF	lcd____mrw, 0
$0197	$0423			IORWF	lcd____mrs, 0
$0198	$00F0			MOVWF	STACK_0
$0199	$0822			MOVF	lcd____menable, 0
$019A	$04F0			IORWF	STACK_0, 1
$019B	$09F0			COMF	STACK_0, F
$019C	$0870			MOVF	STACK_0, 0
$019D	$0580			ANDWF	INDF, 1
;lcd.ppas,144 :: 		
$019E	$1384			BCF	FSR, 7
$019F	$	lcd_L_63:
;lcd.ppas,148 :: 		
$019F	$0824			MOVF	lcd_dataport_address, 0
$01A0	$0084			MOVWF	FSR
;lcd.ppas,149 :: 		
$01A1	$0827			MOVF	lcd____mdb5, 0
$01A2	$0400			IORWF	INDF, 0
$01A3	$00F0			MOVWF	STACK_0
$01A4	$0828			MOVF	lcd____mdb4, 0
$01A5	$0470			IORWF	STACK_0, 0
$01A6	$0080			MOVWF	INDF
;lcd.ppas,151 :: 		
$01A7	$0821			MOVF	lcd_ctrlport_address, 0
$01A8	$0084			MOVWF	FSR
;lcd.ppas,152 :: 		
$01A9	$0822			MOVF	lcd____menable, 0
$01AA	$0480			IORWF	INDF, 1
;lcd.ppas,153 :: 		
$01AB	$0922			COMF	lcd____menable, W
$01AC	$00F0			MOVWF	STACK_0
$01AD	$0870			MOVF	STACK_0, 0
$01AE	$0580			ANDWF	INDF, 1
;lcd.ppas,155 :: 		
$01AF	$2697			CALL	_delay_5500us
;lcd.ppas,160 :: 		
$01B0	$0822			MOVF	lcd____menable, 0
$01B1	$0480			IORWF	INDF, 1
;lcd.ppas,161 :: 		
$01B2	$0922			COMF	lcd____menable, W
$01B3	$00F0			MOVWF	STACK_0
$01B4	$0870			MOVF	STACK_0, 0
$01B5	$0580			ANDWF	INDF, 1
;lcd.ppas,163 :: 		
$01B6	$2697			CALL	_delay_5500us
;lcd.ppas,168 :: 		
$01B7	$0822			MOVF	lcd____menable, 0
$01B8	$0480			IORWF	INDF, 1
;lcd.ppas,169 :: 		
$01B9	$0922			COMF	lcd____menable, W
$01BA	$00F0			MOVWF	STACK_0
$01BB	$0870			MOVF	STACK_0, 0
$01BC	$0580			ANDWF	INDF, 1
;lcd.ppas,171 :: 		
$01BD	$2697			CALL	_delay_5500us
;lcd.ppas,174 :: 		
$01BE	$0824			MOVF	lcd_dataport_address, 0
$01BF	$0084			MOVWF	FSR
;lcd.ppas,175 :: 		
$01C0	$0827			MOVF	lcd____mdb5, 0
$01C1	$0480			IORWF	INDF, 1
;lcd.ppas,176 :: 		
$01C2	$0928			COMF	lcd____mdb4, W
$01C3	$00F0			MOVWF	STACK_0
$01C4	$0870			MOVF	STACK_0, 0
$01C5	$0580			ANDWF	INDF, 1
;lcd.ppas,178 :: 		
$01C6	$0821			MOVF	lcd_ctrlport_address, 0
$01C7	$0084			MOVWF	FSR
;lcd.ppas,179 :: 		
$01C8	$0822			MOVF	lcd____menable, 0
$01C9	$0480			IORWF	INDF, 1
;lcd.ppas,180 :: 		
$01CA	$0922			COMF	lcd____menable, W
$01CB	$00F0			MOVWF	STACK_0
$01CC	$0870			MOVF	STACK_0, 0
$01CD	$0580			ANDWF	INDF, 1
;lcd.ppas,182 :: 		
$01CE	$2697			CALL	_delay_5500us
;lcd.ppas,187 :: 		
$01CF	$0822			MOVF	lcd____menable, 0
$01D0	$0480			IORWF	INDF, 1
;lcd.ppas,188 :: 		
$01D1	$0922			COMF	lcd____menable, W
$01D2	$00F1			MOVWF	STACK_1
$01D3	$0871			MOVF	STACK_1, 0
$01D4	$0580			ANDWF	INDF, 1
;lcd.ppas,190 :: 		
$01D5	$0824			MOVF	lcd_dataport_address, 0
$01D6	$0084			MOVWF	FSR
;lcd.ppas,191 :: 		
$01D7	$0927			COMF	lcd____mdb5, W
$01D8	$00F0			MOVWF	STACK_0
$01D9	$0870			MOVF	STACK_0, 0
$01DA	$0580			ANDWF	INDF, 1
;lcd.ppas,192 :: 		
$01DB	$0825			MOVF	lcd____mdb7, 0
$01DC	$0480			IORWF	INDF, 1
;lcd.ppas,194 :: 		
$01DD	$0821			MOVF	lcd_ctrlport_address, 0
$01DE	$0084			MOVWF	FSR
;lcd.ppas,195 :: 		
$01DF	$0822			MOVF	lcd____menable, 0
$01E0	$0480			IORWF	INDF, 1
;lcd.ppas,196 :: 		
$01E1	$0871			MOVF	STACK_1, 0
$01E2	$0580			ANDWF	INDF, 1
;lcd.ppas,198 :: 		
$01E3	$2697			CALL	_delay_5500us
;lcd.ppas,201 :: 		
$01E4	$0824			MOVF	lcd_dataport_address, 0
$01E5	$0084			MOVWF	FSR
;lcd.ppas,202 :: 		
$01E6	$0925			COMF	lcd____mdb7, W
$01E7	$00F0			MOVWF	STACK_0
$01E8	$0870			MOVF	STACK_0, 0
$01E9	$0580			ANDWF	INDF, 1
;lcd.ppas,203 :: 		
$01EA	$0828			MOVF	lcd____mdb4, 0
$01EB	$0480			IORWF	INDF, 1
;lcd.ppas,204 :: 		
$01EC	$0821			MOVF	lcd_ctrlport_address, 0
$01ED	$0084			MOVWF	FSR
;lcd.ppas,205 :: 		
$01EE	$0822			MOVF	lcd____menable, 0
$01EF	$0480			IORWF	INDF, 1
;lcd.ppas,206 :: 		
$01F0	$0922			COMF	lcd____menable, W
$01F1	$00F1			MOVWF	STACK_1
$01F2	$0871			MOVF	STACK_1, 0
$01F3	$0580			ANDWF	INDF, 1
;lcd.ppas,207 :: 		
$01F4	$0824			MOVF	lcd_dataport_address, 0
$01F5	$0084			MOVWF	FSR
;lcd.ppas,208 :: 		
$01F6	$0928			COMF	lcd____mdb4, W
$01F7	$00F0			MOVWF	STACK_0
$01F8	$0870			MOVF	STACK_0, 0
$01F9	$0580			ANDWF	INDF, 1
;lcd.ppas,209 :: 		
$01FA	$0821			MOVF	lcd_ctrlport_address, 0
$01FB	$0084			MOVWF	FSR
;lcd.ppas,210 :: 		
$01FC	$0822			MOVF	lcd____menable, 0
$01FD	$0480			IORWF	INDF, 1
;lcd.ppas,211 :: 		
$01FE	$0871			MOVF	STACK_1, 0
$01FF	$0580			ANDWF	INDF, 1
;lcd.ppas,213 :: 		
$0200	$2697			CALL	_delay_5500us
;lcd.ppas,218 :: 		
$0201	$0822			MOVF	lcd____menable, 0
$0202	$0480			IORWF	INDF, 1
;lcd.ppas,219 :: 		
$0203	$0922			COMF	lcd____menable, W
$0204	$00F0			MOVWF	STACK_0
$0205	$0870			MOVF	STACK_0, 0
$0206	$0580			ANDWF	INDF, 1
;lcd.ppas,220 :: 		
$0207	$0824			MOVF	lcd_dataport_address, 0
$0208	$0084			MOVWF	FSR
;lcd.ppas,221 :: 		
$0209	$0828			MOVF	lcd____mdb4, 0
$020A	$0480			IORWF	INDF, 1
;lcd.ppas,222 :: 		
$020B	$0821			MOVF	lcd_ctrlport_address, 0
$020C	$0084			MOVWF	FSR
;lcd.ppas,223 :: 		
$020D	$0822			MOVF	lcd____menable, 0
$020E	$0480			IORWF	INDF, 1
;lcd.ppas,224 :: 		
$020F	$0870			MOVF	STACK_0, 0
$0210	$0580			ANDWF	INDF, 1
;lcd.ppas,226 :: 		
$0211	$2697			CALL	_delay_5500us
;lcd.ppas,229 :: 		
$0212	$0824			MOVF	lcd_dataport_address, 0
$0213	$0084			MOVWF	FSR
;lcd.ppas,230 :: 		
$0214	$0928			COMF	lcd____mdb4, W
$0215	$00F0			MOVWF	STACK_0
$0216	$0870			MOVF	STACK_0, 0
$0217	$0580			ANDWF	INDF, 1
;lcd.ppas,231 :: 		
$0218	$0821			MOVF	lcd_ctrlport_address, 0
$0219	$0084			MOVWF	FSR
;lcd.ppas,232 :: 		
$021A	$0822			MOVF	lcd____menable, 0
$021B	$0480			IORWF	INDF, 1
;lcd.ppas,233 :: 		
$021C	$0922			COMF	lcd____menable, W
$021D	$00F1			MOVWF	STACK_1
$021E	$0871			MOVF	STACK_1, 0
$021F	$0580			ANDWF	INDF, 1
;lcd.ppas,234 :: 		
$0220	$0824			MOVF	lcd_dataport_address, 0
$0221	$0084			MOVWF	FSR
;lcd.ppas,235 :: 		
$0222	$0828			MOVF	lcd____mdb4, 0
$0223	$0400			IORWF	INDF, 0
$0224	$00F0			MOVWF	STACK_0
$0225	$0827			MOVF	lcd____mdb5, 0
$0226	$04F0			IORWF	STACK_0, 1
$0227	$0826			MOVF	lcd____mdb6, 0
$0228	$04F0			IORWF	STACK_0, 1
$0229	$0825			MOVF	lcd____mdb7, 0
$022A	$0470			IORWF	STACK_0, 0
$022B	$0080			MOVWF	INDF
;lcd.ppas,236 :: 		
$022C	$0821			MOVF	lcd_ctrlport_address, 0
$022D	$0084			MOVWF	FSR
;lcd.ppas,237 :: 		
$022E	$0822			MOVF	lcd____menable, 0
$022F	$0480			IORWF	INDF, 1
;lcd.ppas,238 :: 		
$0230	$0871			MOVF	STACK_1, 0
$0231	$0580			ANDWF	INDF, 1
;lcd.ppas,240 :: 		
$0232	$2697			CALL	_delay_5500us
;lcd.ppas,242 :: 		
$0233	$3001			MOVLW	1
$0234	$00A9			MOVWF	lcd_lcdcmd_status
$0235	$	lcd_L_55:
;lcd.ppas,243 :: 		
$0235	$0008			RETURN
$06B7	$	_lcd_chr_cp:
;lcd.ppas,97 :: 		
;lcd.ppas,98 :: 		
$06B7	$1303			BCF	STATUS, RP1
$06B8	$1283			BCF	STATUS, RP0
$06B9	$01A9			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,99 :: 		
$06BA	$0858			MOVF	FARG_Lcd_Chr_CP, 0
$06BB	$00E1			MOVWF	FARG_Lcd_Cmd
$06BC	$2364			CALL	_lcd_cmd
;lcd.ppas,100 :: 		
$06BD	$3001			MOVLW	1
$06BE	$00A9			MOVWF	lcd_lcdcmd_status
$06BF	$	lcd_L_48:
;lcd.ppas,101 :: 		
$06BF	$0008			RETURN
$0682	$	_lcd_init:
;lcd.ppas,246 :: 		
;lcd.ppas,247 :: 		
$0682	$1303			BCF	STATUS, RP1
$0683	$1283			BCF	STATUS, RP0
$0684	$0854			MOVF	FARG_Lcd_Init, 0
$0685	$00D8			MOVWF	FARG_Lcd_Config
$0686	$3007			MOVLW	7
$0687	$00D9			MOVWF	FARG_Lcd_Config+1
$0688	$3006			MOVLW	6
$0689	$00DA			MOVWF	FARG_Lcd_Config+2
$068A	$3005			MOVLW	5
$068B	$00DB			MOVWF	FARG_Lcd_Config+3
$068C	$3004			MOVLW	4
$068D	$00DC			MOVWF	FARG_Lcd_Config+4
$068E	$0854			MOVF	FARG_Lcd_Init, 0
$068F	$00DD			MOVWF	FARG_Lcd_Config+5
$0690	$3002			MOVLW	2
$0691	$00DE			MOVWF	FARG_Lcd_Config+6
$0692	$01DF			CLRF	FARG_Lcd_Config+7, 1
$0693	$3003			MOVLW	3
$0694	$00E0			MOVWF	FARG_Lcd_Config+8
$0695	$2117			CALL	_lcd_config
$0696	$	lcd_L_64:
;lcd.ppas,248 :: 		
$0696	$0008			RETURN
$057C	$	_lcd_out:
;lcd.ppas,252 :: 		
;lcd.ppas,254 :: 		
$057C	$	lcd_L_68:
$057C	$1303			BCF	STATUS, RP1
$057D	$1283			BCF	STATUS, RP0
$057E	$0854			MOVF	FARG_Lcd_Out, 0
$057F	$3A01			XORLW	1
$0580	$1D03			BTFSS	STATUS, Z
$0581	$2D85			GOTO	lcd_L_69
$0582	$	lcd_L_67:
$0582	$3080			MOVLW	128
$0583	$00D4			MOVWF	FARG_Lcd_Out
$0584	$2D9C			GOTO	lcd_L_66
$0585	$	lcd_L_69:
;lcd.ppas,255 :: 		
$0585	$	lcd_L_71:
$0585	$0854			MOVF	FARG_Lcd_Out, 0
$0586	$3A02			XORLW	2
$0587	$1D03			BTFSS	STATUS, Z
$0588	$2D8C			GOTO	lcd_L_72
$0589	$	lcd_L_70:
$0589	$30C0			MOVLW	192
$058A	$00D4			MOVWF	FARG_Lcd_Out
$058B	$2D9C			GOTO	lcd_L_66
$058C	$	lcd_L_72:
;lcd.ppas,256 :: 		
$058C	$	lcd_L_74:
$058C	$0854			MOVF	FARG_Lcd_Out, 0
$058D	$3A03			XORLW	3
$058E	$1D03			BTFSS	STATUS, Z
$058F	$2D93			GOTO	lcd_L_75
$0590	$	lcd_L_73:
$0590	$3094			MOVLW	148
$0591	$00D4			MOVWF	FARG_Lcd_Out
$0592	$2D9C			GOTO	lcd_L_66
$0593	$	lcd_L_75:
;lcd.ppas,257 :: 		
$0593	$	lcd_L_77:
$0593	$0854			MOVF	FARG_Lcd_Out, 0
$0594	$3A04			XORLW	4
$0595	$1D03			BTFSS	STATUS, Z
$0596	$2D9A			GOTO	lcd_L_78
$0597	$	lcd_L_76:
$0597	$30D4			MOVLW	212
$0598	$00D4			MOVWF	FARG_Lcd_Out
;lcd.ppas,258 :: 		
$0599	$2D9C			GOTO	lcd_L_66
$059A	$	lcd_L_78:
$059A	$3080			MOVLW	128
$059B	$00D4			MOVWF	FARG_Lcd_Out
$059C	$	lcd_L_66:
;lcd.ppas,260 :: 		
$059C	$0355			DECF	FARG_Lcd_Out+1, 0
$059D	$00F0			MOVWF	STACK_0
$059E	$0854			MOVF	FARG_Lcd_Out, 0
$059F	$07F0			ADDWF	STACK_0, 1
$05A0	$0870			MOVF	STACK_0, 0
$05A1	$00D4			MOVWF	FARG_Lcd_Out
;lcd.ppas,261 :: 		
$05A2	$0870			MOVF	STACK_0, 0
$05A3	$00E1			MOVWF	FARG_Lcd_Cmd
$05A4	$2364			CALL	_lcd_cmd
;lcd.ppas,262 :: 		
$05A5	$01A9			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,263 :: 		
$05A6	$01D7			CLRF	_lcd_out_local_i, 1
;lcd.ppas,264 :: 		
$05A7	$	lcd_L_80:
$05A7	$0857			MOVF	_lcd_out_local_i, 0
$05A8	$0756			ADDWF	FARG_Lcd_Out+2, 0
$05A9	$0084			MOVWF	FSR
$05AA	$0800			MOVF	INDF, 0
$05AB	$00F2			MOVWF	STACK_2
$05AC	$0872			MOVF	STACK_2, 0
$05AD	$3A00			XORLW	0
$05AE	$1903			BTFSC	STATUS, Z
$05AF	$2DB8			GOTO	lcd_L_81
;lcd.ppas,266 :: 		
$05B0	$0857			MOVF	_lcd_out_local_i, 0
$05B1	$0756			ADDWF	FARG_Lcd_Out+2, 0
$05B2	$0084			MOVWF	FSR
$05B3	$0800			MOVF	INDF, 0
$05B4	$00D8			MOVWF	FARG_Lcd_Chr_CP
$05B5	$26B7			CALL	_lcd_chr_cp
;lcd.ppas,267 :: 		
$05B6	$0AD7			INCF	_lcd_out_local_i, 1
;lcd.ppas,268 :: 		
$05B7	$2DA7			GOTO	lcd_L_80
$05B8	$	lcd_L_81:
;lcd.ppas,269 :: 		
$05B8	$3001			MOVLW	1
$05B9	$00A9			MOVWF	lcd_lcdcmd_status
$05BA	$	lcd_L_65:
;lcd.ppas,270 :: 		
$05BA	$0008			RETURN
$06C0	$	_delay_22us:
;delays.ppas,21 :: 		begin
;delays.ppas,22 :: 		Delay_us(22);
$06C0	$300E			MOVLW	14
$06C1	$1303			BCF	STATUS, RP1
$06C2	$1283			BCF	STATUS, RP0
$06C3	$00FA			MOVWF	STACK_10
$06C4	$0BFA			DECFSZ	STACK_10, F
$06C5	$2EC4			GOTO	$-1
$06C6	$0000			NOP
$06C7	$	delays_L_3:
;delays.ppas,23 :: 		end;
$06C7	$0008			RETURN
$0665	$	_div_16x16_u:
$0665	$1303			BCF	STATUS, RP1
$0666	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$0667	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$0668	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$0669	$3010			MOVLW	16
;math.ppas,113 :: 		
$066A	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$066B	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$066C	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$066D	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$066E	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$066F	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$0670	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$0671	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$0672	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$0673	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$0674	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$0675	$2E7D			GOTO	$+8
;math.ppas,125 :: 		
$0676	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$0677	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$0678	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$0679	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$067A	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$067B	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$067C	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$067D	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$067E	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$067F	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$0680	$2E6B			GOTO	$-21
;math.ppas,136 :: 		
$0681	$	math_L_3:
;math.ppas,137 :: 		
$0681	$0008			RETURN
$0236	$	_sdiv3232l:
$0236	$1303			BCF	STATUS, RP1
$0237	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$0238	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0239	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$023A	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$023B	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$023C	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$023D	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$023E	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$023F	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$0240	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$0241	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$0242	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$0243	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$0244	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$0245	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$0246	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$0247	$3007			MOVLW	7
;math.ppas,559 :: 		
$0248	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0249	$	LOOPS3232A:
;math.ppas,561 :: 		
$0249	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$024A	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$024B	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$024C	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$024D	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$024E	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$024F	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$0250	$2A5F			GOTO	SADD22LA
;math.ppas,570 :: 		
$0251	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$0252	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$0253	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$0254	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$0255	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$0256	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$0257	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$0258	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0259	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$025A	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$025B	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$025C	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$025D	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$025E	$2A6C			GOTO	SOK22LA
;math.ppas,585 :: 		
$025F	$	SADD22LA:
;math.ppas,586 :: 		
$025F	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$0260	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$0261	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$0262	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$0263	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$0264	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$0265	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$0266	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$0267	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$0268	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$0269	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$026A	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$026B	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$026C	$	SOK22LA:
;math.ppas,602 :: 		
$026C	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$026D	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$026E	$2A49			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$026F	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$0270	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$0271	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$0272	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$0273	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$0274	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$0275	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$0276	$2A85			GOTO	SADD22L8
;math.ppas,615 :: 		
$0277	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$0278	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$0279	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$027A	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$027B	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$027C	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$027D	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$027E	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$027F	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$0280	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$0281	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$0282	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$0283	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$0284	$2A92			GOTO	SOK22L8
;math.ppas,630 :: 		
$0285	$	SADD22L8:
;math.ppas,631 :: 		
$0285	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$0286	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$0287	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$0288	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$0289	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$028A	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$028B	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$028C	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$028D	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$028E	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$028F	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$0290	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$0291	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$0292	$	SOK22L8:
;math.ppas,647 :: 		
$0292	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$0293	$3007			MOVLW	7
;math.ppas,650 :: 		
$0294	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$0295	$	LOOPS3232B:
;math.ppas,652 :: 		
$0295	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$0296	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$0297	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$0298	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$0299	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$029A	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$029B	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$029C	$2AAB			GOTO	SADD22LB
;math.ppas,661 :: 		
$029D	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$029E	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$029F	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$02A0	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$02A1	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$02A2	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$02A3	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$02A4	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$02A5	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$02A6	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$02A7	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$02A8	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$02A9	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$02AA	$2AB8			GOTO	SOK22LB
;math.ppas,676 :: 		
$02AB	$	SADD22LB:
;math.ppas,677 :: 		
$02AB	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$02AC	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$02AD	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$02AE	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$02AF	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$02B0	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$02B1	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$02B2	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$02B3	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$02B4	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$02B5	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$02B6	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$02B7	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$02B8	$	SOK22LB:
;math.ppas,693 :: 		
$02B8	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$02B9	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$02BA	$2A95			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$02BB	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$02BC	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$02BD	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$02BE	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$02BF	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$02C0	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$02C1	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$02C2	$2AD1			GOTO	SADD22L16
;math.ppas,706 :: 		
$02C3	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$02C4	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$02C5	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$02C6	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$02C7	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$02C8	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$02C9	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$02CA	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$02CB	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$02CC	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$02CD	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$02CE	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$02CF	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$02D0	$2ADE			GOTO	SOK22L16
;math.ppas,721 :: 		
$02D1	$	SADD22L16:
;math.ppas,722 :: 		
$02D1	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$02D2	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$02D3	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$02D4	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$02D5	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$02D6	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$02D7	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$02D8	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$02D9	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$02DA	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$02DB	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$02DC	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$02DD	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$02DE	$	SOK22L16:
;math.ppas,738 :: 		
$02DE	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$02DF	$3007			MOVLW	7
;math.ppas,741 :: 		
$02E0	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$02E1	$	LOOPS3232C:
;math.ppas,743 :: 		
$02E1	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$02E2	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$02E3	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$02E4	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$02E5	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$02E6	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$02E7	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$02E8	$2AF7			GOTO	SADD22LC
;math.ppas,752 :: 		
$02E9	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$02EA	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$02EB	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$02EC	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$02ED	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$02EE	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$02EF	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$02F0	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$02F1	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$02F2	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$02F3	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$02F4	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$02F5	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$02F6	$2B04			GOTO	SOK22LC
;math.ppas,767 :: 		
$02F7	$	SADD22LC:
;math.ppas,768 :: 		
$02F7	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$02F8	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$02F9	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$02FA	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$02FB	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$02FC	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$02FD	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$02FE	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$02FF	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$0300	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$0301	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$0302	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$0303	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$0304	$	SOK22LC:
;math.ppas,784 :: 		
$0304	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$0305	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$0306	$2AE1			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$0307	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$0308	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$0309	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$030A	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$030B	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$030C	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$030D	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$030E	$2B1D			GOTO	SADD22L24
;math.ppas,797 :: 		
$030F	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$0310	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$0311	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$0312	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$0313	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$0314	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$0315	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$0316	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$0317	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$0318	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$0319	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$031A	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$031B	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$031C	$2B2A			GOTO	SOK22L24
;math.ppas,812 :: 		
$031D	$	SADD22L24:
;math.ppas,813 :: 		
$031D	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$031E	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$031F	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$0320	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$0321	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$0322	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$0323	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$0324	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$0325	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$0326	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$0327	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$0328	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$0329	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$032A	$	SOK22L24:
;math.ppas,829 :: 		
$032A	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$032B	$3007			MOVLW	7
;math.ppas,832 :: 		
$032C	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$032D	$	LOOPS3232D:
;math.ppas,834 :: 		
$032D	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$032E	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$032F	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$0330	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$0331	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$0332	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$0333	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$0334	$2B43			GOTO	SADD22LD
;math.ppas,843 :: 		
$0335	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$0336	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$0337	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$0338	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0339	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$033A	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$033B	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$033C	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$033D	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$033E	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$033F	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$0340	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$0341	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$0342	$2B50			GOTO	SOK22LD
;math.ppas,858 :: 		
$0343	$	SADD22LD:
;math.ppas,859 :: 		
$0343	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$0344	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$0345	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$0346	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$0347	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$0348	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0349	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$034A	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$034B	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$034C	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$034D	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$034E	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$034F	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$0350	$	SOK22LD:
;math.ppas,876 :: 		
$0350	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$0351	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$0352	$2B2D			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$0353	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$0354	$2B63			GOTO	SOK22L
;math.ppas,882 :: 		
$0355	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$0356	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$0357	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$0358	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0359	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$035A	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$035B	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$035C	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$035D	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$035E	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$035F	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$0360	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$0361	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$0362	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$0363	$	SOK22L:
;math.ppas,897 :: 		
$0363	$	math_L_9:
;math.ppas,898 :: 		
$0363	$0008			RETURN
$06A9	$	_comfrem:
$06A9	$1303			BCF	STATUS, RP1
$06AA	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$06AB	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$06AC	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$06AD	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$06AE	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$06AF	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$06B0	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$06B1	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$06B2	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$06B3	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$06B4	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$06B5	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$06B6	$	math_L_10:
;math.ppas,915 :: 		
$06B6	$0008			RETURN
$04A5	$	_init:
;Temp.ppas,5 :: 		begin
;Temp.ppas,6 :: 		TRISA:=$ff;
$04A5	$30FF			MOVLW	255
$04A6	$1303			BCF	STATUS, RP1
$04A7	$1683			BSF	STATUS, RP0
$04A8	$0085			MOVWF	TRISA
;Temp.ppas,7 :: 		TRISC:=$00;
$04A9	$0187			CLRF	TRISC, 1
;Temp.ppas,8 :: 		ADCON1:=$0E;
$04AA	$300E			MOVLW	14
$04AB	$009F			MOVWF	ADCON1
;Temp.ppas,9 :: 		Lcd_Init(PORTC);
$04AC	$3007			MOVLW	PORTC
$04AD	$1283			BCF	STATUS, RP0
$04AE	$00D4			MOVWF	FARG_Lcd_Init
$04AF	$2682			CALL	_lcd_init
;Temp.ppas,10 :: 		Lcd_Cmd(LCD_clear);
$04B0	$3001			MOVLW	1
$04B1	$00E1			MOVWF	FARG_Lcd_Cmd
$04B2	$2364			CALL	_lcd_cmd
;Temp.ppas,11 :: 		Lcd_Cmd(LCD_CURSOR_OFF);
$04B3	$300C			MOVLW	12
$04B4	$00E1			MOVWF	FARG_Lcd_Cmd
$04B5	$2364			CALL	_lcd_cmd
;Temp.ppas,12 :: 		Lcd_Out(1,3,'Atelier Conception');
$04B6	$3001			MOVLW	1
$04B7	$00D4			MOVWF	FARG_Lcd_Out
$04B8	$3003			MOVLW	3
$04B9	$00D5			MOVWF	FARG_Lcd_Out+1
$04BA	$3041			MOVLW	65
$04BB	$00C1			MOVWF	?init_Local_Text+0
$04BC	$3074			MOVLW	116
$04BD	$00C2			MOVWF	?init_Local_Text+1
$04BE	$3065			MOVLW	101
$04BF	$00C3			MOVWF	?init_Local_Text+2
$04C0	$306C			MOVLW	108
$04C1	$00C4			MOVWF	?init_Local_Text+3
$04C2	$3069			MOVLW	105
$04C3	$00C5			MOVWF	?init_Local_Text+4
$04C4	$3065			MOVLW	101
$04C5	$00C6			MOVWF	?init_Local_Text+5
$04C6	$3072			MOVLW	114
$04C7	$00C7			MOVWF	?init_Local_Text+6
$04C8	$3020			MOVLW	32
$04C9	$00C8			MOVWF	?init_Local_Text+7
$04CA	$3043			MOVLW	67
$04CB	$00C9			MOVWF	?init_Local_Text+8
$04CC	$306F			MOVLW	111
$04CD	$00CA			MOVWF	?init_Local_Text+9
$04CE	$306E			MOVLW	110
$04CF	$00CB			MOVWF	?init_Local_Text+10
$04D0	$3063			MOVLW	99
$04D1	$00CC			MOVWF	?init_Local_Text+11
$04D2	$3065			MOVLW	101
$04D3	$00CD			MOVWF	?init_Local_Text+12
$04D4	$3070			MOVLW	112
$04D5	$00CE			MOVWF	?init_Local_Text+13
$04D6	$3074			MOVLW	116
$04D7	$00CF			MOVWF	?init_Local_Text+14
$04D8	$3069			MOVLW	105
$04D9	$00D0			MOVWF	?init_Local_Text+15
$04DA	$306F			MOVLW	111
$04DB	$00D1			MOVWF	?init_Local_Text+16
$04DC	$306E			MOVLW	110
$04DD	$00D2			MOVWF	?init_Local_Text+17
$04DE	$01D3			CLRF	?init_Local_Text+18
$04DF	$3041			MOVLW	?init_Local_Text
$04E0	$00D6			MOVWF	FARG_Lcd_Out+2
$04E1	$257C			CALL	_lcd_out
;Temp.ppas,13 :: 		Lcd_Out(2,6,'Interfaces');
$04E2	$3002			MOVLW	2
$04E3	$00D4			MOVWF	FARG_Lcd_Out
$04E4	$3006			MOVLW	6
$04E5	$00D5			MOVWF	FARG_Lcd_Out+1
$04E6	$3049			MOVLW	73
$04E7	$00C1			MOVWF	?init_Local_Text+0
$04E8	$306E			MOVLW	110
$04E9	$00C2			MOVWF	?init_Local_Text+1
$04EA	$3074			MOVLW	116
$04EB	$00C3			MOVWF	?init_Local_Text+2
$04EC	$3065			MOVLW	101
$04ED	$00C4			MOVWF	?init_Local_Text+3
$04EE	$3072			MOVLW	114
$04EF	$00C5			MOVWF	?init_Local_Text+4
$04F0	$3066			MOVLW	102
$04F1	$00C6			MOVWF	?init_Local_Text+5
$04F2	$3061			MOVLW	97
$04F3	$00C7			MOVWF	?init_Local_Text+6
$04F4	$3063			MOVLW	99
$04F5	$00C8			MOVWF	?init_Local_Text+7
$04F6	$3065			MOVLW	101
$04F7	$00C9			MOVWF	?init_Local_Text+8
$04F8	$3073			MOVLW	115
$04F9	$00CA			MOVWF	?init_Local_Text+9
$04FA	$01CB			CLRF	?init_Local_Text+10
$04FB	$3041			MOVLW	?init_Local_Text
$04FC	$00D6			MOVWF	FARG_Lcd_Out+2
$04FD	$257C			CALL	_lcd_out
;Temp.ppas,14 :: 		delay_ms(2000);
$04FE	$3015			MOVLW	21
$04FF	$00FC			MOVWF	STACK_12
$0500	$30FF			MOVLW	255
$0501	$00FB			MOVWF	STACK_11
$0502	$30FF			MOVLW	255
$0503	$00FA			MOVWF	STACK_10
$0504	$0BFC			DECFSZ	STACK_12, F
$0505	$2D07			GOTO	$+2
$0506	$2D0E			GOTO	$+8
$0507	$0BFB			DECFSZ	STACK_11, F
$0508	$2D0A			GOTO	$+2
$0509	$2D0D			GOTO	$+4
$050A	$0BFA			DECFSZ	STACK_10, F
$050B	$2D0A			GOTO	$-1
$050C	$2D07			GOTO	$-5
$050D	$2D04			GOTO	$-9
$050E	$3066			MOVLW	102
$050F	$00FB			MOVWF	STACK_11
$0510	$30FF			MOVLW	255
$0511	$00FA			MOVWF	STACK_10
$0512	$0BFB			DECFSZ	STACK_11, F
$0513	$2D15			GOTO	$+2
$0514	$2D18			GOTO	$+4
$0515	$0BFA			DECFSZ	STACK_10, F
$0516	$2D15			GOTO	$-1
$0517	$2D12			GOTO	$-5
$0518	$3012			MOVLW	18
$0519	$00FA			MOVWF	STACK_10
$051A	$0BFA			DECFSZ	STACK_10, F
$051B	$2D1A			GOTO	$-1
$051C	$0000			NOP
$051D	$0000			NOP
;Temp.ppas,15 :: 		Lcd_Cmd(LCD_clear);
$051E	$3001			MOVLW	1
$051F	$00E1			MOVWF	FARG_Lcd_Cmd
$0520	$2364			CALL	_lcd_cmd
$0521	$	Temp_L_0:
;Temp.ppas,16 :: 		end;
$0521	$0008			RETURN
$05BB	$	_adc_read:
;ADClib_A_C.ppas,12 :: 		
;ADClib_A_C.ppas,13 :: 		
$05BB	$1303			BCF	STATUS, RP1
$05BC	$1283			BCF	STATUS, RP0
$05BD	$019F			CLRF	ADCON0, 1
;ADClib_A_C.ppas,14 :: 		
$05BE	$30C0			MOVLW	192
$05BF	$049F			IORWF	ADCON0, 1
;ADClib_A_C.ppas,15 :: 		
$05C0	$3040			MOVLW	64
$05C1	$1683			BSF	STATUS, RP0
$05C2	$041F			IORWF	ADCON1, 0
$05C3	$00F0			MOVWF	STACK_0
$05C4	$0870			MOVF	STACK_0, 0
$05C5	$009F			MOVWF	ADCON1
;ADClib_A_C.ppas,17 :: 		
$05C6	$3080			MOVLW	128
$05C7	$0470			IORWF	STACK_0, 0
$05C8	$009F			MOVWF	ADCON1
;ADClib_A_C.ppas,18 :: 		
$05C9	$1283			BCF	STATUS, RP0
$05CA	$0841			MOVF	FARG_ADC_read, 0
$05CB	$00F0			MOVWF	STACK_0
$05CC	$0DF0			RLF	STACK_0, 1
$05CD	$1070			BCF	STACK_0, 0
$05CE	$0DF0			RLF	STACK_0, 1
$05CF	$1070			BCF	STACK_0, 0
$05D0	$0DF0			RLF	STACK_0, 1
$05D1	$1070			BCF	STACK_0, 0
$05D2	$0870			MOVF	STACK_0, 0
$05D3	$049F			IORWF	ADCON0, 1
;ADClib_A_C.ppas,19 :: 		
$05D4	$141F			BSF	ADCON0, 0
;ADClib_A_C.ppas,20 :: 		
$05D5	$26C0			CALL	_delay_22us
;ADClib_A_C.ppas,21 :: 		
$05D6	$151F			BSF	ADCON0, 2
;ADClib_A_C.ppas,22 :: 		
$05D7	$	ADClib_A_C_L_2:
$05D7	$081F			MOVF	ADCON0, 0
$05D8	$00F2			MOVWF	STACK_2
$05D9	$3000			MOVLW	0
$05DA	$1972			BTFSC	STACK_2, 2
$05DB	$3001			MOVLW	1
$05DC	$00F2			MOVWF	STACK_2
$05DD	$0872			MOVF	STACK_2, 0
$05DE	$3A01			XORLW	1
$05DF	$1D03			BTFSS	STATUS, Z
$05E0	$2DE3			GOTO	ADClib_A_C_L_3
;ADClib_A_C.ppas,23 :: 		
$05E1	$0000			NOP
$05E2	$2DD7			GOTO	ADClib_A_C_L_2
$05E3	$	ADClib_A_C_L_3:
;ADClib_A_C.ppas,24 :: 		
$05E3	$081E			MOVF	ADRESH, 0
$05E4	$00F2			MOVWF	STACK_2
$05E5	$01F3			CLRF	STACK_2+1
$05E6	$0872			MOVF	STACK_2, 0
$05E7	$00F3			MOVWF	STACK_2+1
$05E8	$01F2			CLRF	STACK_2
$05E9	$0872			MOVF	STACK_2, 0
$05EA	$00C2			MOVWF	_adc_read_local_result
$05EB	$0873			MOVF	STACK_2+1, 0
$05EC	$00C3			MOVWF	_adc_read_local_result+1
;ADClib_A_C.ppas,25 :: 		
$05ED	$1683			BSF	STATUS, RP0
$05EE	$081E			MOVF	ADRESL, 0
$05EF	$0472			IORWF	STACK_2, 0
$05F0	$1283			BCF	STATUS, RP0
$05F1	$00C2			MOVWF	_adc_read_local_result
$05F2	$0873			MOVF	STACK_2+1, 0
$05F3	$00C3			MOVWF	_adc_read_local_result+1
$05F4	$3000			MOVLW	0
$05F5	$04C3			IORWF	_adc_read_local_result+1, 1
;ADClib_A_C.ppas,26 :: 		
$05F6	$101F			BCF	ADCON0, 0
$05F7	$	ADClib_A_C_L_0:
;ADClib_A_C.ppas,27 :: 		
$05F7	$0842			MOVF	_adc_read_local_result, 0
$05F8	$00F0			MOVWF	STACK_0
$05F9	$0843			MOVF	_adc_read_local_result+1, 0
$05FA	$00F1			MOVWF	STACK_0+1
$05FB	$0008			RETURN
$0522	$	_wordtostr:
;conv.ppas,31 :: 		
;conv.ppas,32 :: 		
$0522	$3001			MOVLW	1
$0523	$1303			BCF	STATUS, RP1
$0524	$1283			BCF	STATUS, RP0
$0525	$00C4			MOVWF	_wordtostr_local_len
;conv.ppas,33 :: 		
$0526	$0842			MOVF	FARG_WordToStr+1, 0
$0527	$3C00			SUBLW	0
$0528	$1D03			BTFSS	STATUS, Z
$0529	$2D2C			GOTO	L_WordToStr_0
$052A	$0841			MOVF	FARG_WordToStr, 0
$052B	$3C09			SUBLW	9
$052C	$	L_WordToStr_0:
$052C	$1803			BTFSC	STATUS, C
$052D	$2D2F			GOTO	conv_L_15
$052E	$	conv_L_14:
;conv.ppas,34 :: 		
$052E	$0AC4			INCF	_wordtostr_local_len, 1
$052F	$	conv_L_15:
$052F	$	conv_L_16:
;conv.ppas,35 :: 		
$052F	$0842			MOVF	FARG_WordToStr+1, 0
$0530	$3C00			SUBLW	0
$0531	$1D03			BTFSS	STATUS, Z
$0532	$2D35			GOTO	L_WordToStr_1
$0533	$0841			MOVF	FARG_WordToStr, 0
$0534	$3C63			SUBLW	99
$0535	$	L_WordToStr_1:
$0535	$1803			BTFSC	STATUS, C
$0536	$2D38			GOTO	conv_L_18
$0537	$	conv_L_17:
;conv.ppas,36 :: 		
$0537	$0AC4			INCF	_wordtostr_local_len, 1
$0538	$	conv_L_18:
$0538	$	conv_L_19:
;conv.ppas,37 :: 		
$0538	$0842			MOVF	FARG_WordToStr+1, 0
$0539	$3C03			SUBLW	3
$053A	$1D03			BTFSS	STATUS, Z
$053B	$2D3E			GOTO	L_WordToStr_2
$053C	$0841			MOVF	FARG_WordToStr, 0
$053D	$3CE7			SUBLW	231
$053E	$	L_WordToStr_2:
$053E	$1803			BTFSC	STATUS, C
$053F	$2D41			GOTO	conv_L_21
$0540	$	conv_L_20:
;conv.ppas,38 :: 		
$0540	$0AC4			INCF	_wordtostr_local_len, 1
$0541	$	conv_L_21:
$0541	$	conv_L_22:
;conv.ppas,39 :: 		
$0541	$0842			MOVF	FARG_WordToStr+1, 0
$0542	$3C27			SUBLW	39
$0543	$1D03			BTFSS	STATUS, Z
$0544	$2D47			GOTO	L_WordToStr_3
$0545	$0841			MOVF	FARG_WordToStr, 0
$0546	$3C0F			SUBLW	15
$0547	$	L_WordToStr_3:
$0547	$1803			BTFSC	STATUS, C
$0548	$2D4A			GOTO	conv_L_24
$0549	$	conv_L_23:
;conv.ppas,40 :: 		
$0549	$0AC4			INCF	_wordtostr_local_len, 1
$054A	$	conv_L_24:
$054A	$	conv_L_25:
;conv.ppas,41 :: 		
$054A	$0843			MOVF	FARG_WordToStr+2, 0
$054B	$0084			MOVWF	FSR
$054C	$3020			MOVLW	32
$054D	$0080			MOVWF	INDF
$054E	$0A84			INCF	FSR, 1
$054F	$0080			MOVWF	INDF
$0550	$0A84			INCF	FSR, 1
$0551	$0080			MOVWF	INDF
$0552	$0A84			INCF	FSR, 1
$0553	$0080			MOVWF	INDF
$0554	$0A84			INCF	FSR, 1
$0555	$0080			MOVWF	INDF
$0556	$0A84			INCF	FSR, 1
$0557	$0180			CLRF	INDF
;conv.ppas,42 :: 		
$0558	$0384			DECF	FSR, 1
;conv.ppas,43 :: 		
$0559	$	conv_L_28:
$0559	$0844			MOVF	_wordtostr_local_len, 0
$055A	$3C00			SUBLW	0
$055B	$1803			BTFSC	STATUS, C
$055C	$2D7B			GOTO	conv_L_29
;conv.ppas,45 :: 		
$055D	$300A			MOVLW	10
$055E	$00F4			MOVWF	STACK_4
$055F	$01F5			CLRF	STACK_4+1
$0560	$0841			MOVF	FARG_WordToStr, 0
$0561	$00F0			MOVWF	STACK_0
$0562	$0842			MOVF	FARG_WordToStr+1, 0
$0563	$00F1			MOVWF	STACK_0+1
$0564	$2665			CALL	_div_16x16_u
$0565	$0878			MOVF	STACK_8, 0
$0566	$00F0			MOVWF	STACK_0
$0567	$0879			MOVF	STACK_9, 0
$0568	$00F1			MOVWF	STACK_1
$0569	$3030			MOVLW	48
$056A	$0770			ADDWF	STACK_0, 0
$056B	$0080			MOVWF	INDF
;conv.ppas,46 :: 		
;conv.ppas,47 :: 		
$056C	$0384			DECF	FSR, 1
;conv.ppas,48 :: 		
$056D	$300A			MOVLW	10
$056E	$00F4			MOVWF	STACK_4
$056F	$01F5			CLRF	STACK_4+1
$0570	$0841			MOVF	FARG_WordToStr, 0
$0571	$00F0			MOVWF	STACK_0
$0572	$0842			MOVF	FARG_WordToStr+1, 0
$0573	$00F1			MOVWF	STACK_0+1
$0574	$2665			CALL	_div_16x16_u
$0575	$0870			MOVF	STACK_0, 0
$0576	$00C1			MOVWF	FARG_WordToStr
$0577	$0871			MOVF	STACK_0+1, 0
$0578	$00C2			MOVWF	FARG_WordToStr+1
;conv.ppas,49 :: 		
$0579	$03C4			DECF	_wordtostr_local_len, 1
;conv.ppas,50 :: 		
$057A	$2D59			GOTO	conv_L_28
$057B	$	conv_L_29:
$057B	$	conv_L_13:
;conv.ppas,51 :: 		
$057B	$0008			RETURN
$05FC	$	_lcd_chr:
;lcd.ppas,78 :: 		
;lcd.ppas,80 :: 		
$05FC	$	lcd_L_37:
$05FC	$1303			BCF	STATUS, RP1
$05FD	$1283			BCF	STATUS, RP0
$05FE	$0841			MOVF	FARG_Lcd_Chr, 0
$05FF	$3A01			XORLW	1
$0600	$1D03			BTFSS	STATUS, Z
$0601	$2E05			GOTO	lcd_L_38
$0602	$	lcd_L_36:
$0602	$3080			MOVLW	128
$0603	$00C1			MOVWF	FARG_Lcd_Chr
$0604	$2E1C			GOTO	lcd_L_35
$0605	$	lcd_L_38:
;lcd.ppas,81 :: 		
$0605	$	lcd_L_40:
$0605	$0841			MOVF	FARG_Lcd_Chr, 0
$0606	$3A02			XORLW	2
$0607	$1D03			BTFSS	STATUS, Z
$0608	$2E0C			GOTO	lcd_L_41
$0609	$	lcd_L_39:
$0609	$30C0			MOVLW	192
$060A	$00C1			MOVWF	FARG_Lcd_Chr
$060B	$2E1C			GOTO	lcd_L_35
$060C	$	lcd_L_41:
;lcd.ppas,82 :: 		
$060C	$	lcd_L_43:
$060C	$0841			MOVF	FARG_Lcd_Chr, 0
$060D	$3A03			XORLW	3
$060E	$1D03			BTFSS	STATUS, Z
$060F	$2E13			GOTO	lcd_L_44
$0610	$	lcd_L_42:
$0610	$3094			MOVLW	148
$0611	$00C1			MOVWF	FARG_Lcd_Chr
$0612	$2E1C			GOTO	lcd_L_35
$0613	$	lcd_L_44:
;lcd.ppas,83 :: 		
$0613	$	lcd_L_46:
$0613	$0841			MOVF	FARG_Lcd_Chr, 0
$0614	$3A04			XORLW	4
$0615	$1D03			BTFSS	STATUS, Z
$0616	$2E1A			GOTO	lcd_L_47
$0617	$	lcd_L_45:
$0617	$30D4			MOVLW	212
$0618	$00C1			MOVWF	FARG_Lcd_Chr
;lcd.ppas,84 :: 		
$0619	$2E1C			GOTO	lcd_L_35
$061A	$	lcd_L_47:
$061A	$3080			MOVLW	128
$061B	$00C1			MOVWF	FARG_Lcd_Chr
$061C	$	lcd_L_35:
;lcd.ppas,86 :: 		
$061C	$0842			MOVF	FARG_Lcd_Chr+1, 0
$061D	$0741			ADDWF	FARG_Lcd_Chr, 0
$061E	$00F0			MOVWF	STACK_0
$061F	$03F0			DECF	STACK_0, 1
$0620	$0870			MOVF	STACK_0, 0
$0621	$00C1			MOVWF	FARG_Lcd_Chr
;lcd.ppas,88 :: 		
$0622	$3001			MOVLW	1
$0623	$00A9			MOVWF	lcd_lcdcmd_status
;lcd.ppas,89 :: 		
$0624	$0870			MOVF	STACK_0, 0
$0625	$00E1			MOVWF	FARG_Lcd_Cmd
$0626	$2364			CALL	_lcd_cmd
;lcd.ppas,91 :: 		
$0627	$01A9			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,92 :: 		
$0628	$0843			MOVF	FARG_Lcd_Chr+2, 0
$0629	$00E1			MOVWF	FARG_Lcd_Cmd
$062A	$2364			CALL	_lcd_cmd
;lcd.ppas,93 :: 		
$062B	$3001			MOVLW	1
$062C	$00A9			MOVWF	lcd_lcdcmd_status
$062D	$	lcd_L_34:
;lcd.ppas,94 :: 		
$062D	$0008			RETURN
$062E	$	_mul_32x32_u:
$062E	$1303			BCF	STATUS, RP1
$062F	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$0630	$3022			MOVLW	34
;math.ppas,1579 :: 		
$0631	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$0632	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$0633	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$0634	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$0635	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$0636	$	_NEXT:
;math.ppas,1589 :: 		
$0636	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$0637	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$0638	$2E64			GOTO	_EXIT2
;math.ppas,1593 :: 		
$0639	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$063A	$	_LOOP:
;math.ppas,1603 :: 		
$063A	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$063B	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$063C	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$063D	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$063E	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$063F	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$0640	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$0641	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$0642	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$0643	$2E36			GOTO	_NEXT
;math.ppas,1617 :: 		
$0644	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$0645	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$0646	$2E56			GOTO	_EXIT1
;math.ppas,1626 :: 		
$0647	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$0648	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$0649	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$064A	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$064B	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$064C	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$064D	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$064E	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$064F	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$0650	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$0651	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$0652	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$0653	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$0654	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$0655	$2E3A			GOTO	_LOOP
;math.ppas,1647 :: 		
$0656	$	_EXIT1:
;math.ppas,1648 :: 		
$0656	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$0657	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$0658	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$0659	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$065A	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$065B	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$065C	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$065D	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$065E	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$065F	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$0660	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$0661	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$0662	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$0663	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$0664	$	_EXIT2:
;math.ppas,1665 :: 		
$0664	$	math_L_13:
;math.ppas,1666 :: 		
$0664	$0008			RETURN
$040B	$	_div_32x32_s:
$040B	$1303			BCF	STATUS, RP1
$040C	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$040D	$	FXD3232S:
;math.ppas,929 :: 		
$040D	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$040E	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$040F	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$0410	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$0411	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$0412	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$0413	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$0414	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$0415	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$0416	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$0417	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$0418	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0419	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$041A	$2C9F			GOTO	END_ALL
;math.ppas,944 :: 		
$041B	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$041C	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$041D	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$041E	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$041F	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$0420	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$0421	$2C2D			GOTO	CA3232S
;math.ppas,955 :: 		
$0422	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$0423	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$0424	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$0425	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$0426	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$0427	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$0428	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0429	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$042A	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$042B	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$042C	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$042D	$	CA3232S:
;math.ppas,968 :: 		
$042D	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$042E	$2C3A			GOTO	C3232SX
;math.ppas,971 :: 		
$042F	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$0430	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$0431	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$0432	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$0433	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$0434	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$0435	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$0436	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$0437	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$0438	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$0439	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$043A	$	C3232SX:
;math.ppas,984 :: 		
$043A	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$043B	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$043C	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$043D	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$043E	$2C5B			GOTO	C3232SX1
;math.ppas,989 :: 		
$043F	$	C3232S:
;math.ppas,992 :: 		
$043F	$2236			CALL	_sdiv3232l
;math.ppas,995 :: 		
$0440	$	C3232S2:
;math.ppas,996 :: 		
$0440	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$0441	$2C78			GOTO	C3232SX4
;math.ppas,998 :: 		
$0442	$	C3232SOK:
;math.ppas,999 :: 		
$0442	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$0443	$2C9F			GOTO	END_ALL
;math.ppas,1001 :: 		
$0444	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$0445	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$0446	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$0447	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$0448	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$0449	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$044A	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$044B	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$044C	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$044D	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$044E	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$044F	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$0450	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$0451	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$0452	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$0453	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$0454	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$0455	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$0456	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$0457	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$0458	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$0459	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$045A	$2C9F			GOTO	END_ALL
;math.ppas,1026 :: 		
$045B	$	C3232SX1:
;math.ppas,1027 :: 		
$045B	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$045C	$2C72			GOTO	C3232SX3
;math.ppas,1029 :: 		
$045D	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$045E	$2C6C			GOTO	C3232SX2
;math.ppas,1031 :: 		
$045F	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$0460	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$0461	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$0462	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$0463	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$0464	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$0465	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$0466	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$0467	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$0468	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$0469	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$046A	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$046B	$2C42			GOTO	C3232SOK
;math.ppas,1044 :: 		
$046C	$	C3232SX2:
;math.ppas,1045 :: 		
$046C	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$046D	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$046E	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$046F	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$0470	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$0471	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$0472	$	C3232SX3:
;math.ppas,1053 :: 		
$0472	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$0473	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$0474	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$0475	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$0476	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$0477	$2C3F			GOTO	C3232S
;math.ppas,1061 :: 		
$0478	$	C3232SX4:
;math.ppas,1062 :: 		
$0478	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0479	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$047A	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$047B	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$047C	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$047D	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$047E	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$047F	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$0480	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$0481	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$0482	$2C42			GOTO	C3232SOK
;math.ppas,1073 :: 		
$0483	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$0484	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$0485	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$0486	$2C42			GOTO	C3232SOK
;math.ppas,1077 :: 		
$0487	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$0488	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$0489	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$048A	$2C42			GOTO	C3232SOK
;math.ppas,1081 :: 		
$048B	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$048C	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$048D	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$048E	$2C42			GOTO	C3232SOK
;math.ppas,1085 :: 		
$048F	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$0490	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$0491	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$0492	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$0493	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$0494	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$0495	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$0496	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$0497	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$0498	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0499	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$049A	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$049B	$2C42			GOTO	C3232SOK
;math.ppas,1098 :: 		
$049C	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$049D	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$049E	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$049F	$	END_ALL:
;math.ppas,1102 :: 		
$049F	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$04A0	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$04A1	$2CA3			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$04A2	$26A9			CALL	_comfrem
;math.ppas,1108 :: 		
$04A3	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$04A3	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$04A4	$	math_L_11:
;math.ppas,1111 :: 		
$04A4	$0008			RETURN
$0004	$	_main:
;Temp.ppas,17 :: 		begin
;Temp.ppas,18 :: 		init();
$0004	$24A5			CALL	_init
;Temp.ppas,19 :: 		Lcd_Out(1,1,'Mesure  :');
$0005	$3001			MOVLW	1
$0006	$00D4			MOVWF	FARG_Lcd_Out
$0007	$3001			MOVLW	1
$0008	$00D5			MOVWF	FARG_Lcd_Out+1
$0009	$304D			MOVLW	77
$000A	$00B7			MOVWF	?main_Local_Text+0
$000B	$3065			MOVLW	101
$000C	$00B8			MOVWF	?main_Local_Text+1
$000D	$3073			MOVLW	115
$000E	$00B9			MOVWF	?main_Local_Text+2
$000F	$3075			MOVLW	117
$0010	$00BA			MOVWF	?main_Local_Text+3
$0011	$3072			MOVLW	114
$0012	$00BB			MOVWF	?main_Local_Text+4
$0013	$3065			MOVLW	101
$0014	$00BC			MOVWF	?main_Local_Text+5
$0015	$3020			MOVLW	32
$0016	$00BD			MOVWF	?main_Local_Text+6
$0017	$3020			MOVLW	32
$0018	$00BE			MOVWF	?main_Local_Text+7
$0019	$303A			MOVLW	58
$001A	$00BF			MOVWF	?main_Local_Text+8
$001B	$01C0			CLRF	?main_Local_Text+9
$001C	$3037			MOVLW	?main_Local_Text
$001D	$00D6			MOVWF	FARG_Lcd_Out+2
$001E	$257C			CALL	_lcd_out
;Temp.ppas,20 :: 		Lcd_Out(2,1,'Tension :');
$001F	$3002			MOVLW	2
$0020	$00D4			MOVWF	FARG_Lcd_Out
$0021	$3001			MOVLW	1
$0022	$00D5			MOVWF	FARG_Lcd_Out+1
$0023	$3054			MOVLW	84
$0024	$00B7			MOVWF	?main_Local_Text+0
$0025	$3065			MOVLW	101
$0026	$00B8			MOVWF	?main_Local_Text+1
$0027	$306E			MOVLW	110
$0028	$00B9			MOVWF	?main_Local_Text+2
$0029	$3073			MOVLW	115
$002A	$00BA			MOVWF	?main_Local_Text+3
$002B	$3069			MOVLW	105
$002C	$00BB			MOVWF	?main_Local_Text+4
$002D	$306F			MOVLW	111
$002E	$00BC			MOVWF	?main_Local_Text+5
$002F	$306E			MOVLW	110
$0030	$00BD			MOVWF	?main_Local_Text+6
$0031	$3020			MOVLW	32
$0032	$00BE			MOVWF	?main_Local_Text+7
$0033	$303A			MOVLW	58
$0034	$00BF			MOVWF	?main_Local_Text+8
$0035	$01C0			CLRF	?main_Local_Text+9
$0036	$3037			MOVLW	?main_Local_Text
$0037	$00D6			MOVWF	FARG_Lcd_Out+2
$0038	$257C			CALL	_lcd_out
;Temp.ppas,21 :: 		while(1) do
$0039	$	Temp_L_3:
;Temp.ppas,23 :: 		res:=Adc_Read(0);
$0039	$01C1			CLRF	FARG_ADC_read, 1
$003A	$25BB			CALL	_adc_read
$003B	$0870			MOVF	STACK_0, 0
$003C	$00AB			MOVWF	_res
$003D	$0871			MOVF	STACK_0+1, 0
$003E	$00AC			MOVWF	_res+1
;Temp.ppas,24 :: 		WordtoStr(res,txt);
$003F	$0870			MOVF	STACK_0, 0
$0040	$00C1			MOVWF	FARG_WordToStr
$0041	$0871			MOVF	STACK_0+1, 0
$0042	$00C2			MOVWF	FARG_WordToStr+1
$0043	$302D			MOVLW	_txt
$0044	$00C3			MOVWF	FARG_WordToStr+2
$0045	$2522			CALL	_wordtostr
;Temp.ppas,25 :: 		Lcd_Out(1,10,txt);
$0046	$3001			MOVLW	1
$0047	$00D4			MOVWF	FARG_Lcd_Out
$0048	$300A			MOVLW	10
$0049	$00D5			MOVWF	FARG_Lcd_Out+1
$004A	$302D			MOVLW	_txt
$004B	$00D6			MOVWF	FARG_Lcd_Out+2
$004C	$257C			CALL	_lcd_out
;Temp.ppas,26 :: 		temp:=(res*500)/1023;
$004D	$082B			MOVF	_res, 0
$004E	$00F0			MOVWF	STACK_0
$004F	$082C			MOVF	_res+1, 0
$0050	$00F1			MOVWF	STACK_0+1
$0051	$01F2			CLRF	STACK_0+2
$0052	$01F3			CLRF	STACK_0+3
$0053	$30F4			MOVLW	244
$0054	$00F4			MOVWF	STACK_4
$0055	$3001			MOVLW	1
$0056	$00F5			MOVWF	STACK_4+1
$0057	$01F6			CLRF	STACK_4+2
$0058	$01F7			CLRF	STACK_4+3
$0059	$262E			CALL	_mul_32x32_u
$005A	$30FF			MOVLW	255
$005B	$00F4			MOVWF	STACK_4
$005C	$3003			MOVLW	3
$005D	$00F5			MOVWF	STACK_4+1
$005E	$01F6			CLRF	STACK_4+2
$005F	$01F7			CLRF	STACK_4+3
$0060	$240B			CALL	_div_32x32_s
$0061	$0870			MOVF	STACK_0, 0
$0062	$00B3			MOVWF	_temp
$0063	$0871			MOVF	STACK_0+1, 0
$0064	$00B4			MOVWF	_temp+1
$0065	$0872			MOVF	STACK_0+2, 0
$0066	$00B5			MOVWF	_temp+2
$0067	$0873			MOVF	STACK_0+3, 0
$0068	$00B6			MOVWF	_temp+3
;Temp.ppas,28 :: 		Lcd_Chr(2,11,(temp/100)+48);
$0069	$3002			MOVLW	2
$006A	$00C1			MOVWF	FARG_Lcd_Chr
$006B	$300B			MOVLW	11
$006C	$00C2			MOVWF	FARG_Lcd_Chr+1
$006D	$3064			MOVLW	100
$006E	$00F4			MOVWF	STACK_4
$006F	$01F5			CLRF	STACK_4+1
$0070	$01F6			CLRF	STACK_4+2
$0071	$01F7			CLRF	STACK_4+3
$0072	$240B			CALL	_div_32x32_s
$0073	$3030			MOVLW	48
$0074	$00F4			MOVWF	STACK_4
$0075	$01F5			CLRF	STACK_4+1
$0076	$01F6			CLRF	STACK_4+2
$0077	$01F7			CLRF	STACK_4+3
$0078	$0874			MOVF	STACK_4, 0
$0079	$07F0			ADDWF	STACK_0, 1
$007A	$0875			MOVF	STACK_4+1, 0
$007B	$1803			BTFSC	STATUS, C
$007C	$0F75			INCFSZ	STACK_4+1, 0
$007D	$07F1			ADDWF	STACK_0+1, 1
$007E	$0876			MOVF	STACK_4+2, 0
$007F	$1803			BTFSC	STATUS, C
$0080	$0F76			INCFSZ	STACK_4+2, 0
$0081	$07F2			ADDWF	STACK_0+2, 1
$0082	$0877			MOVF	STACK_4+3, 0
$0083	$1803			BTFSC	STATUS, C
$0084	$0F77			INCFSZ	STACK_4+3, 0
$0085	$07F3			ADDWF	STACK_0+3, 1
$0086	$0870			MOVF	STACK_0, 0
$0087	$00C3			MOVWF	FARG_Lcd_Chr+2
$0088	$25FC			CALL	_lcd_chr
;Temp.ppas,31 :: 		Lcd_Chr(2,12,',');
$0089	$3002			MOVLW	2
$008A	$00C1			MOVWF	FARG_Lcd_Chr
$008B	$300C			MOVLW	12
$008C	$00C2			MOVWF	FARG_Lcd_Chr+1
$008D	$302C			MOVLW	44
$008E	$00C3			MOVWF	FARG_Lcd_Chr+2
$008F	$25FC			CALL	_lcd_chr
;Temp.ppas,32 :: 		Lcd_Chr(2,13,((temp mod 100)/10)+48);
$0090	$3002			MOVLW	2
$0091	$00C1			MOVWF	FARG_Lcd_Chr
$0092	$300D			MOVLW	13
$0093	$00C2			MOVWF	FARG_Lcd_Chr+1
$0094	$3064			MOVLW	100
$0095	$00F4			MOVWF	STACK_4
$0096	$01F5			CLRF	STACK_4+1
$0097	$01F6			CLRF	STACK_4+2
$0098	$01F7			CLRF	STACK_4+3
$0099	$0833			MOVF	_temp, 0
$009A	$00F0			MOVWF	STACK_0
$009B	$0834			MOVF	_temp+1, 0
$009C	$00F1			MOVWF	STACK_0+1
$009D	$0835			MOVF	_temp+2, 0
$009E	$00F2			MOVWF	STACK_0+2
$009F	$0836			MOVF	_temp+3, 0
$00A0	$00F3			MOVWF	STACK_0+3
$00A1	$240B			CALL	_div_32x32_s
$00A2	$0878			MOVF	STACK_8, 0
$00A3	$00F0			MOVWF	STACK_0
$00A4	$0879			MOVF	STACK_9, 0
$00A5	$00F1			MOVWF	STACK_1
$00A6	$087A			MOVF	STACK_10, 0
$00A7	$00F2			MOVWF	STACK_2
$00A8	$087B			MOVF	STACK_11, 0
$00A9	$00F3			MOVWF	STACK_3
$00AA	$300A			MOVLW	10
$00AB	$00F4			MOVWF	STACK_4
$00AC	$01F5			CLRF	STACK_4+1
$00AD	$01F6			CLRF	STACK_4+2
$00AE	$01F7			CLRF	STACK_4+3
$00AF	$240B			CALL	_div_32x32_s
$00B0	$3030			MOVLW	48
$00B1	$00F4			MOVWF	STACK_4
$00B2	$01F5			CLRF	STACK_4+1
$00B3	$01F6			CLRF	STACK_4+2
$00B4	$01F7			CLRF	STACK_4+3
$00B5	$0874			MOVF	STACK_4, 0
$00B6	$07F0			ADDWF	STACK_0, 1
$00B7	$0875			MOVF	STACK_4+1, 0
$00B8	$1803			BTFSC	STATUS, C
$00B9	$0F75			INCFSZ	STACK_4+1, 0
$00BA	$07F1			ADDWF	STACK_0+1, 1
$00BB	$0876			MOVF	STACK_4+2, 0
$00BC	$1803			BTFSC	STATUS, C
$00BD	$0F76			INCFSZ	STACK_4+2, 0
$00BE	$07F2			ADDWF	STACK_0+2, 1
$00BF	$0877			MOVF	STACK_4+3, 0
$00C0	$1803			BTFSC	STATUS, C
$00C1	$0F77			INCFSZ	STACK_4+3, 0
$00C2	$07F3			ADDWF	STACK_0+3, 1
$00C3	$0870			MOVF	STACK_0, 0
$00C4	$00C3			MOVWF	FARG_Lcd_Chr+2
$00C5	$25FC			CALL	_lcd_chr
;Temp.ppas,33 :: 		Lcd_Chr(2,14,(temp mod 10)+48);
$00C6	$3002			MOVLW	2
$00C7	$00C1			MOVWF	FARG_Lcd_Chr
$00C8	$300E			MOVLW	14
$00C9	$00C2			MOVWF	FARG_Lcd_Chr+1
$00CA	$300A			MOVLW	10
$00CB	$00F4			MOVWF	STACK_4
$00CC	$01F5			CLRF	STACK_4+1
$00CD	$01F6			CLRF	STACK_4+2
$00CE	$01F7			CLRF	STACK_4+3
$00CF	$0833			MOVF	_temp, 0
$00D0	$00F0			MOVWF	STACK_0
$00D1	$0834			MOVF	_temp+1, 0
$00D2	$00F1			MOVWF	STACK_0+1
$00D3	$0835			MOVF	_temp+2, 0
$00D4	$00F2			MOVWF	STACK_0+2
$00D5	$0836			MOVF	_temp+3, 0
$00D6	$00F3			MOVWF	STACK_0+3
$00D7	$240B			CALL	_div_32x32_s
$00D8	$0878			MOVF	STACK_8, 0
$00D9	$00F0			MOVWF	STACK_0
$00DA	$0879			MOVF	STACK_9, 0
$00DB	$00F1			MOVWF	STACK_1
$00DC	$087A			MOVF	STACK_10, 0
$00DD	$00F2			MOVWF	STACK_2
$00DE	$087B			MOVF	STACK_11, 0
$00DF	$00F3			MOVWF	STACK_3
$00E0	$3030			MOVLW	48
$00E1	$00F4			MOVWF	STACK_4
$00E2	$01F5			CLRF	STACK_4+1
$00E3	$01F6			CLRF	STACK_4+2
$00E4	$01F7			CLRF	STACK_4+3
$00E5	$0874			MOVF	STACK_4, 0
$00E6	$07F0			ADDWF	STACK_0, 1
$00E7	$0875			MOVF	STACK_4+1, 0
$00E8	$1803			BTFSC	STATUS, C
$00E9	$0F75			INCFSZ	STACK_4+1, 0
$00EA	$07F1			ADDWF	STACK_0+1, 1
$00EB	$0876			MOVF	STACK_4+2, 0
$00EC	$1803			BTFSC	STATUS, C
$00ED	$0F76			INCFSZ	STACK_4+2, 0
$00EE	$07F2			ADDWF	STACK_0+2, 1
$00EF	$0877			MOVF	STACK_4+3, 0
$00F0	$1803			BTFSC	STATUS, C
$00F1	$0F77			INCFSZ	STACK_4+3, 0
$00F2	$07F3			ADDWF	STACK_0+3, 1
$00F3	$0870			MOVF	STACK_0, 0
$00F4	$00C3			MOVWF	FARG_Lcd_Chr+2
$00F5	$25FC			CALL	_lcd_chr
;Temp.ppas,34 :: 		delay_ms(100);
$00F6	$3002			MOVLW	2
$00F7	$00FC			MOVWF	STACK_12
$00F8	$30FF			MOVLW	255
$00F9	$00FB			MOVWF	STACK_11
$00FA	$30FF			MOVLW	255
$00FB	$00FA			MOVWF	STACK_10
$00FC	$0BFC			DECFSZ	STACK_12, F
$00FD	$28FF			GOTO	$+2
$00FE	$2906			GOTO	$+8
$00FF	$0BFB			DECFSZ	STACK_11, F
$0100	$2902			GOTO	$+2
$0101	$2905			GOTO	$+4
$0102	$0BFA			DECFSZ	STACK_10, F
$0103	$2902			GOTO	$-1
$0104	$28FF			GOTO	$-5
$0105	$28FC			GOTO	$-9
$0106	$3006			MOVLW	6
$0107	$00FB			MOVWF	STACK_11
$0108	$30FF			MOVLW	255
$0109	$00FA			MOVWF	STACK_10
$010A	$0BFB			DECFSZ	STACK_11, F
$010B	$290D			GOTO	$+2
$010C	$2910			GOTO	$+4
$010D	$0BFA			DECFSZ	STACK_10, F
$010E	$290D			GOTO	$-1
$010F	$290A			GOTO	$-5
$0110	$300A			MOVLW	10
$0111	$00FA			MOVWF	STACK_10
$0112	$0BFA			DECFSZ	STACK_10, F
$0113	$2912			GOTO	$-1
$0114	$0000			NOP
;Temp.ppas,36 :: 		end;
$0115	$2839			GOTO	Temp_L_3
;Temp.ppas,42 :: 		end.
$0116	$2916			GOTO	$
