;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 07/06/2021 13:42:10
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2A51			GOTO	_main
$0660	$	_delay_1us:
;delays.ppas,11 :: 		begin
;delays.ppas,12 :: 		Delay_us(1);
$0660	$0000			NOP
$0661	$0000			NOP
$0662	$	delays_L_1:
;delays.ppas,13 :: 		end;
$0662	$0008			RETURN
$0628	$	_delay_5500us:
;delays.ppas,41 :: 		begin
;delays.ppas,42 :: 		Delay_us(5500);
$0628	$300F			MOVLW	15
$0629	$1303			BCF	STATUS, RP1
$062A	$1283			BCF	STATUS, RP0
$062B	$00FB			MOVWF	STACK_11
$062C	$30FF			MOVLW	255
$062D	$00FA			MOVWF	STACK_10
$062E	$0BFB			DECFSZ	STACK_11, F
$062F	$2E31			GOTO	$+2
$0630	$2E34			GOTO	$+4
$0631	$0BFA			DECFSZ	STACK_10, F
$0632	$2E31			GOTO	$-1
$0633	$2E2E			GOTO	$-5
$0634	$303E			MOVLW	62
$0635	$00FA			MOVWF	STACK_10
$0636	$0BFA			DECFSZ	STACK_10, F
$0637	$2E36			GOTO	$-1
$0638	$0000			NOP
$0639	$	delays_L_7:
;delays.ppas,43 :: 		end;
$0639	$0008			RETURN
$0659	$	_delay_50us:
;delays.ppas,26 :: 		begin
;delays.ppas,27 :: 		Delay_us(50);
$0659	$3021			MOVLW	33
$065A	$1303			BCF	STATUS, RP1
$065B	$1283			BCF	STATUS, RP0
$065C	$00FA			MOVWF	STACK_10
$065D	$0BFA			DECFSZ	STACK_10, F
$065E	$2E5D			GOTO	$-1
$065F	$	delays_L_4:
;delays.ppas,28 :: 		end;
$065F	$0008			RETURN
$02F1	$	_lcd_cmd:
;lcd.ppas,19 :: 		
;lcd.ppas,20 :: 		
$02F1	$1303			BCF	STATUS, RP1
$02F2	$1283			BCF	STATUS, RP0
$02F3	$0821			MOVF	lcd_ctrlport_address, 0
$02F4	$0084			MOVWF	FSR
;lcd.ppas,22 :: 		
$02F5	$0922			COMF	lcd____menable, W
$02F6	$00F0			MOVWF	STACK_0
$02F7	$0870			MOVF	STACK_0, 0
$02F8	$0580			ANDWF	INDF, 1
;lcd.ppas,23 :: 		
$02F9	$0923			COMF	lcd____mrs, W
$02FA	$00F0			MOVWF	STACK_0
$02FB	$0870			MOVF	STACK_0, 0
$02FC	$0580			ANDWF	INDF, 1
;lcd.ppas,25 :: 		
$02FD	$0824			MOVF	lcd_dataport_address, 0
$02FE	$0084			MOVWF	FSR
;lcd.ppas,26 :: 		
$02FF	$0826			MOVF	lcd____mdb6, 0
$0300	$0425			IORWF	lcd____mdb7, 0
$0301	$00F0			MOVWF	STACK_0
$0302	$0827			MOVF	lcd____mdb5, 0
$0303	$04F0			IORWF	STACK_0, 1
$0304	$0828			MOVF	lcd____mdb4, 0
$0305	$04F0			IORWF	STACK_0, 1
$0306	$09F0			COMF	STACK_0, F
$0307	$0870			MOVF	STACK_0, 0
$0308	$0580			ANDWF	INDF, 1
;lcd.ppas,28 :: 		
$0309	$3000			MOVLW	0
$030A	$1BE2			BTFSC	FARG_Lcd_Cmd, 7
$030B	$3001			MOVLW	1
$030C	$00F1			MOVWF	STACK_1
$030D	$0871			MOVF	STACK_1, 0
$030E	$3A01			XORLW	1
$030F	$1D03			BTFSS	STATUS, Z
$0310	$2B13			GOTO	lcd_L_2
$0311	$	lcd_L_1:
;lcd.ppas,29 :: 		
$0311	$0825			MOVF	lcd____mdb7, 0
$0312	$0480			IORWF	INDF, 1
$0313	$	lcd_L_2:
$0313	$	lcd_L_3:
;lcd.ppas,30 :: 		
$0313	$3000			MOVLW	0
$0314	$1B62			BTFSC	FARG_Lcd_Cmd, 6
$0315	$3001			MOVLW	1
$0316	$00F1			MOVWF	STACK_1
$0317	$0871			MOVF	STACK_1, 0
$0318	$3A01			XORLW	1
$0319	$1D03			BTFSS	STATUS, Z
$031A	$2B1D			GOTO	lcd_L_5
$031B	$	lcd_L_4:
;lcd.ppas,31 :: 		
$031B	$0826			MOVF	lcd____mdb6, 0
$031C	$0480			IORWF	INDF, 1
$031D	$	lcd_L_5:
$031D	$	lcd_L_6:
;lcd.ppas,32 :: 		
$031D	$3000			MOVLW	0
$031E	$1AE2			BTFSC	FARG_Lcd_Cmd, 5
$031F	$3001			MOVLW	1
$0320	$00F1			MOVWF	STACK_1
$0321	$0871			MOVF	STACK_1, 0
$0322	$3A01			XORLW	1
$0323	$1D03			BTFSS	STATUS, Z
$0324	$2B27			GOTO	lcd_L_8
$0325	$	lcd_L_7:
;lcd.ppas,33 :: 		
$0325	$0827			MOVF	lcd____mdb5, 0
$0326	$0480			IORWF	INDF, 1
$0327	$	lcd_L_8:
$0327	$	lcd_L_9:
;lcd.ppas,34 :: 		
$0327	$3000			MOVLW	0
$0328	$1A62			BTFSC	FARG_Lcd_Cmd, 4
$0329	$3001			MOVLW	1
$032A	$00F1			MOVWF	STACK_1
$032B	$0871			MOVF	STACK_1, 0
$032C	$3A01			XORLW	1
$032D	$1D03			BTFSS	STATUS, Z
$032E	$2B31			GOTO	lcd_L_11
$032F	$	lcd_L_10:
;lcd.ppas,35 :: 		
$032F	$0828			MOVF	lcd____mdb4, 0
$0330	$0480			IORWF	INDF, 1
$0331	$	lcd_L_11:
$0331	$	lcd_L_12:
;lcd.ppas,37 :: 		
$0331	$0821			MOVF	lcd_ctrlport_address, 0
$0332	$0084			MOVWF	FSR
;lcd.ppas,38 :: 		
$0333	$0829			MOVF	lcd_lcdcmd_status, 0
$0334	$3A01			XORLW	1
$0335	$1D03			BTFSS	STATUS, Z
$0336	$2B3C			GOTO	lcd_L_14
$0337	$	lcd_L_13:
;lcd.ppas,39 :: 		
$0337	$0923			COMF	lcd____mrs, W
$0338	$00F0			MOVWF	STACK_0
$0339	$0870			MOVF	STACK_0, 0
$033A	$0580			ANDWF	INDF, 1
$033B	$2B3E			GOTO	lcd_L_15
;lcd.ppas,40 :: 		
$033C	$	lcd_L_14:
;lcd.ppas,41 :: 		
$033C	$0823			MOVF	lcd____mrs, 0
$033D	$0480			IORWF	INDF, 1
$033E	$	lcd_L_15:
;lcd.ppas,43 :: 		
$033E	$0822			MOVF	lcd____menable, 0
$033F	$0480			IORWF	INDF, 1
;lcd.ppas,44 :: 		
$0340	$2660			CALL	_delay_1us
;lcd.ppas,45 :: 		
$0341	$0922			COMF	lcd____menable, W
$0342	$00F0			MOVWF	STACK_0
$0343	$0870			MOVF	STACK_0, 0
$0344	$0580			ANDWF	INDF, 1
;lcd.ppas,47 :: 		
$0345	$0923			COMF	lcd____mrs, W
$0346	$00F0			MOVWF	STACK_0
$0347	$0870			MOVF	STACK_0, 0
$0348	$0580			ANDWF	INDF, 1
;lcd.ppas,49 :: 		
$0349	$0824			MOVF	lcd_dataport_address, 0
$034A	$0084			MOVWF	FSR
;lcd.ppas,50 :: 		
$034B	$0826			MOVF	lcd____mdb6, 0
$034C	$0425			IORWF	lcd____mdb7, 0
$034D	$00F0			MOVWF	STACK_0
$034E	$0827			MOVF	lcd____mdb5, 0
$034F	$04F0			IORWF	STACK_0, 1
$0350	$0828			MOVF	lcd____mdb4, 0
$0351	$04F0			IORWF	STACK_0, 1
$0352	$09F0			COMF	STACK_0, F
$0353	$0870			MOVF	STACK_0, 0
$0354	$0580			ANDWF	INDF, 1
;lcd.ppas,52 :: 		
$0355	$3000			MOVLW	0
$0356	$19E2			BTFSC	FARG_Lcd_Cmd, 3
$0357	$3001			MOVLW	1
$0358	$00F1			MOVWF	STACK_1
$0359	$0871			MOVF	STACK_1, 0
$035A	$3A01			XORLW	1
$035B	$1D03			BTFSS	STATUS, Z
$035C	$2B5F			GOTO	lcd_L_17
$035D	$	lcd_L_16:
;lcd.ppas,53 :: 		
$035D	$0825			MOVF	lcd____mdb7, 0
$035E	$0480			IORWF	INDF, 1
$035F	$	lcd_L_17:
$035F	$	lcd_L_18:
;lcd.ppas,54 :: 		
$035F	$3000			MOVLW	0
$0360	$1962			BTFSC	FARG_Lcd_Cmd, 2
$0361	$3001			MOVLW	1
$0362	$00F1			MOVWF	STACK_1
$0363	$0871			MOVF	STACK_1, 0
$0364	$3A01			XORLW	1
$0365	$1D03			BTFSS	STATUS, Z
$0366	$2B69			GOTO	lcd_L_20
$0367	$	lcd_L_19:
;lcd.ppas,55 :: 		
$0367	$0826			MOVF	lcd____mdb6, 0
$0368	$0480			IORWF	INDF, 1
$0369	$	lcd_L_20:
$0369	$	lcd_L_21:
;lcd.ppas,56 :: 		
$0369	$3000			MOVLW	0
$036A	$18E2			BTFSC	FARG_Lcd_Cmd, 1
$036B	$3001			MOVLW	1
$036C	$00F1			MOVWF	STACK_1
$036D	$0871			MOVF	STACK_1, 0
$036E	$3A01			XORLW	1
$036F	$1D03			BTFSS	STATUS, Z
$0370	$2B73			GOTO	lcd_L_23
$0371	$	lcd_L_22:
;lcd.ppas,57 :: 		
$0371	$0827			MOVF	lcd____mdb5, 0
$0372	$0480			IORWF	INDF, 1
$0373	$	lcd_L_23:
$0373	$	lcd_L_24:
;lcd.ppas,58 :: 		
$0373	$3001			MOVLW	1
$0374	$0562			ANDWF	FARG_Lcd_Cmd, 0
$0375	$00F1			MOVWF	STACK_1
$0376	$0871			MOVF	STACK_1, 0
$0377	$3A01			XORLW	1
$0378	$1D03			BTFSS	STATUS, Z
$0379	$2B7C			GOTO	lcd_L_26
$037A	$	lcd_L_25:
;lcd.ppas,59 :: 		
$037A	$0828			MOVF	lcd____mdb4, 0
$037B	$0480			IORWF	INDF, 1
$037C	$	lcd_L_26:
$037C	$	lcd_L_27:
;lcd.ppas,61 :: 		
$037C	$0821			MOVF	lcd_ctrlport_address, 0
$037D	$0084			MOVWF	FSR
;lcd.ppas,62 :: 		
$037E	$0829			MOVF	lcd_lcdcmd_status, 0
$037F	$3A01			XORLW	1
$0380	$1D03			BTFSS	STATUS, Z
$0381	$2B87			GOTO	lcd_L_29
$0382	$	lcd_L_28:
;lcd.ppas,63 :: 		
$0382	$0923			COMF	lcd____mrs, W
$0383	$00F0			MOVWF	STACK_0
$0384	$0870			MOVF	STACK_0, 0
$0385	$0580			ANDWF	INDF, 1
$0386	$2B89			GOTO	lcd_L_30
;lcd.ppas,64 :: 		
$0387	$	lcd_L_29:
;lcd.ppas,65 :: 		
$0387	$0823			MOVF	lcd____mrs, 0
$0388	$0480			IORWF	INDF, 1
$0389	$	lcd_L_30:
;lcd.ppas,67 :: 		
$0389	$0822			MOVF	lcd____menable, 0
$038A	$0480			IORWF	INDF, 1
;lcd.ppas,68 :: 		
$038B	$2660			CALL	_delay_1us
;lcd.ppas,69 :: 		
$038C	$0922			COMF	lcd____menable, W
$038D	$00F0			MOVWF	STACK_0
$038E	$0870			MOVF	STACK_0, 0
$038F	$0580			ANDWF	INDF, 1
;lcd.ppas,71 :: 		
$0390	$0829			MOVF	lcd_lcdcmd_status, 0
$0391	$3A01			XORLW	1
$0392	$1D03			BTFSS	STATUS, Z
$0393	$2B96			GOTO	lcd_L_32
$0394	$	lcd_L_31:
;lcd.ppas,72 :: 		
$0394	$2628			CALL	_delay_5500us
$0395	$2B97			GOTO	lcd_L_33
;lcd.ppas,73 :: 		
$0396	$	lcd_L_32:
;lcd.ppas,74 :: 		
$0396	$2659			CALL	_delay_50us
$0397	$	lcd_L_33:
$0397	$	lcd_L_0:
;lcd.ppas,75 :: 		
$0397	$0008			RETURN
$0004	$	_lcd_config:
;lcd.ppas,115 :: 		
;lcd.ppas,116 :: 		
$0004	$2628			CALL	_delay_5500us
;lcd.ppas,117 :: 		
$0005	$2628			CALL	_delay_5500us
;lcd.ppas,118 :: 		
$0006	$2628			CALL	_delay_5500us
;lcd.ppas,120 :: 		
$0007	$085A			MOVF	FARG_Lcd_Config+1, 0
$0008	$00F0			MOVWF	STACK_0
$0009	$3001			MOVLW	1
$000A	$00F4			MOVWF	STACK_4
$000B	$0870			MOVF	STACK_0, 0
$000C	$	L_Lcd_Config_0:
$000C	$1903			BTFSC	STATUS, Z
$000D	$2812			GOTO	L_Lcd_Config_1
$000E	$0DF4			RLF	STACK_4, 1
$000F	$1074			BCF	STACK_4, 0
$0010	$3FFF			ADDLW	255
$0011	$280C			GOTO	L_Lcd_Config_0
$0012	$	L_Lcd_Config_1:
$0012	$0874			MOVF	STACK_4, 0
$0013	$00A5			MOVWF	lcd____mdb7
;lcd.ppas,121 :: 		
$0014	$085B			MOVF	FARG_Lcd_Config+2, 0
$0015	$00F0			MOVWF	STACK_0
$0016	$3001			MOVLW	1
$0017	$00F3			MOVWF	STACK_3
$0018	$0870			MOVF	STACK_0, 0
$0019	$	L_Lcd_Config_2:
$0019	$1903			BTFSC	STATUS, Z
$001A	$281F			GOTO	L_Lcd_Config_3
$001B	$0DF3			RLF	STACK_3, 1
$001C	$1073			BCF	STACK_3, 0
$001D	$3FFF			ADDLW	255
$001E	$2819			GOTO	L_Lcd_Config_2
$001F	$	L_Lcd_Config_3:
$001F	$0873			MOVF	STACK_3, 0
$0020	$00A6			MOVWF	lcd____mdb6
;lcd.ppas,122 :: 		
$0021	$085C			MOVF	FARG_Lcd_Config+3, 0
$0022	$00F0			MOVWF	STACK_0
$0023	$3001			MOVLW	1
$0024	$00F2			MOVWF	STACK_2
$0025	$0870			MOVF	STACK_0, 0
$0026	$	L_Lcd_Config_4:
$0026	$1903			BTFSC	STATUS, Z
$0027	$282C			GOTO	L_Lcd_Config_5
$0028	$0DF2			RLF	STACK_2, 1
$0029	$1072			BCF	STACK_2, 0
$002A	$3FFF			ADDLW	255
$002B	$2826			GOTO	L_Lcd_Config_4
$002C	$	L_Lcd_Config_5:
$002C	$0872			MOVF	STACK_2, 0
$002D	$00A7			MOVWF	lcd____mdb5
;lcd.ppas,123 :: 		
$002E	$085D			MOVF	FARG_Lcd_Config+4, 0
$002F	$00F0			MOVWF	STACK_0
$0030	$3001			MOVLW	1
$0031	$00F1			MOVWF	STACK_1
$0032	$0870			MOVF	STACK_0, 0
$0033	$	L_Lcd_Config_6:
$0033	$1903			BTFSC	STATUS, Z
$0034	$2839			GOTO	L_Lcd_Config_7
$0035	$0DF1			RLF	STACK_1, 1
$0036	$1071			BCF	STACK_1, 0
$0037	$3FFF			ADDLW	255
$0038	$2833			GOTO	L_Lcd_Config_6
$0039	$	L_Lcd_Config_7:
$0039	$0871			MOVF	STACK_1, 0
$003A	$00A8			MOVWF	lcd____mdb4
;lcd.ppas,124 :: 		
$003B	$085F			MOVF	FARG_Lcd_Config+6, 0
$003C	$00F0			MOVWF	STACK_0
$003D	$3001			MOVLW	1
$003E	$00A3			MOVWF	lcd____mrs
$003F	$0870			MOVF	STACK_0, 0
$0040	$	L_Lcd_Config_8:
$0040	$1903			BTFSC	STATUS, Z
$0041	$2846			GOTO	L_Lcd_Config_9
$0042	$0DA3			RLF	lcd____mrs, 1
$0043	$1023			BCF	lcd____mrs, 0
$0044	$3FFF			ADDLW	255
$0045	$2840			GOTO	L_Lcd_Config_8
$0046	$	L_Lcd_Config_9:
;lcd.ppas,125 :: 		
$0046	$0860			MOVF	FARG_Lcd_Config+7, 0
$0047	$00F0			MOVWF	STACK_0
$0048	$3001			MOVLW	1
$0049	$00AA			MOVWF	lcd____mrw
$004A	$0870			MOVF	STACK_0, 0
$004B	$	L_Lcd_Config_10:
$004B	$1903			BTFSC	STATUS, Z
$004C	$2851			GOTO	L_Lcd_Config_11
$004D	$0DAA			RLF	lcd____mrw, 1
$004E	$102A			BCF	lcd____mrw, 0
$004F	$3FFF			ADDLW	255
$0050	$284B			GOTO	L_Lcd_Config_10
$0051	$	L_Lcd_Config_11:
;lcd.ppas,126 :: 		
$0051	$0861			MOVF	FARG_Lcd_Config+8, 0
$0052	$00F0			MOVWF	STACK_0
$0053	$3001			MOVLW	1
$0054	$00A2			MOVWF	lcd____menable
$0055	$0870			MOVF	STACK_0, 0
$0056	$	L_Lcd_Config_12:
$0056	$1903			BTFSC	STATUS, Z
$0057	$285C			GOTO	L_Lcd_Config_13
$0058	$0DA2			RLF	lcd____menable, 1
$0059	$1022			BCF	lcd____menable, 0
$005A	$3FFF			ADDLW	255
$005B	$2856			GOTO	L_Lcd_Config_12
$005C	$	L_Lcd_Config_13:
;lcd.ppas,128 :: 		
$005C	$0859			MOVF	FARG_Lcd_Config, 0
$005D	$00A4			MOVWF	lcd_dataport_address
;lcd.ppas,129 :: 		
$005E	$085E			MOVF	FARG_Lcd_Config+5, 0
$005F	$00A1			MOVWF	lcd_ctrlport_address
;lcd.ppas,131 :: 		
$0060	$0859			MOVF	FARG_Lcd_Config, 0
$0061	$0084			MOVWF	FSR
;lcd.ppas,133 :: 		
$0062	$0873			MOVF	STACK_3, 0
$0063	$0474			IORWF	STACK_4, 0
$0064	$00F0			MOVWF	STACK_0
$0065	$0872			MOVF	STACK_2, 0
$0066	$04F0			IORWF	STACK_0, 1
$0067	$0871			MOVF	STACK_1, 0
$0068	$04F0			IORWF	STACK_0, 1
$0069	$09F0			COMF	STACK_0, F
$006A	$0870			MOVF	STACK_0, 0
$006B	$0580			ANDWF	INDF, 1
;lcd.ppas,134 :: 		
$006C	$	lcd_L_56:
$006C	$1784			BSF	FSR, 7
$006D	$	lcd_L_57:
;lcd.ppas,135 :: 		
$006D	$0826			MOVF	lcd____mdb6, 0
$006E	$0425			IORWF	lcd____mdb7, 0
$006F	$00F0			MOVWF	STACK_0
$0070	$0827			MOVF	lcd____mdb5, 0
$0071	$04F0			IORWF	STACK_0, 1
$0072	$0828			MOVF	lcd____mdb4, 0
$0073	$04F0			IORWF	STACK_0, 1
$0074	$09F0			COMF	STACK_0, F
$0075	$0870			MOVF	STACK_0, 0
$0076	$0580			ANDWF	INDF, 1
;lcd.ppas,136 :: 		
$0077	$1384			BCF	FSR, 7
$0078	$	lcd_L_59:
;lcd.ppas,139 :: 		
$0078	$0821			MOVF	lcd_ctrlport_address, 0
$0079	$0084			MOVWF	FSR
;lcd.ppas,141 :: 		
$007A	$082A			MOVF	lcd____mrw, 0
$007B	$0423			IORWF	lcd____mrs, 0
$007C	$00F0			MOVWF	STACK_0
$007D	$0822			MOVF	lcd____menable, 0
$007E	$04F0			IORWF	STACK_0, 1
$007F	$09F0			COMF	STACK_0, F
$0080	$0870			MOVF	STACK_0, 0
$0081	$0580			ANDWF	INDF, 1
;lcd.ppas,142 :: 		
$0082	$	lcd_L_60:
$0082	$1784			BSF	FSR, 7
$0083	$	lcd_L_61:
;lcd.ppas,143 :: 		
$0083	$082A			MOVF	lcd____mrw, 0
$0084	$0423			IORWF	lcd____mrs, 0
$0085	$00F0			MOVWF	STACK_0
$0086	$0822			MOVF	lcd____menable, 0
$0087	$04F0			IORWF	STACK_0, 1
$0088	$09F0			COMF	STACK_0, F
$0089	$0870			MOVF	STACK_0, 0
$008A	$0580			ANDWF	INDF, 1
;lcd.ppas,144 :: 		
$008B	$1384			BCF	FSR, 7
$008C	$	lcd_L_63:
;lcd.ppas,148 :: 		
$008C	$0824			MOVF	lcd_dataport_address, 0
$008D	$0084			MOVWF	FSR
;lcd.ppas,149 :: 		
$008E	$0827			MOVF	lcd____mdb5, 0
$008F	$0400			IORWF	INDF, 0
$0090	$00F0			MOVWF	STACK_0
$0091	$0828			MOVF	lcd____mdb4, 0
$0092	$0470			IORWF	STACK_0, 0
$0093	$0080			MOVWF	INDF
;lcd.ppas,151 :: 		
$0094	$0821			MOVF	lcd_ctrlport_address, 0
$0095	$0084			MOVWF	FSR
;lcd.ppas,152 :: 		
$0096	$0822			MOVF	lcd____menable, 0
$0097	$0480			IORWF	INDF, 1
;lcd.ppas,153 :: 		
$0098	$0922			COMF	lcd____menable, W
$0099	$00F0			MOVWF	STACK_0
$009A	$0870			MOVF	STACK_0, 0
$009B	$0580			ANDWF	INDF, 1
;lcd.ppas,155 :: 		
$009C	$2628			CALL	_delay_5500us
;lcd.ppas,160 :: 		
$009D	$0822			MOVF	lcd____menable, 0
$009E	$0480			IORWF	INDF, 1
;lcd.ppas,161 :: 		
$009F	$0922			COMF	lcd____menable, W
$00A0	$00F0			MOVWF	STACK_0
$00A1	$0870			MOVF	STACK_0, 0
$00A2	$0580			ANDWF	INDF, 1
;lcd.ppas,163 :: 		
$00A3	$2628			CALL	_delay_5500us
;lcd.ppas,168 :: 		
$00A4	$0822			MOVF	lcd____menable, 0
$00A5	$0480			IORWF	INDF, 1
;lcd.ppas,169 :: 		
$00A6	$0922			COMF	lcd____menable, W
$00A7	$00F0			MOVWF	STACK_0
$00A8	$0870			MOVF	STACK_0, 0
$00A9	$0580			ANDWF	INDF, 1
;lcd.ppas,171 :: 		
$00AA	$2628			CALL	_delay_5500us
;lcd.ppas,174 :: 		
$00AB	$0824			MOVF	lcd_dataport_address, 0
$00AC	$0084			MOVWF	FSR
;lcd.ppas,175 :: 		
$00AD	$0827			MOVF	lcd____mdb5, 0
$00AE	$0480			IORWF	INDF, 1
;lcd.ppas,176 :: 		
$00AF	$0928			COMF	lcd____mdb4, W
$00B0	$00F0			MOVWF	STACK_0
$00B1	$0870			MOVF	STACK_0, 0
$00B2	$0580			ANDWF	INDF, 1
;lcd.ppas,178 :: 		
$00B3	$0821			MOVF	lcd_ctrlport_address, 0
$00B4	$0084			MOVWF	FSR
;lcd.ppas,179 :: 		
$00B5	$0822			MOVF	lcd____menable, 0
$00B6	$0480			IORWF	INDF, 1
;lcd.ppas,180 :: 		
$00B7	$0922			COMF	lcd____menable, W
$00B8	$00F0			MOVWF	STACK_0
$00B9	$0870			MOVF	STACK_0, 0
$00BA	$0580			ANDWF	INDF, 1
;lcd.ppas,182 :: 		
$00BB	$2628			CALL	_delay_5500us
;lcd.ppas,187 :: 		
$00BC	$0822			MOVF	lcd____menable, 0
$00BD	$0480			IORWF	INDF, 1
;lcd.ppas,188 :: 		
$00BE	$0922			COMF	lcd____menable, W
$00BF	$00F1			MOVWF	STACK_1
$00C0	$0871			MOVF	STACK_1, 0
$00C1	$0580			ANDWF	INDF, 1
;lcd.ppas,190 :: 		
$00C2	$0824			MOVF	lcd_dataport_address, 0
$00C3	$0084			MOVWF	FSR
;lcd.ppas,191 :: 		
$00C4	$0927			COMF	lcd____mdb5, W
$00C5	$00F0			MOVWF	STACK_0
$00C6	$0870			MOVF	STACK_0, 0
$00C7	$0580			ANDWF	INDF, 1
;lcd.ppas,192 :: 		
$00C8	$0825			MOVF	lcd____mdb7, 0
$00C9	$0480			IORWF	INDF, 1
;lcd.ppas,194 :: 		
$00CA	$0821			MOVF	lcd_ctrlport_address, 0
$00CB	$0084			MOVWF	FSR
;lcd.ppas,195 :: 		
$00CC	$0822			MOVF	lcd____menable, 0
$00CD	$0480			IORWF	INDF, 1
;lcd.ppas,196 :: 		
$00CE	$0871			MOVF	STACK_1, 0
$00CF	$0580			ANDWF	INDF, 1
;lcd.ppas,198 :: 		
$00D0	$2628			CALL	_delay_5500us
;lcd.ppas,201 :: 		
$00D1	$0824			MOVF	lcd_dataport_address, 0
$00D2	$0084			MOVWF	FSR
;lcd.ppas,202 :: 		
$00D3	$0925			COMF	lcd____mdb7, W
$00D4	$00F0			MOVWF	STACK_0
$00D5	$0870			MOVF	STACK_0, 0
$00D6	$0580			ANDWF	INDF, 1
;lcd.ppas,203 :: 		
$00D7	$0828			MOVF	lcd____mdb4, 0
$00D8	$0480			IORWF	INDF, 1
;lcd.ppas,204 :: 		
$00D9	$0821			MOVF	lcd_ctrlport_address, 0
$00DA	$0084			MOVWF	FSR
;lcd.ppas,205 :: 		
$00DB	$0822			MOVF	lcd____menable, 0
$00DC	$0480			IORWF	INDF, 1
;lcd.ppas,206 :: 		
$00DD	$0922			COMF	lcd____menable, W
$00DE	$00F1			MOVWF	STACK_1
$00DF	$0871			MOVF	STACK_1, 0
$00E0	$0580			ANDWF	INDF, 1
;lcd.ppas,207 :: 		
$00E1	$0824			MOVF	lcd_dataport_address, 0
$00E2	$0084			MOVWF	FSR
;lcd.ppas,208 :: 		
$00E3	$0928			COMF	lcd____mdb4, W
$00E4	$00F0			MOVWF	STACK_0
$00E5	$0870			MOVF	STACK_0, 0
$00E6	$0580			ANDWF	INDF, 1
;lcd.ppas,209 :: 		
$00E7	$0821			MOVF	lcd_ctrlport_address, 0
$00E8	$0084			MOVWF	FSR
;lcd.ppas,210 :: 		
$00E9	$0822			MOVF	lcd____menable, 0
$00EA	$0480			IORWF	INDF, 1
;lcd.ppas,211 :: 		
$00EB	$0871			MOVF	STACK_1, 0
$00EC	$0580			ANDWF	INDF, 1
;lcd.ppas,213 :: 		
$00ED	$2628			CALL	_delay_5500us
;lcd.ppas,218 :: 		
$00EE	$0822			MOVF	lcd____menable, 0
$00EF	$0480			IORWF	INDF, 1
;lcd.ppas,219 :: 		
$00F0	$0922			COMF	lcd____menable, W
$00F1	$00F0			MOVWF	STACK_0
$00F2	$0870			MOVF	STACK_0, 0
$00F3	$0580			ANDWF	INDF, 1
;lcd.ppas,220 :: 		
$00F4	$0824			MOVF	lcd_dataport_address, 0
$00F5	$0084			MOVWF	FSR
;lcd.ppas,221 :: 		
$00F6	$0828			MOVF	lcd____mdb4, 0
$00F7	$0480			IORWF	INDF, 1
;lcd.ppas,222 :: 		
$00F8	$0821			MOVF	lcd_ctrlport_address, 0
$00F9	$0084			MOVWF	FSR
;lcd.ppas,223 :: 		
$00FA	$0822			MOVF	lcd____menable, 0
$00FB	$0480			IORWF	INDF, 1
;lcd.ppas,224 :: 		
$00FC	$0870			MOVF	STACK_0, 0
$00FD	$0580			ANDWF	INDF, 1
;lcd.ppas,226 :: 		
$00FE	$2628			CALL	_delay_5500us
;lcd.ppas,229 :: 		
$00FF	$0824			MOVF	lcd_dataport_address, 0
$0100	$0084			MOVWF	FSR
;lcd.ppas,230 :: 		
$0101	$0928			COMF	lcd____mdb4, W
$0102	$00F0			MOVWF	STACK_0
$0103	$0870			MOVF	STACK_0, 0
$0104	$0580			ANDWF	INDF, 1
;lcd.ppas,231 :: 		
$0105	$0821			MOVF	lcd_ctrlport_address, 0
$0106	$0084			MOVWF	FSR
;lcd.ppas,232 :: 		
$0107	$0822			MOVF	lcd____menable, 0
$0108	$0480			IORWF	INDF, 1
;lcd.ppas,233 :: 		
$0109	$0922			COMF	lcd____menable, W
$010A	$00F1			MOVWF	STACK_1
$010B	$0871			MOVF	STACK_1, 0
$010C	$0580			ANDWF	INDF, 1
;lcd.ppas,234 :: 		
$010D	$0824			MOVF	lcd_dataport_address, 0
$010E	$0084			MOVWF	FSR
;lcd.ppas,235 :: 		
$010F	$0828			MOVF	lcd____mdb4, 0
$0110	$0400			IORWF	INDF, 0
$0111	$00F0			MOVWF	STACK_0
$0112	$0827			MOVF	lcd____mdb5, 0
$0113	$04F0			IORWF	STACK_0, 1
$0114	$0826			MOVF	lcd____mdb6, 0
$0115	$04F0			IORWF	STACK_0, 1
$0116	$0825			MOVF	lcd____mdb7, 0
$0117	$0470			IORWF	STACK_0, 0
$0118	$0080			MOVWF	INDF
;lcd.ppas,236 :: 		
$0119	$0821			MOVF	lcd_ctrlport_address, 0
$011A	$0084			MOVWF	FSR
;lcd.ppas,237 :: 		
$011B	$0822			MOVF	lcd____menable, 0
$011C	$0480			IORWF	INDF, 1
;lcd.ppas,238 :: 		
$011D	$0871			MOVF	STACK_1, 0
$011E	$0580			ANDWF	INDF, 1
;lcd.ppas,240 :: 		
$011F	$2628			CALL	_delay_5500us
;lcd.ppas,242 :: 		
$0120	$3001			MOVLW	1
$0121	$00A9			MOVWF	lcd_lcdcmd_status
$0122	$	lcd_L_55:
;lcd.ppas,243 :: 		
$0122	$0008			RETURN
$0648	$	_lcd_chr_cp:
;lcd.ppas,97 :: 		
;lcd.ppas,98 :: 		
$0648	$1303			BCF	STATUS, RP1
$0649	$1283			BCF	STATUS, RP0
$064A	$01A9			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,99 :: 		
$064B	$0859			MOVF	FARG_Lcd_Chr_CP, 0
$064C	$00E2			MOVWF	FARG_Lcd_Cmd
$064D	$22F1			CALL	_lcd_cmd
;lcd.ppas,100 :: 		
$064E	$3001			MOVLW	1
$064F	$00A9			MOVWF	lcd_lcdcmd_status
$0650	$	lcd_L_48:
;lcd.ppas,101 :: 		
$0650	$0008			RETURN
$0613	$	_lcd_init:
;lcd.ppas,246 :: 		
;lcd.ppas,247 :: 		
$0613	$1303			BCF	STATUS, RP1
$0614	$1283			BCF	STATUS, RP0
$0615	$0855			MOVF	FARG_Lcd_Init, 0
$0616	$00D9			MOVWF	FARG_Lcd_Config
$0617	$3007			MOVLW	7
$0618	$00DA			MOVWF	FARG_Lcd_Config+1
$0619	$3006			MOVLW	6
$061A	$00DB			MOVWF	FARG_Lcd_Config+2
$061B	$3005			MOVLW	5
$061C	$00DC			MOVWF	FARG_Lcd_Config+3
$061D	$3004			MOVLW	4
$061E	$00DD			MOVWF	FARG_Lcd_Config+4
$061F	$0855			MOVF	FARG_Lcd_Init, 0
$0620	$00DE			MOVWF	FARG_Lcd_Config+5
$0621	$3002			MOVLW	2
$0622	$00DF			MOVWF	FARG_Lcd_Config+6
$0623	$01E0			CLRF	FARG_Lcd_Config+7, 1
$0624	$3003			MOVLW	3
$0625	$00E1			MOVWF	FARG_Lcd_Config+8
$0626	$2004			CALL	_lcd_config
$0627	$	lcd_L_64:
;lcd.ppas,248 :: 		
$0627	$0008			RETURN
$050D	$	_lcd_out:
;lcd.ppas,252 :: 		
;lcd.ppas,254 :: 		
$050D	$	lcd_L_68:
$050D	$1303			BCF	STATUS, RP1
$050E	$1283			BCF	STATUS, RP0
$050F	$0855			MOVF	FARG_Lcd_Out, 0
$0510	$3A01			XORLW	1
$0511	$1D03			BTFSS	STATUS, Z
$0512	$2D16			GOTO	lcd_L_69
$0513	$	lcd_L_67:
$0513	$3080			MOVLW	128
$0514	$00D5			MOVWF	FARG_Lcd_Out
$0515	$2D2D			GOTO	lcd_L_66
$0516	$	lcd_L_69:
;lcd.ppas,255 :: 		
$0516	$	lcd_L_71:
$0516	$0855			MOVF	FARG_Lcd_Out, 0
$0517	$3A02			XORLW	2
$0518	$1D03			BTFSS	STATUS, Z
$0519	$2D1D			GOTO	lcd_L_72
$051A	$	lcd_L_70:
$051A	$30C0			MOVLW	192
$051B	$00D5			MOVWF	FARG_Lcd_Out
$051C	$2D2D			GOTO	lcd_L_66
$051D	$	lcd_L_72:
;lcd.ppas,256 :: 		
$051D	$	lcd_L_74:
$051D	$0855			MOVF	FARG_Lcd_Out, 0
$051E	$3A03			XORLW	3
$051F	$1D03			BTFSS	STATUS, Z
$0520	$2D24			GOTO	lcd_L_75
$0521	$	lcd_L_73:
$0521	$3094			MOVLW	148
$0522	$00D5			MOVWF	FARG_Lcd_Out
$0523	$2D2D			GOTO	lcd_L_66
$0524	$	lcd_L_75:
;lcd.ppas,257 :: 		
$0524	$	lcd_L_77:
$0524	$0855			MOVF	FARG_Lcd_Out, 0
$0525	$3A04			XORLW	4
$0526	$1D03			BTFSS	STATUS, Z
$0527	$2D2B			GOTO	lcd_L_78
$0528	$	lcd_L_76:
$0528	$30D4			MOVLW	212
$0529	$00D5			MOVWF	FARG_Lcd_Out
;lcd.ppas,258 :: 		
$052A	$2D2D			GOTO	lcd_L_66
$052B	$	lcd_L_78:
$052B	$3080			MOVLW	128
$052C	$00D5			MOVWF	FARG_Lcd_Out
$052D	$	lcd_L_66:
;lcd.ppas,260 :: 		
$052D	$0356			DECF	FARG_Lcd_Out+1, 0
$052E	$00F0			MOVWF	STACK_0
$052F	$0855			MOVF	FARG_Lcd_Out, 0
$0530	$07F0			ADDWF	STACK_0, 1
$0531	$0870			MOVF	STACK_0, 0
$0532	$00D5			MOVWF	FARG_Lcd_Out
;lcd.ppas,261 :: 		
$0533	$0870			MOVF	STACK_0, 0
$0534	$00E2			MOVWF	FARG_Lcd_Cmd
$0535	$22F1			CALL	_lcd_cmd
;lcd.ppas,262 :: 		
$0536	$01A9			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,263 :: 		
$0537	$01D8			CLRF	_lcd_out_local_i, 1
;lcd.ppas,264 :: 		
$0538	$	lcd_L_80:
$0538	$0858			MOVF	_lcd_out_local_i, 0
$0539	$0757			ADDWF	FARG_Lcd_Out+2, 0
$053A	$0084			MOVWF	FSR
$053B	$0800			MOVF	INDF, 0
$053C	$00F2			MOVWF	STACK_2
$053D	$0872			MOVF	STACK_2, 0
$053E	$3A00			XORLW	0
$053F	$1903			BTFSC	STATUS, Z
$0540	$2D49			GOTO	lcd_L_81
;lcd.ppas,266 :: 		
$0541	$0858			MOVF	_lcd_out_local_i, 0
$0542	$0757			ADDWF	FARG_Lcd_Out+2, 0
$0543	$0084			MOVWF	FSR
$0544	$0800			MOVF	INDF, 0
$0545	$00D9			MOVWF	FARG_Lcd_Chr_CP
$0546	$2648			CALL	_lcd_chr_cp
;lcd.ppas,267 :: 		
$0547	$0AD8			INCF	_lcd_out_local_i, 1
;lcd.ppas,268 :: 		
$0548	$2D38			GOTO	lcd_L_80
$0549	$	lcd_L_81:
;lcd.ppas,269 :: 		
$0549	$3001			MOVLW	1
$054A	$00A9			MOVWF	lcd_lcdcmd_status
$054B	$	lcd_L_65:
;lcd.ppas,270 :: 		
$054B	$0008			RETURN
$0651	$	_delay_22us:
;delays.ppas,21 :: 		begin
;delays.ppas,22 :: 		Delay_us(22);
$0651	$300E			MOVLW	14
$0652	$1303			BCF	STATUS, RP1
$0653	$1283			BCF	STATUS, RP0
$0654	$00FA			MOVWF	STACK_10
$0655	$0BFA			DECFSZ	STACK_10, F
$0656	$2E55			GOTO	$-1
$0657	$0000			NOP
$0658	$	delays_L_3:
;delays.ppas,23 :: 		end;
$0658	$0008			RETURN
$05F6	$	_div_16x16_u:
$05F6	$1303			BCF	STATUS, RP1
$05F7	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$05F8	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$05F9	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$05FA	$3010			MOVLW	16
;math.ppas,113 :: 		
$05FB	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$05FC	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$05FD	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$05FE	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$05FF	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$0600	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$0601	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$0602	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$0603	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$0604	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$0605	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$0606	$2E0E			GOTO	$+8
;math.ppas,125 :: 		
$0607	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$0608	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$0609	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$060A	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$060B	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$060C	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$060D	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$060E	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$060F	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$0610	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$0611	$2DFC			GOTO	$-21
;math.ppas,136 :: 		
$0612	$	math_L_3:
;math.ppas,137 :: 		
$0612	$0008			RETURN
$0123	$	_sdiv3232l:
$0123	$1303			BCF	STATUS, RP1
$0124	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$0125	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0126	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0127	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0128	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$0129	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$012A	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$012B	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$012C	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$012D	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$012E	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$012F	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$0130	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$0131	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$0132	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$0133	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$0134	$3007			MOVLW	7
;math.ppas,559 :: 		
$0135	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0136	$	LOOPS3232A:
;math.ppas,561 :: 		
$0136	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0137	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0138	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$0139	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$013A	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$013B	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$013C	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$013D	$294C			GOTO	SADD22LA
;math.ppas,570 :: 		
$013E	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$013F	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$0140	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$0141	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$0142	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$0143	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$0144	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$0145	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0146	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0147	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0148	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$0149	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$014A	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$014B	$2959			GOTO	SOK22LA
;math.ppas,585 :: 		
$014C	$	SADD22LA:
;math.ppas,586 :: 		
$014C	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$014D	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$014E	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$014F	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$0150	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$0151	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$0152	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$0153	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$0154	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$0155	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$0156	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$0157	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$0158	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$0159	$	SOK22LA:
;math.ppas,602 :: 		
$0159	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$015A	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$015B	$2936			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$015C	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$015D	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$015E	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$015F	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$0160	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$0161	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$0162	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$0163	$2972			GOTO	SADD22L8
;math.ppas,615 :: 		
$0164	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$0165	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$0166	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$0167	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$0168	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$0169	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$016A	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$016B	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$016C	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$016D	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$016E	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$016F	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$0170	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$0171	$297F			GOTO	SOK22L8
;math.ppas,630 :: 		
$0172	$	SADD22L8:
;math.ppas,631 :: 		
$0172	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$0173	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$0174	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$0175	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$0176	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$0177	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$0178	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$0179	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$017A	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$017B	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$017C	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$017D	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$017E	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$017F	$	SOK22L8:
;math.ppas,647 :: 		
$017F	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$0180	$3007			MOVLW	7
;math.ppas,650 :: 		
$0181	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$0182	$	LOOPS3232B:
;math.ppas,652 :: 		
$0182	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$0183	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$0184	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$0185	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$0186	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$0187	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$0188	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$0189	$2998			GOTO	SADD22LB
;math.ppas,661 :: 		
$018A	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$018B	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$018C	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$018D	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$018E	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$018F	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$0190	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$0191	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$0192	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$0193	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$0194	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$0195	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$0196	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$0197	$29A5			GOTO	SOK22LB
;math.ppas,676 :: 		
$0198	$	SADD22LB:
;math.ppas,677 :: 		
$0198	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$0199	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$019A	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$019B	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$019C	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$019D	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$019E	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$019F	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$01A0	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$01A1	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$01A2	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$01A3	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$01A4	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$01A5	$	SOK22LB:
;math.ppas,693 :: 		
$01A5	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$01A6	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$01A7	$2982			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$01A8	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$01A9	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$01AA	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$01AB	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$01AC	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$01AD	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$01AE	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$01AF	$29BE			GOTO	SADD22L16
;math.ppas,706 :: 		
$01B0	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$01B1	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$01B2	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$01B3	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$01B4	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$01B5	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$01B6	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$01B7	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$01B8	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$01B9	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$01BA	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$01BB	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$01BC	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$01BD	$29CB			GOTO	SOK22L16
;math.ppas,721 :: 		
$01BE	$	SADD22L16:
;math.ppas,722 :: 		
$01BE	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$01BF	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$01C0	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$01C1	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$01C2	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$01C3	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$01C4	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$01C5	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$01C6	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$01C7	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$01C8	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$01C9	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$01CA	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$01CB	$	SOK22L16:
;math.ppas,738 :: 		
$01CB	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$01CC	$3007			MOVLW	7
;math.ppas,741 :: 		
$01CD	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$01CE	$	LOOPS3232C:
;math.ppas,743 :: 		
$01CE	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$01CF	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$01D0	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$01D1	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$01D2	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$01D3	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$01D4	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$01D5	$29E4			GOTO	SADD22LC
;math.ppas,752 :: 		
$01D6	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$01D7	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$01D8	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$01D9	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$01DA	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$01DB	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$01DC	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$01DD	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$01DE	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$01DF	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$01E0	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$01E1	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$01E2	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$01E3	$29F1			GOTO	SOK22LC
;math.ppas,767 :: 		
$01E4	$	SADD22LC:
;math.ppas,768 :: 		
$01E4	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$01E5	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$01E6	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$01E7	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$01E8	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$01E9	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$01EA	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$01EB	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$01EC	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$01ED	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$01EE	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$01EF	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$01F0	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$01F1	$	SOK22LC:
;math.ppas,784 :: 		
$01F1	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$01F2	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$01F3	$29CE			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$01F4	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$01F5	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$01F6	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$01F7	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$01F8	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$01F9	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$01FA	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$01FB	$2A0A			GOTO	SADD22L24
;math.ppas,797 :: 		
$01FC	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$01FD	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$01FE	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$01FF	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$0200	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$0201	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$0202	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$0203	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$0204	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$0205	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$0206	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$0207	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$0208	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$0209	$2A17			GOTO	SOK22L24
;math.ppas,812 :: 		
$020A	$	SADD22L24:
;math.ppas,813 :: 		
$020A	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$020B	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$020C	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$020D	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$020E	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$020F	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$0210	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$0211	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$0212	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$0213	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$0214	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$0215	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$0216	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$0217	$	SOK22L24:
;math.ppas,829 :: 		
$0217	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$0218	$3007			MOVLW	7
;math.ppas,832 :: 		
$0219	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$021A	$	LOOPS3232D:
;math.ppas,834 :: 		
$021A	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$021B	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$021C	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$021D	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$021E	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$021F	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$0220	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$0221	$2A30			GOTO	SADD22LD
;math.ppas,843 :: 		
$0222	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$0223	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$0224	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$0225	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0226	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0227	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0228	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$0229	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$022A	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$022B	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$022C	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$022D	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$022E	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$022F	$2A3D			GOTO	SOK22LD
;math.ppas,858 :: 		
$0230	$	SADD22LD:
;math.ppas,859 :: 		
$0230	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$0231	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$0232	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$0233	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$0234	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$0235	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0236	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0237	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0238	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$0239	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$023A	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$023B	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$023C	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$023D	$	SOK22LD:
;math.ppas,876 :: 		
$023D	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$023E	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$023F	$2A1A			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$0240	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$0241	$2A50			GOTO	SOK22L
;math.ppas,882 :: 		
$0242	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$0243	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$0244	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$0245	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0246	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0247	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0248	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$0249	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$024A	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$024B	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$024C	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$024D	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$024E	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$024F	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$0250	$	SOK22L:
;math.ppas,897 :: 		
$0250	$	math_L_9:
;math.ppas,898 :: 		
$0250	$0008			RETURN
$063A	$	_comfrem:
$063A	$1303			BCF	STATUS, RP1
$063B	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$063C	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$063D	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$063E	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$063F	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$0640	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$0641	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$0642	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$0643	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$0644	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$0645	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$0646	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$0647	$	math_L_10:
;math.ppas,915 :: 		
$0647	$0008			RETURN
$0432	$	_init:
;Temperature.ppas,5 :: 		begin
;Temperature.ppas,6 :: 		TRISA:=$ff;
$0432	$30FF			MOVLW	255
$0433	$1303			BCF	STATUS, RP1
$0434	$1683			BSF	STATUS, RP0
$0435	$0085			MOVWF	TRISA
;Temperature.ppas,7 :: 		TRISC:=$00;
$0436	$0187			CLRF	TRISC, 1
;Temperature.ppas,8 :: 		ADCON1:=$0E;
$0437	$300E			MOVLW	14
$0438	$009F			MOVWF	ADCON1
;Temperature.ppas,9 :: 		Lcd_Init(PORTC);
$0439	$3007			MOVLW	PORTC
$043A	$1283			BCF	STATUS, RP0
$043B	$00D5			MOVWF	FARG_Lcd_Init
$043C	$2613			CALL	_lcd_init
;Temperature.ppas,10 :: 		Lcd_Cmd(LCD_clear);
$043D	$3001			MOVLW	1
$043E	$00E2			MOVWF	FARG_Lcd_Cmd
$043F	$22F1			CALL	_lcd_cmd
;Temperature.ppas,11 :: 		Lcd_Cmd(LCD_CURSOR_OFF);
$0440	$300C			MOVLW	12
$0441	$00E2			MOVWF	FARG_Lcd_Cmd
$0442	$22F1			CALL	_lcd_cmd
;Temperature.ppas,12 :: 		Lcd_Out(1,3,'Projet Atelier');
$0443	$3001			MOVLW	1
$0444	$00D5			MOVWF	FARG_Lcd_Out
$0445	$3003			MOVLW	3
$0446	$00D6			MOVWF	FARG_Lcd_Out+1
$0447	$3050			MOVLW	80
$0448	$00C4			MOVWF	?init_Local_Text+0
$0449	$3072			MOVLW	114
$044A	$00C5			MOVWF	?init_Local_Text+1
$044B	$306F			MOVLW	111
$044C	$00C6			MOVWF	?init_Local_Text+2
$044D	$306A			MOVLW	106
$044E	$00C7			MOVWF	?init_Local_Text+3
$044F	$3065			MOVLW	101
$0450	$00C8			MOVWF	?init_Local_Text+4
$0451	$3074			MOVLW	116
$0452	$00C9			MOVWF	?init_Local_Text+5
$0453	$3020			MOVLW	32
$0454	$00CA			MOVWF	?init_Local_Text+6
$0455	$3041			MOVLW	65
$0456	$00CB			MOVWF	?init_Local_Text+7
$0457	$3074			MOVLW	116
$0458	$00CC			MOVWF	?init_Local_Text+8
$0459	$3065			MOVLW	101
$045A	$00CD			MOVWF	?init_Local_Text+9
$045B	$306C			MOVLW	108
$045C	$00CE			MOVWF	?init_Local_Text+10
$045D	$3069			MOVLW	105
$045E	$00CF			MOVWF	?init_Local_Text+11
$045F	$3065			MOVLW	101
$0460	$00D0			MOVWF	?init_Local_Text+12
$0461	$3072			MOVLW	114
$0462	$00D1			MOVWF	?init_Local_Text+13
$0463	$01D2			CLRF	?init_Local_Text+14
$0464	$3044			MOVLW	?init_Local_Text
$0465	$00D7			MOVWF	FARG_Lcd_Out+2
$0466	$250D			CALL	_lcd_out
;Temperature.ppas,13 :: 		Lcd_Out(2,4,'Micro-Controleur');
$0467	$3002			MOVLW	2
$0468	$00D5			MOVWF	FARG_Lcd_Out
$0469	$3004			MOVLW	4
$046A	$00D6			MOVWF	FARG_Lcd_Out+1
$046B	$304D			MOVLW	77
$046C	$00C4			MOVWF	?init_Local_Text+0
$046D	$3069			MOVLW	105
$046E	$00C5			MOVWF	?init_Local_Text+1
$046F	$3063			MOVLW	99
$0470	$00C6			MOVWF	?init_Local_Text+2
$0471	$3072			MOVLW	114
$0472	$00C7			MOVWF	?init_Local_Text+3
$0473	$306F			MOVLW	111
$0474	$00C8			MOVWF	?init_Local_Text+4
$0475	$302D			MOVLW	45
$0476	$00C9			MOVWF	?init_Local_Text+5
$0477	$3043			MOVLW	67
$0478	$00CA			MOVWF	?init_Local_Text+6
$0479	$306F			MOVLW	111
$047A	$00CB			MOVWF	?init_Local_Text+7
$047B	$306E			MOVLW	110
$047C	$00CC			MOVWF	?init_Local_Text+8
$047D	$3074			MOVLW	116
$047E	$00CD			MOVWF	?init_Local_Text+9
$047F	$3072			MOVLW	114
$0480	$00CE			MOVWF	?init_Local_Text+10
$0481	$306F			MOVLW	111
$0482	$00CF			MOVWF	?init_Local_Text+11
$0483	$306C			MOVLW	108
$0484	$00D0			MOVWF	?init_Local_Text+12
$0485	$3065			MOVLW	101
$0486	$00D1			MOVWF	?init_Local_Text+13
$0487	$3075			MOVLW	117
$0488	$00D2			MOVWF	?init_Local_Text+14
$0489	$3072			MOVLW	114
$048A	$00D3			MOVWF	?init_Local_Text+15
$048B	$01D4			CLRF	?init_Local_Text+16
$048C	$3044			MOVLW	?init_Local_Text
$048D	$00D7			MOVWF	FARG_Lcd_Out+2
$048E	$250D			CALL	_lcd_out
;Temperature.ppas,14 :: 		delay_ms(2000);
$048F	$3015			MOVLW	21
$0490	$00FC			MOVWF	STACK_12
$0491	$30FF			MOVLW	255
$0492	$00FB			MOVWF	STACK_11
$0493	$30FF			MOVLW	255
$0494	$00FA			MOVWF	STACK_10
$0495	$0BFC			DECFSZ	STACK_12, F
$0496	$2C98			GOTO	$+2
$0497	$2C9F			GOTO	$+8
$0498	$0BFB			DECFSZ	STACK_11, F
$0499	$2C9B			GOTO	$+2
$049A	$2C9E			GOTO	$+4
$049B	$0BFA			DECFSZ	STACK_10, F
$049C	$2C9B			GOTO	$-1
$049D	$2C98			GOTO	$-5
$049E	$2C95			GOTO	$-9
$049F	$3066			MOVLW	102
$04A0	$00FB			MOVWF	STACK_11
$04A1	$30FF			MOVLW	255
$04A2	$00FA			MOVWF	STACK_10
$04A3	$0BFB			DECFSZ	STACK_11, F
$04A4	$2CA6			GOTO	$+2
$04A5	$2CA9			GOTO	$+4
$04A6	$0BFA			DECFSZ	STACK_10, F
$04A7	$2CA6			GOTO	$-1
$04A8	$2CA3			GOTO	$-5
$04A9	$3012			MOVLW	18
$04AA	$00FA			MOVWF	STACK_10
$04AB	$0BFA			DECFSZ	STACK_10, F
$04AC	$2CAB			GOTO	$-1
$04AD	$0000			NOP
$04AE	$0000			NOP
;Temperature.ppas,15 :: 		Lcd_Cmd(LCD_clear);
$04AF	$3001			MOVLW	1
$04B0	$00E2			MOVWF	FARG_Lcd_Cmd
$04B1	$22F1			CALL	_lcd_cmd
$04B2	$	Temperature_L_0:
;Temperature.ppas,16 :: 		end;
$04B2	$0008			RETURN
$054C	$	_adc_read:
;ADClib_A_C.ppas,12 :: 		
;ADClib_A_C.ppas,13 :: 		
$054C	$1303			BCF	STATUS, RP1
$054D	$1283			BCF	STATUS, RP0
$054E	$019F			CLRF	ADCON0, 1
;ADClib_A_C.ppas,14 :: 		
$054F	$30C0			MOVLW	192
$0550	$049F			IORWF	ADCON0, 1
;ADClib_A_C.ppas,15 :: 		
$0551	$3040			MOVLW	64
$0552	$1683			BSF	STATUS, RP0
$0553	$041F			IORWF	ADCON1, 0
$0554	$00F0			MOVWF	STACK_0
$0555	$0870			MOVF	STACK_0, 0
$0556	$009F			MOVWF	ADCON1
;ADClib_A_C.ppas,17 :: 		
$0557	$3080			MOVLW	128
$0558	$0470			IORWF	STACK_0, 0
$0559	$009F			MOVWF	ADCON1
;ADClib_A_C.ppas,18 :: 		
$055A	$1283			BCF	STATUS, RP0
$055B	$0844			MOVF	FARG_ADC_read, 0
$055C	$00F0			MOVWF	STACK_0
$055D	$0DF0			RLF	STACK_0, 1
$055E	$1070			BCF	STACK_0, 0
$055F	$0DF0			RLF	STACK_0, 1
$0560	$1070			BCF	STACK_0, 0
$0561	$0DF0			RLF	STACK_0, 1
$0562	$1070			BCF	STACK_0, 0
$0563	$0870			MOVF	STACK_0, 0
$0564	$049F			IORWF	ADCON0, 1
;ADClib_A_C.ppas,19 :: 		
$0565	$141F			BSF	ADCON0, 0
;ADClib_A_C.ppas,20 :: 		
$0566	$2651			CALL	_delay_22us
;ADClib_A_C.ppas,21 :: 		
$0567	$151F			BSF	ADCON0, 2
;ADClib_A_C.ppas,22 :: 		
$0568	$	ADClib_A_C_L_2:
$0568	$081F			MOVF	ADCON0, 0
$0569	$00F2			MOVWF	STACK_2
$056A	$3000			MOVLW	0
$056B	$1972			BTFSC	STACK_2, 2
$056C	$3001			MOVLW	1
$056D	$00F2			MOVWF	STACK_2
$056E	$0872			MOVF	STACK_2, 0
$056F	$3A01			XORLW	1
$0570	$1D03			BTFSS	STATUS, Z
$0571	$2D74			GOTO	ADClib_A_C_L_3
;ADClib_A_C.ppas,23 :: 		
$0572	$0000			NOP
$0573	$2D68			GOTO	ADClib_A_C_L_2
$0574	$	ADClib_A_C_L_3:
;ADClib_A_C.ppas,24 :: 		
$0574	$081E			MOVF	ADRESH, 0
$0575	$00F2			MOVWF	STACK_2
$0576	$01F3			CLRF	STACK_2+1
$0577	$0872			MOVF	STACK_2, 0
$0578	$00F3			MOVWF	STACK_2+1
$0579	$01F2			CLRF	STACK_2
$057A	$0872			MOVF	STACK_2, 0
$057B	$00C5			MOVWF	_adc_read_local_result
$057C	$0873			MOVF	STACK_2+1, 0
$057D	$00C6			MOVWF	_adc_read_local_result+1
;ADClib_A_C.ppas,25 :: 		
$057E	$1683			BSF	STATUS, RP0
$057F	$081E			MOVF	ADRESL, 0
$0580	$0472			IORWF	STACK_2, 0
$0581	$1283			BCF	STATUS, RP0
$0582	$00C5			MOVWF	_adc_read_local_result
$0583	$0873			MOVF	STACK_2+1, 0
$0584	$00C6			MOVWF	_adc_read_local_result+1
$0585	$3000			MOVLW	0
$0586	$04C6			IORWF	_adc_read_local_result+1, 1
;ADClib_A_C.ppas,26 :: 		
$0587	$101F			BCF	ADCON0, 0
$0588	$	ADClib_A_C_L_0:
;ADClib_A_C.ppas,27 :: 		
$0588	$0845			MOVF	_adc_read_local_result, 0
$0589	$00F0			MOVWF	STACK_0
$058A	$0846			MOVF	_adc_read_local_result+1, 0
$058B	$00F1			MOVWF	STACK_0+1
$058C	$0008			RETURN
$04B3	$	_wordtostr:
;conv.ppas,31 :: 		
;conv.ppas,32 :: 		
$04B3	$3001			MOVLW	1
$04B4	$1303			BCF	STATUS, RP1
$04B5	$1283			BCF	STATUS, RP0
$04B6	$00C7			MOVWF	_wordtostr_local_len
;conv.ppas,33 :: 		
$04B7	$0845			MOVF	FARG_WordToStr+1, 0
$04B8	$3C00			SUBLW	0
$04B9	$1D03			BTFSS	STATUS, Z
$04BA	$2CBD			GOTO	L_WordToStr_0
$04BB	$0844			MOVF	FARG_WordToStr, 0
$04BC	$3C09			SUBLW	9
$04BD	$	L_WordToStr_0:
$04BD	$1803			BTFSC	STATUS, C
$04BE	$2CC0			GOTO	conv_L_15
$04BF	$	conv_L_14:
;conv.ppas,34 :: 		
$04BF	$0AC7			INCF	_wordtostr_local_len, 1
$04C0	$	conv_L_15:
$04C0	$	conv_L_16:
;conv.ppas,35 :: 		
$04C0	$0845			MOVF	FARG_WordToStr+1, 0
$04C1	$3C00			SUBLW	0
$04C2	$1D03			BTFSS	STATUS, Z
$04C3	$2CC6			GOTO	L_WordToStr_1
$04C4	$0844			MOVF	FARG_WordToStr, 0
$04C5	$3C63			SUBLW	99
$04C6	$	L_WordToStr_1:
$04C6	$1803			BTFSC	STATUS, C
$04C7	$2CC9			GOTO	conv_L_18
$04C8	$	conv_L_17:
;conv.ppas,36 :: 		
$04C8	$0AC7			INCF	_wordtostr_local_len, 1
$04C9	$	conv_L_18:
$04C9	$	conv_L_19:
;conv.ppas,37 :: 		
$04C9	$0845			MOVF	FARG_WordToStr+1, 0
$04CA	$3C03			SUBLW	3
$04CB	$1D03			BTFSS	STATUS, Z
$04CC	$2CCF			GOTO	L_WordToStr_2
$04CD	$0844			MOVF	FARG_WordToStr, 0
$04CE	$3CE7			SUBLW	231
$04CF	$	L_WordToStr_2:
$04CF	$1803			BTFSC	STATUS, C
$04D0	$2CD2			GOTO	conv_L_21
$04D1	$	conv_L_20:
;conv.ppas,38 :: 		
$04D1	$0AC7			INCF	_wordtostr_local_len, 1
$04D2	$	conv_L_21:
$04D2	$	conv_L_22:
;conv.ppas,39 :: 		
$04D2	$0845			MOVF	FARG_WordToStr+1, 0
$04D3	$3C27			SUBLW	39
$04D4	$1D03			BTFSS	STATUS, Z
$04D5	$2CD8			GOTO	L_WordToStr_3
$04D6	$0844			MOVF	FARG_WordToStr, 0
$04D7	$3C0F			SUBLW	15
$04D8	$	L_WordToStr_3:
$04D8	$1803			BTFSC	STATUS, C
$04D9	$2CDB			GOTO	conv_L_24
$04DA	$	conv_L_23:
;conv.ppas,40 :: 		
$04DA	$0AC7			INCF	_wordtostr_local_len, 1
$04DB	$	conv_L_24:
$04DB	$	conv_L_25:
;conv.ppas,41 :: 		
$04DB	$0846			MOVF	FARG_WordToStr+2, 0
$04DC	$0084			MOVWF	FSR
$04DD	$3020			MOVLW	32
$04DE	$0080			MOVWF	INDF
$04DF	$0A84			INCF	FSR, 1
$04E0	$0080			MOVWF	INDF
$04E1	$0A84			INCF	FSR, 1
$04E2	$0080			MOVWF	INDF
$04E3	$0A84			INCF	FSR, 1
$04E4	$0080			MOVWF	INDF
$04E5	$0A84			INCF	FSR, 1
$04E6	$0080			MOVWF	INDF
$04E7	$0A84			INCF	FSR, 1
$04E8	$0180			CLRF	INDF
;conv.ppas,42 :: 		
$04E9	$0384			DECF	FSR, 1
;conv.ppas,43 :: 		
$04EA	$	conv_L_28:
$04EA	$0847			MOVF	_wordtostr_local_len, 0
$04EB	$3C00			SUBLW	0
$04EC	$1803			BTFSC	STATUS, C
$04ED	$2D0C			GOTO	conv_L_29
;conv.ppas,45 :: 		
$04EE	$300A			MOVLW	10
$04EF	$00F4			MOVWF	STACK_4
$04F0	$01F5			CLRF	STACK_4+1
$04F1	$0844			MOVF	FARG_WordToStr, 0
$04F2	$00F0			MOVWF	STACK_0
$04F3	$0845			MOVF	FARG_WordToStr+1, 0
$04F4	$00F1			MOVWF	STACK_0+1
$04F5	$25F6			CALL	_div_16x16_u
$04F6	$0878			MOVF	STACK_8, 0
$04F7	$00F0			MOVWF	STACK_0
$04F8	$0879			MOVF	STACK_9, 0
$04F9	$00F1			MOVWF	STACK_1
$04FA	$3030			MOVLW	48
$04FB	$0770			ADDWF	STACK_0, 0
$04FC	$0080			MOVWF	INDF
;conv.ppas,46 :: 		
;conv.ppas,47 :: 		
$04FD	$0384			DECF	FSR, 1
;conv.ppas,48 :: 		
$04FE	$300A			MOVLW	10
$04FF	$00F4			MOVWF	STACK_4
$0500	$01F5			CLRF	STACK_4+1
$0501	$0844			MOVF	FARG_WordToStr, 0
$0502	$00F0			MOVWF	STACK_0
$0503	$0845			MOVF	FARG_WordToStr+1, 0
$0504	$00F1			MOVWF	STACK_0+1
$0505	$25F6			CALL	_div_16x16_u
$0506	$0870			MOVF	STACK_0, 0
$0507	$00C4			MOVWF	FARG_WordToStr
$0508	$0871			MOVF	STACK_0+1, 0
$0509	$00C5			MOVWF	FARG_WordToStr+1
;conv.ppas,49 :: 		
$050A	$03C7			DECF	_wordtostr_local_len, 1
;conv.ppas,50 :: 		
$050B	$2CEA			GOTO	conv_L_28
$050C	$	conv_L_29:
$050C	$	conv_L_13:
;conv.ppas,51 :: 		
$050C	$0008			RETURN
$058D	$	_lcd_chr:
;lcd.ppas,78 :: 		
;lcd.ppas,80 :: 		
$058D	$	lcd_L_37:
$058D	$1303			BCF	STATUS, RP1
$058E	$1283			BCF	STATUS, RP0
$058F	$0844			MOVF	FARG_Lcd_Chr, 0
$0590	$3A01			XORLW	1
$0591	$1D03			BTFSS	STATUS, Z
$0592	$2D96			GOTO	lcd_L_38
$0593	$	lcd_L_36:
$0593	$3080			MOVLW	128
$0594	$00C4			MOVWF	FARG_Lcd_Chr
$0595	$2DAD			GOTO	lcd_L_35
$0596	$	lcd_L_38:
;lcd.ppas,81 :: 		
$0596	$	lcd_L_40:
$0596	$0844			MOVF	FARG_Lcd_Chr, 0
$0597	$3A02			XORLW	2
$0598	$1D03			BTFSS	STATUS, Z
$0599	$2D9D			GOTO	lcd_L_41
$059A	$	lcd_L_39:
$059A	$30C0			MOVLW	192
$059B	$00C4			MOVWF	FARG_Lcd_Chr
$059C	$2DAD			GOTO	lcd_L_35
$059D	$	lcd_L_41:
;lcd.ppas,82 :: 		
$059D	$	lcd_L_43:
$059D	$0844			MOVF	FARG_Lcd_Chr, 0
$059E	$3A03			XORLW	3
$059F	$1D03			BTFSS	STATUS, Z
$05A0	$2DA4			GOTO	lcd_L_44
$05A1	$	lcd_L_42:
$05A1	$3094			MOVLW	148
$05A2	$00C4			MOVWF	FARG_Lcd_Chr
$05A3	$2DAD			GOTO	lcd_L_35
$05A4	$	lcd_L_44:
;lcd.ppas,83 :: 		
$05A4	$	lcd_L_46:
$05A4	$0844			MOVF	FARG_Lcd_Chr, 0
$05A5	$3A04			XORLW	4
$05A6	$1D03			BTFSS	STATUS, Z
$05A7	$2DAB			GOTO	lcd_L_47
$05A8	$	lcd_L_45:
$05A8	$30D4			MOVLW	212
$05A9	$00C4			MOVWF	FARG_Lcd_Chr
;lcd.ppas,84 :: 		
$05AA	$2DAD			GOTO	lcd_L_35
$05AB	$	lcd_L_47:
$05AB	$3080			MOVLW	128
$05AC	$00C4			MOVWF	FARG_Lcd_Chr
$05AD	$	lcd_L_35:
;lcd.ppas,86 :: 		
$05AD	$0845			MOVF	FARG_Lcd_Chr+1, 0
$05AE	$0744			ADDWF	FARG_Lcd_Chr, 0
$05AF	$00F0			MOVWF	STACK_0
$05B0	$03F0			DECF	STACK_0, 1
$05B1	$0870			MOVF	STACK_0, 0
$05B2	$00C4			MOVWF	FARG_Lcd_Chr
;lcd.ppas,88 :: 		
$05B3	$3001			MOVLW	1
$05B4	$00A9			MOVWF	lcd_lcdcmd_status
;lcd.ppas,89 :: 		
$05B5	$0870			MOVF	STACK_0, 0
$05B6	$00E2			MOVWF	FARG_Lcd_Cmd
$05B7	$22F1			CALL	_lcd_cmd
;lcd.ppas,91 :: 		
$05B8	$01A9			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,92 :: 		
$05B9	$0846			MOVF	FARG_Lcd_Chr+2, 0
$05BA	$00E2			MOVWF	FARG_Lcd_Cmd
$05BB	$22F1			CALL	_lcd_cmd
;lcd.ppas,93 :: 		
$05BC	$3001			MOVLW	1
$05BD	$00A9			MOVWF	lcd_lcdcmd_status
$05BE	$	lcd_L_34:
;lcd.ppas,94 :: 		
$05BE	$0008			RETURN
$05BF	$	_mul_32x32_u:
$05BF	$1303			BCF	STATUS, RP1
$05C0	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$05C1	$3022			MOVLW	34
;math.ppas,1579 :: 		
$05C2	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$05C3	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$05C4	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$05C5	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$05C6	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$05C7	$	_NEXT:
;math.ppas,1589 :: 		
$05C7	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$05C8	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$05C9	$2DF5			GOTO	_EXIT2
;math.ppas,1593 :: 		
$05CA	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$05CB	$	_LOOP:
;math.ppas,1603 :: 		
$05CB	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$05CC	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$05CD	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$05CE	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$05CF	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$05D0	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$05D1	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$05D2	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$05D3	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$05D4	$2DC7			GOTO	_NEXT
;math.ppas,1617 :: 		
$05D5	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$05D6	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$05D7	$2DE7			GOTO	_EXIT1
;math.ppas,1626 :: 		
$05D8	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$05D9	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$05DA	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$05DB	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$05DC	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$05DD	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$05DE	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$05DF	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$05E0	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$05E1	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$05E2	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$05E3	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$05E4	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$05E5	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$05E6	$2DCB			GOTO	_LOOP
;math.ppas,1647 :: 		
$05E7	$	_EXIT1:
;math.ppas,1648 :: 		
$05E7	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$05E8	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$05E9	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$05EA	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$05EB	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$05EC	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$05ED	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$05EE	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$05EF	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$05F0	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$05F1	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$05F2	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$05F3	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$05F4	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$05F5	$	_EXIT2:
;math.ppas,1665 :: 		
$05F5	$	math_L_13:
;math.ppas,1666 :: 		
$05F5	$0008			RETURN
$0398	$	_div_32x32_s:
$0398	$1303			BCF	STATUS, RP1
$0399	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$039A	$	FXD3232S:
;math.ppas,929 :: 		
$039A	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$039B	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$039C	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$039D	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$039E	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$039F	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$03A0	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$03A1	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$03A2	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$03A3	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$03A4	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$03A5	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$03A6	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$03A7	$2C2C			GOTO	END_ALL
;math.ppas,944 :: 		
$03A8	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$03A9	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$03AA	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$03AB	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$03AC	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$03AD	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$03AE	$2BBA			GOTO	CA3232S
;math.ppas,955 :: 		
$03AF	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$03B0	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$03B1	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$03B2	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$03B3	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$03B4	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$03B5	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$03B6	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$03B7	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$03B8	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$03B9	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$03BA	$	CA3232S:
;math.ppas,968 :: 		
$03BA	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$03BB	$2BC7			GOTO	C3232SX
;math.ppas,971 :: 		
$03BC	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$03BD	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$03BE	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$03BF	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$03C0	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$03C1	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$03C2	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$03C3	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$03C4	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$03C5	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$03C6	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$03C7	$	C3232SX:
;math.ppas,984 :: 		
$03C7	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$03C8	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$03C9	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$03CA	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$03CB	$2BE8			GOTO	C3232SX1
;math.ppas,989 :: 		
$03CC	$	C3232S:
;math.ppas,992 :: 		
$03CC	$2123			CALL	_sdiv3232l
;math.ppas,995 :: 		
$03CD	$	C3232S2:
;math.ppas,996 :: 		
$03CD	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$03CE	$2C05			GOTO	C3232SX4
;math.ppas,998 :: 		
$03CF	$	C3232SOK:
;math.ppas,999 :: 		
$03CF	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$03D0	$2C2C			GOTO	END_ALL
;math.ppas,1001 :: 		
$03D1	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$03D2	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$03D3	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$03D4	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$03D5	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$03D6	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$03D7	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$03D8	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$03D9	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$03DA	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$03DB	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$03DC	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$03DD	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$03DE	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$03DF	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$03E0	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$03E1	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$03E2	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$03E3	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$03E4	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$03E5	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$03E6	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$03E7	$2C2C			GOTO	END_ALL
;math.ppas,1026 :: 		
$03E8	$	C3232SX1:
;math.ppas,1027 :: 		
$03E8	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$03E9	$2BFF			GOTO	C3232SX3
;math.ppas,1029 :: 		
$03EA	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$03EB	$2BF9			GOTO	C3232SX2
;math.ppas,1031 :: 		
$03EC	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$03ED	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$03EE	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$03EF	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$03F0	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$03F1	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$03F2	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$03F3	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$03F4	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$03F5	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$03F6	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$03F7	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$03F8	$2BCF			GOTO	C3232SOK
;math.ppas,1044 :: 		
$03F9	$	C3232SX2:
;math.ppas,1045 :: 		
$03F9	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$03FA	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$03FB	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$03FC	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$03FD	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$03FE	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$03FF	$	C3232SX3:
;math.ppas,1053 :: 		
$03FF	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$0400	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$0401	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$0402	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$0403	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$0404	$2BCC			GOTO	C3232S
;math.ppas,1061 :: 		
$0405	$	C3232SX4:
;math.ppas,1062 :: 		
$0405	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0406	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$0407	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$0408	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$0409	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$040A	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$040B	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$040C	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$040D	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$040E	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$040F	$2BCF			GOTO	C3232SOK
;math.ppas,1073 :: 		
$0410	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$0411	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$0412	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$0413	$2BCF			GOTO	C3232SOK
;math.ppas,1077 :: 		
$0414	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$0415	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$0416	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$0417	$2BCF			GOTO	C3232SOK
;math.ppas,1081 :: 		
$0418	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$0419	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$041A	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$041B	$2BCF			GOTO	C3232SOK
;math.ppas,1085 :: 		
$041C	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$041D	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$041E	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$041F	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$0420	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$0421	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$0422	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$0423	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$0424	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$0425	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0426	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$0427	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$0428	$2BCF			GOTO	C3232SOK
;math.ppas,1098 :: 		
$0429	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$042A	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$042B	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$042C	$	END_ALL:
;math.ppas,1102 :: 		
$042C	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$042D	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$042E	$2C30			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$042F	$263A			CALL	_comfrem
;math.ppas,1108 :: 		
$0430	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$0430	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$0431	$	math_L_11:
;math.ppas,1111 :: 		
$0431	$0008			RETURN
$0251	$	_main:
;Temperature.ppas,17 :: 		begin
;Temperature.ppas,18 :: 		init();
$0251	$2432			CALL	_init
;Temperature.ppas,19 :: 		Lcd_Out(1,1,'Mesure  :');
$0252	$3001			MOVLW	1
$0253	$00D5			MOVWF	FARG_Lcd_Out
$0254	$3001			MOVLW	1
$0255	$00D6			MOVWF	FARG_Lcd_Out+1
$0256	$304D			MOVLW	77
$0257	$00B7			MOVWF	?main_Local_Text+0
$0258	$3065			MOVLW	101
$0259	$00B8			MOVWF	?main_Local_Text+1
$025A	$3073			MOVLW	115
$025B	$00B9			MOVWF	?main_Local_Text+2
$025C	$3075			MOVLW	117
$025D	$00BA			MOVWF	?main_Local_Text+3
$025E	$3072			MOVLW	114
$025F	$00BB			MOVWF	?main_Local_Text+4
$0260	$3065			MOVLW	101
$0261	$00BC			MOVWF	?main_Local_Text+5
$0262	$3020			MOVLW	32
$0263	$00BD			MOVWF	?main_Local_Text+6
$0264	$3020			MOVLW	32
$0265	$00BE			MOVWF	?main_Local_Text+7
$0266	$303A			MOVLW	58
$0267	$00BF			MOVWF	?main_Local_Text+8
$0268	$01C0			CLRF	?main_Local_Text+9
$0269	$3037			MOVLW	?main_Local_Text
$026A	$00D7			MOVWF	FARG_Lcd_Out+2
$026B	$250D			CALL	_lcd_out
;Temperature.ppas,20 :: 		Lcd_Out(2,1,'Temperature:');
$026C	$3002			MOVLW	2
$026D	$00D5			MOVWF	FARG_Lcd_Out
$026E	$3001			MOVLW	1
$026F	$00D6			MOVWF	FARG_Lcd_Out+1
$0270	$3054			MOVLW	84
$0271	$00B7			MOVWF	?main_Local_Text+0
$0272	$3065			MOVLW	101
$0273	$00B8			MOVWF	?main_Local_Text+1
$0274	$306D			MOVLW	109
$0275	$00B9			MOVWF	?main_Local_Text+2
$0276	$3070			MOVLW	112
$0277	$00BA			MOVWF	?main_Local_Text+3
$0278	$3065			MOVLW	101
$0279	$00BB			MOVWF	?main_Local_Text+4
$027A	$3072			MOVLW	114
$027B	$00BC			MOVWF	?main_Local_Text+5
$027C	$3061			MOVLW	97
$027D	$00BD			MOVWF	?main_Local_Text+6
$027E	$3074			MOVLW	116
$027F	$00BE			MOVWF	?main_Local_Text+7
$0280	$3075			MOVLW	117
$0281	$00BF			MOVWF	?main_Local_Text+8
$0282	$3072			MOVLW	114
$0283	$00C0			MOVWF	?main_Local_Text+9
$0284	$3065			MOVLW	101
$0285	$00C1			MOVWF	?main_Local_Text+10
$0286	$303A			MOVLW	58
$0287	$00C2			MOVWF	?main_Local_Text+11
$0288	$01C3			CLRF	?main_Local_Text+12
$0289	$3037			MOVLW	?main_Local_Text
$028A	$00D7			MOVWF	FARG_Lcd_Out+2
$028B	$250D			CALL	_lcd_out
;Temperature.ppas,21 :: 		while(1) do
$028C	$	Temperature_L_3:
;Temperature.ppas,23 :: 		res:=Adc_Read(0);
$028C	$01C4			CLRF	FARG_ADC_read, 1
$028D	$254C			CALL	_adc_read
$028E	$0870			MOVF	STACK_0, 0
$028F	$00AB			MOVWF	_res
$0290	$0871			MOVF	STACK_0+1, 0
$0291	$00AC			MOVWF	_res+1
;Temperature.ppas,24 :: 		WordtoStr(res,txt);
$0292	$0870			MOVF	STACK_0, 0
$0293	$00C4			MOVWF	FARG_WordToStr
$0294	$0871			MOVF	STACK_0+1, 0
$0295	$00C5			MOVWF	FARG_WordToStr+1
$0296	$302D			MOVLW	_txt
$0297	$00C6			MOVWF	FARG_WordToStr+2
$0298	$24B3			CALL	_wordtostr
;Temperature.ppas,25 :: 		Lcd_Out(1,10,txt);
$0299	$3001			MOVLW	1
$029A	$00D5			MOVWF	FARG_Lcd_Out
$029B	$300A			MOVLW	10
$029C	$00D6			MOVWF	FARG_Lcd_Out+1
$029D	$302D			MOVLW	_txt
$029E	$00D7			MOVWF	FARG_Lcd_Out+2
$029F	$250D			CALL	_lcd_out
;Temperature.ppas,26 :: 		temp:=(res*150)/1023;
$02A0	$082B			MOVF	_res, 0
$02A1	$00F0			MOVWF	STACK_0
$02A2	$082C			MOVF	_res+1, 0
$02A3	$00F1			MOVWF	STACK_0+1
$02A4	$01F2			CLRF	STACK_0+2
$02A5	$01F3			CLRF	STACK_0+3
$02A6	$3096			MOVLW	150
$02A7	$00F4			MOVWF	STACK_4
$02A8	$01F5			CLRF	STACK_4+1
$02A9	$01F6			CLRF	STACK_4+2
$02AA	$01F7			CLRF	STACK_4+3
$02AB	$25BF			CALL	_mul_32x32_u
$02AC	$30FF			MOVLW	255
$02AD	$00F4			MOVWF	STACK_4
$02AE	$3003			MOVLW	3
$02AF	$00F5			MOVWF	STACK_4+1
$02B0	$01F6			CLRF	STACK_4+2
$02B1	$01F7			CLRF	STACK_4+3
$02B2	$2398			CALL	_div_32x32_s
$02B3	$0870			MOVF	STACK_0, 0
$02B4	$00B3			MOVWF	_temp
$02B5	$0871			MOVF	STACK_0+1, 0
$02B6	$00B4			MOVWF	_temp+1
$02B7	$0872			MOVF	STACK_0+2, 0
$02B8	$00B5			MOVWF	_temp+2
$02B9	$0873			MOVF	STACK_0+3, 0
$02BA	$00B6			MOVWF	_temp+3
;Temperature.ppas,27 :: 		WordtoStr(temp,txt);
$02BB	$0870			MOVF	STACK_0, 0
$02BC	$00C4			MOVWF	FARG_WordToStr
$02BD	$0871			MOVF	STACK_0+1, 0
$02BE	$00C5			MOVWF	FARG_WordToStr+1
$02BF	$302D			MOVLW	_txt
$02C0	$00C6			MOVWF	FARG_WordToStr+2
$02C1	$24B3			CALL	_wordtostr
;Temperature.ppas,28 :: 		Lcd_Out(2,13,txt);
$02C2	$3002			MOVLW	2
$02C3	$00D5			MOVWF	FARG_Lcd_Out
$02C4	$300D			MOVLW	13
$02C5	$00D6			MOVWF	FARG_Lcd_Out+1
$02C6	$302D			MOVLW	_txt
$02C7	$00D7			MOVWF	FARG_Lcd_Out+2
$02C8	$250D			CALL	_lcd_out
;Temperature.ppas,29 :: 		Lcd_Chr(2,17,'C');
$02C9	$3002			MOVLW	2
$02CA	$00C4			MOVWF	FARG_Lcd_Chr
$02CB	$3011			MOVLW	17
$02CC	$00C5			MOVWF	FARG_Lcd_Chr+1
$02CD	$3043			MOVLW	67
$02CE	$00C6			MOVWF	FARG_Lcd_Chr+2
$02CF	$258D			CALL	_lcd_chr
;Temperature.ppas,32 :: 		delay_ms(100);
$02D0	$3002			MOVLW	2
$02D1	$00FC			MOVWF	STACK_12
$02D2	$30FF			MOVLW	255
$02D3	$00FB			MOVWF	STACK_11
$02D4	$30FF			MOVLW	255
$02D5	$00FA			MOVWF	STACK_10
$02D6	$0BFC			DECFSZ	STACK_12, F
$02D7	$2AD9			GOTO	$+2
$02D8	$2AE0			GOTO	$+8
$02D9	$0BFB			DECFSZ	STACK_11, F
$02DA	$2ADC			GOTO	$+2
$02DB	$2ADF			GOTO	$+4
$02DC	$0BFA			DECFSZ	STACK_10, F
$02DD	$2ADC			GOTO	$-1
$02DE	$2AD9			GOTO	$-5
$02DF	$2AD6			GOTO	$-9
$02E0	$3006			MOVLW	6
$02E1	$00FB			MOVWF	STACK_11
$02E2	$30FF			MOVLW	255
$02E3	$00FA			MOVWF	STACK_10
$02E4	$0BFB			DECFSZ	STACK_11, F
$02E5	$2AE7			GOTO	$+2
$02E6	$2AEA			GOTO	$+4
$02E7	$0BFA			DECFSZ	STACK_10, F
$02E8	$2AE7			GOTO	$-1
$02E9	$2AE4			GOTO	$-5
$02EA	$300A			MOVLW	10
$02EB	$00FA			MOVWF	STACK_10
$02EC	$0BFA			DECFSZ	STACK_10, F
$02ED	$2AEC			GOTO	$-1
$02EE	$0000			NOP
;Temperature.ppas,34 :: 		end;
$02EF	$2A8C			GOTO	Temperature_L_3
;Temperature.ppas,40 :: 		end.
$02F0	$2AF0			GOTO	$
