;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 02/03/2021 11:35:23
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$003F	$	_init:
;Telerupteur.ppas,3 :: 		begin
;Telerupteur.ppas,4 :: 		TRISB := $00;
$003F	$1303			BCF	STATUS, RP1
$0040	$1683			BSF	STATUS, RP0
$0041	$0186			CLRF	TRISB, 1
;Telerupteur.ppas,5 :: 		TRISA := $FF;
$0042	$30FF			MOVLW	255
$0043	$0085			MOVWF	TRISA
;Telerupteur.ppas,6 :: 		PORTB := $00;
$0044	$1283			BCF	STATUS, RP0
$0045	$0186			CLRF	PORTB, 1
$0046	$	Telerupteur_L_0:
;Telerupteur.ppas,8 :: 		end;
$0046	$0008			RETURN
$0004	$	_main:
;Telerupteur.ppas,10 :: 		begin
;Telerupteur.ppas,11 :: 		Init();
$0004	$203F			CALL	_init
;Telerupteur.ppas,12 :: 		ADCON1:=$06;
$0005	$3006			MOVLW	6
$0006	$1683			BSF	STATUS, RP0
$0007	$009F			MOVWF	ADCON1
;Telerupteur.ppas,13 :: 		while (1) do
$0008	$	Telerupteur_L_3:
;Telerupteur.ppas,15 :: 		if (PORTA.0 =1) then
$0008	$1283			BCF	STATUS, RP0
$0009	$0805			MOVF	PORTA, 0
$000A	$00F1			MOVWF	STACK_1
$000B	$3001			MOVLW	1
$000C	$05F1			ANDWF	STACK_1, 1
$000D	$0871			MOVF	STACK_1, 0
$000E	$3A01			XORLW	1
$000F	$1D03			BTFSS	STATUS, Z
$0010	$283D			GOTO	Telerupteur_L_8
$0011	$	Telerupteur_L_7:
;Telerupteur.ppas,17 :: 		PORTB.0:= 1 xor PORTB.0;
$0011	$0806			MOVF	PORTB, 0
$0012	$00F1			MOVWF	STACK_1
$0013	$3001			MOVLW	1
$0014	$05F1			ANDWF	STACK_1, 1
$0015	$3001			MOVLW	1
$0016	$06F1			XORWF	STACK_1, 1
$0017	$0871			MOVF	STACK_1, 0
$0018	$3A00			XORLW	0
$0019	$1D03			BTFSS	STATUS, Z
$001A	$281D			GOTO	Telerupteur_L_10
$001B	$1006			BCF	PORTB, 0
$001C	$281E			GOTO	Telerupteur_L_11
$001D	$	Telerupteur_L_10:
$001D	$1406			BSF	PORTB, 0
$001E	$	Telerupteur_L_11:
;Telerupteur.ppas,18 :: 		Delay_ms(500);
$001E	$3006			MOVLW	6
$001F	$00FC			MOVWF	STACK_12
$0020	$30FF			MOVLW	255
$0021	$00FB			MOVWF	STACK_11
$0022	$30FF			MOVLW	255
$0023	$00FA			MOVWF	STACK_10
$0024	$0BFC			DECFSZ	STACK_12, F
$0025	$2827			GOTO	$+2
$0026	$282E			GOTO	$+8
$0027	$0BFB			DECFSZ	STACK_11, F
$0028	$282A			GOTO	$+2
$0029	$282D			GOTO	$+4
$002A	$0BFA			DECFSZ	STACK_10, F
$002B	$282A			GOTO	$-1
$002C	$2827			GOTO	$-5
$002D	$2824			GOTO	$-9
$002E	$301A			MOVLW	26
$002F	$00FB			MOVWF	STACK_11
$0030	$30FF			MOVLW	255
$0031	$00FA			MOVWF	STACK_10
$0032	$0BFB			DECFSZ	STACK_11, F
$0033	$2835			GOTO	$+2
$0034	$2838			GOTO	$+4
$0035	$0BFA			DECFSZ	STACK_10, F
$0036	$2835			GOTO	$-1
$0037	$2832			GOTO	$-5
$0038	$3042			MOVLW	66
$0039	$00FA			MOVWF	STACK_10
$003A	$0BFA			DECFSZ	STACK_10, F
$003B	$283A			GOTO	$-1
$003C	$0000			NOP
;Telerupteur.ppas,19 :: 		end;
$003D	$	Telerupteur_L_8:
$003D	$	Telerupteur_L_9:
;Telerupteur.ppas,20 :: 		end;
$003D	$2808			GOTO	Telerupteur_L_3
;Telerupteur.ppas,21 :: 		end.
$003E	$283E			GOTO	$
