;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 07/06/2021 13:46:09
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2AF8			GOTO	_main
$0641	$	_delay_1us:
;delays.ppas,11 :: 		begin
;delays.ppas,12 :: 		Delay_us(1);
$0641	$0000			NOP
$0642	$0000			NOP
$0643	$	delays_L_1:
;delays.ppas,13 :: 		end;
$0643	$0008			RETURN
$0609	$	_delay_5500us:
;delays.ppas,41 :: 		begin
;delays.ppas,42 :: 		Delay_us(5500);
$0609	$300F			MOVLW	15
$060A	$1303			BCF	STATUS, RP1
$060B	$1283			BCF	STATUS, RP0
$060C	$00FB			MOVWF	STACK_11
$060D	$30FF			MOVLW	255
$060E	$00FA			MOVWF	STACK_10
$060F	$0BFB			DECFSZ	STACK_11, F
$0610	$2E12			GOTO	$+2
$0611	$2E15			GOTO	$+4
$0612	$0BFA			DECFSZ	STACK_10, F
$0613	$2E12			GOTO	$-1
$0614	$2E0F			GOTO	$-5
$0615	$303E			MOVLW	62
$0616	$00FA			MOVWF	STACK_10
$0617	$0BFA			DECFSZ	STACK_10, F
$0618	$2E17			GOTO	$-1
$0619	$0000			NOP
$061A	$	delays_L_7:
;delays.ppas,43 :: 		end;
$061A	$0008			RETURN
$063A	$	_delay_50us:
;delays.ppas,26 :: 		begin
;delays.ppas,27 :: 		Delay_us(50);
$063A	$3021			MOVLW	33
$063B	$1303			BCF	STATUS, RP1
$063C	$1283			BCF	STATUS, RP0
$063D	$00FA			MOVWF	STACK_10
$063E	$0BFA			DECFSZ	STACK_10, F
$063F	$2E3E			GOTO	$-1
$0640	$	delays_L_4:
;delays.ppas,28 :: 		end;
$0640	$0008			RETURN
$0251	$	_lcd_cmd:
;lcd.ppas,19 :: 		
;lcd.ppas,20 :: 		
$0251	$1303			BCF	STATUS, RP1
$0252	$1283			BCF	STATUS, RP0
$0253	$0821			MOVF	lcd_ctrlport_address, 0
$0254	$0084			MOVWF	FSR
;lcd.ppas,22 :: 		
$0255	$0922			COMF	lcd____menable, W
$0256	$00F0			MOVWF	STACK_0
$0257	$0870			MOVF	STACK_0, 0
$0258	$0580			ANDWF	INDF, 1
;lcd.ppas,23 :: 		
$0259	$0923			COMF	lcd____mrs, W
$025A	$00F0			MOVWF	STACK_0
$025B	$0870			MOVF	STACK_0, 0
$025C	$0580			ANDWF	INDF, 1
;lcd.ppas,25 :: 		
$025D	$0824			MOVF	lcd_dataport_address, 0
$025E	$0084			MOVWF	FSR
;lcd.ppas,26 :: 		
$025F	$0826			MOVF	lcd____mdb6, 0
$0260	$0425			IORWF	lcd____mdb7, 0
$0261	$00F0			MOVWF	STACK_0
$0262	$0827			MOVF	lcd____mdb5, 0
$0263	$04F0			IORWF	STACK_0, 1
$0264	$0828			MOVF	lcd____mdb4, 0
$0265	$04F0			IORWF	STACK_0, 1
$0266	$09F0			COMF	STACK_0, F
$0267	$0870			MOVF	STACK_0, 0
$0268	$0580			ANDWF	INDF, 1
;lcd.ppas,28 :: 		
$0269	$3000			MOVLW	0
$026A	$1BE2			BTFSC	FARG_Lcd_Cmd, 7
$026B	$3001			MOVLW	1
$026C	$00F1			MOVWF	STACK_1
$026D	$0871			MOVF	STACK_1, 0
$026E	$3A01			XORLW	1
$026F	$1D03			BTFSS	STATUS, Z
$0270	$2A73			GOTO	lcd_L_2
$0271	$	lcd_L_1:
;lcd.ppas,29 :: 		
$0271	$0825			MOVF	lcd____mdb7, 0
$0272	$0480			IORWF	INDF, 1
$0273	$	lcd_L_2:
$0273	$	lcd_L_3:
;lcd.ppas,30 :: 		
$0273	$3000			MOVLW	0
$0274	$1B62			BTFSC	FARG_Lcd_Cmd, 6
$0275	$3001			MOVLW	1
$0276	$00F1			MOVWF	STACK_1
$0277	$0871			MOVF	STACK_1, 0
$0278	$3A01			XORLW	1
$0279	$1D03			BTFSS	STATUS, Z
$027A	$2A7D			GOTO	lcd_L_5
$027B	$	lcd_L_4:
;lcd.ppas,31 :: 		
$027B	$0826			MOVF	lcd____mdb6, 0
$027C	$0480			IORWF	INDF, 1
$027D	$	lcd_L_5:
$027D	$	lcd_L_6:
;lcd.ppas,32 :: 		
$027D	$3000			MOVLW	0
$027E	$1AE2			BTFSC	FARG_Lcd_Cmd, 5
$027F	$3001			MOVLW	1
$0280	$00F1			MOVWF	STACK_1
$0281	$0871			MOVF	STACK_1, 0
$0282	$3A01			XORLW	1
$0283	$1D03			BTFSS	STATUS, Z
$0284	$2A87			GOTO	lcd_L_8
$0285	$	lcd_L_7:
;lcd.ppas,33 :: 		
$0285	$0827			MOVF	lcd____mdb5, 0
$0286	$0480			IORWF	INDF, 1
$0287	$	lcd_L_8:
$0287	$	lcd_L_9:
;lcd.ppas,34 :: 		
$0287	$3000			MOVLW	0
$0288	$1A62			BTFSC	FARG_Lcd_Cmd, 4
$0289	$3001			MOVLW	1
$028A	$00F1			MOVWF	STACK_1
$028B	$0871			MOVF	STACK_1, 0
$028C	$3A01			XORLW	1
$028D	$1D03			BTFSS	STATUS, Z
$028E	$2A91			GOTO	lcd_L_11
$028F	$	lcd_L_10:
;lcd.ppas,35 :: 		
$028F	$0828			MOVF	lcd____mdb4, 0
$0290	$0480			IORWF	INDF, 1
$0291	$	lcd_L_11:
$0291	$	lcd_L_12:
;lcd.ppas,37 :: 		
$0291	$0821			MOVF	lcd_ctrlport_address, 0
$0292	$0084			MOVWF	FSR
;lcd.ppas,38 :: 		
$0293	$0829			MOVF	lcd_lcdcmd_status, 0
$0294	$3A01			XORLW	1
$0295	$1D03			BTFSS	STATUS, Z
$0296	$2A9C			GOTO	lcd_L_14
$0297	$	lcd_L_13:
;lcd.ppas,39 :: 		
$0297	$0923			COMF	lcd____mrs, W
$0298	$00F0			MOVWF	STACK_0
$0299	$0870			MOVF	STACK_0, 0
$029A	$0580			ANDWF	INDF, 1
$029B	$2A9E			GOTO	lcd_L_15
;lcd.ppas,40 :: 		
$029C	$	lcd_L_14:
;lcd.ppas,41 :: 		
$029C	$0823			MOVF	lcd____mrs, 0
$029D	$0480			IORWF	INDF, 1
$029E	$	lcd_L_15:
;lcd.ppas,43 :: 		
$029E	$0822			MOVF	lcd____menable, 0
$029F	$0480			IORWF	INDF, 1
;lcd.ppas,44 :: 		
$02A0	$2641			CALL	_delay_1us
;lcd.ppas,45 :: 		
$02A1	$0922			COMF	lcd____menable, W
$02A2	$00F0			MOVWF	STACK_0
$02A3	$0870			MOVF	STACK_0, 0
$02A4	$0580			ANDWF	INDF, 1
;lcd.ppas,47 :: 		
$02A5	$0923			COMF	lcd____mrs, W
$02A6	$00F0			MOVWF	STACK_0
$02A7	$0870			MOVF	STACK_0, 0
$02A8	$0580			ANDWF	INDF, 1
;lcd.ppas,49 :: 		
$02A9	$0824			MOVF	lcd_dataport_address, 0
$02AA	$0084			MOVWF	FSR
;lcd.ppas,50 :: 		
$02AB	$0826			MOVF	lcd____mdb6, 0
$02AC	$0425			IORWF	lcd____mdb7, 0
$02AD	$00F0			MOVWF	STACK_0
$02AE	$0827			MOVF	lcd____mdb5, 0
$02AF	$04F0			IORWF	STACK_0, 1
$02B0	$0828			MOVF	lcd____mdb4, 0
$02B1	$04F0			IORWF	STACK_0, 1
$02B2	$09F0			COMF	STACK_0, F
$02B3	$0870			MOVF	STACK_0, 0
$02B4	$0580			ANDWF	INDF, 1
;lcd.ppas,52 :: 		
$02B5	$3000			MOVLW	0
$02B6	$19E2			BTFSC	FARG_Lcd_Cmd, 3
$02B7	$3001			MOVLW	1
$02B8	$00F1			MOVWF	STACK_1
$02B9	$0871			MOVF	STACK_1, 0
$02BA	$3A01			XORLW	1
$02BB	$1D03			BTFSS	STATUS, Z
$02BC	$2ABF			GOTO	lcd_L_17
$02BD	$	lcd_L_16:
;lcd.ppas,53 :: 		
$02BD	$0825			MOVF	lcd____mdb7, 0
$02BE	$0480			IORWF	INDF, 1
$02BF	$	lcd_L_17:
$02BF	$	lcd_L_18:
;lcd.ppas,54 :: 		
$02BF	$3000			MOVLW	0
$02C0	$1962			BTFSC	FARG_Lcd_Cmd, 2
$02C1	$3001			MOVLW	1
$02C2	$00F1			MOVWF	STACK_1
$02C3	$0871			MOVF	STACK_1, 0
$02C4	$3A01			XORLW	1
$02C5	$1D03			BTFSS	STATUS, Z
$02C6	$2AC9			GOTO	lcd_L_20
$02C7	$	lcd_L_19:
;lcd.ppas,55 :: 		
$02C7	$0826			MOVF	lcd____mdb6, 0
$02C8	$0480			IORWF	INDF, 1
$02C9	$	lcd_L_20:
$02C9	$	lcd_L_21:
;lcd.ppas,56 :: 		
$02C9	$3000			MOVLW	0
$02CA	$18E2			BTFSC	FARG_Lcd_Cmd, 1
$02CB	$3001			MOVLW	1
$02CC	$00F1			MOVWF	STACK_1
$02CD	$0871			MOVF	STACK_1, 0
$02CE	$3A01			XORLW	1
$02CF	$1D03			BTFSS	STATUS, Z
$02D0	$2AD3			GOTO	lcd_L_23
$02D1	$	lcd_L_22:
;lcd.ppas,57 :: 		
$02D1	$0827			MOVF	lcd____mdb5, 0
$02D2	$0480			IORWF	INDF, 1
$02D3	$	lcd_L_23:
$02D3	$	lcd_L_24:
;lcd.ppas,58 :: 		
$02D3	$3001			MOVLW	1
$02D4	$0562			ANDWF	FARG_Lcd_Cmd, 0
$02D5	$00F1			MOVWF	STACK_1
$02D6	$0871			MOVF	STACK_1, 0
$02D7	$3A01			XORLW	1
$02D8	$1D03			BTFSS	STATUS, Z
$02D9	$2ADC			GOTO	lcd_L_26
$02DA	$	lcd_L_25:
;lcd.ppas,59 :: 		
$02DA	$0828			MOVF	lcd____mdb4, 0
$02DB	$0480			IORWF	INDF, 1
$02DC	$	lcd_L_26:
$02DC	$	lcd_L_27:
;lcd.ppas,61 :: 		
$02DC	$0821			MOVF	lcd_ctrlport_address, 0
$02DD	$0084			MOVWF	FSR
;lcd.ppas,62 :: 		
$02DE	$0829			MOVF	lcd_lcdcmd_status, 0
$02DF	$3A01			XORLW	1
$02E0	$1D03			BTFSS	STATUS, Z
$02E1	$2AE7			GOTO	lcd_L_29
$02E2	$	lcd_L_28:
;lcd.ppas,63 :: 		
$02E2	$0923			COMF	lcd____mrs, W
$02E3	$00F0			MOVWF	STACK_0
$02E4	$0870			MOVF	STACK_0, 0
$02E5	$0580			ANDWF	INDF, 1
$02E6	$2AE9			GOTO	lcd_L_30
;lcd.ppas,64 :: 		
$02E7	$	lcd_L_29:
;lcd.ppas,65 :: 		
$02E7	$0823			MOVF	lcd____mrs, 0
$02E8	$0480			IORWF	INDF, 1
$02E9	$	lcd_L_30:
;lcd.ppas,67 :: 		
$02E9	$0822			MOVF	lcd____menable, 0
$02EA	$0480			IORWF	INDF, 1
;lcd.ppas,68 :: 		
$02EB	$2641			CALL	_delay_1us
;lcd.ppas,69 :: 		
$02EC	$0922			COMF	lcd____menable, W
$02ED	$00F0			MOVWF	STACK_0
$02EE	$0870			MOVF	STACK_0, 0
$02EF	$0580			ANDWF	INDF, 1
;lcd.ppas,71 :: 		
$02F0	$0829			MOVF	lcd_lcdcmd_status, 0
$02F1	$3A01			XORLW	1
$02F2	$1D03			BTFSS	STATUS, Z
$02F3	$2AF6			GOTO	lcd_L_32
$02F4	$	lcd_L_31:
;lcd.ppas,72 :: 		
$02F4	$2609			CALL	_delay_5500us
$02F5	$2AF7			GOTO	lcd_L_33
;lcd.ppas,73 :: 		
$02F6	$	lcd_L_32:
;lcd.ppas,74 :: 		
$02F6	$263A			CALL	_delay_50us
$02F7	$	lcd_L_33:
$02F7	$	lcd_L_0:
;lcd.ppas,75 :: 		
$02F7	$0008			RETURN
$0004	$	_lcd_config:
;lcd.ppas,115 :: 		
;lcd.ppas,116 :: 		
$0004	$2609			CALL	_delay_5500us
;lcd.ppas,117 :: 		
$0005	$2609			CALL	_delay_5500us
;lcd.ppas,118 :: 		
$0006	$2609			CALL	_delay_5500us
;lcd.ppas,120 :: 		
$0007	$085A			MOVF	FARG_Lcd_Config+1, 0
$0008	$00F0			MOVWF	STACK_0
$0009	$3001			MOVLW	1
$000A	$00F4			MOVWF	STACK_4
$000B	$0870			MOVF	STACK_0, 0
$000C	$	L_Lcd_Config_0:
$000C	$1903			BTFSC	STATUS, Z
$000D	$2812			GOTO	L_Lcd_Config_1
$000E	$0DF4			RLF	STACK_4, 1
$000F	$1074			BCF	STACK_4, 0
$0010	$3FFF			ADDLW	255
$0011	$280C			GOTO	L_Lcd_Config_0
$0012	$	L_Lcd_Config_1:
$0012	$0874			MOVF	STACK_4, 0
$0013	$00A5			MOVWF	lcd____mdb7
;lcd.ppas,121 :: 		
$0014	$085B			MOVF	FARG_Lcd_Config+2, 0
$0015	$00F0			MOVWF	STACK_0
$0016	$3001			MOVLW	1
$0017	$00F3			MOVWF	STACK_3
$0018	$0870			MOVF	STACK_0, 0
$0019	$	L_Lcd_Config_2:
$0019	$1903			BTFSC	STATUS, Z
$001A	$281F			GOTO	L_Lcd_Config_3
$001B	$0DF3			RLF	STACK_3, 1
$001C	$1073			BCF	STACK_3, 0
$001D	$3FFF			ADDLW	255
$001E	$2819			GOTO	L_Lcd_Config_2
$001F	$	L_Lcd_Config_3:
$001F	$0873			MOVF	STACK_3, 0
$0020	$00A6			MOVWF	lcd____mdb6
;lcd.ppas,122 :: 		
$0021	$085C			MOVF	FARG_Lcd_Config+3, 0
$0022	$00F0			MOVWF	STACK_0
$0023	$3001			MOVLW	1
$0024	$00F2			MOVWF	STACK_2
$0025	$0870			MOVF	STACK_0, 0
$0026	$	L_Lcd_Config_4:
$0026	$1903			BTFSC	STATUS, Z
$0027	$282C			GOTO	L_Lcd_Config_5
$0028	$0DF2			RLF	STACK_2, 1
$0029	$1072			BCF	STACK_2, 0
$002A	$3FFF			ADDLW	255
$002B	$2826			GOTO	L_Lcd_Config_4
$002C	$	L_Lcd_Config_5:
$002C	$0872			MOVF	STACK_2, 0
$002D	$00A7			MOVWF	lcd____mdb5
;lcd.ppas,123 :: 		
$002E	$085D			MOVF	FARG_Lcd_Config+4, 0
$002F	$00F0			MOVWF	STACK_0
$0030	$3001			MOVLW	1
$0031	$00F1			MOVWF	STACK_1
$0032	$0870			MOVF	STACK_0, 0
$0033	$	L_Lcd_Config_6:
$0033	$1903			BTFSC	STATUS, Z
$0034	$2839			GOTO	L_Lcd_Config_7
$0035	$0DF1			RLF	STACK_1, 1
$0036	$1071			BCF	STACK_1, 0
$0037	$3FFF			ADDLW	255
$0038	$2833			GOTO	L_Lcd_Config_6
$0039	$	L_Lcd_Config_7:
$0039	$0871			MOVF	STACK_1, 0
$003A	$00A8			MOVWF	lcd____mdb4
;lcd.ppas,124 :: 		
$003B	$085F			MOVF	FARG_Lcd_Config+6, 0
$003C	$00F0			MOVWF	STACK_0
$003D	$3001			MOVLW	1
$003E	$00A3			MOVWF	lcd____mrs
$003F	$0870			MOVF	STACK_0, 0
$0040	$	L_Lcd_Config_8:
$0040	$1903			BTFSC	STATUS, Z
$0041	$2846			GOTO	L_Lcd_Config_9
$0042	$0DA3			RLF	lcd____mrs, 1
$0043	$1023			BCF	lcd____mrs, 0
$0044	$3FFF			ADDLW	255
$0045	$2840			GOTO	L_Lcd_Config_8
$0046	$	L_Lcd_Config_9:
;lcd.ppas,125 :: 		
$0046	$0860			MOVF	FARG_Lcd_Config+7, 0
$0047	$00F0			MOVWF	STACK_0
$0048	$3001			MOVLW	1
$0049	$00AA			MOVWF	lcd____mrw
$004A	$0870			MOVF	STACK_0, 0
$004B	$	L_Lcd_Config_10:
$004B	$1903			BTFSC	STATUS, Z
$004C	$2851			GOTO	L_Lcd_Config_11
$004D	$0DAA			RLF	lcd____mrw, 1
$004E	$102A			BCF	lcd____mrw, 0
$004F	$3FFF			ADDLW	255
$0050	$284B			GOTO	L_Lcd_Config_10
$0051	$	L_Lcd_Config_11:
;lcd.ppas,126 :: 		
$0051	$0861			MOVF	FARG_Lcd_Config+8, 0
$0052	$00F0			MOVWF	STACK_0
$0053	$3001			MOVLW	1
$0054	$00A2			MOVWF	lcd____menable
$0055	$0870			MOVF	STACK_0, 0
$0056	$	L_Lcd_Config_12:
$0056	$1903			BTFSC	STATUS, Z
$0057	$285C			GOTO	L_Lcd_Config_13
$0058	$0DA2			RLF	lcd____menable, 1
$0059	$1022			BCF	lcd____menable, 0
$005A	$3FFF			ADDLW	255
$005B	$2856			GOTO	L_Lcd_Config_12
$005C	$	L_Lcd_Config_13:
;lcd.ppas,128 :: 		
$005C	$0859			MOVF	FARG_Lcd_Config, 0
$005D	$00A4			MOVWF	lcd_dataport_address
;lcd.ppas,129 :: 		
$005E	$085E			MOVF	FARG_Lcd_Config+5, 0
$005F	$00A1			MOVWF	lcd_ctrlport_address
;lcd.ppas,131 :: 		
$0060	$0859			MOVF	FARG_Lcd_Config, 0
$0061	$0084			MOVWF	FSR
;lcd.ppas,133 :: 		
$0062	$0873			MOVF	STACK_3, 0
$0063	$0474			IORWF	STACK_4, 0
$0064	$00F0			MOVWF	STACK_0
$0065	$0872			MOVF	STACK_2, 0
$0066	$04F0			IORWF	STACK_0, 1
$0067	$0871			MOVF	STACK_1, 0
$0068	$04F0			IORWF	STACK_0, 1
$0069	$09F0			COMF	STACK_0, F
$006A	$0870			MOVF	STACK_0, 0
$006B	$0580			ANDWF	INDF, 1
;lcd.ppas,134 :: 		
$006C	$	lcd_L_56:
$006C	$1784			BSF	FSR, 7
$006D	$	lcd_L_57:
;lcd.ppas,135 :: 		
$006D	$0826			MOVF	lcd____mdb6, 0
$006E	$0425			IORWF	lcd____mdb7, 0
$006F	$00F0			MOVWF	STACK_0
$0070	$0827			MOVF	lcd____mdb5, 0
$0071	$04F0			IORWF	STACK_0, 1
$0072	$0828			MOVF	lcd____mdb4, 0
$0073	$04F0			IORWF	STACK_0, 1
$0074	$09F0			COMF	STACK_0, F
$0075	$0870			MOVF	STACK_0, 0
$0076	$0580			ANDWF	INDF, 1
;lcd.ppas,136 :: 		
$0077	$1384			BCF	FSR, 7
$0078	$	lcd_L_59:
;lcd.ppas,139 :: 		
$0078	$0821			MOVF	lcd_ctrlport_address, 0
$0079	$0084			MOVWF	FSR
;lcd.ppas,141 :: 		
$007A	$082A			MOVF	lcd____mrw, 0
$007B	$0423			IORWF	lcd____mrs, 0
$007C	$00F0			MOVWF	STACK_0
$007D	$0822			MOVF	lcd____menable, 0
$007E	$04F0			IORWF	STACK_0, 1
$007F	$09F0			COMF	STACK_0, F
$0080	$0870			MOVF	STACK_0, 0
$0081	$0580			ANDWF	INDF, 1
;lcd.ppas,142 :: 		
$0082	$	lcd_L_60:
$0082	$1784			BSF	FSR, 7
$0083	$	lcd_L_61:
;lcd.ppas,143 :: 		
$0083	$082A			MOVF	lcd____mrw, 0
$0084	$0423			IORWF	lcd____mrs, 0
$0085	$00F0			MOVWF	STACK_0
$0086	$0822			MOVF	lcd____menable, 0
$0087	$04F0			IORWF	STACK_0, 1
$0088	$09F0			COMF	STACK_0, F
$0089	$0870			MOVF	STACK_0, 0
$008A	$0580			ANDWF	INDF, 1
;lcd.ppas,144 :: 		
$008B	$1384			BCF	FSR, 7
$008C	$	lcd_L_63:
;lcd.ppas,148 :: 		
$008C	$0824			MOVF	lcd_dataport_address, 0
$008D	$0084			MOVWF	FSR
;lcd.ppas,149 :: 		
$008E	$0827			MOVF	lcd____mdb5, 0
$008F	$0400			IORWF	INDF, 0
$0090	$00F0			MOVWF	STACK_0
$0091	$0828			MOVF	lcd____mdb4, 0
$0092	$0470			IORWF	STACK_0, 0
$0093	$0080			MOVWF	INDF
;lcd.ppas,151 :: 		
$0094	$0821			MOVF	lcd_ctrlport_address, 0
$0095	$0084			MOVWF	FSR
;lcd.ppas,152 :: 		
$0096	$0822			MOVF	lcd____menable, 0
$0097	$0480			IORWF	INDF, 1
;lcd.ppas,153 :: 		
$0098	$0922			COMF	lcd____menable, W
$0099	$00F0			MOVWF	STACK_0
$009A	$0870			MOVF	STACK_0, 0
$009B	$0580			ANDWF	INDF, 1
;lcd.ppas,155 :: 		
$009C	$2609			CALL	_delay_5500us
;lcd.ppas,160 :: 		
$009D	$0822			MOVF	lcd____menable, 0
$009E	$0480			IORWF	INDF, 1
;lcd.ppas,161 :: 		
$009F	$0922			COMF	lcd____menable, W
$00A0	$00F0			MOVWF	STACK_0
$00A1	$0870			MOVF	STACK_0, 0
$00A2	$0580			ANDWF	INDF, 1
;lcd.ppas,163 :: 		
$00A3	$2609			CALL	_delay_5500us
;lcd.ppas,168 :: 		
$00A4	$0822			MOVF	lcd____menable, 0
$00A5	$0480			IORWF	INDF, 1
;lcd.ppas,169 :: 		
$00A6	$0922			COMF	lcd____menable, W
$00A7	$00F0			MOVWF	STACK_0
$00A8	$0870			MOVF	STACK_0, 0
$00A9	$0580			ANDWF	INDF, 1
;lcd.ppas,171 :: 		
$00AA	$2609			CALL	_delay_5500us
;lcd.ppas,174 :: 		
$00AB	$0824			MOVF	lcd_dataport_address, 0
$00AC	$0084			MOVWF	FSR
;lcd.ppas,175 :: 		
$00AD	$0827			MOVF	lcd____mdb5, 0
$00AE	$0480			IORWF	INDF, 1
;lcd.ppas,176 :: 		
$00AF	$0928			COMF	lcd____mdb4, W
$00B0	$00F0			MOVWF	STACK_0
$00B1	$0870			MOVF	STACK_0, 0
$00B2	$0580			ANDWF	INDF, 1
;lcd.ppas,178 :: 		
$00B3	$0821			MOVF	lcd_ctrlport_address, 0
$00B4	$0084			MOVWF	FSR
;lcd.ppas,179 :: 		
$00B5	$0822			MOVF	lcd____menable, 0
$00B6	$0480			IORWF	INDF, 1
;lcd.ppas,180 :: 		
$00B7	$0922			COMF	lcd____menable, W
$00B8	$00F0			MOVWF	STACK_0
$00B9	$0870			MOVF	STACK_0, 0
$00BA	$0580			ANDWF	INDF, 1
;lcd.ppas,182 :: 		
$00BB	$2609			CALL	_delay_5500us
;lcd.ppas,187 :: 		
$00BC	$0822			MOVF	lcd____menable, 0
$00BD	$0480			IORWF	INDF, 1
;lcd.ppas,188 :: 		
$00BE	$0922			COMF	lcd____menable, W
$00BF	$00F1			MOVWF	STACK_1
$00C0	$0871			MOVF	STACK_1, 0
$00C1	$0580			ANDWF	INDF, 1
;lcd.ppas,190 :: 		
$00C2	$0824			MOVF	lcd_dataport_address, 0
$00C3	$0084			MOVWF	FSR
;lcd.ppas,191 :: 		
$00C4	$0927			COMF	lcd____mdb5, W
$00C5	$00F0			MOVWF	STACK_0
$00C6	$0870			MOVF	STACK_0, 0
$00C7	$0580			ANDWF	INDF, 1
;lcd.ppas,192 :: 		
$00C8	$0825			MOVF	lcd____mdb7, 0
$00C9	$0480			IORWF	INDF, 1
;lcd.ppas,194 :: 		
$00CA	$0821			MOVF	lcd_ctrlport_address, 0
$00CB	$0084			MOVWF	FSR
;lcd.ppas,195 :: 		
$00CC	$0822			MOVF	lcd____menable, 0
$00CD	$0480			IORWF	INDF, 1
;lcd.ppas,196 :: 		
$00CE	$0871			MOVF	STACK_1, 0
$00CF	$0580			ANDWF	INDF, 1
;lcd.ppas,198 :: 		
$00D0	$2609			CALL	_delay_5500us
;lcd.ppas,201 :: 		
$00D1	$0824			MOVF	lcd_dataport_address, 0
$00D2	$0084			MOVWF	FSR
;lcd.ppas,202 :: 		
$00D3	$0925			COMF	lcd____mdb7, W
$00D4	$00F0			MOVWF	STACK_0
$00D5	$0870			MOVF	STACK_0, 0
$00D6	$0580			ANDWF	INDF, 1
;lcd.ppas,203 :: 		
$00D7	$0828			MOVF	lcd____mdb4, 0
$00D8	$0480			IORWF	INDF, 1
;lcd.ppas,204 :: 		
$00D9	$0821			MOVF	lcd_ctrlport_address, 0
$00DA	$0084			MOVWF	FSR
;lcd.ppas,205 :: 		
$00DB	$0822			MOVF	lcd____menable, 0
$00DC	$0480			IORWF	INDF, 1
;lcd.ppas,206 :: 		
$00DD	$0922			COMF	lcd____menable, W
$00DE	$00F1			MOVWF	STACK_1
$00DF	$0871			MOVF	STACK_1, 0
$00E0	$0580			ANDWF	INDF, 1
;lcd.ppas,207 :: 		
$00E1	$0824			MOVF	lcd_dataport_address, 0
$00E2	$0084			MOVWF	FSR
;lcd.ppas,208 :: 		
$00E3	$0928			COMF	lcd____mdb4, W
$00E4	$00F0			MOVWF	STACK_0
$00E5	$0870			MOVF	STACK_0, 0
$00E6	$0580			ANDWF	INDF, 1
;lcd.ppas,209 :: 		
$00E7	$0821			MOVF	lcd_ctrlport_address, 0
$00E8	$0084			MOVWF	FSR
;lcd.ppas,210 :: 		
$00E9	$0822			MOVF	lcd____menable, 0
$00EA	$0480			IORWF	INDF, 1
;lcd.ppas,211 :: 		
$00EB	$0871			MOVF	STACK_1, 0
$00EC	$0580			ANDWF	INDF, 1
;lcd.ppas,213 :: 		
$00ED	$2609			CALL	_delay_5500us
;lcd.ppas,218 :: 		
$00EE	$0822			MOVF	lcd____menable, 0
$00EF	$0480			IORWF	INDF, 1
;lcd.ppas,219 :: 		
$00F0	$0922			COMF	lcd____menable, W
$00F1	$00F0			MOVWF	STACK_0
$00F2	$0870			MOVF	STACK_0, 0
$00F3	$0580			ANDWF	INDF, 1
;lcd.ppas,220 :: 		
$00F4	$0824			MOVF	lcd_dataport_address, 0
$00F5	$0084			MOVWF	FSR
;lcd.ppas,221 :: 		
$00F6	$0828			MOVF	lcd____mdb4, 0
$00F7	$0480			IORWF	INDF, 1
;lcd.ppas,222 :: 		
$00F8	$0821			MOVF	lcd_ctrlport_address, 0
$00F9	$0084			MOVWF	FSR
;lcd.ppas,223 :: 		
$00FA	$0822			MOVF	lcd____menable, 0
$00FB	$0480			IORWF	INDF, 1
;lcd.ppas,224 :: 		
$00FC	$0870			MOVF	STACK_0, 0
$00FD	$0580			ANDWF	INDF, 1
;lcd.ppas,226 :: 		
$00FE	$2609			CALL	_delay_5500us
;lcd.ppas,229 :: 		
$00FF	$0824			MOVF	lcd_dataport_address, 0
$0100	$0084			MOVWF	FSR
;lcd.ppas,230 :: 		
$0101	$0928			COMF	lcd____mdb4, W
$0102	$00F0			MOVWF	STACK_0
$0103	$0870			MOVF	STACK_0, 0
$0104	$0580			ANDWF	INDF, 1
;lcd.ppas,231 :: 		
$0105	$0821			MOVF	lcd_ctrlport_address, 0
$0106	$0084			MOVWF	FSR
;lcd.ppas,232 :: 		
$0107	$0822			MOVF	lcd____menable, 0
$0108	$0480			IORWF	INDF, 1
;lcd.ppas,233 :: 		
$0109	$0922			COMF	lcd____menable, W
$010A	$00F1			MOVWF	STACK_1
$010B	$0871			MOVF	STACK_1, 0
$010C	$0580			ANDWF	INDF, 1
;lcd.ppas,234 :: 		
$010D	$0824			MOVF	lcd_dataport_address, 0
$010E	$0084			MOVWF	FSR
;lcd.ppas,235 :: 		
$010F	$0828			MOVF	lcd____mdb4, 0
$0110	$0400			IORWF	INDF, 0
$0111	$00F0			MOVWF	STACK_0
$0112	$0827			MOVF	lcd____mdb5, 0
$0113	$04F0			IORWF	STACK_0, 1
$0114	$0826			MOVF	lcd____mdb6, 0
$0115	$04F0			IORWF	STACK_0, 1
$0116	$0825			MOVF	lcd____mdb7, 0
$0117	$0470			IORWF	STACK_0, 0
$0118	$0080			MOVWF	INDF
;lcd.ppas,236 :: 		
$0119	$0821			MOVF	lcd_ctrlport_address, 0
$011A	$0084			MOVWF	FSR
;lcd.ppas,237 :: 		
$011B	$0822			MOVF	lcd____menable, 0
$011C	$0480			IORWF	INDF, 1
;lcd.ppas,238 :: 		
$011D	$0871			MOVF	STACK_1, 0
$011E	$0580			ANDWF	INDF, 1
;lcd.ppas,240 :: 		
$011F	$2609			CALL	_delay_5500us
;lcd.ppas,242 :: 		
$0120	$3001			MOVLW	1
$0121	$00A9			MOVWF	lcd_lcdcmd_status
$0122	$	lcd_L_55:
;lcd.ppas,243 :: 		
$0122	$0008			RETURN
$0629	$	_lcd_chr_cp:
;lcd.ppas,97 :: 		
;lcd.ppas,98 :: 		
$0629	$1303			BCF	STATUS, RP1
$062A	$1283			BCF	STATUS, RP0
$062B	$01A9			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,99 :: 		
$062C	$0859			MOVF	FARG_Lcd_Chr_CP, 0
$062D	$00E2			MOVWF	FARG_Lcd_Cmd
$062E	$2251			CALL	_lcd_cmd
;lcd.ppas,100 :: 		
$062F	$3001			MOVLW	1
$0630	$00A9			MOVWF	lcd_lcdcmd_status
$0631	$	lcd_L_48:
;lcd.ppas,101 :: 		
$0631	$0008			RETURN
$05F4	$	_lcd_init:
;lcd.ppas,246 :: 		
;lcd.ppas,247 :: 		
$05F4	$1303			BCF	STATUS, RP1
$05F5	$1283			BCF	STATUS, RP0
$05F6	$0855			MOVF	FARG_Lcd_Init, 0
$05F7	$00D9			MOVWF	FARG_Lcd_Config
$05F8	$3007			MOVLW	7
$05F9	$00DA			MOVWF	FARG_Lcd_Config+1
$05FA	$3006			MOVLW	6
$05FB	$00DB			MOVWF	FARG_Lcd_Config+2
$05FC	$3005			MOVLW	5
$05FD	$00DC			MOVWF	FARG_Lcd_Config+3
$05FE	$3004			MOVLW	4
$05FF	$00DD			MOVWF	FARG_Lcd_Config+4
$0600	$0855			MOVF	FARG_Lcd_Init, 0
$0601	$00DE			MOVWF	FARG_Lcd_Config+5
$0602	$3002			MOVLW	2
$0603	$00DF			MOVWF	FARG_Lcd_Config+6
$0604	$01E0			CLRF	FARG_Lcd_Config+7, 1
$0605	$3003			MOVLW	3
$0606	$00E1			MOVWF	FARG_Lcd_Config+8
$0607	$2004			CALL	_lcd_config
$0608	$	lcd_L_64:
;lcd.ppas,248 :: 		
$0608	$0008			RETURN
$04EE	$	_lcd_out:
;lcd.ppas,252 :: 		
;lcd.ppas,254 :: 		
$04EE	$	lcd_L_68:
$04EE	$1303			BCF	STATUS, RP1
$04EF	$1283			BCF	STATUS, RP0
$04F0	$0855			MOVF	FARG_Lcd_Out, 0
$04F1	$3A01			XORLW	1
$04F2	$1D03			BTFSS	STATUS, Z
$04F3	$2CF7			GOTO	lcd_L_69
$04F4	$	lcd_L_67:
$04F4	$3080			MOVLW	128
$04F5	$00D5			MOVWF	FARG_Lcd_Out
$04F6	$2D0E			GOTO	lcd_L_66
$04F7	$	lcd_L_69:
;lcd.ppas,255 :: 		
$04F7	$	lcd_L_71:
$04F7	$0855			MOVF	FARG_Lcd_Out, 0
$04F8	$3A02			XORLW	2
$04F9	$1D03			BTFSS	STATUS, Z
$04FA	$2CFE			GOTO	lcd_L_72
$04FB	$	lcd_L_70:
$04FB	$30C0			MOVLW	192
$04FC	$00D5			MOVWF	FARG_Lcd_Out
$04FD	$2D0E			GOTO	lcd_L_66
$04FE	$	lcd_L_72:
;lcd.ppas,256 :: 		
$04FE	$	lcd_L_74:
$04FE	$0855			MOVF	FARG_Lcd_Out, 0
$04FF	$3A03			XORLW	3
$0500	$1D03			BTFSS	STATUS, Z
$0501	$2D05			GOTO	lcd_L_75
$0502	$	lcd_L_73:
$0502	$3094			MOVLW	148
$0503	$00D5			MOVWF	FARG_Lcd_Out
$0504	$2D0E			GOTO	lcd_L_66
$0505	$	lcd_L_75:
;lcd.ppas,257 :: 		
$0505	$	lcd_L_77:
$0505	$0855			MOVF	FARG_Lcd_Out, 0
$0506	$3A04			XORLW	4
$0507	$1D03			BTFSS	STATUS, Z
$0508	$2D0C			GOTO	lcd_L_78
$0509	$	lcd_L_76:
$0509	$30D4			MOVLW	212
$050A	$00D5			MOVWF	FARG_Lcd_Out
;lcd.ppas,258 :: 		
$050B	$2D0E			GOTO	lcd_L_66
$050C	$	lcd_L_78:
$050C	$3080			MOVLW	128
$050D	$00D5			MOVWF	FARG_Lcd_Out
$050E	$	lcd_L_66:
;lcd.ppas,260 :: 		
$050E	$0356			DECF	FARG_Lcd_Out+1, 0
$050F	$00F0			MOVWF	STACK_0
$0510	$0855			MOVF	FARG_Lcd_Out, 0
$0511	$07F0			ADDWF	STACK_0, 1
$0512	$0870			MOVF	STACK_0, 0
$0513	$00D5			MOVWF	FARG_Lcd_Out
;lcd.ppas,261 :: 		
$0514	$0870			MOVF	STACK_0, 0
$0515	$00E2			MOVWF	FARG_Lcd_Cmd
$0516	$2251			CALL	_lcd_cmd
;lcd.ppas,262 :: 		
$0517	$01A9			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,263 :: 		
$0518	$01D8			CLRF	_lcd_out_local_i, 1
;lcd.ppas,264 :: 		
$0519	$	lcd_L_80:
$0519	$0858			MOVF	_lcd_out_local_i, 0
$051A	$0757			ADDWF	FARG_Lcd_Out+2, 0
$051B	$0084			MOVWF	FSR
$051C	$0800			MOVF	INDF, 0
$051D	$00F2			MOVWF	STACK_2
$051E	$0872			MOVF	STACK_2, 0
$051F	$3A00			XORLW	0
$0520	$1903			BTFSC	STATUS, Z
$0521	$2D2A			GOTO	lcd_L_81
;lcd.ppas,266 :: 		
$0522	$0858			MOVF	_lcd_out_local_i, 0
$0523	$0757			ADDWF	FARG_Lcd_Out+2, 0
$0524	$0084			MOVWF	FSR
$0525	$0800			MOVF	INDF, 0
$0526	$00D9			MOVWF	FARG_Lcd_Chr_CP
$0527	$2629			CALL	_lcd_chr_cp
;lcd.ppas,267 :: 		
$0528	$0AD8			INCF	_lcd_out_local_i, 1
;lcd.ppas,268 :: 		
$0529	$2D19			GOTO	lcd_L_80
$052A	$	lcd_L_81:
;lcd.ppas,269 :: 		
$052A	$3001			MOVLW	1
$052B	$00A9			MOVWF	lcd_lcdcmd_status
$052C	$	lcd_L_65:
;lcd.ppas,270 :: 		
$052C	$0008			RETURN
$0632	$	_delay_22us:
;delays.ppas,21 :: 		begin
;delays.ppas,22 :: 		Delay_us(22);
$0632	$300E			MOVLW	14
$0633	$1303			BCF	STATUS, RP1
$0634	$1283			BCF	STATUS, RP0
$0635	$00FA			MOVWF	STACK_10
$0636	$0BFA			DECFSZ	STACK_10, F
$0637	$2E36			GOTO	$-1
$0638	$0000			NOP
$0639	$	delays_L_3:
;delays.ppas,23 :: 		end;
$0639	$0008			RETURN
$05D7	$	_div_16x16_u:
$05D7	$1303			BCF	STATUS, RP1
$05D8	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$05D9	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$05DA	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$05DB	$3010			MOVLW	16
;math.ppas,113 :: 		
$05DC	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$05DD	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$05DE	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$05DF	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$05E0	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$05E1	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$05E2	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$05E3	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$05E4	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$05E5	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$05E6	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$05E7	$2DEF			GOTO	$+8
;math.ppas,125 :: 		
$05E8	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$05E9	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$05EA	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$05EB	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$05EC	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$05ED	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$05EE	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$05EF	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$05F0	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$05F1	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$05F2	$2DDD			GOTO	$-21
;math.ppas,136 :: 		
$05F3	$	math_L_3:
;math.ppas,137 :: 		
$05F3	$0008			RETURN
$0123	$	_sdiv3232l:
$0123	$1303			BCF	STATUS, RP1
$0124	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$0125	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0126	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0127	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0128	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$0129	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$012A	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$012B	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$012C	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$012D	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$012E	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$012F	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$0130	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$0131	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$0132	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$0133	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$0134	$3007			MOVLW	7
;math.ppas,559 :: 		
$0135	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0136	$	LOOPS3232A:
;math.ppas,561 :: 		
$0136	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0137	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0138	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$0139	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$013A	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$013B	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$013C	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$013D	$294C			GOTO	SADD22LA
;math.ppas,570 :: 		
$013E	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$013F	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$0140	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$0141	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$0142	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$0143	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$0144	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$0145	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0146	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0147	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0148	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$0149	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$014A	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$014B	$2959			GOTO	SOK22LA
;math.ppas,585 :: 		
$014C	$	SADD22LA:
;math.ppas,586 :: 		
$014C	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$014D	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$014E	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$014F	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$0150	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$0151	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$0152	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$0153	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$0154	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$0155	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$0156	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$0157	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$0158	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$0159	$	SOK22LA:
;math.ppas,602 :: 		
$0159	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$015A	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$015B	$2936			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$015C	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$015D	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$015E	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$015F	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$0160	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$0161	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$0162	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$0163	$2972			GOTO	SADD22L8
;math.ppas,615 :: 		
$0164	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$0165	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$0166	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$0167	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$0168	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$0169	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$016A	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$016B	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$016C	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$016D	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$016E	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$016F	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$0170	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$0171	$297F			GOTO	SOK22L8
;math.ppas,630 :: 		
$0172	$	SADD22L8:
;math.ppas,631 :: 		
$0172	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$0173	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$0174	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$0175	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$0176	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$0177	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$0178	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$0179	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$017A	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$017B	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$017C	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$017D	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$017E	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$017F	$	SOK22L8:
;math.ppas,647 :: 		
$017F	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$0180	$3007			MOVLW	7
;math.ppas,650 :: 		
$0181	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$0182	$	LOOPS3232B:
;math.ppas,652 :: 		
$0182	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$0183	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$0184	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$0185	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$0186	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$0187	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$0188	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$0189	$2998			GOTO	SADD22LB
;math.ppas,661 :: 		
$018A	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$018B	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$018C	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$018D	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$018E	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$018F	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$0190	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$0191	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$0192	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$0193	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$0194	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$0195	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$0196	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$0197	$29A5			GOTO	SOK22LB
;math.ppas,676 :: 		
$0198	$	SADD22LB:
;math.ppas,677 :: 		
$0198	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$0199	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$019A	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$019B	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$019C	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$019D	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$019E	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$019F	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$01A0	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$01A1	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$01A2	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$01A3	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$01A4	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$01A5	$	SOK22LB:
;math.ppas,693 :: 		
$01A5	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$01A6	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$01A7	$2982			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$01A8	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$01A9	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$01AA	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$01AB	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$01AC	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$01AD	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$01AE	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$01AF	$29BE			GOTO	SADD22L16
;math.ppas,706 :: 		
$01B0	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$01B1	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$01B2	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$01B3	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$01B4	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$01B5	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$01B6	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$01B7	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$01B8	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$01B9	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$01BA	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$01BB	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$01BC	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$01BD	$29CB			GOTO	SOK22L16
;math.ppas,721 :: 		
$01BE	$	SADD22L16:
;math.ppas,722 :: 		
$01BE	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$01BF	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$01C0	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$01C1	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$01C2	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$01C3	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$01C4	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$01C5	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$01C6	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$01C7	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$01C8	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$01C9	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$01CA	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$01CB	$	SOK22L16:
;math.ppas,738 :: 		
$01CB	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$01CC	$3007			MOVLW	7
;math.ppas,741 :: 		
$01CD	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$01CE	$	LOOPS3232C:
;math.ppas,743 :: 		
$01CE	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$01CF	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$01D0	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$01D1	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$01D2	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$01D3	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$01D4	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$01D5	$29E4			GOTO	SADD22LC
;math.ppas,752 :: 		
$01D6	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$01D7	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$01D8	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$01D9	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$01DA	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$01DB	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$01DC	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$01DD	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$01DE	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$01DF	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$01E0	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$01E1	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$01E2	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$01E3	$29F1			GOTO	SOK22LC
;math.ppas,767 :: 		
$01E4	$	SADD22LC:
;math.ppas,768 :: 		
$01E4	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$01E5	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$01E6	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$01E7	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$01E8	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$01E9	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$01EA	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$01EB	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$01EC	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$01ED	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$01EE	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$01EF	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$01F0	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$01F1	$	SOK22LC:
;math.ppas,784 :: 		
$01F1	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$01F2	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$01F3	$29CE			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$01F4	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$01F5	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$01F6	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$01F7	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$01F8	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$01F9	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$01FA	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$01FB	$2A0A			GOTO	SADD22L24
;math.ppas,797 :: 		
$01FC	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$01FD	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$01FE	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$01FF	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$0200	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$0201	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$0202	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$0203	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$0204	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$0205	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$0206	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$0207	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$0208	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$0209	$2A17			GOTO	SOK22L24
;math.ppas,812 :: 		
$020A	$	SADD22L24:
;math.ppas,813 :: 		
$020A	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$020B	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$020C	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$020D	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$020E	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$020F	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$0210	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$0211	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$0212	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$0213	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$0214	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$0215	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$0216	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$0217	$	SOK22L24:
;math.ppas,829 :: 		
$0217	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$0218	$3007			MOVLW	7
;math.ppas,832 :: 		
$0219	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$021A	$	LOOPS3232D:
;math.ppas,834 :: 		
$021A	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$021B	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$021C	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$021D	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$021E	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$021F	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$0220	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$0221	$2A30			GOTO	SADD22LD
;math.ppas,843 :: 		
$0222	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$0223	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$0224	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$0225	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0226	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0227	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0228	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$0229	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$022A	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$022B	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$022C	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$022D	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$022E	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$022F	$2A3D			GOTO	SOK22LD
;math.ppas,858 :: 		
$0230	$	SADD22LD:
;math.ppas,859 :: 		
$0230	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$0231	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$0232	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$0233	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$0234	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$0235	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0236	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0237	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0238	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$0239	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$023A	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$023B	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$023C	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$023D	$	SOK22LD:
;math.ppas,876 :: 		
$023D	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$023E	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$023F	$2A1A			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$0240	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$0241	$2A50			GOTO	SOK22L
;math.ppas,882 :: 		
$0242	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$0243	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$0244	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$0245	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0246	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0247	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0248	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$0249	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$024A	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$024B	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$024C	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$024D	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$024E	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$024F	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$0250	$	SOK22L:
;math.ppas,897 :: 		
$0250	$	math_L_9:
;math.ppas,898 :: 		
$0250	$0008			RETURN
$061B	$	_comfrem:
$061B	$1303			BCF	STATUS, RP1
$061C	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$061D	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$061E	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$061F	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$0620	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$0621	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$0622	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$0623	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$0624	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$0625	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$0626	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$0627	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$0628	$	math_L_10:
;math.ppas,915 :: 		
$0628	$0008			RETURN
$0413	$	_init:
;Temperature.ppas,5 :: 		begin
;Temperature.ppas,6 :: 		TRISA:=$ff;
$0413	$30FF			MOVLW	255
$0414	$1303			BCF	STATUS, RP1
$0415	$1683			BSF	STATUS, RP0
$0416	$0085			MOVWF	TRISA
;Temperature.ppas,7 :: 		TRISC:=$00;
$0417	$0187			CLRF	TRISC, 1
;Temperature.ppas,8 :: 		ADCON1:=$0E;
$0418	$300E			MOVLW	14
$0419	$009F			MOVWF	ADCON1
;Temperature.ppas,9 :: 		Lcd_Init(PORTC);
$041A	$3007			MOVLW	PORTC
$041B	$1283			BCF	STATUS, RP0
$041C	$00D5			MOVWF	FARG_Lcd_Init
$041D	$25F4			CALL	_lcd_init
;Temperature.ppas,10 :: 		Lcd_Cmd(LCD_clear);
$041E	$3001			MOVLW	1
$041F	$00E2			MOVWF	FARG_Lcd_Cmd
$0420	$2251			CALL	_lcd_cmd
;Temperature.ppas,11 :: 		Lcd_Cmd(LCD_CURSOR_OFF);
$0421	$300C			MOVLW	12
$0422	$00E2			MOVWF	FARG_Lcd_Cmd
$0423	$2251			CALL	_lcd_cmd
;Temperature.ppas,12 :: 		Lcd_Out(1,3,'Projet Atelier');
$0424	$3001			MOVLW	1
$0425	$00D5			MOVWF	FARG_Lcd_Out
$0426	$3003			MOVLW	3
$0427	$00D6			MOVWF	FARG_Lcd_Out+1
$0428	$3050			MOVLW	80
$0429	$00C4			MOVWF	?init_Local_Text+0
$042A	$3072			MOVLW	114
$042B	$00C5			MOVWF	?init_Local_Text+1
$042C	$306F			MOVLW	111
$042D	$00C6			MOVWF	?init_Local_Text+2
$042E	$306A			MOVLW	106
$042F	$00C7			MOVWF	?init_Local_Text+3
$0430	$3065			MOVLW	101
$0431	$00C8			MOVWF	?init_Local_Text+4
$0432	$3074			MOVLW	116
$0433	$00C9			MOVWF	?init_Local_Text+5
$0434	$3020			MOVLW	32
$0435	$00CA			MOVWF	?init_Local_Text+6
$0436	$3041			MOVLW	65
$0437	$00CB			MOVWF	?init_Local_Text+7
$0438	$3074			MOVLW	116
$0439	$00CC			MOVWF	?init_Local_Text+8
$043A	$3065			MOVLW	101
$043B	$00CD			MOVWF	?init_Local_Text+9
$043C	$306C			MOVLW	108
$043D	$00CE			MOVWF	?init_Local_Text+10
$043E	$3069			MOVLW	105
$043F	$00CF			MOVWF	?init_Local_Text+11
$0440	$3065			MOVLW	101
$0441	$00D0			MOVWF	?init_Local_Text+12
$0442	$3072			MOVLW	114
$0443	$00D1			MOVWF	?init_Local_Text+13
$0444	$01D2			CLRF	?init_Local_Text+14
$0445	$3044			MOVLW	?init_Local_Text
$0446	$00D7			MOVWF	FARG_Lcd_Out+2
$0447	$24EE			CALL	_lcd_out
;Temperature.ppas,13 :: 		Lcd_Out(2,4,'Micro-Controleur');
$0448	$3002			MOVLW	2
$0449	$00D5			MOVWF	FARG_Lcd_Out
$044A	$3004			MOVLW	4
$044B	$00D6			MOVWF	FARG_Lcd_Out+1
$044C	$304D			MOVLW	77
$044D	$00C4			MOVWF	?init_Local_Text+0
$044E	$3069			MOVLW	105
$044F	$00C5			MOVWF	?init_Local_Text+1
$0450	$3063			MOVLW	99
$0451	$00C6			MOVWF	?init_Local_Text+2
$0452	$3072			MOVLW	114
$0453	$00C7			MOVWF	?init_Local_Text+3
$0454	$306F			MOVLW	111
$0455	$00C8			MOVWF	?init_Local_Text+4
$0456	$302D			MOVLW	45
$0457	$00C9			MOVWF	?init_Local_Text+5
$0458	$3043			MOVLW	67
$0459	$00CA			MOVWF	?init_Local_Text+6
$045A	$306F			MOVLW	111
$045B	$00CB			MOVWF	?init_Local_Text+7
$045C	$306E			MOVLW	110
$045D	$00CC			MOVWF	?init_Local_Text+8
$045E	$3074			MOVLW	116
$045F	$00CD			MOVWF	?init_Local_Text+9
$0460	$3072			MOVLW	114
$0461	$00CE			MOVWF	?init_Local_Text+10
$0462	$306F			MOVLW	111
$0463	$00CF			MOVWF	?init_Local_Text+11
$0464	$306C			MOVLW	108
$0465	$00D0			MOVWF	?init_Local_Text+12
$0466	$3065			MOVLW	101
$0467	$00D1			MOVWF	?init_Local_Text+13
$0468	$3075			MOVLW	117
$0469	$00D2			MOVWF	?init_Local_Text+14
$046A	$3072			MOVLW	114
$046B	$00D3			MOVWF	?init_Local_Text+15
$046C	$01D4			CLRF	?init_Local_Text+16
$046D	$3044			MOVLW	?init_Local_Text
$046E	$00D7			MOVWF	FARG_Lcd_Out+2
$046F	$24EE			CALL	_lcd_out
;Temperature.ppas,14 :: 		delay_ms(2000);
$0470	$3015			MOVLW	21
$0471	$00FC			MOVWF	STACK_12
$0472	$30FF			MOVLW	255
$0473	$00FB			MOVWF	STACK_11
$0474	$30FF			MOVLW	255
$0475	$00FA			MOVWF	STACK_10
$0476	$0BFC			DECFSZ	STACK_12, F
$0477	$2C79			GOTO	$+2
$0478	$2C80			GOTO	$+8
$0479	$0BFB			DECFSZ	STACK_11, F
$047A	$2C7C			GOTO	$+2
$047B	$2C7F			GOTO	$+4
$047C	$0BFA			DECFSZ	STACK_10, F
$047D	$2C7C			GOTO	$-1
$047E	$2C79			GOTO	$-5
$047F	$2C76			GOTO	$-9
$0480	$3066			MOVLW	102
$0481	$00FB			MOVWF	STACK_11
$0482	$30FF			MOVLW	255
$0483	$00FA			MOVWF	STACK_10
$0484	$0BFB			DECFSZ	STACK_11, F
$0485	$2C87			GOTO	$+2
$0486	$2C8A			GOTO	$+4
$0487	$0BFA			DECFSZ	STACK_10, F
$0488	$2C87			GOTO	$-1
$0489	$2C84			GOTO	$-5
$048A	$3012			MOVLW	18
$048B	$00FA			MOVWF	STACK_10
$048C	$0BFA			DECFSZ	STACK_10, F
$048D	$2C8C			GOTO	$-1
$048E	$0000			NOP
$048F	$0000			NOP
;Temperature.ppas,15 :: 		Lcd_Cmd(LCD_clear);
$0490	$3001			MOVLW	1
$0491	$00E2			MOVWF	FARG_Lcd_Cmd
$0492	$2251			CALL	_lcd_cmd
$0493	$	Temperature_L_0:
;Temperature.ppas,16 :: 		end;
$0493	$0008			RETURN
$052D	$	_adc_read:
;ADClib_A_C.ppas,12 :: 		
;ADClib_A_C.ppas,13 :: 		
$052D	$1303			BCF	STATUS, RP1
$052E	$1283			BCF	STATUS, RP0
$052F	$019F			CLRF	ADCON0, 1
;ADClib_A_C.ppas,14 :: 		
$0530	$30C0			MOVLW	192
$0531	$049F			IORWF	ADCON0, 1
;ADClib_A_C.ppas,15 :: 		
$0532	$3040			MOVLW	64
$0533	$1683			BSF	STATUS, RP0
$0534	$041F			IORWF	ADCON1, 0
$0535	$00F0			MOVWF	STACK_0
$0536	$0870			MOVF	STACK_0, 0
$0537	$009F			MOVWF	ADCON1
;ADClib_A_C.ppas,17 :: 		
$0538	$3080			MOVLW	128
$0539	$0470			IORWF	STACK_0, 0
$053A	$009F			MOVWF	ADCON1
;ADClib_A_C.ppas,18 :: 		
$053B	$1283			BCF	STATUS, RP0
$053C	$0844			MOVF	FARG_ADC_read, 0
$053D	$00F0			MOVWF	STACK_0
$053E	$0DF0			RLF	STACK_0, 1
$053F	$1070			BCF	STACK_0, 0
$0540	$0DF0			RLF	STACK_0, 1
$0541	$1070			BCF	STACK_0, 0
$0542	$0DF0			RLF	STACK_0, 1
$0543	$1070			BCF	STACK_0, 0
$0544	$0870			MOVF	STACK_0, 0
$0545	$049F			IORWF	ADCON0, 1
;ADClib_A_C.ppas,19 :: 		
$0546	$141F			BSF	ADCON0, 0
;ADClib_A_C.ppas,20 :: 		
$0547	$2632			CALL	_delay_22us
;ADClib_A_C.ppas,21 :: 		
$0548	$151F			BSF	ADCON0, 2
;ADClib_A_C.ppas,22 :: 		
$0549	$	ADClib_A_C_L_2:
$0549	$081F			MOVF	ADCON0, 0
$054A	$00F2			MOVWF	STACK_2
$054B	$3000			MOVLW	0
$054C	$1972			BTFSC	STACK_2, 2
$054D	$3001			MOVLW	1
$054E	$00F2			MOVWF	STACK_2
$054F	$0872			MOVF	STACK_2, 0
$0550	$3A01			XORLW	1
$0551	$1D03			BTFSS	STATUS, Z
$0552	$2D55			GOTO	ADClib_A_C_L_3
;ADClib_A_C.ppas,23 :: 		
$0553	$0000			NOP
$0554	$2D49			GOTO	ADClib_A_C_L_2
$0555	$	ADClib_A_C_L_3:
;ADClib_A_C.ppas,24 :: 		
$0555	$081E			MOVF	ADRESH, 0
$0556	$00F2			MOVWF	STACK_2
$0557	$01F3			CLRF	STACK_2+1
$0558	$0872			MOVF	STACK_2, 0
$0559	$00F3			MOVWF	STACK_2+1
$055A	$01F2			CLRF	STACK_2
$055B	$0872			MOVF	STACK_2, 0
$055C	$00C5			MOVWF	_adc_read_local_result
$055D	$0873			MOVF	STACK_2+1, 0
$055E	$00C6			MOVWF	_adc_read_local_result+1
;ADClib_A_C.ppas,25 :: 		
$055F	$1683			BSF	STATUS, RP0
$0560	$081E			MOVF	ADRESL, 0
$0561	$0472			IORWF	STACK_2, 0
$0562	$1283			BCF	STATUS, RP0
$0563	$00C5			MOVWF	_adc_read_local_result
$0564	$0873			MOVF	STACK_2+1, 0
$0565	$00C6			MOVWF	_adc_read_local_result+1
$0566	$3000			MOVLW	0
$0567	$04C6			IORWF	_adc_read_local_result+1, 1
;ADClib_A_C.ppas,26 :: 		
$0568	$101F			BCF	ADCON0, 0
$0569	$	ADClib_A_C_L_0:
;ADClib_A_C.ppas,27 :: 		
$0569	$0845			MOVF	_adc_read_local_result, 0
$056A	$00F0			MOVWF	STACK_0
$056B	$0846			MOVF	_adc_read_local_result+1, 0
$056C	$00F1			MOVWF	STACK_0+1
$056D	$0008			RETURN
$0494	$	_wordtostr:
;conv.ppas,31 :: 		
;conv.ppas,32 :: 		
$0494	$3001			MOVLW	1
$0495	$1303			BCF	STATUS, RP1
$0496	$1283			BCF	STATUS, RP0
$0497	$00C7			MOVWF	_wordtostr_local_len
;conv.ppas,33 :: 		
$0498	$0845			MOVF	FARG_WordToStr+1, 0
$0499	$3C00			SUBLW	0
$049A	$1D03			BTFSS	STATUS, Z
$049B	$2C9E			GOTO	L_WordToStr_0
$049C	$0844			MOVF	FARG_WordToStr, 0
$049D	$3C09			SUBLW	9
$049E	$	L_WordToStr_0:
$049E	$1803			BTFSC	STATUS, C
$049F	$2CA1			GOTO	conv_L_15
$04A0	$	conv_L_14:
;conv.ppas,34 :: 		
$04A0	$0AC7			INCF	_wordtostr_local_len, 1
$04A1	$	conv_L_15:
$04A1	$	conv_L_16:
;conv.ppas,35 :: 		
$04A1	$0845			MOVF	FARG_WordToStr+1, 0
$04A2	$3C00			SUBLW	0
$04A3	$1D03			BTFSS	STATUS, Z
$04A4	$2CA7			GOTO	L_WordToStr_1
$04A5	$0844			MOVF	FARG_WordToStr, 0
$04A6	$3C63			SUBLW	99
$04A7	$	L_WordToStr_1:
$04A7	$1803			BTFSC	STATUS, C
$04A8	$2CAA			GOTO	conv_L_18
$04A9	$	conv_L_17:
;conv.ppas,36 :: 		
$04A9	$0AC7			INCF	_wordtostr_local_len, 1
$04AA	$	conv_L_18:
$04AA	$	conv_L_19:
;conv.ppas,37 :: 		
$04AA	$0845			MOVF	FARG_WordToStr+1, 0
$04AB	$3C03			SUBLW	3
$04AC	$1D03			BTFSS	STATUS, Z
$04AD	$2CB0			GOTO	L_WordToStr_2
$04AE	$0844			MOVF	FARG_WordToStr, 0
$04AF	$3CE7			SUBLW	231
$04B0	$	L_WordToStr_2:
$04B0	$1803			BTFSC	STATUS, C
$04B1	$2CB3			GOTO	conv_L_21
$04B2	$	conv_L_20:
;conv.ppas,38 :: 		
$04B2	$0AC7			INCF	_wordtostr_local_len, 1
$04B3	$	conv_L_21:
$04B3	$	conv_L_22:
;conv.ppas,39 :: 		
$04B3	$0845			MOVF	FARG_WordToStr+1, 0
$04B4	$3C27			SUBLW	39
$04B5	$1D03			BTFSS	STATUS, Z
$04B6	$2CB9			GOTO	L_WordToStr_3
$04B7	$0844			MOVF	FARG_WordToStr, 0
$04B8	$3C0F			SUBLW	15
$04B9	$	L_WordToStr_3:
$04B9	$1803			BTFSC	STATUS, C
$04BA	$2CBC			GOTO	conv_L_24
$04BB	$	conv_L_23:
;conv.ppas,40 :: 		
$04BB	$0AC7			INCF	_wordtostr_local_len, 1
$04BC	$	conv_L_24:
$04BC	$	conv_L_25:
;conv.ppas,41 :: 		
$04BC	$0846			MOVF	FARG_WordToStr+2, 0
$04BD	$0084			MOVWF	FSR
$04BE	$3020			MOVLW	32
$04BF	$0080			MOVWF	INDF
$04C0	$0A84			INCF	FSR, 1
$04C1	$0080			MOVWF	INDF
$04C2	$0A84			INCF	FSR, 1
$04C3	$0080			MOVWF	INDF
$04C4	$0A84			INCF	FSR, 1
$04C5	$0080			MOVWF	INDF
$04C6	$0A84			INCF	FSR, 1
$04C7	$0080			MOVWF	INDF
$04C8	$0A84			INCF	FSR, 1
$04C9	$0180			CLRF	INDF
;conv.ppas,42 :: 		
$04CA	$0384			DECF	FSR, 1
;conv.ppas,43 :: 		
$04CB	$	conv_L_28:
$04CB	$0847			MOVF	_wordtostr_local_len, 0
$04CC	$3C00			SUBLW	0
$04CD	$1803			BTFSC	STATUS, C
$04CE	$2CED			GOTO	conv_L_29
;conv.ppas,45 :: 		
$04CF	$300A			MOVLW	10
$04D0	$00F4			MOVWF	STACK_4
$04D1	$01F5			CLRF	STACK_4+1
$04D2	$0844			MOVF	FARG_WordToStr, 0
$04D3	$00F0			MOVWF	STACK_0
$04D4	$0845			MOVF	FARG_WordToStr+1, 0
$04D5	$00F1			MOVWF	STACK_0+1
$04D6	$25D7			CALL	_div_16x16_u
$04D7	$0878			MOVF	STACK_8, 0
$04D8	$00F0			MOVWF	STACK_0
$04D9	$0879			MOVF	STACK_9, 0
$04DA	$00F1			MOVWF	STACK_1
$04DB	$3030			MOVLW	48
$04DC	$0770			ADDWF	STACK_0, 0
$04DD	$0080			MOVWF	INDF
;conv.ppas,46 :: 		
;conv.ppas,47 :: 		
$04DE	$0384			DECF	FSR, 1
;conv.ppas,48 :: 		
$04DF	$300A			MOVLW	10
$04E0	$00F4			MOVWF	STACK_4
$04E1	$01F5			CLRF	STACK_4+1
$04E2	$0844			MOVF	FARG_WordToStr, 0
$04E3	$00F0			MOVWF	STACK_0
$04E4	$0845			MOVF	FARG_WordToStr+1, 0
$04E5	$00F1			MOVWF	STACK_0+1
$04E6	$25D7			CALL	_div_16x16_u
$04E7	$0870			MOVF	STACK_0, 0
$04E8	$00C4			MOVWF	FARG_WordToStr
$04E9	$0871			MOVF	STACK_0+1, 0
$04EA	$00C5			MOVWF	FARG_WordToStr+1
;conv.ppas,49 :: 		
$04EB	$03C7			DECF	_wordtostr_local_len, 1
;conv.ppas,50 :: 		
$04EC	$2CCB			GOTO	conv_L_28
$04ED	$	conv_L_29:
$04ED	$	conv_L_13:
;conv.ppas,51 :: 		
$04ED	$0008			RETURN
$056E	$	_lcd_chr:
;lcd.ppas,78 :: 		
;lcd.ppas,80 :: 		
$056E	$	lcd_L_37:
$056E	$1303			BCF	STATUS, RP1
$056F	$1283			BCF	STATUS, RP0
$0570	$0844			MOVF	FARG_Lcd_Chr, 0
$0571	$3A01			XORLW	1
$0572	$1D03			BTFSS	STATUS, Z
$0573	$2D77			GOTO	lcd_L_38
$0574	$	lcd_L_36:
$0574	$3080			MOVLW	128
$0575	$00C4			MOVWF	FARG_Lcd_Chr
$0576	$2D8E			GOTO	lcd_L_35
$0577	$	lcd_L_38:
;lcd.ppas,81 :: 		
$0577	$	lcd_L_40:
$0577	$0844			MOVF	FARG_Lcd_Chr, 0
$0578	$3A02			XORLW	2
$0579	$1D03			BTFSS	STATUS, Z
$057A	$2D7E			GOTO	lcd_L_41
$057B	$	lcd_L_39:
$057B	$30C0			MOVLW	192
$057C	$00C4			MOVWF	FARG_Lcd_Chr
$057D	$2D8E			GOTO	lcd_L_35
$057E	$	lcd_L_41:
;lcd.ppas,82 :: 		
$057E	$	lcd_L_43:
$057E	$0844			MOVF	FARG_Lcd_Chr, 0
$057F	$3A03			XORLW	3
$0580	$1D03			BTFSS	STATUS, Z
$0581	$2D85			GOTO	lcd_L_44
$0582	$	lcd_L_42:
$0582	$3094			MOVLW	148
$0583	$00C4			MOVWF	FARG_Lcd_Chr
$0584	$2D8E			GOTO	lcd_L_35
$0585	$	lcd_L_44:
;lcd.ppas,83 :: 		
$0585	$	lcd_L_46:
$0585	$0844			MOVF	FARG_Lcd_Chr, 0
$0586	$3A04			XORLW	4
$0587	$1D03			BTFSS	STATUS, Z
$0588	$2D8C			GOTO	lcd_L_47
$0589	$	lcd_L_45:
$0589	$30D4			MOVLW	212
$058A	$00C4			MOVWF	FARG_Lcd_Chr
;lcd.ppas,84 :: 		
$058B	$2D8E			GOTO	lcd_L_35
$058C	$	lcd_L_47:
$058C	$3080			MOVLW	128
$058D	$00C4			MOVWF	FARG_Lcd_Chr
$058E	$	lcd_L_35:
;lcd.ppas,86 :: 		
$058E	$0845			MOVF	FARG_Lcd_Chr+1, 0
$058F	$0744			ADDWF	FARG_Lcd_Chr, 0
$0590	$00F0			MOVWF	STACK_0
$0591	$03F0			DECF	STACK_0, 1
$0592	$0870			MOVF	STACK_0, 0
$0593	$00C4			MOVWF	FARG_Lcd_Chr
;lcd.ppas,88 :: 		
$0594	$3001			MOVLW	1
$0595	$00A9			MOVWF	lcd_lcdcmd_status
;lcd.ppas,89 :: 		
$0596	$0870			MOVF	STACK_0, 0
$0597	$00E2			MOVWF	FARG_Lcd_Cmd
$0598	$2251			CALL	_lcd_cmd
;lcd.ppas,91 :: 		
$0599	$01A9			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,92 :: 		
$059A	$0846			MOVF	FARG_Lcd_Chr+2, 0
$059B	$00E2			MOVWF	FARG_Lcd_Cmd
$059C	$2251			CALL	_lcd_cmd
;lcd.ppas,93 :: 		
$059D	$3001			MOVLW	1
$059E	$00A9			MOVWF	lcd_lcdcmd_status
$059F	$	lcd_L_34:
;lcd.ppas,94 :: 		
$059F	$0008			RETURN
$05A0	$	_mul_32x32_u:
$05A0	$1303			BCF	STATUS, RP1
$05A1	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$05A2	$3022			MOVLW	34
;math.ppas,1579 :: 		
$05A3	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$05A4	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$05A5	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$05A6	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$05A7	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$05A8	$	_NEXT:
;math.ppas,1589 :: 		
$05A8	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$05A9	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$05AA	$2DD6			GOTO	_EXIT2
;math.ppas,1593 :: 		
$05AB	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$05AC	$	_LOOP:
;math.ppas,1603 :: 		
$05AC	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$05AD	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$05AE	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$05AF	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$05B0	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$05B1	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$05B2	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$05B3	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$05B4	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$05B5	$2DA8			GOTO	_NEXT
;math.ppas,1617 :: 		
$05B6	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$05B7	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$05B8	$2DC8			GOTO	_EXIT1
;math.ppas,1626 :: 		
$05B9	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$05BA	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$05BB	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$05BC	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$05BD	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$05BE	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$05BF	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$05C0	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$05C1	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$05C2	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$05C3	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$05C4	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$05C5	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$05C6	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$05C7	$2DAC			GOTO	_LOOP
;math.ppas,1647 :: 		
$05C8	$	_EXIT1:
;math.ppas,1648 :: 		
$05C8	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$05C9	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$05CA	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$05CB	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$05CC	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$05CD	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$05CE	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$05CF	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$05D0	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$05D1	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$05D2	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$05D3	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$05D4	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$05D5	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$05D6	$	_EXIT2:
;math.ppas,1665 :: 		
$05D6	$	math_L_13:
;math.ppas,1666 :: 		
$05D6	$0008			RETURN
$0379	$	_div_32x32_s:
$0379	$1303			BCF	STATUS, RP1
$037A	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$037B	$	FXD3232S:
;math.ppas,929 :: 		
$037B	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$037C	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$037D	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$037E	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$037F	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$0380	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$0381	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$0382	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$0383	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$0384	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$0385	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$0386	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0387	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$0388	$2C0D			GOTO	END_ALL
;math.ppas,944 :: 		
$0389	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$038A	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$038B	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$038C	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$038D	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$038E	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$038F	$2B9B			GOTO	CA3232S
;math.ppas,955 :: 		
$0390	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$0391	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$0392	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$0393	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$0394	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$0395	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$0396	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0397	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$0398	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$0399	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$039A	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$039B	$	CA3232S:
;math.ppas,968 :: 		
$039B	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$039C	$2BA8			GOTO	C3232SX
;math.ppas,971 :: 		
$039D	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$039E	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$039F	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$03A0	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$03A1	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$03A2	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$03A3	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$03A4	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$03A5	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$03A6	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$03A7	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$03A8	$	C3232SX:
;math.ppas,984 :: 		
$03A8	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$03A9	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$03AA	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$03AB	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$03AC	$2BC9			GOTO	C3232SX1
;math.ppas,989 :: 		
$03AD	$	C3232S:
;math.ppas,992 :: 		
$03AD	$2123			CALL	_sdiv3232l
;math.ppas,995 :: 		
$03AE	$	C3232S2:
;math.ppas,996 :: 		
$03AE	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$03AF	$2BE6			GOTO	C3232SX4
;math.ppas,998 :: 		
$03B0	$	C3232SOK:
;math.ppas,999 :: 		
$03B0	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$03B1	$2C0D			GOTO	END_ALL
;math.ppas,1001 :: 		
$03B2	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$03B3	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$03B4	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$03B5	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$03B6	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$03B7	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$03B8	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$03B9	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$03BA	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$03BB	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$03BC	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$03BD	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$03BE	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$03BF	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$03C0	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$03C1	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$03C2	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$03C3	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$03C4	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$03C5	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$03C6	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$03C7	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$03C8	$2C0D			GOTO	END_ALL
;math.ppas,1026 :: 		
$03C9	$	C3232SX1:
;math.ppas,1027 :: 		
$03C9	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$03CA	$2BE0			GOTO	C3232SX3
;math.ppas,1029 :: 		
$03CB	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$03CC	$2BDA			GOTO	C3232SX2
;math.ppas,1031 :: 		
$03CD	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$03CE	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$03CF	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$03D0	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$03D1	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$03D2	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$03D3	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$03D4	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$03D5	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$03D6	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$03D7	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$03D8	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$03D9	$2BB0			GOTO	C3232SOK
;math.ppas,1044 :: 		
$03DA	$	C3232SX2:
;math.ppas,1045 :: 		
$03DA	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$03DB	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$03DC	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$03DD	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$03DE	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$03DF	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$03E0	$	C3232SX3:
;math.ppas,1053 :: 		
$03E0	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$03E1	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$03E2	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$03E3	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$03E4	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$03E5	$2BAD			GOTO	C3232S
;math.ppas,1061 :: 		
$03E6	$	C3232SX4:
;math.ppas,1062 :: 		
$03E6	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$03E7	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$03E8	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$03E9	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$03EA	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$03EB	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$03EC	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$03ED	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$03EE	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$03EF	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$03F0	$2BB0			GOTO	C3232SOK
;math.ppas,1073 :: 		
$03F1	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$03F2	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$03F3	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$03F4	$2BB0			GOTO	C3232SOK
;math.ppas,1077 :: 		
$03F5	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$03F6	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$03F7	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$03F8	$2BB0			GOTO	C3232SOK
;math.ppas,1081 :: 		
$03F9	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$03FA	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$03FB	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$03FC	$2BB0			GOTO	C3232SOK
;math.ppas,1085 :: 		
$03FD	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$03FE	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$03FF	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$0400	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$0401	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$0402	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$0403	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$0404	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$0405	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$0406	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0407	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$0408	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$0409	$2BB0			GOTO	C3232SOK
;math.ppas,1098 :: 		
$040A	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$040B	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$040C	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$040D	$	END_ALL:
;math.ppas,1102 :: 		
$040D	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$040E	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$040F	$2C11			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$0410	$261B			CALL	_comfrem
;math.ppas,1108 :: 		
$0411	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$0411	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$0412	$	math_L_11:
;math.ppas,1111 :: 		
$0412	$0008			RETURN
$02F8	$	_main:
;Temperature.ppas,17 :: 		begin
;Temperature.ppas,18 :: 		init();
$02F8	$2413			CALL	_init
;Temperature.ppas,19 :: 		Lcd_Out(1,1,'Mesure  :');
$02F9	$3001			MOVLW	1
$02FA	$00D5			MOVWF	FARG_Lcd_Out
$02FB	$3001			MOVLW	1
$02FC	$00D6			MOVWF	FARG_Lcd_Out+1
$02FD	$304D			MOVLW	77
$02FE	$00B7			MOVWF	?main_Local_Text+0
$02FF	$3065			MOVLW	101
$0300	$00B8			MOVWF	?main_Local_Text+1
$0301	$3073			MOVLW	115
$0302	$00B9			MOVWF	?main_Local_Text+2
$0303	$3075			MOVLW	117
$0304	$00BA			MOVWF	?main_Local_Text+3
$0305	$3072			MOVLW	114
$0306	$00BB			MOVWF	?main_Local_Text+4
$0307	$3065			MOVLW	101
$0308	$00BC			MOVWF	?main_Local_Text+5
$0309	$3020			MOVLW	32
$030A	$00BD			MOVWF	?main_Local_Text+6
$030B	$3020			MOVLW	32
$030C	$00BE			MOVWF	?main_Local_Text+7
$030D	$303A			MOVLW	58
$030E	$00BF			MOVWF	?main_Local_Text+8
$030F	$01C0			CLRF	?main_Local_Text+9
$0310	$3037			MOVLW	?main_Local_Text
$0311	$00D7			MOVWF	FARG_Lcd_Out+2
$0312	$24EE			CALL	_lcd_out
;Temperature.ppas,20 :: 		Lcd_Out(2,1,'Temperature:');
$0313	$3002			MOVLW	2
$0314	$00D5			MOVWF	FARG_Lcd_Out
$0315	$3001			MOVLW	1
$0316	$00D6			MOVWF	FARG_Lcd_Out+1
$0317	$3054			MOVLW	84
$0318	$00B7			MOVWF	?main_Local_Text+0
$0319	$3065			MOVLW	101
$031A	$00B8			MOVWF	?main_Local_Text+1
$031B	$306D			MOVLW	109
$031C	$00B9			MOVWF	?main_Local_Text+2
$031D	$3070			MOVLW	112
$031E	$00BA			MOVWF	?main_Local_Text+3
$031F	$3065			MOVLW	101
$0320	$00BB			MOVWF	?main_Local_Text+4
$0321	$3072			MOVLW	114
$0322	$00BC			MOVWF	?main_Local_Text+5
$0323	$3061			MOVLW	97
$0324	$00BD			MOVWF	?main_Local_Text+6
$0325	$3074			MOVLW	116
$0326	$00BE			MOVWF	?main_Local_Text+7
$0327	$3075			MOVLW	117
$0328	$00BF			MOVWF	?main_Local_Text+8
$0329	$3072			MOVLW	114
$032A	$00C0			MOVWF	?main_Local_Text+9
$032B	$3065			MOVLW	101
$032C	$00C1			MOVWF	?main_Local_Text+10
$032D	$303A			MOVLW	58
$032E	$00C2			MOVWF	?main_Local_Text+11
$032F	$01C3			CLRF	?main_Local_Text+12
$0330	$3037			MOVLW	?main_Local_Text
$0331	$00D7			MOVWF	FARG_Lcd_Out+2
$0332	$24EE			CALL	_lcd_out
;Temperature.ppas,21 :: 		while(1) do
$0333	$	Temperature_L_3:
;Temperature.ppas,23 :: 		res:=Adc_Read(0);
$0333	$01C4			CLRF	FARG_ADC_read, 1
$0334	$252D			CALL	_adc_read
$0335	$0870			MOVF	STACK_0, 0
$0336	$00AB			MOVWF	_res
$0337	$0871			MOVF	STACK_0+1, 0
$0338	$00AC			MOVWF	_res+1
;Temperature.ppas,24 :: 		WordtoStr(res,txt);
$0339	$0870			MOVF	STACK_0, 0
$033A	$00C4			MOVWF	FARG_WordToStr
$033B	$0871			MOVF	STACK_0+1, 0
$033C	$00C5			MOVWF	FARG_WordToStr+1
$033D	$302D			MOVLW	_txt
$033E	$00C6			MOVWF	FARG_WordToStr+2
$033F	$2494			CALL	_wordtostr
;Temperature.ppas,25 :: 		Lcd_Out(1,10,txt);
$0340	$3001			MOVLW	1
$0341	$00D5			MOVWF	FARG_Lcd_Out
$0342	$300A			MOVLW	10
$0343	$00D6			MOVWF	FARG_Lcd_Out+1
$0344	$302D			MOVLW	_txt
$0345	$00D7			MOVWF	FARG_Lcd_Out+2
$0346	$24EE			CALL	_lcd_out
;Temperature.ppas,26 :: 		temp:=(res*150)/1023;
$0347	$082B			MOVF	_res, 0
$0348	$00F0			MOVWF	STACK_0
$0349	$082C			MOVF	_res+1, 0
$034A	$00F1			MOVWF	STACK_0+1
$034B	$01F2			CLRF	STACK_0+2
$034C	$01F3			CLRF	STACK_0+3
$034D	$3096			MOVLW	150
$034E	$00F4			MOVWF	STACK_4
$034F	$01F5			CLRF	STACK_4+1
$0350	$01F6			CLRF	STACK_4+2
$0351	$01F7			CLRF	STACK_4+3
$0352	$25A0			CALL	_mul_32x32_u
$0353	$30FF			MOVLW	255
$0354	$00F4			MOVWF	STACK_4
$0355	$3003			MOVLW	3
$0356	$00F5			MOVWF	STACK_4+1
$0357	$01F6			CLRF	STACK_4+2
$0358	$01F7			CLRF	STACK_4+3
$0359	$2379			CALL	_div_32x32_s
$035A	$0870			MOVF	STACK_0, 0
$035B	$00B3			MOVWF	_temp
$035C	$0871			MOVF	STACK_0+1, 0
$035D	$00B4			MOVWF	_temp+1
$035E	$0872			MOVF	STACK_0+2, 0
$035F	$00B5			MOVWF	_temp+2
$0360	$0873			MOVF	STACK_0+3, 0
$0361	$00B6			MOVWF	_temp+3
;Temperature.ppas,27 :: 		WordtoStr(temp,txt);
$0362	$0870			MOVF	STACK_0, 0
$0363	$00C4			MOVWF	FARG_WordToStr
$0364	$0871			MOVF	STACK_0+1, 0
$0365	$00C5			MOVWF	FARG_WordToStr+1
$0366	$302D			MOVLW	_txt
$0367	$00C6			MOVWF	FARG_WordToStr+2
$0368	$2494			CALL	_wordtostr
;Temperature.ppas,28 :: 		Lcd_Out(2,13,txt);
$0369	$3002			MOVLW	2
$036A	$00D5			MOVWF	FARG_Lcd_Out
$036B	$300D			MOVLW	13
$036C	$00D6			MOVWF	FARG_Lcd_Out+1
$036D	$302D			MOVLW	_txt
$036E	$00D7			MOVWF	FARG_Lcd_Out+2
$036F	$24EE			CALL	_lcd_out
;Temperature.ppas,29 :: 		Lcd_Chr(2,19,'C');
$0370	$3002			MOVLW	2
$0371	$00C4			MOVWF	FARG_Lcd_Chr
$0372	$3013			MOVLW	19
$0373	$00C5			MOVWF	FARG_Lcd_Chr+1
$0374	$3043			MOVLW	67
$0375	$00C6			MOVWF	FARG_Lcd_Chr+2
$0376	$256E			CALL	_lcd_chr
;Temperature.ppas,34 :: 		end;
$0377	$2B33			GOTO	Temperature_L_3
;Temperature.ppas,40 :: 		end.
$0378	$2B78			GOTO	$
