;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 3/30/2021 9:57:42 AM
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2923			GOTO	_main
$0314	$	_delay_1us:
;delays.ppas,11 :: 		begin
;delays.ppas,12 :: 		Delay_us(1);
$0314	$0000			NOP
$0315	$0000			NOP
$0316	$	delays_L_1:
;delays.ppas,13 :: 		end;
$0316	$0008			RETURN
$02F2	$	_delay_5500us:
;delays.ppas,41 :: 		begin
;delays.ppas,42 :: 		Delay_us(5500);
$02F2	$300F			MOVLW	15
$02F3	$1303			BCF	STATUS, RP1
$02F4	$1283			BCF	STATUS, RP0
$02F5	$00FB			MOVWF	STACK_11
$02F6	$30FF			MOVLW	255
$02F7	$00FA			MOVWF	STACK_10
$02F8	$0BFB			DECFSZ	STACK_11, F
$02F9	$2AFB			GOTO	$+2
$02FA	$2AFE			GOTO	$+4
$02FB	$0BFA			DECFSZ	STACK_10, F
$02FC	$2AFB			GOTO	$-1
$02FD	$2AF8			GOTO	$-5
$02FE	$303E			MOVLW	62
$02FF	$00FA			MOVWF	STACK_10
$0300	$0BFA			DECFSZ	STACK_10, F
$0301	$2B00			GOTO	$-1
$0302	$0000			NOP
$0303	$	delays_L_7:
;delays.ppas,43 :: 		end;
$0303	$0008			RETURN
$030D	$	_delay_50us:
;delays.ppas,26 :: 		begin
;delays.ppas,27 :: 		Delay_us(50);
$030D	$3021			MOVLW	33
$030E	$1303			BCF	STATUS, RP1
$030F	$1283			BCF	STATUS, RP0
$0310	$00FA			MOVWF	STACK_10
$0311	$0BFA			DECFSZ	STACK_10, F
$0312	$2B11			GOTO	$-1
$0313	$	delays_L_4:
;delays.ppas,28 :: 		end;
$0313	$0008			RETURN
$01F7	$	_lcd_cmd:
;lcd.ppas,19 :: 		
;lcd.ppas,20 :: 		
$01F7	$1303			BCF	STATUS, RP1
$01F8	$1283			BCF	STATUS, RP0
$01F9	$0820			MOVF	lcd_ctrlport_address, 0
$01FA	$0084			MOVWF	FSR
;lcd.ppas,22 :: 		
$01FB	$0921			COMF	lcd____menable, W
$01FC	$00F0			MOVWF	STACK_0
$01FD	$0870			MOVF	STACK_0, 0
$01FE	$0580			ANDWF	INDF, 1
;lcd.ppas,23 :: 		
$01FF	$0922			COMF	lcd____mrs, W
$0200	$00F0			MOVWF	STACK_0
$0201	$0870			MOVF	STACK_0, 0
$0202	$0580			ANDWF	INDF, 1
;lcd.ppas,25 :: 		
$0203	$0823			MOVF	lcd_dataport_address, 0
$0204	$0084			MOVWF	FSR
;lcd.ppas,26 :: 		
$0205	$0825			MOVF	lcd____mdb6, 0
$0206	$0424			IORWF	lcd____mdb7, 0
$0207	$00F0			MOVWF	STACK_0
$0208	$0826			MOVF	lcd____mdb5, 0
$0209	$04F0			IORWF	STACK_0, 1
$020A	$0827			MOVF	lcd____mdb4, 0
$020B	$04F0			IORWF	STACK_0, 1
$020C	$09F0			COMF	STACK_0, F
$020D	$0870			MOVF	STACK_0, 0
$020E	$0580			ANDWF	INDF, 1
;lcd.ppas,28 :: 		
$020F	$3000			MOVLW	0
$0210	$1BCA			BTFSC	FARG_Lcd_Cmd, 7
$0211	$3001			MOVLW	1
$0212	$00F1			MOVWF	STACK_1
$0213	$0871			MOVF	STACK_1, 0
$0214	$3A01			XORLW	1
$0215	$1D03			BTFSS	STATUS, Z
$0216	$2A19			GOTO	lcd_L_2
$0217	$	lcd_L_1:
;lcd.ppas,29 :: 		
$0217	$0824			MOVF	lcd____mdb7, 0
$0218	$0480			IORWF	INDF, 1
$0219	$	lcd_L_2:
$0219	$	lcd_L_3:
;lcd.ppas,30 :: 		
$0219	$3000			MOVLW	0
$021A	$1B4A			BTFSC	FARG_Lcd_Cmd, 6
$021B	$3001			MOVLW	1
$021C	$00F1			MOVWF	STACK_1
$021D	$0871			MOVF	STACK_1, 0
$021E	$3A01			XORLW	1
$021F	$1D03			BTFSS	STATUS, Z
$0220	$2A23			GOTO	lcd_L_5
$0221	$	lcd_L_4:
;lcd.ppas,31 :: 		
$0221	$0825			MOVF	lcd____mdb6, 0
$0222	$0480			IORWF	INDF, 1
$0223	$	lcd_L_5:
$0223	$	lcd_L_6:
;lcd.ppas,32 :: 		
$0223	$3000			MOVLW	0
$0224	$1ACA			BTFSC	FARG_Lcd_Cmd, 5
$0225	$3001			MOVLW	1
$0226	$00F1			MOVWF	STACK_1
$0227	$0871			MOVF	STACK_1, 0
$0228	$3A01			XORLW	1
$0229	$1D03			BTFSS	STATUS, Z
$022A	$2A2D			GOTO	lcd_L_8
$022B	$	lcd_L_7:
;lcd.ppas,33 :: 		
$022B	$0826			MOVF	lcd____mdb5, 0
$022C	$0480			IORWF	INDF, 1
$022D	$	lcd_L_8:
$022D	$	lcd_L_9:
;lcd.ppas,34 :: 		
$022D	$3000			MOVLW	0
$022E	$1A4A			BTFSC	FARG_Lcd_Cmd, 4
$022F	$3001			MOVLW	1
$0230	$00F1			MOVWF	STACK_1
$0231	$0871			MOVF	STACK_1, 0
$0232	$3A01			XORLW	1
$0233	$1D03			BTFSS	STATUS, Z
$0234	$2A37			GOTO	lcd_L_11
$0235	$	lcd_L_10:
;lcd.ppas,35 :: 		
$0235	$0827			MOVF	lcd____mdb4, 0
$0236	$0480			IORWF	INDF, 1
$0237	$	lcd_L_11:
$0237	$	lcd_L_12:
;lcd.ppas,37 :: 		
$0237	$0820			MOVF	lcd_ctrlport_address, 0
$0238	$0084			MOVWF	FSR
;lcd.ppas,38 :: 		
$0239	$0828			MOVF	lcd_lcdcmd_status, 0
$023A	$3A01			XORLW	1
$023B	$1D03			BTFSS	STATUS, Z
$023C	$2A42			GOTO	lcd_L_14
$023D	$	lcd_L_13:
;lcd.ppas,39 :: 		
$023D	$0922			COMF	lcd____mrs, W
$023E	$00F0			MOVWF	STACK_0
$023F	$0870			MOVF	STACK_0, 0
$0240	$0580			ANDWF	INDF, 1
$0241	$2A44			GOTO	lcd_L_15
;lcd.ppas,40 :: 		
$0242	$	lcd_L_14:
;lcd.ppas,41 :: 		
$0242	$0822			MOVF	lcd____mrs, 0
$0243	$0480			IORWF	INDF, 1
$0244	$	lcd_L_15:
;lcd.ppas,43 :: 		
$0244	$0821			MOVF	lcd____menable, 0
$0245	$0480			IORWF	INDF, 1
;lcd.ppas,44 :: 		
$0246	$2314			CALL	_delay_1us
;lcd.ppas,45 :: 		
$0247	$0921			COMF	lcd____menable, W
$0248	$00F0			MOVWF	STACK_0
$0249	$0870			MOVF	STACK_0, 0
$024A	$0580			ANDWF	INDF, 1
;lcd.ppas,47 :: 		
$024B	$0922			COMF	lcd____mrs, W
$024C	$00F0			MOVWF	STACK_0
$024D	$0870			MOVF	STACK_0, 0
$024E	$0580			ANDWF	INDF, 1
;lcd.ppas,49 :: 		
$024F	$0823			MOVF	lcd_dataport_address, 0
$0250	$0084			MOVWF	FSR
;lcd.ppas,50 :: 		
$0251	$0825			MOVF	lcd____mdb6, 0
$0252	$0424			IORWF	lcd____mdb7, 0
$0253	$00F0			MOVWF	STACK_0
$0254	$0826			MOVF	lcd____mdb5, 0
$0255	$04F0			IORWF	STACK_0, 1
$0256	$0827			MOVF	lcd____mdb4, 0
$0257	$04F0			IORWF	STACK_0, 1
$0258	$09F0			COMF	STACK_0, F
$0259	$0870			MOVF	STACK_0, 0
$025A	$0580			ANDWF	INDF, 1
;lcd.ppas,52 :: 		
$025B	$3000			MOVLW	0
$025C	$19CA			BTFSC	FARG_Lcd_Cmd, 3
$025D	$3001			MOVLW	1
$025E	$00F1			MOVWF	STACK_1
$025F	$0871			MOVF	STACK_1, 0
$0260	$3A01			XORLW	1
$0261	$1D03			BTFSS	STATUS, Z
$0262	$2A65			GOTO	lcd_L_17
$0263	$	lcd_L_16:
;lcd.ppas,53 :: 		
$0263	$0824			MOVF	lcd____mdb7, 0
$0264	$0480			IORWF	INDF, 1
$0265	$	lcd_L_17:
$0265	$	lcd_L_18:
;lcd.ppas,54 :: 		
$0265	$3000			MOVLW	0
$0266	$194A			BTFSC	FARG_Lcd_Cmd, 2
$0267	$3001			MOVLW	1
$0268	$00F1			MOVWF	STACK_1
$0269	$0871			MOVF	STACK_1, 0
$026A	$3A01			XORLW	1
$026B	$1D03			BTFSS	STATUS, Z
$026C	$2A6F			GOTO	lcd_L_20
$026D	$	lcd_L_19:
;lcd.ppas,55 :: 		
$026D	$0825			MOVF	lcd____mdb6, 0
$026E	$0480			IORWF	INDF, 1
$026F	$	lcd_L_20:
$026F	$	lcd_L_21:
;lcd.ppas,56 :: 		
$026F	$3000			MOVLW	0
$0270	$18CA			BTFSC	FARG_Lcd_Cmd, 1
$0271	$3001			MOVLW	1
$0272	$00F1			MOVWF	STACK_1
$0273	$0871			MOVF	STACK_1, 0
$0274	$3A01			XORLW	1
$0275	$1D03			BTFSS	STATUS, Z
$0276	$2A79			GOTO	lcd_L_23
$0277	$	lcd_L_22:
;lcd.ppas,57 :: 		
$0277	$0826			MOVF	lcd____mdb5, 0
$0278	$0480			IORWF	INDF, 1
$0279	$	lcd_L_23:
$0279	$	lcd_L_24:
;lcd.ppas,58 :: 		
$0279	$3001			MOVLW	1
$027A	$054A			ANDWF	FARG_Lcd_Cmd, 0
$027B	$00F1			MOVWF	STACK_1
$027C	$0871			MOVF	STACK_1, 0
$027D	$3A01			XORLW	1
$027E	$1D03			BTFSS	STATUS, Z
$027F	$2A82			GOTO	lcd_L_26
$0280	$	lcd_L_25:
;lcd.ppas,59 :: 		
$0280	$0827			MOVF	lcd____mdb4, 0
$0281	$0480			IORWF	INDF, 1
$0282	$	lcd_L_26:
$0282	$	lcd_L_27:
;lcd.ppas,61 :: 		
$0282	$0820			MOVF	lcd_ctrlport_address, 0
$0283	$0084			MOVWF	FSR
;lcd.ppas,62 :: 		
$0284	$0828			MOVF	lcd_lcdcmd_status, 0
$0285	$3A01			XORLW	1
$0286	$1D03			BTFSS	STATUS, Z
$0287	$2A8D			GOTO	lcd_L_29
$0288	$	lcd_L_28:
;lcd.ppas,63 :: 		
$0288	$0922			COMF	lcd____mrs, W
$0289	$00F0			MOVWF	STACK_0
$028A	$0870			MOVF	STACK_0, 0
$028B	$0580			ANDWF	INDF, 1
$028C	$2A8F			GOTO	lcd_L_30
;lcd.ppas,64 :: 		
$028D	$	lcd_L_29:
;lcd.ppas,65 :: 		
$028D	$0822			MOVF	lcd____mrs, 0
$028E	$0480			IORWF	INDF, 1
$028F	$	lcd_L_30:
;lcd.ppas,67 :: 		
$028F	$0821			MOVF	lcd____menable, 0
$0290	$0480			IORWF	INDF, 1
;lcd.ppas,68 :: 		
$0291	$2314			CALL	_delay_1us
;lcd.ppas,69 :: 		
$0292	$0921			COMF	lcd____menable, W
$0293	$00F0			MOVWF	STACK_0
$0294	$0870			MOVF	STACK_0, 0
$0295	$0580			ANDWF	INDF, 1
;lcd.ppas,71 :: 		
$0296	$0828			MOVF	lcd_lcdcmd_status, 0
$0297	$3A01			XORLW	1
$0298	$1D03			BTFSS	STATUS, Z
$0299	$2A9C			GOTO	lcd_L_32
$029A	$	lcd_L_31:
;lcd.ppas,72 :: 		
$029A	$22F2			CALL	_delay_5500us
$029B	$2A9D			GOTO	lcd_L_33
;lcd.ppas,73 :: 		
$029C	$	lcd_L_32:
;lcd.ppas,74 :: 		
$029C	$230D			CALL	_delay_50us
$029D	$	lcd_L_33:
$029D	$	lcd_L_0:
;lcd.ppas,75 :: 		
$029D	$0008			RETURN
$0004	$	_lcd_config:
;lcd.ppas,115 :: 		
;lcd.ppas,116 :: 		
$0004	$22F2			CALL	_delay_5500us
;lcd.ppas,117 :: 		
$0005	$22F2			CALL	_delay_5500us
;lcd.ppas,118 :: 		
$0006	$22F2			CALL	_delay_5500us
;lcd.ppas,120 :: 		
$0007	$0842			MOVF	FARG_Lcd_Config+1, 0
$0008	$00F0			MOVWF	STACK_0
$0009	$3001			MOVLW	1
$000A	$00F4			MOVWF	STACK_4
$000B	$0870			MOVF	STACK_0, 0
$000C	$	L_Lcd_Config_0:
$000C	$1903			BTFSC	STATUS, Z
$000D	$2812			GOTO	L_Lcd_Config_1
$000E	$0DF4			RLF	STACK_4, 1
$000F	$1074			BCF	STACK_4, 0
$0010	$3FFF			ADDLW	255
$0011	$280C			GOTO	L_Lcd_Config_0
$0012	$	L_Lcd_Config_1:
$0012	$0874			MOVF	STACK_4, 0
$0013	$00A4			MOVWF	lcd____mdb7
;lcd.ppas,121 :: 		
$0014	$0843			MOVF	FARG_Lcd_Config+2, 0
$0015	$00F0			MOVWF	STACK_0
$0016	$3001			MOVLW	1
$0017	$00F3			MOVWF	STACK_3
$0018	$0870			MOVF	STACK_0, 0
$0019	$	L_Lcd_Config_2:
$0019	$1903			BTFSC	STATUS, Z
$001A	$281F			GOTO	L_Lcd_Config_3
$001B	$0DF3			RLF	STACK_3, 1
$001C	$1073			BCF	STACK_3, 0
$001D	$3FFF			ADDLW	255
$001E	$2819			GOTO	L_Lcd_Config_2
$001F	$	L_Lcd_Config_3:
$001F	$0873			MOVF	STACK_3, 0
$0020	$00A5			MOVWF	lcd____mdb6
;lcd.ppas,122 :: 		
$0021	$0844			MOVF	FARG_Lcd_Config+3, 0
$0022	$00F0			MOVWF	STACK_0
$0023	$3001			MOVLW	1
$0024	$00F2			MOVWF	STACK_2
$0025	$0870			MOVF	STACK_0, 0
$0026	$	L_Lcd_Config_4:
$0026	$1903			BTFSC	STATUS, Z
$0027	$282C			GOTO	L_Lcd_Config_5
$0028	$0DF2			RLF	STACK_2, 1
$0029	$1072			BCF	STACK_2, 0
$002A	$3FFF			ADDLW	255
$002B	$2826			GOTO	L_Lcd_Config_4
$002C	$	L_Lcd_Config_5:
$002C	$0872			MOVF	STACK_2, 0
$002D	$00A6			MOVWF	lcd____mdb5
;lcd.ppas,123 :: 		
$002E	$0845			MOVF	FARG_Lcd_Config+4, 0
$002F	$00F0			MOVWF	STACK_0
$0030	$3001			MOVLW	1
$0031	$00F1			MOVWF	STACK_1
$0032	$0870			MOVF	STACK_0, 0
$0033	$	L_Lcd_Config_6:
$0033	$1903			BTFSC	STATUS, Z
$0034	$2839			GOTO	L_Lcd_Config_7
$0035	$0DF1			RLF	STACK_1, 1
$0036	$1071			BCF	STACK_1, 0
$0037	$3FFF			ADDLW	255
$0038	$2833			GOTO	L_Lcd_Config_6
$0039	$	L_Lcd_Config_7:
$0039	$0871			MOVF	STACK_1, 0
$003A	$00A7			MOVWF	lcd____mdb4
;lcd.ppas,124 :: 		
$003B	$0847			MOVF	FARG_Lcd_Config+6, 0
$003C	$00F0			MOVWF	STACK_0
$003D	$3001			MOVLW	1
$003E	$00A2			MOVWF	lcd____mrs
$003F	$0870			MOVF	STACK_0, 0
$0040	$	L_Lcd_Config_8:
$0040	$1903			BTFSC	STATUS, Z
$0041	$2846			GOTO	L_Lcd_Config_9
$0042	$0DA2			RLF	lcd____mrs, 1
$0043	$1022			BCF	lcd____mrs, 0
$0044	$3FFF			ADDLW	255
$0045	$2840			GOTO	L_Lcd_Config_8
$0046	$	L_Lcd_Config_9:
;lcd.ppas,125 :: 		
$0046	$0848			MOVF	FARG_Lcd_Config+7, 0
$0047	$00F0			MOVWF	STACK_0
$0048	$3001			MOVLW	1
$0049	$00A9			MOVWF	lcd____mrw
$004A	$0870			MOVF	STACK_0, 0
$004B	$	L_Lcd_Config_10:
$004B	$1903			BTFSC	STATUS, Z
$004C	$2851			GOTO	L_Lcd_Config_11
$004D	$0DA9			RLF	lcd____mrw, 1
$004E	$1029			BCF	lcd____mrw, 0
$004F	$3FFF			ADDLW	255
$0050	$284B			GOTO	L_Lcd_Config_10
$0051	$	L_Lcd_Config_11:
;lcd.ppas,126 :: 		
$0051	$0849			MOVF	FARG_Lcd_Config+8, 0
$0052	$00F0			MOVWF	STACK_0
$0053	$3001			MOVLW	1
$0054	$00A1			MOVWF	lcd____menable
$0055	$0870			MOVF	STACK_0, 0
$0056	$	L_Lcd_Config_12:
$0056	$1903			BTFSC	STATUS, Z
$0057	$285C			GOTO	L_Lcd_Config_13
$0058	$0DA1			RLF	lcd____menable, 1
$0059	$1021			BCF	lcd____menable, 0
$005A	$3FFF			ADDLW	255
$005B	$2856			GOTO	L_Lcd_Config_12
$005C	$	L_Lcd_Config_13:
;lcd.ppas,128 :: 		
$005C	$0841			MOVF	FARG_Lcd_Config, 0
$005D	$00A3			MOVWF	lcd_dataport_address
;lcd.ppas,129 :: 		
$005E	$0846			MOVF	FARG_Lcd_Config+5, 0
$005F	$00A0			MOVWF	lcd_ctrlport_address
;lcd.ppas,131 :: 		
$0060	$0841			MOVF	FARG_Lcd_Config, 0
$0061	$0084			MOVWF	FSR
;lcd.ppas,133 :: 		
$0062	$0873			MOVF	STACK_3, 0
$0063	$0474			IORWF	STACK_4, 0
$0064	$00F0			MOVWF	STACK_0
$0065	$0872			MOVF	STACK_2, 0
$0066	$04F0			IORWF	STACK_0, 1
$0067	$0871			MOVF	STACK_1, 0
$0068	$04F0			IORWF	STACK_0, 1
$0069	$09F0			COMF	STACK_0, F
$006A	$0870			MOVF	STACK_0, 0
$006B	$0580			ANDWF	INDF, 1
;lcd.ppas,134 :: 		
$006C	$	lcd_L_56:
$006C	$1784			BSF	FSR, 7
$006D	$	lcd_L_57:
;lcd.ppas,135 :: 		
$006D	$0825			MOVF	lcd____mdb6, 0
$006E	$0424			IORWF	lcd____mdb7, 0
$006F	$00F0			MOVWF	STACK_0
$0070	$0826			MOVF	lcd____mdb5, 0
$0071	$04F0			IORWF	STACK_0, 1
$0072	$0827			MOVF	lcd____mdb4, 0
$0073	$04F0			IORWF	STACK_0, 1
$0074	$09F0			COMF	STACK_0, F
$0075	$0870			MOVF	STACK_0, 0
$0076	$0580			ANDWF	INDF, 1
;lcd.ppas,136 :: 		
$0077	$1384			BCF	FSR, 7
$0078	$	lcd_L_59:
;lcd.ppas,139 :: 		
$0078	$0820			MOVF	lcd_ctrlport_address, 0
$0079	$0084			MOVWF	FSR
;lcd.ppas,141 :: 		
$007A	$0829			MOVF	lcd____mrw, 0
$007B	$0422			IORWF	lcd____mrs, 0
$007C	$00F0			MOVWF	STACK_0
$007D	$0821			MOVF	lcd____menable, 0
$007E	$04F0			IORWF	STACK_0, 1
$007F	$09F0			COMF	STACK_0, F
$0080	$0870			MOVF	STACK_0, 0
$0081	$0580			ANDWF	INDF, 1
;lcd.ppas,142 :: 		
$0082	$	lcd_L_60:
$0082	$1784			BSF	FSR, 7
$0083	$	lcd_L_61:
;lcd.ppas,143 :: 		
$0083	$0829			MOVF	lcd____mrw, 0
$0084	$0422			IORWF	lcd____mrs, 0
$0085	$00F0			MOVWF	STACK_0
$0086	$0821			MOVF	lcd____menable, 0
$0087	$04F0			IORWF	STACK_0, 1
$0088	$09F0			COMF	STACK_0, F
$0089	$0870			MOVF	STACK_0, 0
$008A	$0580			ANDWF	INDF, 1
;lcd.ppas,144 :: 		
$008B	$1384			BCF	FSR, 7
$008C	$	lcd_L_63:
;lcd.ppas,148 :: 		
$008C	$0823			MOVF	lcd_dataport_address, 0
$008D	$0084			MOVWF	FSR
;lcd.ppas,149 :: 		
$008E	$0826			MOVF	lcd____mdb5, 0
$008F	$0400			IORWF	INDF, 0
$0090	$00F0			MOVWF	STACK_0
$0091	$0827			MOVF	lcd____mdb4, 0
$0092	$0470			IORWF	STACK_0, 0
$0093	$0080			MOVWF	INDF
;lcd.ppas,151 :: 		
$0094	$0820			MOVF	lcd_ctrlport_address, 0
$0095	$0084			MOVWF	FSR
;lcd.ppas,152 :: 		
$0096	$0821			MOVF	lcd____menable, 0
$0097	$0480			IORWF	INDF, 1
;lcd.ppas,153 :: 		
$0098	$0921			COMF	lcd____menable, W
$0099	$00F0			MOVWF	STACK_0
$009A	$0870			MOVF	STACK_0, 0
$009B	$0580			ANDWF	INDF, 1
;lcd.ppas,155 :: 		
$009C	$22F2			CALL	_delay_5500us
;lcd.ppas,160 :: 		
$009D	$0821			MOVF	lcd____menable, 0
$009E	$0480			IORWF	INDF, 1
;lcd.ppas,161 :: 		
$009F	$0921			COMF	lcd____menable, W
$00A0	$00F0			MOVWF	STACK_0
$00A1	$0870			MOVF	STACK_0, 0
$00A2	$0580			ANDWF	INDF, 1
;lcd.ppas,163 :: 		
$00A3	$22F2			CALL	_delay_5500us
;lcd.ppas,168 :: 		
$00A4	$0821			MOVF	lcd____menable, 0
$00A5	$0480			IORWF	INDF, 1
;lcd.ppas,169 :: 		
$00A6	$0921			COMF	lcd____menable, W
$00A7	$00F0			MOVWF	STACK_0
$00A8	$0870			MOVF	STACK_0, 0
$00A9	$0580			ANDWF	INDF, 1
;lcd.ppas,171 :: 		
$00AA	$22F2			CALL	_delay_5500us
;lcd.ppas,174 :: 		
$00AB	$0823			MOVF	lcd_dataport_address, 0
$00AC	$0084			MOVWF	FSR
;lcd.ppas,175 :: 		
$00AD	$0826			MOVF	lcd____mdb5, 0
$00AE	$0480			IORWF	INDF, 1
;lcd.ppas,176 :: 		
$00AF	$0927			COMF	lcd____mdb4, W
$00B0	$00F0			MOVWF	STACK_0
$00B1	$0870			MOVF	STACK_0, 0
$00B2	$0580			ANDWF	INDF, 1
;lcd.ppas,178 :: 		
$00B3	$0820			MOVF	lcd_ctrlport_address, 0
$00B4	$0084			MOVWF	FSR
;lcd.ppas,179 :: 		
$00B5	$0821			MOVF	lcd____menable, 0
$00B6	$0480			IORWF	INDF, 1
;lcd.ppas,180 :: 		
$00B7	$0921			COMF	lcd____menable, W
$00B8	$00F0			MOVWF	STACK_0
$00B9	$0870			MOVF	STACK_0, 0
$00BA	$0580			ANDWF	INDF, 1
;lcd.ppas,182 :: 		
$00BB	$22F2			CALL	_delay_5500us
;lcd.ppas,187 :: 		
$00BC	$0821			MOVF	lcd____menable, 0
$00BD	$0480			IORWF	INDF, 1
;lcd.ppas,188 :: 		
$00BE	$0921			COMF	lcd____menable, W
$00BF	$00F1			MOVWF	STACK_1
$00C0	$0871			MOVF	STACK_1, 0
$00C1	$0580			ANDWF	INDF, 1
;lcd.ppas,190 :: 		
$00C2	$0823			MOVF	lcd_dataport_address, 0
$00C3	$0084			MOVWF	FSR
;lcd.ppas,191 :: 		
$00C4	$0926			COMF	lcd____mdb5, W
$00C5	$00F0			MOVWF	STACK_0
$00C6	$0870			MOVF	STACK_0, 0
$00C7	$0580			ANDWF	INDF, 1
;lcd.ppas,192 :: 		
$00C8	$0824			MOVF	lcd____mdb7, 0
$00C9	$0480			IORWF	INDF, 1
;lcd.ppas,194 :: 		
$00CA	$0820			MOVF	lcd_ctrlport_address, 0
$00CB	$0084			MOVWF	FSR
;lcd.ppas,195 :: 		
$00CC	$0821			MOVF	lcd____menable, 0
$00CD	$0480			IORWF	INDF, 1
;lcd.ppas,196 :: 		
$00CE	$0871			MOVF	STACK_1, 0
$00CF	$0580			ANDWF	INDF, 1
;lcd.ppas,198 :: 		
$00D0	$22F2			CALL	_delay_5500us
;lcd.ppas,201 :: 		
$00D1	$0823			MOVF	lcd_dataport_address, 0
$00D2	$0084			MOVWF	FSR
;lcd.ppas,202 :: 		
$00D3	$0924			COMF	lcd____mdb7, W
$00D4	$00F0			MOVWF	STACK_0
$00D5	$0870			MOVF	STACK_0, 0
$00D6	$0580			ANDWF	INDF, 1
;lcd.ppas,203 :: 		
$00D7	$0827			MOVF	lcd____mdb4, 0
$00D8	$0480			IORWF	INDF, 1
;lcd.ppas,204 :: 		
$00D9	$0820			MOVF	lcd_ctrlport_address, 0
$00DA	$0084			MOVWF	FSR
;lcd.ppas,205 :: 		
$00DB	$0821			MOVF	lcd____menable, 0
$00DC	$0480			IORWF	INDF, 1
;lcd.ppas,206 :: 		
$00DD	$0921			COMF	lcd____menable, W
$00DE	$00F1			MOVWF	STACK_1
$00DF	$0871			MOVF	STACK_1, 0
$00E0	$0580			ANDWF	INDF, 1
;lcd.ppas,207 :: 		
$00E1	$0823			MOVF	lcd_dataport_address, 0
$00E2	$0084			MOVWF	FSR
;lcd.ppas,208 :: 		
$00E3	$0927			COMF	lcd____mdb4, W
$00E4	$00F0			MOVWF	STACK_0
$00E5	$0870			MOVF	STACK_0, 0
$00E6	$0580			ANDWF	INDF, 1
;lcd.ppas,209 :: 		
$00E7	$0820			MOVF	lcd_ctrlport_address, 0
$00E8	$0084			MOVWF	FSR
;lcd.ppas,210 :: 		
$00E9	$0821			MOVF	lcd____menable, 0
$00EA	$0480			IORWF	INDF, 1
;lcd.ppas,211 :: 		
$00EB	$0871			MOVF	STACK_1, 0
$00EC	$0580			ANDWF	INDF, 1
;lcd.ppas,213 :: 		
$00ED	$22F2			CALL	_delay_5500us
;lcd.ppas,218 :: 		
$00EE	$0821			MOVF	lcd____menable, 0
$00EF	$0480			IORWF	INDF, 1
;lcd.ppas,219 :: 		
$00F0	$0921			COMF	lcd____menable, W
$00F1	$00F0			MOVWF	STACK_0
$00F2	$0870			MOVF	STACK_0, 0
$00F3	$0580			ANDWF	INDF, 1
;lcd.ppas,220 :: 		
$00F4	$0823			MOVF	lcd_dataport_address, 0
$00F5	$0084			MOVWF	FSR
;lcd.ppas,221 :: 		
$00F6	$0827			MOVF	lcd____mdb4, 0
$00F7	$0480			IORWF	INDF, 1
;lcd.ppas,222 :: 		
$00F8	$0820			MOVF	lcd_ctrlport_address, 0
$00F9	$0084			MOVWF	FSR
;lcd.ppas,223 :: 		
$00FA	$0821			MOVF	lcd____menable, 0
$00FB	$0480			IORWF	INDF, 1
;lcd.ppas,224 :: 		
$00FC	$0870			MOVF	STACK_0, 0
$00FD	$0580			ANDWF	INDF, 1
;lcd.ppas,226 :: 		
$00FE	$22F2			CALL	_delay_5500us
;lcd.ppas,229 :: 		
$00FF	$0823			MOVF	lcd_dataport_address, 0
$0100	$0084			MOVWF	FSR
;lcd.ppas,230 :: 		
$0101	$0927			COMF	lcd____mdb4, W
$0102	$00F0			MOVWF	STACK_0
$0103	$0870			MOVF	STACK_0, 0
$0104	$0580			ANDWF	INDF, 1
;lcd.ppas,231 :: 		
$0105	$0820			MOVF	lcd_ctrlport_address, 0
$0106	$0084			MOVWF	FSR
;lcd.ppas,232 :: 		
$0107	$0821			MOVF	lcd____menable, 0
$0108	$0480			IORWF	INDF, 1
;lcd.ppas,233 :: 		
$0109	$0921			COMF	lcd____menable, W
$010A	$00F1			MOVWF	STACK_1
$010B	$0871			MOVF	STACK_1, 0
$010C	$0580			ANDWF	INDF, 1
;lcd.ppas,234 :: 		
$010D	$0823			MOVF	lcd_dataport_address, 0
$010E	$0084			MOVWF	FSR
;lcd.ppas,235 :: 		
$010F	$0827			MOVF	lcd____mdb4, 0
$0110	$0400			IORWF	INDF, 0
$0111	$00F0			MOVWF	STACK_0
$0112	$0826			MOVF	lcd____mdb5, 0
$0113	$04F0			IORWF	STACK_0, 1
$0114	$0825			MOVF	lcd____mdb6, 0
$0115	$04F0			IORWF	STACK_0, 1
$0116	$0824			MOVF	lcd____mdb7, 0
$0117	$0470			IORWF	STACK_0, 0
$0118	$0080			MOVWF	INDF
;lcd.ppas,236 :: 		
$0119	$0820			MOVF	lcd_ctrlport_address, 0
$011A	$0084			MOVWF	FSR
;lcd.ppas,237 :: 		
$011B	$0821			MOVF	lcd____menable, 0
$011C	$0480			IORWF	INDF, 1
;lcd.ppas,238 :: 		
$011D	$0871			MOVF	STACK_1, 0
$011E	$0580			ANDWF	INDF, 1
;lcd.ppas,240 :: 		
$011F	$22F2			CALL	_delay_5500us
;lcd.ppas,242 :: 		
$0120	$3001			MOVLW	1
$0121	$00A8			MOVWF	lcd_lcdcmd_status
$0122	$	lcd_L_55:
;lcd.ppas,243 :: 		
$0122	$0008			RETURN
$0304	$	_lcd_chr_cp:
;lcd.ppas,97 :: 		
;lcd.ppas,98 :: 		
$0304	$1303			BCF	STATUS, RP1
$0305	$1283			BCF	STATUS, RP0
$0306	$01A8			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,99 :: 		
$0307	$0841			MOVF	FARG_Lcd_Chr_CP, 0
$0308	$00CA			MOVWF	FARG_Lcd_Cmd
$0309	$21F7			CALL	_lcd_cmd
;lcd.ppas,100 :: 		
$030A	$3001			MOVLW	1
$030B	$00A8			MOVWF	lcd_lcdcmd_status
$030C	$	lcd_L_48:
;lcd.ppas,101 :: 		
$030C	$0008			RETURN
$02DD	$	_lcd_init:
;lcd.ppas,246 :: 		
;lcd.ppas,247 :: 		
$02DD	$1303			BCF	STATUS, RP1
$02DE	$1283			BCF	STATUS, RP0
$02DF	$083D			MOVF	FARG_Lcd_Init, 0
$02E0	$00C1			MOVWF	FARG_Lcd_Config
$02E1	$3007			MOVLW	7
$02E2	$00C2			MOVWF	FARG_Lcd_Config+1
$02E3	$3006			MOVLW	6
$02E4	$00C3			MOVWF	FARG_Lcd_Config+2
$02E5	$3005			MOVLW	5
$02E6	$00C4			MOVWF	FARG_Lcd_Config+3
$02E7	$3004			MOVLW	4
$02E8	$00C5			MOVWF	FARG_Lcd_Config+4
$02E9	$083D			MOVF	FARG_Lcd_Init, 0
$02EA	$00C6			MOVWF	FARG_Lcd_Config+5
$02EB	$3002			MOVLW	2
$02EC	$00C7			MOVWF	FARG_Lcd_Config+6
$02ED	$01C8			CLRF	FARG_Lcd_Config+7, 1
$02EE	$3003			MOVLW	3
$02EF	$00C9			MOVWF	FARG_Lcd_Config+8
$02F0	$2004			CALL	_lcd_config
$02F1	$	lcd_L_64:
;lcd.ppas,248 :: 		
$02F1	$0008			RETURN
$029E	$	_lcd_out:
;lcd.ppas,252 :: 		
;lcd.ppas,254 :: 		
$029E	$	lcd_L_68:
$029E	$1303			BCF	STATUS, RP1
$029F	$1283			BCF	STATUS, RP0
$02A0	$083D			MOVF	FARG_Lcd_Out, 0
$02A1	$3A01			XORLW	1
$02A2	$1D03			BTFSS	STATUS, Z
$02A3	$2AA7			GOTO	lcd_L_69
$02A4	$	lcd_L_67:
$02A4	$3080			MOVLW	128
$02A5	$00BD			MOVWF	FARG_Lcd_Out
$02A6	$2ABE			GOTO	lcd_L_66
$02A7	$	lcd_L_69:
;lcd.ppas,255 :: 		
$02A7	$	lcd_L_71:
$02A7	$083D			MOVF	FARG_Lcd_Out, 0
$02A8	$3A02			XORLW	2
$02A9	$1D03			BTFSS	STATUS, Z
$02AA	$2AAE			GOTO	lcd_L_72
$02AB	$	lcd_L_70:
$02AB	$30C0			MOVLW	192
$02AC	$00BD			MOVWF	FARG_Lcd_Out
$02AD	$2ABE			GOTO	lcd_L_66
$02AE	$	lcd_L_72:
;lcd.ppas,256 :: 		
$02AE	$	lcd_L_74:
$02AE	$083D			MOVF	FARG_Lcd_Out, 0
$02AF	$3A03			XORLW	3
$02B0	$1D03			BTFSS	STATUS, Z
$02B1	$2AB5			GOTO	lcd_L_75
$02B2	$	lcd_L_73:
$02B2	$3094			MOVLW	148
$02B3	$00BD			MOVWF	FARG_Lcd_Out
$02B4	$2ABE			GOTO	lcd_L_66
$02B5	$	lcd_L_75:
;lcd.ppas,257 :: 		
$02B5	$	lcd_L_77:
$02B5	$083D			MOVF	FARG_Lcd_Out, 0
$02B6	$3A04			XORLW	4
$02B7	$1D03			BTFSS	STATUS, Z
$02B8	$2ABC			GOTO	lcd_L_78
$02B9	$	lcd_L_76:
$02B9	$30D4			MOVLW	212
$02BA	$00BD			MOVWF	FARG_Lcd_Out
;lcd.ppas,258 :: 		
$02BB	$2ABE			GOTO	lcd_L_66
$02BC	$	lcd_L_78:
$02BC	$3080			MOVLW	128
$02BD	$00BD			MOVWF	FARG_Lcd_Out
$02BE	$	lcd_L_66:
;lcd.ppas,260 :: 		
$02BE	$033E			DECF	FARG_Lcd_Out+1, 0
$02BF	$00F0			MOVWF	STACK_0
$02C0	$083D			MOVF	FARG_Lcd_Out, 0
$02C1	$07F0			ADDWF	STACK_0, 1
$02C2	$0870			MOVF	STACK_0, 0
$02C3	$00BD			MOVWF	FARG_Lcd_Out
;lcd.ppas,261 :: 		
$02C4	$0870			MOVF	STACK_0, 0
$02C5	$00CA			MOVWF	FARG_Lcd_Cmd
$02C6	$21F7			CALL	_lcd_cmd
;lcd.ppas,262 :: 		
$02C7	$01A8			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,263 :: 		
$02C8	$01C0			CLRF	_lcd_out_local_i, 1
;lcd.ppas,264 :: 		
$02C9	$	lcd_L_80:
$02C9	$0840			MOVF	_lcd_out_local_i, 0
$02CA	$073F			ADDWF	FARG_Lcd_Out+2, 0
$02CB	$0084			MOVWF	FSR
$02CC	$0800			MOVF	INDF, 0
$02CD	$00F2			MOVWF	STACK_2
$02CE	$0872			MOVF	STACK_2, 0
$02CF	$3A00			XORLW	0
$02D0	$1903			BTFSC	STATUS, Z
$02D1	$2ADA			GOTO	lcd_L_81
;lcd.ppas,266 :: 		
$02D2	$0840			MOVF	_lcd_out_local_i, 0
$02D3	$073F			ADDWF	FARG_Lcd_Out+2, 0
$02D4	$0084			MOVWF	FSR
$02D5	$0800			MOVF	INDF, 0
$02D6	$00C1			MOVWF	FARG_Lcd_Chr_CP
$02D7	$2304			CALL	_lcd_chr_cp
;lcd.ppas,267 :: 		
$02D8	$0AC0			INCF	_lcd_out_local_i, 1
;lcd.ppas,268 :: 		
$02D9	$2AC9			GOTO	lcd_L_80
$02DA	$	lcd_L_81:
;lcd.ppas,269 :: 		
$02DA	$3001			MOVLW	1
$02DB	$00A8			MOVWF	lcd_lcdcmd_status
$02DC	$	lcd_L_65:
;lcd.ppas,270 :: 		
$02DC	$0008			RETURN
$0123	$	_main:
;Exercice2.ppas,8 :: 		begin
;Exercice2.ppas,9 :: 		Lcd_Init(PORTB);
$0123	$3006			MOVLW	PORTB
$0124	$1303			BCF	STATUS, RP1
$0125	$1283			BCF	STATUS, RP0
$0126	$00BD			MOVWF	FARG_Lcd_Init
$0127	$22DD			CALL	_lcd_init
;Exercice2.ppas,10 :: 		Lcd_Cmd(LCD_CURSOR_OFF);
$0128	$300C			MOVLW	12
$0129	$00CA			MOVWF	FARG_Lcd_Cmd
$012A	$21F7			CALL	_lcd_cmd
;Exercice2.ppas,11 :: 		Lcd_Out(1,3,'SEM2 ISET NABEUL');
$012B	$3001			MOVLW	1
$012C	$00BD			MOVWF	FARG_Lcd_Out
$012D	$3003			MOVLW	3
$012E	$00BE			MOVWF	FARG_Lcd_Out+1
$012F	$3053			MOVLW	83
$0130	$00AA			MOVWF	?main_Local_Text+0
$0131	$3045			MOVLW	69
$0132	$00AB			MOVWF	?main_Local_Text+1
$0133	$304D			MOVLW	77
$0134	$00AC			MOVWF	?main_Local_Text+2
$0135	$3032			MOVLW	50
$0136	$00AD			MOVWF	?main_Local_Text+3
$0137	$3020			MOVLW	32
$0138	$00AE			MOVWF	?main_Local_Text+4
$0139	$3049			MOVLW	73
$013A	$00AF			MOVWF	?main_Local_Text+5
$013B	$3053			MOVLW	83
$013C	$00B0			MOVWF	?main_Local_Text+6
$013D	$3045			MOVLW	69
$013E	$00B1			MOVWF	?main_Local_Text+7
$013F	$3054			MOVLW	84
$0140	$00B2			MOVWF	?main_Local_Text+8
$0141	$3020			MOVLW	32
$0142	$00B3			MOVWF	?main_Local_Text+9
$0143	$304E			MOVLW	78
$0144	$00B4			MOVWF	?main_Local_Text+10
$0145	$3041			MOVLW	65
$0146	$00B5			MOVWF	?main_Local_Text+11
$0147	$3042			MOVLW	66
$0148	$00B6			MOVWF	?main_Local_Text+12
$0149	$3045			MOVLW	69
$014A	$00B7			MOVWF	?main_Local_Text+13
$014B	$3055			MOVLW	85
$014C	$00B8			MOVWF	?main_Local_Text+14
$014D	$304C			MOVLW	76
$014E	$00B9			MOVWF	?main_Local_Text+15
$014F	$01BA			CLRF	?main_Local_Text+16
$0150	$302A			MOVLW	?main_Local_Text
$0151	$00BF			MOVWF	FARG_Lcd_Out+2
$0152	$229E			CALL	_lcd_out
;Exercice2.ppas,12 :: 		Lcd_Out(2,2,'TP3 ARCH ET SYST 2');
$0153	$3002			MOVLW	2
$0154	$00BD			MOVWF	FARG_Lcd_Out
$0155	$3002			MOVLW	2
$0156	$00BE			MOVWF	FARG_Lcd_Out+1
$0157	$3054			MOVLW	84
$0158	$00AA			MOVWF	?main_Local_Text+0
$0159	$3050			MOVLW	80
$015A	$00AB			MOVWF	?main_Local_Text+1
$015B	$3033			MOVLW	51
$015C	$00AC			MOVWF	?main_Local_Text+2
$015D	$3020			MOVLW	32
$015E	$00AD			MOVWF	?main_Local_Text+3
$015F	$3041			MOVLW	65
$0160	$00AE			MOVWF	?main_Local_Text+4
$0161	$3052			MOVLW	82
$0162	$00AF			MOVWF	?main_Local_Text+5
$0163	$3043			MOVLW	67
$0164	$00B0			MOVWF	?main_Local_Text+6
$0165	$3048			MOVLW	72
$0166	$00B1			MOVWF	?main_Local_Text+7
$0167	$3020			MOVLW	32
$0168	$00B2			MOVWF	?main_Local_Text+8
$0169	$3045			MOVLW	69
$016A	$00B3			MOVWF	?main_Local_Text+9
$016B	$3054			MOVLW	84
$016C	$00B4			MOVWF	?main_Local_Text+10
$016D	$3020			MOVLW	32
$016E	$00B5			MOVWF	?main_Local_Text+11
$016F	$3053			MOVLW	83
$0170	$00B6			MOVWF	?main_Local_Text+12
$0171	$3059			MOVLW	89
$0172	$00B7			MOVWF	?main_Local_Text+13
$0173	$3053			MOVLW	83
$0174	$00B8			MOVWF	?main_Local_Text+14
$0175	$3054			MOVLW	84
$0176	$00B9			MOVWF	?main_Local_Text+15
$0177	$3020			MOVLW	32
$0178	$00BA			MOVWF	?main_Local_Text+16
$0179	$3032			MOVLW	50
$017A	$00BB			MOVWF	?main_Local_Text+17
$017B	$01BC			CLRF	?main_Local_Text+18
$017C	$302A			MOVLW	?main_Local_Text
$017D	$00BF			MOVWF	FARG_Lcd_Out+2
$017E	$229E			CALL	_lcd_out
;Exercice2.ppas,14 :: 		delay_ms(2000);
$017F	$3015			MOVLW	21
$0180	$00FC			MOVWF	STACK_12
$0181	$30FF			MOVLW	255
$0182	$00FB			MOVWF	STACK_11
$0183	$30FF			MOVLW	255
$0184	$00FA			MOVWF	STACK_10
$0185	$0BFC			DECFSZ	STACK_12, F
$0186	$2988			GOTO	$+2
$0187	$298F			GOTO	$+8
$0188	$0BFB			DECFSZ	STACK_11, F
$0189	$298B			GOTO	$+2
$018A	$298E			GOTO	$+4
$018B	$0BFA			DECFSZ	STACK_10, F
$018C	$298B			GOTO	$-1
$018D	$2988			GOTO	$-5
$018E	$2985			GOTO	$-9
$018F	$3066			MOVLW	102
$0190	$00FB			MOVWF	STACK_11
$0191	$30FF			MOVLW	255
$0192	$00FA			MOVWF	STACK_10
$0193	$0BFB			DECFSZ	STACK_11, F
$0194	$2996			GOTO	$+2
$0195	$2999			GOTO	$+4
$0196	$0BFA			DECFSZ	STACK_10, F
$0197	$2996			GOTO	$-1
$0198	$2993			GOTO	$-5
$0199	$3012			MOVLW	18
$019A	$00FA			MOVWF	STACK_10
$019B	$0BFA			DECFSZ	STACK_10, F
$019C	$299B			GOTO	$-1
$019D	$0000			NOP
$019E	$0000			NOP
;Exercice2.ppas,16 :: 		Lcd_Cmd(LCD_clear);
$019F	$3001			MOVLW	1
$01A0	$00CA			MOVWF	FARG_Lcd_Cmd
$01A1	$21F7			CALL	_lcd_cmd
;Exercice2.ppas,17 :: 		while(1) do
$01A2	$	Exercice2_L_3:
;Exercice2.ppas,19 :: 		if(PORTC.1=0) then
$01A2	$0807			MOVF	PORTC, 0
$01A3	$00F1			MOVWF	STACK_1
$01A4	$3000			MOVLW	0
$01A5	$18F1			BTFSC	STACK_1, 1
$01A6	$3001			MOVLW	1
$01A7	$00F1			MOVWF	STACK_1
$01A8	$0871			MOVF	STACK_1, 0
$01A9	$3A00			XORLW	0
$01AA	$1D03			BTFSS	STATUS, Z
$01AB	$29D1			GOTO	Exercice2_L_8
$01AC	$	Exercice2_L_7:
;Exercice2.ppas,21 :: 		Lcd_Out(1,4,'ACCES INTERDIT');
$01AC	$3001			MOVLW	1
$01AD	$00BD			MOVWF	FARG_Lcd_Out
$01AE	$3004			MOVLW	4
$01AF	$00BE			MOVWF	FARG_Lcd_Out+1
$01B0	$3041			MOVLW	65
$01B1	$00AA			MOVWF	?main_Local_Text+0
$01B2	$3043			MOVLW	67
$01B3	$00AB			MOVWF	?main_Local_Text+1
$01B4	$3043			MOVLW	67
$01B5	$00AC			MOVWF	?main_Local_Text+2
$01B6	$3045			MOVLW	69
$01B7	$00AD			MOVWF	?main_Local_Text+3
$01B8	$3053			MOVLW	83
$01B9	$00AE			MOVWF	?main_Local_Text+4
$01BA	$3020			MOVLW	32
$01BB	$00AF			MOVWF	?main_Local_Text+5
$01BC	$3049			MOVLW	73
$01BD	$00B0			MOVWF	?main_Local_Text+6
$01BE	$304E			MOVLW	78
$01BF	$00B1			MOVWF	?main_Local_Text+7
$01C0	$3054			MOVLW	84
$01C1	$00B2			MOVWF	?main_Local_Text+8
$01C2	$3045			MOVLW	69
$01C3	$00B3			MOVWF	?main_Local_Text+9
$01C4	$3052			MOVLW	82
$01C5	$00B4			MOVWF	?main_Local_Text+10
$01C6	$3044			MOVLW	68
$01C7	$00B5			MOVWF	?main_Local_Text+11
$01C8	$3049			MOVLW	73
$01C9	$00B6			MOVWF	?main_Local_Text+12
$01CA	$3054			MOVLW	84
$01CB	$00B7			MOVWF	?main_Local_Text+13
$01CC	$01B8			CLRF	?main_Local_Text+14
$01CD	$302A			MOVLW	?main_Local_Text
$01CE	$00BF			MOVWF	FARG_Lcd_Out+2
$01CF	$229E			CALL	_lcd_out
;Exercice2.ppas,22 :: 		end
$01D0	$29F5			GOTO	Exercice2_L_9
;Exercice2.ppas,23 :: 		else
$01D1	$	Exercice2_L_8:
;Exercice2.ppas,24 :: 		Lcd_Out(1,4,'ACCES AUTORISE');
$01D1	$3001			MOVLW	1
$01D2	$00BD			MOVWF	FARG_Lcd_Out
$01D3	$3004			MOVLW	4
$01D4	$00BE			MOVWF	FARG_Lcd_Out+1
$01D5	$3041			MOVLW	65
$01D6	$00AA			MOVWF	?main_Local_Text+0
$01D7	$3043			MOVLW	67
$01D8	$00AB			MOVWF	?main_Local_Text+1
$01D9	$3043			MOVLW	67
$01DA	$00AC			MOVWF	?main_Local_Text+2
$01DB	$3045			MOVLW	69
$01DC	$00AD			MOVWF	?main_Local_Text+3
$01DD	$3053			MOVLW	83
$01DE	$00AE			MOVWF	?main_Local_Text+4
$01DF	$3020			MOVLW	32
$01E0	$00AF			MOVWF	?main_Local_Text+5
$01E1	$3041			MOVLW	65
$01E2	$00B0			MOVWF	?main_Local_Text+6
$01E3	$3055			MOVLW	85
$01E4	$00B1			MOVWF	?main_Local_Text+7
$01E5	$3054			MOVLW	84
$01E6	$00B2			MOVWF	?main_Local_Text+8
$01E7	$304F			MOVLW	79
$01E8	$00B3			MOVWF	?main_Local_Text+9
$01E9	$3052			MOVLW	82
$01EA	$00B4			MOVWF	?main_Local_Text+10
$01EB	$3049			MOVLW	73
$01EC	$00B5			MOVWF	?main_Local_Text+11
$01ED	$3053			MOVLW	83
$01EE	$00B6			MOVWF	?main_Local_Text+12
$01EF	$3045			MOVLW	69
$01F0	$00B7			MOVWF	?main_Local_Text+13
$01F1	$01B8			CLRF	?main_Local_Text+14
$01F2	$302A			MOVLW	?main_Local_Text
$01F3	$00BF			MOVWF	FARG_Lcd_Out+2
$01F4	$229E			CALL	_lcd_out
$01F5	$	Exercice2_L_9:
;Exercice2.ppas,25 :: 		end
$01F5	$29A2			GOTO	Exercice2_L_3
;Exercice2.ppas,28 :: 		end.
$01F6	$29F6			GOTO	$
