;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 3/30/2021 9:39:13 AM
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$29CA			GOTO	_main
$02C6	$	_delay_1us:
;delays.ppas,11 :: 		begin
;delays.ppas,12 :: 		Delay_us(1);
$02C6	$0000			NOP
$02C7	$0000			NOP
$02C8	$	delays_L_1:
;delays.ppas,13 :: 		end;
$02C8	$0008			RETURN
$029C	$	_delay_5500us:
;delays.ppas,41 :: 		begin
;delays.ppas,42 :: 		Delay_us(5500);
$029C	$300F			MOVLW	15
$029D	$1303			BCF	STATUS, RP1
$029E	$1283			BCF	STATUS, RP0
$029F	$00FB			MOVWF	STACK_11
$02A0	$30FF			MOVLW	255
$02A1	$00FA			MOVWF	STACK_10
$02A2	$0BFB			DECFSZ	STACK_11, F
$02A3	$2AA5			GOTO	$+2
$02A4	$2AA8			GOTO	$+4
$02A5	$0BFA			DECFSZ	STACK_10, F
$02A6	$2AA5			GOTO	$-1
$02A7	$2AA2			GOTO	$-5
$02A8	$303E			MOVLW	62
$02A9	$00FA			MOVWF	STACK_10
$02AA	$0BFA			DECFSZ	STACK_10, F
$02AB	$2AAA			GOTO	$-1
$02AC	$0000			NOP
$02AD	$	delays_L_7:
;delays.ppas,43 :: 		end;
$02AD	$0008			RETURN
$02BF	$	_delay_50us:
;delays.ppas,26 :: 		begin
;delays.ppas,27 :: 		Delay_us(50);
$02BF	$3021			MOVLW	33
$02C0	$1303			BCF	STATUS, RP1
$02C1	$1283			BCF	STATUS, RP0
$02C2	$00FA			MOVWF	STACK_10
$02C3	$0BFA			DECFSZ	STACK_10, F
$02C4	$2AC3			GOTO	$-1
$02C5	$	delays_L_4:
;delays.ppas,28 :: 		end;
$02C5	$0008			RETURN
$0123	$	_lcd_cmd:
;lcd.ppas,19 :: 		
;lcd.ppas,20 :: 		
$0123	$1303			BCF	STATUS, RP1
$0124	$1283			BCF	STATUS, RP0
$0125	$0820			MOVF	lcd_ctrlport_address, 0
$0126	$0084			MOVWF	FSR
;lcd.ppas,22 :: 		
$0127	$0921			COMF	lcd____menable, W
$0128	$00F0			MOVWF	STACK_0
$0129	$0870			MOVF	STACK_0, 0
$012A	$0580			ANDWF	INDF, 1
;lcd.ppas,23 :: 		
$012B	$0922			COMF	lcd____mrs, W
$012C	$00F0			MOVWF	STACK_0
$012D	$0870			MOVF	STACK_0, 0
$012E	$0580			ANDWF	INDF, 1
;lcd.ppas,25 :: 		
$012F	$0823			MOVF	lcd_dataport_address, 0
$0130	$0084			MOVWF	FSR
;lcd.ppas,26 :: 		
$0131	$0825			MOVF	lcd____mdb6, 0
$0132	$0424			IORWF	lcd____mdb7, 0
$0133	$00F0			MOVWF	STACK_0
$0134	$0826			MOVF	lcd____mdb5, 0
$0135	$04F0			IORWF	STACK_0, 1
$0136	$0827			MOVF	lcd____mdb4, 0
$0137	$04F0			IORWF	STACK_0, 1
$0138	$09F0			COMF	STACK_0, F
$0139	$0870			MOVF	STACK_0, 0
$013A	$0580			ANDWF	INDF, 1
;lcd.ppas,28 :: 		
$013B	$3000			MOVLW	0
$013C	$1BCA			BTFSC	FARG_Lcd_Cmd, 7
$013D	$3001			MOVLW	1
$013E	$00F1			MOVWF	STACK_1
$013F	$0871			MOVF	STACK_1, 0
$0140	$3A01			XORLW	1
$0141	$1D03			BTFSS	STATUS, Z
$0142	$2945			GOTO	lcd_L_2
$0143	$	lcd_L_1:
;lcd.ppas,29 :: 		
$0143	$0824			MOVF	lcd____mdb7, 0
$0144	$0480			IORWF	INDF, 1
$0145	$	lcd_L_2:
$0145	$	lcd_L_3:
;lcd.ppas,30 :: 		
$0145	$3000			MOVLW	0
$0146	$1B4A			BTFSC	FARG_Lcd_Cmd, 6
$0147	$3001			MOVLW	1
$0148	$00F1			MOVWF	STACK_1
$0149	$0871			MOVF	STACK_1, 0
$014A	$3A01			XORLW	1
$014B	$1D03			BTFSS	STATUS, Z
$014C	$294F			GOTO	lcd_L_5
$014D	$	lcd_L_4:
;lcd.ppas,31 :: 		
$014D	$0825			MOVF	lcd____mdb6, 0
$014E	$0480			IORWF	INDF, 1
$014F	$	lcd_L_5:
$014F	$	lcd_L_6:
;lcd.ppas,32 :: 		
$014F	$3000			MOVLW	0
$0150	$1ACA			BTFSC	FARG_Lcd_Cmd, 5
$0151	$3001			MOVLW	1
$0152	$00F1			MOVWF	STACK_1
$0153	$0871			MOVF	STACK_1, 0
$0154	$3A01			XORLW	1
$0155	$1D03			BTFSS	STATUS, Z
$0156	$2959			GOTO	lcd_L_8
$0157	$	lcd_L_7:
;lcd.ppas,33 :: 		
$0157	$0826			MOVF	lcd____mdb5, 0
$0158	$0480			IORWF	INDF, 1
$0159	$	lcd_L_8:
$0159	$	lcd_L_9:
;lcd.ppas,34 :: 		
$0159	$3000			MOVLW	0
$015A	$1A4A			BTFSC	FARG_Lcd_Cmd, 4
$015B	$3001			MOVLW	1
$015C	$00F1			MOVWF	STACK_1
$015D	$0871			MOVF	STACK_1, 0
$015E	$3A01			XORLW	1
$015F	$1D03			BTFSS	STATUS, Z
$0160	$2963			GOTO	lcd_L_11
$0161	$	lcd_L_10:
;lcd.ppas,35 :: 		
$0161	$0827			MOVF	lcd____mdb4, 0
$0162	$0480			IORWF	INDF, 1
$0163	$	lcd_L_11:
$0163	$	lcd_L_12:
;lcd.ppas,37 :: 		
$0163	$0820			MOVF	lcd_ctrlport_address, 0
$0164	$0084			MOVWF	FSR
;lcd.ppas,38 :: 		
$0165	$0828			MOVF	lcd_lcdcmd_status, 0
$0166	$3A01			XORLW	1
$0167	$1D03			BTFSS	STATUS, Z
$0168	$296E			GOTO	lcd_L_14
$0169	$	lcd_L_13:
;lcd.ppas,39 :: 		
$0169	$0922			COMF	lcd____mrs, W
$016A	$00F0			MOVWF	STACK_0
$016B	$0870			MOVF	STACK_0, 0
$016C	$0580			ANDWF	INDF, 1
$016D	$2970			GOTO	lcd_L_15
;lcd.ppas,40 :: 		
$016E	$	lcd_L_14:
;lcd.ppas,41 :: 		
$016E	$0822			MOVF	lcd____mrs, 0
$016F	$0480			IORWF	INDF, 1
$0170	$	lcd_L_15:
;lcd.ppas,43 :: 		
$0170	$0821			MOVF	lcd____menable, 0
$0171	$0480			IORWF	INDF, 1
;lcd.ppas,44 :: 		
$0172	$22C6			CALL	_delay_1us
;lcd.ppas,45 :: 		
$0173	$0921			COMF	lcd____menable, W
$0174	$00F0			MOVWF	STACK_0
$0175	$0870			MOVF	STACK_0, 0
$0176	$0580			ANDWF	INDF, 1
;lcd.ppas,47 :: 		
$0177	$0922			COMF	lcd____mrs, W
$0178	$00F0			MOVWF	STACK_0
$0179	$0870			MOVF	STACK_0, 0
$017A	$0580			ANDWF	INDF, 1
;lcd.ppas,49 :: 		
$017B	$0823			MOVF	lcd_dataport_address, 0
$017C	$0084			MOVWF	FSR
;lcd.ppas,50 :: 		
$017D	$0825			MOVF	lcd____mdb6, 0
$017E	$0424			IORWF	lcd____mdb7, 0
$017F	$00F0			MOVWF	STACK_0
$0180	$0826			MOVF	lcd____mdb5, 0
$0181	$04F0			IORWF	STACK_0, 1
$0182	$0827			MOVF	lcd____mdb4, 0
$0183	$04F0			IORWF	STACK_0, 1
$0184	$09F0			COMF	STACK_0, F
$0185	$0870			MOVF	STACK_0, 0
$0186	$0580			ANDWF	INDF, 1
;lcd.ppas,52 :: 		
$0187	$3000			MOVLW	0
$0188	$19CA			BTFSC	FARG_Lcd_Cmd, 3
$0189	$3001			MOVLW	1
$018A	$00F1			MOVWF	STACK_1
$018B	$0871			MOVF	STACK_1, 0
$018C	$3A01			XORLW	1
$018D	$1D03			BTFSS	STATUS, Z
$018E	$2991			GOTO	lcd_L_17
$018F	$	lcd_L_16:
;lcd.ppas,53 :: 		
$018F	$0824			MOVF	lcd____mdb7, 0
$0190	$0480			IORWF	INDF, 1
$0191	$	lcd_L_17:
$0191	$	lcd_L_18:
;lcd.ppas,54 :: 		
$0191	$3000			MOVLW	0
$0192	$194A			BTFSC	FARG_Lcd_Cmd, 2
$0193	$3001			MOVLW	1
$0194	$00F1			MOVWF	STACK_1
$0195	$0871			MOVF	STACK_1, 0
$0196	$3A01			XORLW	1
$0197	$1D03			BTFSS	STATUS, Z
$0198	$299B			GOTO	lcd_L_20
$0199	$	lcd_L_19:
;lcd.ppas,55 :: 		
$0199	$0825			MOVF	lcd____mdb6, 0
$019A	$0480			IORWF	INDF, 1
$019B	$	lcd_L_20:
$019B	$	lcd_L_21:
;lcd.ppas,56 :: 		
$019B	$3000			MOVLW	0
$019C	$18CA			BTFSC	FARG_Lcd_Cmd, 1
$019D	$3001			MOVLW	1
$019E	$00F1			MOVWF	STACK_1
$019F	$0871			MOVF	STACK_1, 0
$01A0	$3A01			XORLW	1
$01A1	$1D03			BTFSS	STATUS, Z
$01A2	$29A5			GOTO	lcd_L_23
$01A3	$	lcd_L_22:
;lcd.ppas,57 :: 		
$01A3	$0826			MOVF	lcd____mdb5, 0
$01A4	$0480			IORWF	INDF, 1
$01A5	$	lcd_L_23:
$01A5	$	lcd_L_24:
;lcd.ppas,58 :: 		
$01A5	$3001			MOVLW	1
$01A6	$054A			ANDWF	FARG_Lcd_Cmd, 0
$01A7	$00F1			MOVWF	STACK_1
$01A8	$0871			MOVF	STACK_1, 0
$01A9	$3A01			XORLW	1
$01AA	$1D03			BTFSS	STATUS, Z
$01AB	$29AE			GOTO	lcd_L_26
$01AC	$	lcd_L_25:
;lcd.ppas,59 :: 		
$01AC	$0827			MOVF	lcd____mdb4, 0
$01AD	$0480			IORWF	INDF, 1
$01AE	$	lcd_L_26:
$01AE	$	lcd_L_27:
;lcd.ppas,61 :: 		
$01AE	$0820			MOVF	lcd_ctrlport_address, 0
$01AF	$0084			MOVWF	FSR
;lcd.ppas,62 :: 		
$01B0	$0828			MOVF	lcd_lcdcmd_status, 0
$01B1	$3A01			XORLW	1
$01B2	$1D03			BTFSS	STATUS, Z
$01B3	$29B9			GOTO	lcd_L_29
$01B4	$	lcd_L_28:
;lcd.ppas,63 :: 		
$01B4	$0922			COMF	lcd____mrs, W
$01B5	$00F0			MOVWF	STACK_0
$01B6	$0870			MOVF	STACK_0, 0
$01B7	$0580			ANDWF	INDF, 1
$01B8	$29BB			GOTO	lcd_L_30
;lcd.ppas,64 :: 		
$01B9	$	lcd_L_29:
;lcd.ppas,65 :: 		
$01B9	$0822			MOVF	lcd____mrs, 0
$01BA	$0480			IORWF	INDF, 1
$01BB	$	lcd_L_30:
;lcd.ppas,67 :: 		
$01BB	$0821			MOVF	lcd____menable, 0
$01BC	$0480			IORWF	INDF, 1
;lcd.ppas,68 :: 		
$01BD	$22C6			CALL	_delay_1us
;lcd.ppas,69 :: 		
$01BE	$0921			COMF	lcd____menable, W
$01BF	$00F0			MOVWF	STACK_0
$01C0	$0870			MOVF	STACK_0, 0
$01C1	$0580			ANDWF	INDF, 1
;lcd.ppas,71 :: 		
$01C2	$0828			MOVF	lcd_lcdcmd_status, 0
$01C3	$3A01			XORLW	1
$01C4	$1D03			BTFSS	STATUS, Z
$01C5	$29C8			GOTO	lcd_L_32
$01C6	$	lcd_L_31:
;lcd.ppas,72 :: 		
$01C6	$229C			CALL	_delay_5500us
$01C7	$29C9			GOTO	lcd_L_33
;lcd.ppas,73 :: 		
$01C8	$	lcd_L_32:
;lcd.ppas,74 :: 		
$01C8	$22BF			CALL	_delay_50us
$01C9	$	lcd_L_33:
$01C9	$	lcd_L_0:
;lcd.ppas,75 :: 		
$01C9	$0008			RETURN
$0004	$	_lcd_config:
;lcd.ppas,115 :: 		
;lcd.ppas,116 :: 		
$0004	$229C			CALL	_delay_5500us
;lcd.ppas,117 :: 		
$0005	$229C			CALL	_delay_5500us
;lcd.ppas,118 :: 		
$0006	$229C			CALL	_delay_5500us
;lcd.ppas,120 :: 		
$0007	$0842			MOVF	FARG_Lcd_Config+1, 0
$0008	$00F0			MOVWF	STACK_0
$0009	$3001			MOVLW	1
$000A	$00F4			MOVWF	STACK_4
$000B	$0870			MOVF	STACK_0, 0
$000C	$	L_Lcd_Config_0:
$000C	$1903			BTFSC	STATUS, Z
$000D	$2812			GOTO	L_Lcd_Config_1
$000E	$0DF4			RLF	STACK_4, 1
$000F	$1074			BCF	STACK_4, 0
$0010	$3FFF			ADDLW	255
$0011	$280C			GOTO	L_Lcd_Config_0
$0012	$	L_Lcd_Config_1:
$0012	$0874			MOVF	STACK_4, 0
$0013	$00A4			MOVWF	lcd____mdb7
;lcd.ppas,121 :: 		
$0014	$0843			MOVF	FARG_Lcd_Config+2, 0
$0015	$00F0			MOVWF	STACK_0
$0016	$3001			MOVLW	1
$0017	$00F3			MOVWF	STACK_3
$0018	$0870			MOVF	STACK_0, 0
$0019	$	L_Lcd_Config_2:
$0019	$1903			BTFSC	STATUS, Z
$001A	$281F			GOTO	L_Lcd_Config_3
$001B	$0DF3			RLF	STACK_3, 1
$001C	$1073			BCF	STACK_3, 0
$001D	$3FFF			ADDLW	255
$001E	$2819			GOTO	L_Lcd_Config_2
$001F	$	L_Lcd_Config_3:
$001F	$0873			MOVF	STACK_3, 0
$0020	$00A5			MOVWF	lcd____mdb6
;lcd.ppas,122 :: 		
$0021	$0844			MOVF	FARG_Lcd_Config+3, 0
$0022	$00F0			MOVWF	STACK_0
$0023	$3001			MOVLW	1
$0024	$00F2			MOVWF	STACK_2
$0025	$0870			MOVF	STACK_0, 0
$0026	$	L_Lcd_Config_4:
$0026	$1903			BTFSC	STATUS, Z
$0027	$282C			GOTO	L_Lcd_Config_5
$0028	$0DF2			RLF	STACK_2, 1
$0029	$1072			BCF	STACK_2, 0
$002A	$3FFF			ADDLW	255
$002B	$2826			GOTO	L_Lcd_Config_4
$002C	$	L_Lcd_Config_5:
$002C	$0872			MOVF	STACK_2, 0
$002D	$00A6			MOVWF	lcd____mdb5
;lcd.ppas,123 :: 		
$002E	$0845			MOVF	FARG_Lcd_Config+4, 0
$002F	$00F0			MOVWF	STACK_0
$0030	$3001			MOVLW	1
$0031	$00F1			MOVWF	STACK_1
$0032	$0870			MOVF	STACK_0, 0
$0033	$	L_Lcd_Config_6:
$0033	$1903			BTFSC	STATUS, Z
$0034	$2839			GOTO	L_Lcd_Config_7
$0035	$0DF1			RLF	STACK_1, 1
$0036	$1071			BCF	STACK_1, 0
$0037	$3FFF			ADDLW	255
$0038	$2833			GOTO	L_Lcd_Config_6
$0039	$	L_Lcd_Config_7:
$0039	$0871			MOVF	STACK_1, 0
$003A	$00A7			MOVWF	lcd____mdb4
;lcd.ppas,124 :: 		
$003B	$0847			MOVF	FARG_Lcd_Config+6, 0
$003C	$00F0			MOVWF	STACK_0
$003D	$3001			MOVLW	1
$003E	$00A2			MOVWF	lcd____mrs
$003F	$0870			MOVF	STACK_0, 0
$0040	$	L_Lcd_Config_8:
$0040	$1903			BTFSC	STATUS, Z
$0041	$2846			GOTO	L_Lcd_Config_9
$0042	$0DA2			RLF	lcd____mrs, 1
$0043	$1022			BCF	lcd____mrs, 0
$0044	$3FFF			ADDLW	255
$0045	$2840			GOTO	L_Lcd_Config_8
$0046	$	L_Lcd_Config_9:
;lcd.ppas,125 :: 		
$0046	$0848			MOVF	FARG_Lcd_Config+7, 0
$0047	$00F0			MOVWF	STACK_0
$0048	$3001			MOVLW	1
$0049	$00A9			MOVWF	lcd____mrw
$004A	$0870			MOVF	STACK_0, 0
$004B	$	L_Lcd_Config_10:
$004B	$1903			BTFSC	STATUS, Z
$004C	$2851			GOTO	L_Lcd_Config_11
$004D	$0DA9			RLF	lcd____mrw, 1
$004E	$1029			BCF	lcd____mrw, 0
$004F	$3FFF			ADDLW	255
$0050	$284B			GOTO	L_Lcd_Config_10
$0051	$	L_Lcd_Config_11:
;lcd.ppas,126 :: 		
$0051	$0849			MOVF	FARG_Lcd_Config+8, 0
$0052	$00F0			MOVWF	STACK_0
$0053	$3001			MOVLW	1
$0054	$00A1			MOVWF	lcd____menable
$0055	$0870			MOVF	STACK_0, 0
$0056	$	L_Lcd_Config_12:
$0056	$1903			BTFSC	STATUS, Z
$0057	$285C			GOTO	L_Lcd_Config_13
$0058	$0DA1			RLF	lcd____menable, 1
$0059	$1021			BCF	lcd____menable, 0
$005A	$3FFF			ADDLW	255
$005B	$2856			GOTO	L_Lcd_Config_12
$005C	$	L_Lcd_Config_13:
;lcd.ppas,128 :: 		
$005C	$0841			MOVF	FARG_Lcd_Config, 0
$005D	$00A3			MOVWF	lcd_dataport_address
;lcd.ppas,129 :: 		
$005E	$0846			MOVF	FARG_Lcd_Config+5, 0
$005F	$00A0			MOVWF	lcd_ctrlport_address
;lcd.ppas,131 :: 		
$0060	$0841			MOVF	FARG_Lcd_Config, 0
$0061	$0084			MOVWF	FSR
;lcd.ppas,133 :: 		
$0062	$0873			MOVF	STACK_3, 0
$0063	$0474			IORWF	STACK_4, 0
$0064	$00F0			MOVWF	STACK_0
$0065	$0872			MOVF	STACK_2, 0
$0066	$04F0			IORWF	STACK_0, 1
$0067	$0871			MOVF	STACK_1, 0
$0068	$04F0			IORWF	STACK_0, 1
$0069	$09F0			COMF	STACK_0, F
$006A	$0870			MOVF	STACK_0, 0
$006B	$0580			ANDWF	INDF, 1
;lcd.ppas,134 :: 		
$006C	$	lcd_L_56:
$006C	$1784			BSF	FSR, 7
$006D	$	lcd_L_57:
;lcd.ppas,135 :: 		
$006D	$0825			MOVF	lcd____mdb6, 0
$006E	$0424			IORWF	lcd____mdb7, 0
$006F	$00F0			MOVWF	STACK_0
$0070	$0826			MOVF	lcd____mdb5, 0
$0071	$04F0			IORWF	STACK_0, 1
$0072	$0827			MOVF	lcd____mdb4, 0
$0073	$04F0			IORWF	STACK_0, 1
$0074	$09F0			COMF	STACK_0, F
$0075	$0870			MOVF	STACK_0, 0
$0076	$0580			ANDWF	INDF, 1
;lcd.ppas,136 :: 		
$0077	$1384			BCF	FSR, 7
$0078	$	lcd_L_59:
;lcd.ppas,139 :: 		
$0078	$0820			MOVF	lcd_ctrlport_address, 0
$0079	$0084			MOVWF	FSR
;lcd.ppas,141 :: 		
$007A	$0829			MOVF	lcd____mrw, 0
$007B	$0422			IORWF	lcd____mrs, 0
$007C	$00F0			MOVWF	STACK_0
$007D	$0821			MOVF	lcd____menable, 0
$007E	$04F0			IORWF	STACK_0, 1
$007F	$09F0			COMF	STACK_0, F
$0080	$0870			MOVF	STACK_0, 0
$0081	$0580			ANDWF	INDF, 1
;lcd.ppas,142 :: 		
$0082	$	lcd_L_60:
$0082	$1784			BSF	FSR, 7
$0083	$	lcd_L_61:
;lcd.ppas,143 :: 		
$0083	$0829			MOVF	lcd____mrw, 0
$0084	$0422			IORWF	lcd____mrs, 0
$0085	$00F0			MOVWF	STACK_0
$0086	$0821			MOVF	lcd____menable, 0
$0087	$04F0			IORWF	STACK_0, 1
$0088	$09F0			COMF	STACK_0, F
$0089	$0870			MOVF	STACK_0, 0
$008A	$0580			ANDWF	INDF, 1
;lcd.ppas,144 :: 		
$008B	$1384			BCF	FSR, 7
$008C	$	lcd_L_63:
;lcd.ppas,148 :: 		
$008C	$0823			MOVF	lcd_dataport_address, 0
$008D	$0084			MOVWF	FSR
;lcd.ppas,149 :: 		
$008E	$0826			MOVF	lcd____mdb5, 0
$008F	$0400			IORWF	INDF, 0
$0090	$00F0			MOVWF	STACK_0
$0091	$0827			MOVF	lcd____mdb4, 0
$0092	$0470			IORWF	STACK_0, 0
$0093	$0080			MOVWF	INDF
;lcd.ppas,151 :: 		
$0094	$0820			MOVF	lcd_ctrlport_address, 0
$0095	$0084			MOVWF	FSR
;lcd.ppas,152 :: 		
$0096	$0821			MOVF	lcd____menable, 0
$0097	$0480			IORWF	INDF, 1
;lcd.ppas,153 :: 		
$0098	$0921			COMF	lcd____menable, W
$0099	$00F0			MOVWF	STACK_0
$009A	$0870			MOVF	STACK_0, 0
$009B	$0580			ANDWF	INDF, 1
;lcd.ppas,155 :: 		
$009C	$229C			CALL	_delay_5500us
;lcd.ppas,160 :: 		
$009D	$0821			MOVF	lcd____menable, 0
$009E	$0480			IORWF	INDF, 1
;lcd.ppas,161 :: 		
$009F	$0921			COMF	lcd____menable, W
$00A0	$00F0			MOVWF	STACK_0
$00A1	$0870			MOVF	STACK_0, 0
$00A2	$0580			ANDWF	INDF, 1
;lcd.ppas,163 :: 		
$00A3	$229C			CALL	_delay_5500us
;lcd.ppas,168 :: 		
$00A4	$0821			MOVF	lcd____menable, 0
$00A5	$0480			IORWF	INDF, 1
;lcd.ppas,169 :: 		
$00A6	$0921			COMF	lcd____menable, W
$00A7	$00F0			MOVWF	STACK_0
$00A8	$0870			MOVF	STACK_0, 0
$00A9	$0580			ANDWF	INDF, 1
;lcd.ppas,171 :: 		
$00AA	$229C			CALL	_delay_5500us
;lcd.ppas,174 :: 		
$00AB	$0823			MOVF	lcd_dataport_address, 0
$00AC	$0084			MOVWF	FSR
;lcd.ppas,175 :: 		
$00AD	$0826			MOVF	lcd____mdb5, 0
$00AE	$0480			IORWF	INDF, 1
;lcd.ppas,176 :: 		
$00AF	$0927			COMF	lcd____mdb4, W
$00B0	$00F0			MOVWF	STACK_0
$00B1	$0870			MOVF	STACK_0, 0
$00B2	$0580			ANDWF	INDF, 1
;lcd.ppas,178 :: 		
$00B3	$0820			MOVF	lcd_ctrlport_address, 0
$00B4	$0084			MOVWF	FSR
;lcd.ppas,179 :: 		
$00B5	$0821			MOVF	lcd____menable, 0
$00B6	$0480			IORWF	INDF, 1
;lcd.ppas,180 :: 		
$00B7	$0921			COMF	lcd____menable, W
$00B8	$00F0			MOVWF	STACK_0
$00B9	$0870			MOVF	STACK_0, 0
$00BA	$0580			ANDWF	INDF, 1
;lcd.ppas,182 :: 		
$00BB	$229C			CALL	_delay_5500us
;lcd.ppas,187 :: 		
$00BC	$0821			MOVF	lcd____menable, 0
$00BD	$0480			IORWF	INDF, 1
;lcd.ppas,188 :: 		
$00BE	$0921			COMF	lcd____menable, W
$00BF	$00F1			MOVWF	STACK_1
$00C0	$0871			MOVF	STACK_1, 0
$00C1	$0580			ANDWF	INDF, 1
;lcd.ppas,190 :: 		
$00C2	$0823			MOVF	lcd_dataport_address, 0
$00C3	$0084			MOVWF	FSR
;lcd.ppas,191 :: 		
$00C4	$0926			COMF	lcd____mdb5, W
$00C5	$00F0			MOVWF	STACK_0
$00C6	$0870			MOVF	STACK_0, 0
$00C7	$0580			ANDWF	INDF, 1
;lcd.ppas,192 :: 		
$00C8	$0824			MOVF	lcd____mdb7, 0
$00C9	$0480			IORWF	INDF, 1
;lcd.ppas,194 :: 		
$00CA	$0820			MOVF	lcd_ctrlport_address, 0
$00CB	$0084			MOVWF	FSR
;lcd.ppas,195 :: 		
$00CC	$0821			MOVF	lcd____menable, 0
$00CD	$0480			IORWF	INDF, 1
;lcd.ppas,196 :: 		
$00CE	$0871			MOVF	STACK_1, 0
$00CF	$0580			ANDWF	INDF, 1
;lcd.ppas,198 :: 		
$00D0	$229C			CALL	_delay_5500us
;lcd.ppas,201 :: 		
$00D1	$0823			MOVF	lcd_dataport_address, 0
$00D2	$0084			MOVWF	FSR
;lcd.ppas,202 :: 		
$00D3	$0924			COMF	lcd____mdb7, W
$00D4	$00F0			MOVWF	STACK_0
$00D5	$0870			MOVF	STACK_0, 0
$00D6	$0580			ANDWF	INDF, 1
;lcd.ppas,203 :: 		
$00D7	$0827			MOVF	lcd____mdb4, 0
$00D8	$0480			IORWF	INDF, 1
;lcd.ppas,204 :: 		
$00D9	$0820			MOVF	lcd_ctrlport_address, 0
$00DA	$0084			MOVWF	FSR
;lcd.ppas,205 :: 		
$00DB	$0821			MOVF	lcd____menable, 0
$00DC	$0480			IORWF	INDF, 1
;lcd.ppas,206 :: 		
$00DD	$0921			COMF	lcd____menable, W
$00DE	$00F1			MOVWF	STACK_1
$00DF	$0871			MOVF	STACK_1, 0
$00E0	$0580			ANDWF	INDF, 1
;lcd.ppas,207 :: 		
$00E1	$0823			MOVF	lcd_dataport_address, 0
$00E2	$0084			MOVWF	FSR
;lcd.ppas,208 :: 		
$00E3	$0927			COMF	lcd____mdb4, W
$00E4	$00F0			MOVWF	STACK_0
$00E5	$0870			MOVF	STACK_0, 0
$00E6	$0580			ANDWF	INDF, 1
;lcd.ppas,209 :: 		
$00E7	$0820			MOVF	lcd_ctrlport_address, 0
$00E8	$0084			MOVWF	FSR
;lcd.ppas,210 :: 		
$00E9	$0821			MOVF	lcd____menable, 0
$00EA	$0480			IORWF	INDF, 1
;lcd.ppas,211 :: 		
$00EB	$0871			MOVF	STACK_1, 0
$00EC	$0580			ANDWF	INDF, 1
;lcd.ppas,213 :: 		
$00ED	$229C			CALL	_delay_5500us
;lcd.ppas,218 :: 		
$00EE	$0821			MOVF	lcd____menable, 0
$00EF	$0480			IORWF	INDF, 1
;lcd.ppas,219 :: 		
$00F0	$0921			COMF	lcd____menable, W
$00F1	$00F0			MOVWF	STACK_0
$00F2	$0870			MOVF	STACK_0, 0
$00F3	$0580			ANDWF	INDF, 1
;lcd.ppas,220 :: 		
$00F4	$0823			MOVF	lcd_dataport_address, 0
$00F5	$0084			MOVWF	FSR
;lcd.ppas,221 :: 		
$00F6	$0827			MOVF	lcd____mdb4, 0
$00F7	$0480			IORWF	INDF, 1
;lcd.ppas,222 :: 		
$00F8	$0820			MOVF	lcd_ctrlport_address, 0
$00F9	$0084			MOVWF	FSR
;lcd.ppas,223 :: 		
$00FA	$0821			MOVF	lcd____menable, 0
$00FB	$0480			IORWF	INDF, 1
;lcd.ppas,224 :: 		
$00FC	$0870			MOVF	STACK_0, 0
$00FD	$0580			ANDWF	INDF, 1
;lcd.ppas,226 :: 		
$00FE	$229C			CALL	_delay_5500us
;lcd.ppas,229 :: 		
$00FF	$0823			MOVF	lcd_dataport_address, 0
$0100	$0084			MOVWF	FSR
;lcd.ppas,230 :: 		
$0101	$0927			COMF	lcd____mdb4, W
$0102	$00F0			MOVWF	STACK_0
$0103	$0870			MOVF	STACK_0, 0
$0104	$0580			ANDWF	INDF, 1
;lcd.ppas,231 :: 		
$0105	$0820			MOVF	lcd_ctrlport_address, 0
$0106	$0084			MOVWF	FSR
;lcd.ppas,232 :: 		
$0107	$0821			MOVF	lcd____menable, 0
$0108	$0480			IORWF	INDF, 1
;lcd.ppas,233 :: 		
$0109	$0921			COMF	lcd____menable, W
$010A	$00F1			MOVWF	STACK_1
$010B	$0871			MOVF	STACK_1, 0
$010C	$0580			ANDWF	INDF, 1
;lcd.ppas,234 :: 		
$010D	$0823			MOVF	lcd_dataport_address, 0
$010E	$0084			MOVWF	FSR
;lcd.ppas,235 :: 		
$010F	$0827			MOVF	lcd____mdb4, 0
$0110	$0400			IORWF	INDF, 0
$0111	$00F0			MOVWF	STACK_0
$0112	$0826			MOVF	lcd____mdb5, 0
$0113	$04F0			IORWF	STACK_0, 1
$0114	$0825			MOVF	lcd____mdb6, 0
$0115	$04F0			IORWF	STACK_0, 1
$0116	$0824			MOVF	lcd____mdb7, 0
$0117	$0470			IORWF	STACK_0, 0
$0118	$0080			MOVWF	INDF
;lcd.ppas,236 :: 		
$0119	$0820			MOVF	lcd_ctrlport_address, 0
$011A	$0084			MOVWF	FSR
;lcd.ppas,237 :: 		
$011B	$0821			MOVF	lcd____menable, 0
$011C	$0480			IORWF	INDF, 1
;lcd.ppas,238 :: 		
$011D	$0871			MOVF	STACK_1, 0
$011E	$0580			ANDWF	INDF, 1
;lcd.ppas,240 :: 		
$011F	$229C			CALL	_delay_5500us
;lcd.ppas,242 :: 		
$0120	$3001			MOVLW	1
$0121	$00A8			MOVWF	lcd_lcdcmd_status
$0122	$	lcd_L_55:
;lcd.ppas,243 :: 		
$0122	$0008			RETURN
$02AE	$	_lcd_chr_cp:
;lcd.ppas,97 :: 		
;lcd.ppas,98 :: 		
$02AE	$1303			BCF	STATUS, RP1
$02AF	$1283			BCF	STATUS, RP0
$02B0	$01A8			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,99 :: 		
$02B1	$0841			MOVF	FARG_Lcd_Chr_CP, 0
$02B2	$00CA			MOVWF	FARG_Lcd_Cmd
$02B3	$2123			CALL	_lcd_cmd
;lcd.ppas,100 :: 		
$02B4	$3001			MOVLW	1
$02B5	$00A8			MOVWF	lcd_lcdcmd_status
$02B6	$	lcd_L_48:
;lcd.ppas,101 :: 		
$02B6	$0008			RETURN
$02B7	$	_init:
;Exercice1.ppas,3 :: 		begin
;Exercice1.ppas,4 :: 		TRISC:=$ff;
$02B7	$30FF			MOVLW	255
$02B8	$1303			BCF	STATUS, RP1
$02B9	$1683			BSF	STATUS, RP0
$02BA	$0087			MOVWF	TRISC
;Exercice1.ppas,5 :: 		TRISB:=$00;
$02BB	$0186			CLRF	TRISB, 1
;Exercice1.ppas,6 :: 		PORTB:=$00;
$02BC	$1283			BCF	STATUS, RP0
$02BD	$0186			CLRF	PORTB, 1
$02BE	$	Exercice1_L_0:
;Exercice1.ppas,7 :: 		end;
$02BE	$0008			RETURN
$0287	$	_lcd_init:
;lcd.ppas,246 :: 		
;lcd.ppas,247 :: 		
$0287	$1303			BCF	STATUS, RP1
$0288	$1283			BCF	STATUS, RP0
$0289	$083D			MOVF	FARG_Lcd_Init, 0
$028A	$00C1			MOVWF	FARG_Lcd_Config
$028B	$3007			MOVLW	7
$028C	$00C2			MOVWF	FARG_Lcd_Config+1
$028D	$3006			MOVLW	6
$028E	$00C3			MOVWF	FARG_Lcd_Config+2
$028F	$3005			MOVLW	5
$0290	$00C4			MOVWF	FARG_Lcd_Config+3
$0291	$3004			MOVLW	4
$0292	$00C5			MOVWF	FARG_Lcd_Config+4
$0293	$083D			MOVF	FARG_Lcd_Init, 0
$0294	$00C6			MOVWF	FARG_Lcd_Config+5
$0295	$3002			MOVLW	2
$0296	$00C7			MOVWF	FARG_Lcd_Config+6
$0297	$01C8			CLRF	FARG_Lcd_Config+7, 1
$0298	$3003			MOVLW	3
$0299	$00C9			MOVWF	FARG_Lcd_Config+8
$029A	$2004			CALL	_lcd_config
$029B	$	lcd_L_64:
;lcd.ppas,248 :: 		
$029B	$0008			RETURN
$0248	$	_lcd_out:
;lcd.ppas,252 :: 		
;lcd.ppas,254 :: 		
$0248	$	lcd_L_68:
$0248	$1303			BCF	STATUS, RP1
$0249	$1283			BCF	STATUS, RP0
$024A	$083D			MOVF	FARG_Lcd_Out, 0
$024B	$3A01			XORLW	1
$024C	$1D03			BTFSS	STATUS, Z
$024D	$2A51			GOTO	lcd_L_69
$024E	$	lcd_L_67:
$024E	$3080			MOVLW	128
$024F	$00BD			MOVWF	FARG_Lcd_Out
$0250	$2A68			GOTO	lcd_L_66
$0251	$	lcd_L_69:
;lcd.ppas,255 :: 		
$0251	$	lcd_L_71:
$0251	$083D			MOVF	FARG_Lcd_Out, 0
$0252	$3A02			XORLW	2
$0253	$1D03			BTFSS	STATUS, Z
$0254	$2A58			GOTO	lcd_L_72
$0255	$	lcd_L_70:
$0255	$30C0			MOVLW	192
$0256	$00BD			MOVWF	FARG_Lcd_Out
$0257	$2A68			GOTO	lcd_L_66
$0258	$	lcd_L_72:
;lcd.ppas,256 :: 		
$0258	$	lcd_L_74:
$0258	$083D			MOVF	FARG_Lcd_Out, 0
$0259	$3A03			XORLW	3
$025A	$1D03			BTFSS	STATUS, Z
$025B	$2A5F			GOTO	lcd_L_75
$025C	$	lcd_L_73:
$025C	$3094			MOVLW	148
$025D	$00BD			MOVWF	FARG_Lcd_Out
$025E	$2A68			GOTO	lcd_L_66
$025F	$	lcd_L_75:
;lcd.ppas,257 :: 		
$025F	$	lcd_L_77:
$025F	$083D			MOVF	FARG_Lcd_Out, 0
$0260	$3A04			XORLW	4
$0261	$1D03			BTFSS	STATUS, Z
$0262	$2A66			GOTO	lcd_L_78
$0263	$	lcd_L_76:
$0263	$30D4			MOVLW	212
$0264	$00BD			MOVWF	FARG_Lcd_Out
;lcd.ppas,258 :: 		
$0265	$2A68			GOTO	lcd_L_66
$0266	$	lcd_L_78:
$0266	$3080			MOVLW	128
$0267	$00BD			MOVWF	FARG_Lcd_Out
$0268	$	lcd_L_66:
;lcd.ppas,260 :: 		
$0268	$033E			DECF	FARG_Lcd_Out+1, 0
$0269	$00F0			MOVWF	STACK_0
$026A	$083D			MOVF	FARG_Lcd_Out, 0
$026B	$07F0			ADDWF	STACK_0, 1
$026C	$0870			MOVF	STACK_0, 0
$026D	$00BD			MOVWF	FARG_Lcd_Out
;lcd.ppas,261 :: 		
$026E	$0870			MOVF	STACK_0, 0
$026F	$00CA			MOVWF	FARG_Lcd_Cmd
$0270	$2123			CALL	_lcd_cmd
;lcd.ppas,262 :: 		
$0271	$01A8			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,263 :: 		
$0272	$01C0			CLRF	_lcd_out_local_i, 1
;lcd.ppas,264 :: 		
$0273	$	lcd_L_80:
$0273	$0840			MOVF	_lcd_out_local_i, 0
$0274	$073F			ADDWF	FARG_Lcd_Out+2, 0
$0275	$0084			MOVWF	FSR
$0276	$0800			MOVF	INDF, 0
$0277	$00F2			MOVWF	STACK_2
$0278	$0872			MOVF	STACK_2, 0
$0279	$3A00			XORLW	0
$027A	$1903			BTFSC	STATUS, Z
$027B	$2A84			GOTO	lcd_L_81
;lcd.ppas,266 :: 		
$027C	$0840			MOVF	_lcd_out_local_i, 0
$027D	$073F			ADDWF	FARG_Lcd_Out+2, 0
$027E	$0084			MOVWF	FSR
$027F	$0800			MOVF	INDF, 0
$0280	$00C1			MOVWF	FARG_Lcd_Chr_CP
$0281	$22AE			CALL	_lcd_chr_cp
;lcd.ppas,267 :: 		
$0282	$0AC0			INCF	_lcd_out_local_i, 1
;lcd.ppas,268 :: 		
$0283	$2A73			GOTO	lcd_L_80
$0284	$	lcd_L_81:
;lcd.ppas,269 :: 		
$0284	$3001			MOVLW	1
$0285	$00A8			MOVWF	lcd_lcdcmd_status
$0286	$	lcd_L_65:
;lcd.ppas,270 :: 		
$0286	$0008			RETURN
$01CA	$	_main:
;Exercice1.ppas,9 :: 		begin
;Exercice1.ppas,10 :: 		init();
$01CA	$22B7			CALL	_init
;Exercice1.ppas,11 :: 		Lcd_Init(PORTB);
$01CB	$3006			MOVLW	PORTB
$01CC	$00BD			MOVWF	FARG_Lcd_Init
$01CD	$2287			CALL	_lcd_init
;Exercice1.ppas,12 :: 		Lcd_Cmd(LCD_CURSOR_OFF);
$01CE	$300C			MOVLW	12
$01CF	$00CA			MOVWF	FARG_Lcd_Cmd
$01D0	$2123			CALL	_lcd_cmd
;Exercice1.ppas,13 :: 		Lcd_Out(1,3,'SEM2 ISET NABEUL');
$01D1	$3001			MOVLW	1
$01D2	$00BD			MOVWF	FARG_Lcd_Out
$01D3	$3003			MOVLW	3
$01D4	$00BE			MOVWF	FARG_Lcd_Out+1
$01D5	$3053			MOVLW	83
$01D6	$00AA			MOVWF	?main_Local_Text+0
$01D7	$3045			MOVLW	69
$01D8	$00AB			MOVWF	?main_Local_Text+1
$01D9	$304D			MOVLW	77
$01DA	$00AC			MOVWF	?main_Local_Text+2
$01DB	$3032			MOVLW	50
$01DC	$00AD			MOVWF	?main_Local_Text+3
$01DD	$3020			MOVLW	32
$01DE	$00AE			MOVWF	?main_Local_Text+4
$01DF	$3049			MOVLW	73
$01E0	$00AF			MOVWF	?main_Local_Text+5
$01E1	$3053			MOVLW	83
$01E2	$00B0			MOVWF	?main_Local_Text+6
$01E3	$3045			MOVLW	69
$01E4	$00B1			MOVWF	?main_Local_Text+7
$01E5	$3054			MOVLW	84
$01E6	$00B2			MOVWF	?main_Local_Text+8
$01E7	$3020			MOVLW	32
$01E8	$00B3			MOVWF	?main_Local_Text+9
$01E9	$304E			MOVLW	78
$01EA	$00B4			MOVWF	?main_Local_Text+10
$01EB	$3041			MOVLW	65
$01EC	$00B5			MOVWF	?main_Local_Text+11
$01ED	$3042			MOVLW	66
$01EE	$00B6			MOVWF	?main_Local_Text+12
$01EF	$3045			MOVLW	69
$01F0	$00B7			MOVWF	?main_Local_Text+13
$01F1	$3055			MOVLW	85
$01F2	$00B8			MOVWF	?main_Local_Text+14
$01F3	$304C			MOVLW	76
$01F4	$00B9			MOVWF	?main_Local_Text+15
$01F5	$01BA			CLRF	?main_Local_Text+16
$01F6	$302A			MOVLW	?main_Local_Text
$01F7	$00BF			MOVWF	FARG_Lcd_Out+2
$01F8	$2248			CALL	_lcd_out
;Exercice1.ppas,14 :: 		Lcd_Out(2,2,'TP3 ARCH ET SYST 2');
$01F9	$3002			MOVLW	2
$01FA	$00BD			MOVWF	FARG_Lcd_Out
$01FB	$3002			MOVLW	2
$01FC	$00BE			MOVWF	FARG_Lcd_Out+1
$01FD	$3054			MOVLW	84
$01FE	$00AA			MOVWF	?main_Local_Text+0
$01FF	$3050			MOVLW	80
$0200	$00AB			MOVWF	?main_Local_Text+1
$0201	$3033			MOVLW	51
$0202	$00AC			MOVWF	?main_Local_Text+2
$0203	$3020			MOVLW	32
$0204	$00AD			MOVWF	?main_Local_Text+3
$0205	$3041			MOVLW	65
$0206	$00AE			MOVWF	?main_Local_Text+4
$0207	$3052			MOVLW	82
$0208	$00AF			MOVWF	?main_Local_Text+5
$0209	$3043			MOVLW	67
$020A	$00B0			MOVWF	?main_Local_Text+6
$020B	$3048			MOVLW	72
$020C	$00B1			MOVWF	?main_Local_Text+7
$020D	$3020			MOVLW	32
$020E	$00B2			MOVWF	?main_Local_Text+8
$020F	$3045			MOVLW	69
$0210	$00B3			MOVWF	?main_Local_Text+9
$0211	$3054			MOVLW	84
$0212	$00B4			MOVWF	?main_Local_Text+10
$0213	$3020			MOVLW	32
$0214	$00B5			MOVWF	?main_Local_Text+11
$0215	$3053			MOVLW	83
$0216	$00B6			MOVWF	?main_Local_Text+12
$0217	$3059			MOVLW	89
$0218	$00B7			MOVWF	?main_Local_Text+13
$0219	$3053			MOVLW	83
$021A	$00B8			MOVWF	?main_Local_Text+14
$021B	$3054			MOVLW	84
$021C	$00B9			MOVWF	?main_Local_Text+15
$021D	$3020			MOVLW	32
$021E	$00BA			MOVWF	?main_Local_Text+16
$021F	$3032			MOVLW	50
$0220	$00BB			MOVWF	?main_Local_Text+17
$0221	$01BC			CLRF	?main_Local_Text+18
$0222	$302A			MOVLW	?main_Local_Text
$0223	$00BF			MOVWF	FARG_Lcd_Out+2
$0224	$2248			CALL	_lcd_out
;Exercice1.ppas,16 :: 		delay_ms(10000);
$0225	$3066			MOVLW	102
$0226	$00FC			MOVWF	STACK_12
$0227	$30FF			MOVLW	255
$0228	$00FB			MOVWF	STACK_11
$0229	$30FF			MOVLW	255
$022A	$00FA			MOVWF	STACK_10
$022B	$0BFC			DECFSZ	STACK_12, F
$022C	$2A2E			GOTO	$+2
$022D	$2A35			GOTO	$+8
$022E	$0BFB			DECFSZ	STACK_11, F
$022F	$2A31			GOTO	$+2
$0230	$2A34			GOTO	$+4
$0231	$0BFA			DECFSZ	STACK_10, F
$0232	$2A31			GOTO	$-1
$0233	$2A2E			GOTO	$-5
$0234	$2A2B			GOTO	$-9
$0235	$30FC			MOVLW	252
$0236	$00FB			MOVWF	STACK_11
$0237	$30FF			MOVLW	255
$0238	$00FA			MOVWF	STACK_10
$0239	$0BFB			DECFSZ	STACK_11, F
$023A	$2A3C			GOTO	$+2
$023B	$2A3F			GOTO	$+4
$023C	$0BFA			DECFSZ	STACK_10, F
$023D	$2A3C			GOTO	$-1
$023E	$2A39			GOTO	$-5
$023F	$306A			MOVLW	106
$0240	$00FA			MOVWF	STACK_10
$0241	$0BFA			DECFSZ	STACK_10, F
$0242	$2A41			GOTO	$-1
$0243	$0000			NOP
;Exercice1.ppas,18 :: 		Lcd_Cmd(LCD_clear);
$0244	$3001			MOVLW	1
$0245	$00CA			MOVWF	FARG_Lcd_Cmd
$0246	$2123			CALL	_lcd_cmd
$0247	$	Exercice1_L_1:
;Exercice1.ppas,20 :: 		end.
$0247	$2A47			GOTO	$
