;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 3/30/2021 10:37:15 AM
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2923			GOTO	_main
$0366	$	_delay_1us:
;delays.ppas,11 :: 		begin
;delays.ppas,12 :: 		Delay_us(1);
$0366	$0000			NOP
$0367	$0000			NOP
$0368	$	delays_L_1:
;delays.ppas,13 :: 		end;
$0368	$0008			RETURN
$032B	$	_delay_5500us:
;delays.ppas,41 :: 		begin
;delays.ppas,42 :: 		Delay_us(5500);
$032B	$300F			MOVLW	15
$032C	$1303			BCF	STATUS, RP1
$032D	$1283			BCF	STATUS, RP0
$032E	$00FB			MOVWF	STACK_11
$032F	$30FF			MOVLW	255
$0330	$00FA			MOVWF	STACK_10
$0331	$0BFB			DECFSZ	STACK_11, F
$0332	$2B34			GOTO	$+2
$0333	$2B37			GOTO	$+4
$0334	$0BFA			DECFSZ	STACK_10, F
$0335	$2B34			GOTO	$-1
$0336	$2B31			GOTO	$-5
$0337	$303E			MOVLW	62
$0338	$00FA			MOVWF	STACK_10
$0339	$0BFA			DECFSZ	STACK_10, F
$033A	$2B39			GOTO	$-1
$033B	$0000			NOP
$033C	$	delays_L_7:
;delays.ppas,43 :: 		end;
$033C	$0008			RETURN
$035F	$	_delay_50us:
;delays.ppas,26 :: 		begin
;delays.ppas,27 :: 		Delay_us(50);
$035F	$3021			MOVLW	33
$0360	$1303			BCF	STATUS, RP1
$0361	$1283			BCF	STATUS, RP0
$0362	$00FA			MOVWF	STACK_10
$0363	$0BFA			DECFSZ	STACK_10, F
$0364	$2B63			GOTO	$-1
$0365	$	delays_L_4:
;delays.ppas,28 :: 		end;
$0365	$0008			RETURN
$01FE	$	_lcd_cmd:
;lcd.ppas,19 :: 		
;lcd.ppas,20 :: 		
$01FE	$1303			BCF	STATUS, RP1
$01FF	$1283			BCF	STATUS, RP0
$0200	$0820			MOVF	lcd_ctrlport_address, 0
$0201	$0084			MOVWF	FSR
;lcd.ppas,22 :: 		
$0202	$0921			COMF	lcd____menable, W
$0203	$00F0			MOVWF	STACK_0
$0204	$0870			MOVF	STACK_0, 0
$0205	$0580			ANDWF	INDF, 1
;lcd.ppas,23 :: 		
$0206	$0922			COMF	lcd____mrs, W
$0207	$00F0			MOVWF	STACK_0
$0208	$0870			MOVF	STACK_0, 0
$0209	$0580			ANDWF	INDF, 1
;lcd.ppas,25 :: 		
$020A	$0823			MOVF	lcd_dataport_address, 0
$020B	$0084			MOVWF	FSR
;lcd.ppas,26 :: 		
$020C	$0825			MOVF	lcd____mdb6, 0
$020D	$0424			IORWF	lcd____mdb7, 0
$020E	$00F0			MOVWF	STACK_0
$020F	$0826			MOVF	lcd____mdb5, 0
$0210	$04F0			IORWF	STACK_0, 1
$0211	$0827			MOVF	lcd____mdb4, 0
$0212	$04F0			IORWF	STACK_0, 1
$0213	$09F0			COMF	STACK_0, F
$0214	$0870			MOVF	STACK_0, 0
$0215	$0580			ANDWF	INDF, 1
;lcd.ppas,28 :: 		
$0216	$3000			MOVLW	0
$0217	$1BD0			BTFSC	FARG_Lcd_Cmd, 7
$0218	$3001			MOVLW	1
$0219	$00F1			MOVWF	STACK_1
$021A	$0871			MOVF	STACK_1, 0
$021B	$3A01			XORLW	1
$021C	$1D03			BTFSS	STATUS, Z
$021D	$2A20			GOTO	lcd_L_2
$021E	$	lcd_L_1:
;lcd.ppas,29 :: 		
$021E	$0824			MOVF	lcd____mdb7, 0
$021F	$0480			IORWF	INDF, 1
$0220	$	lcd_L_2:
$0220	$	lcd_L_3:
;lcd.ppas,30 :: 		
$0220	$3000			MOVLW	0
$0221	$1B50			BTFSC	FARG_Lcd_Cmd, 6
$0222	$3001			MOVLW	1
$0223	$00F1			MOVWF	STACK_1
$0224	$0871			MOVF	STACK_1, 0
$0225	$3A01			XORLW	1
$0226	$1D03			BTFSS	STATUS, Z
$0227	$2A2A			GOTO	lcd_L_5
$0228	$	lcd_L_4:
;lcd.ppas,31 :: 		
$0228	$0825			MOVF	lcd____mdb6, 0
$0229	$0480			IORWF	INDF, 1
$022A	$	lcd_L_5:
$022A	$	lcd_L_6:
;lcd.ppas,32 :: 		
$022A	$3000			MOVLW	0
$022B	$1AD0			BTFSC	FARG_Lcd_Cmd, 5
$022C	$3001			MOVLW	1
$022D	$00F1			MOVWF	STACK_1
$022E	$0871			MOVF	STACK_1, 0
$022F	$3A01			XORLW	1
$0230	$1D03			BTFSS	STATUS, Z
$0231	$2A34			GOTO	lcd_L_8
$0232	$	lcd_L_7:
;lcd.ppas,33 :: 		
$0232	$0826			MOVF	lcd____mdb5, 0
$0233	$0480			IORWF	INDF, 1
$0234	$	lcd_L_8:
$0234	$	lcd_L_9:
;lcd.ppas,34 :: 		
$0234	$3000			MOVLW	0
$0235	$1A50			BTFSC	FARG_Lcd_Cmd, 4
$0236	$3001			MOVLW	1
$0237	$00F1			MOVWF	STACK_1
$0238	$0871			MOVF	STACK_1, 0
$0239	$3A01			XORLW	1
$023A	$1D03			BTFSS	STATUS, Z
$023B	$2A3E			GOTO	lcd_L_11
$023C	$	lcd_L_10:
;lcd.ppas,35 :: 		
$023C	$0827			MOVF	lcd____mdb4, 0
$023D	$0480			IORWF	INDF, 1
$023E	$	lcd_L_11:
$023E	$	lcd_L_12:
;lcd.ppas,37 :: 		
$023E	$0820			MOVF	lcd_ctrlport_address, 0
$023F	$0084			MOVWF	FSR
;lcd.ppas,38 :: 		
$0240	$0828			MOVF	lcd_lcdcmd_status, 0
$0241	$3A01			XORLW	1
$0242	$1D03			BTFSS	STATUS, Z
$0243	$2A49			GOTO	lcd_L_14
$0244	$	lcd_L_13:
;lcd.ppas,39 :: 		
$0244	$0922			COMF	lcd____mrs, W
$0245	$00F0			MOVWF	STACK_0
$0246	$0870			MOVF	STACK_0, 0
$0247	$0580			ANDWF	INDF, 1
$0248	$2A4B			GOTO	lcd_L_15
;lcd.ppas,40 :: 		
$0249	$	lcd_L_14:
;lcd.ppas,41 :: 		
$0249	$0822			MOVF	lcd____mrs, 0
$024A	$0480			IORWF	INDF, 1
$024B	$	lcd_L_15:
;lcd.ppas,43 :: 		
$024B	$0821			MOVF	lcd____menable, 0
$024C	$0480			IORWF	INDF, 1
;lcd.ppas,44 :: 		
$024D	$2366			CALL	_delay_1us
;lcd.ppas,45 :: 		
$024E	$0921			COMF	lcd____menable, W
$024F	$00F0			MOVWF	STACK_0
$0250	$0870			MOVF	STACK_0, 0
$0251	$0580			ANDWF	INDF, 1
;lcd.ppas,47 :: 		
$0252	$0922			COMF	lcd____mrs, W
$0253	$00F0			MOVWF	STACK_0
$0254	$0870			MOVF	STACK_0, 0
$0255	$0580			ANDWF	INDF, 1
;lcd.ppas,49 :: 		
$0256	$0823			MOVF	lcd_dataport_address, 0
$0257	$0084			MOVWF	FSR
;lcd.ppas,50 :: 		
$0258	$0825			MOVF	lcd____mdb6, 0
$0259	$0424			IORWF	lcd____mdb7, 0
$025A	$00F0			MOVWF	STACK_0
$025B	$0826			MOVF	lcd____mdb5, 0
$025C	$04F0			IORWF	STACK_0, 1
$025D	$0827			MOVF	lcd____mdb4, 0
$025E	$04F0			IORWF	STACK_0, 1
$025F	$09F0			COMF	STACK_0, F
$0260	$0870			MOVF	STACK_0, 0
$0261	$0580			ANDWF	INDF, 1
;lcd.ppas,52 :: 		
$0262	$3000			MOVLW	0
$0263	$19D0			BTFSC	FARG_Lcd_Cmd, 3
$0264	$3001			MOVLW	1
$0265	$00F1			MOVWF	STACK_1
$0266	$0871			MOVF	STACK_1, 0
$0267	$3A01			XORLW	1
$0268	$1D03			BTFSS	STATUS, Z
$0269	$2A6C			GOTO	lcd_L_17
$026A	$	lcd_L_16:
;lcd.ppas,53 :: 		
$026A	$0824			MOVF	lcd____mdb7, 0
$026B	$0480			IORWF	INDF, 1
$026C	$	lcd_L_17:
$026C	$	lcd_L_18:
;lcd.ppas,54 :: 		
$026C	$3000			MOVLW	0
$026D	$1950			BTFSC	FARG_Lcd_Cmd, 2
$026E	$3001			MOVLW	1
$026F	$00F1			MOVWF	STACK_1
$0270	$0871			MOVF	STACK_1, 0
$0271	$3A01			XORLW	1
$0272	$1D03			BTFSS	STATUS, Z
$0273	$2A76			GOTO	lcd_L_20
$0274	$	lcd_L_19:
;lcd.ppas,55 :: 		
$0274	$0825			MOVF	lcd____mdb6, 0
$0275	$0480			IORWF	INDF, 1
$0276	$	lcd_L_20:
$0276	$	lcd_L_21:
;lcd.ppas,56 :: 		
$0276	$3000			MOVLW	0
$0277	$18D0			BTFSC	FARG_Lcd_Cmd, 1
$0278	$3001			MOVLW	1
$0279	$00F1			MOVWF	STACK_1
$027A	$0871			MOVF	STACK_1, 0
$027B	$3A01			XORLW	1
$027C	$1D03			BTFSS	STATUS, Z
$027D	$2A80			GOTO	lcd_L_23
$027E	$	lcd_L_22:
;lcd.ppas,57 :: 		
$027E	$0826			MOVF	lcd____mdb5, 0
$027F	$0480			IORWF	INDF, 1
$0280	$	lcd_L_23:
$0280	$	lcd_L_24:
;lcd.ppas,58 :: 		
$0280	$3001			MOVLW	1
$0281	$0550			ANDWF	FARG_Lcd_Cmd, 0
$0282	$00F1			MOVWF	STACK_1
$0283	$0871			MOVF	STACK_1, 0
$0284	$3A01			XORLW	1
$0285	$1D03			BTFSS	STATUS, Z
$0286	$2A89			GOTO	lcd_L_26
$0287	$	lcd_L_25:
;lcd.ppas,59 :: 		
$0287	$0827			MOVF	lcd____mdb4, 0
$0288	$0480			IORWF	INDF, 1
$0289	$	lcd_L_26:
$0289	$	lcd_L_27:
;lcd.ppas,61 :: 		
$0289	$0820			MOVF	lcd_ctrlport_address, 0
$028A	$0084			MOVWF	FSR
;lcd.ppas,62 :: 		
$028B	$0828			MOVF	lcd_lcdcmd_status, 0
$028C	$3A01			XORLW	1
$028D	$1D03			BTFSS	STATUS, Z
$028E	$2A94			GOTO	lcd_L_29
$028F	$	lcd_L_28:
;lcd.ppas,63 :: 		
$028F	$0922			COMF	lcd____mrs, W
$0290	$00F0			MOVWF	STACK_0
$0291	$0870			MOVF	STACK_0, 0
$0292	$0580			ANDWF	INDF, 1
$0293	$2A96			GOTO	lcd_L_30
;lcd.ppas,64 :: 		
$0294	$	lcd_L_29:
;lcd.ppas,65 :: 		
$0294	$0822			MOVF	lcd____mrs, 0
$0295	$0480			IORWF	INDF, 1
$0296	$	lcd_L_30:
;lcd.ppas,67 :: 		
$0296	$0821			MOVF	lcd____menable, 0
$0297	$0480			IORWF	INDF, 1
;lcd.ppas,68 :: 		
$0298	$2366			CALL	_delay_1us
;lcd.ppas,69 :: 		
$0299	$0921			COMF	lcd____menable, W
$029A	$00F0			MOVWF	STACK_0
$029B	$0870			MOVF	STACK_0, 0
$029C	$0580			ANDWF	INDF, 1
;lcd.ppas,71 :: 		
$029D	$0828			MOVF	lcd_lcdcmd_status, 0
$029E	$3A01			XORLW	1
$029F	$1D03			BTFSS	STATUS, Z
$02A0	$2AA3			GOTO	lcd_L_32
$02A1	$	lcd_L_31:
;lcd.ppas,72 :: 		
$02A1	$232B			CALL	_delay_5500us
$02A2	$2AA4			GOTO	lcd_L_33
;lcd.ppas,73 :: 		
$02A3	$	lcd_L_32:
;lcd.ppas,74 :: 		
$02A3	$235F			CALL	_delay_50us
$02A4	$	lcd_L_33:
$02A4	$	lcd_L_0:
;lcd.ppas,75 :: 		
$02A4	$0008			RETURN
$0004	$	_lcd_config:
;lcd.ppas,115 :: 		
;lcd.ppas,116 :: 		
$0004	$232B			CALL	_delay_5500us
;lcd.ppas,117 :: 		
$0005	$232B			CALL	_delay_5500us
;lcd.ppas,118 :: 		
$0006	$232B			CALL	_delay_5500us
;lcd.ppas,120 :: 		
$0007	$0848			MOVF	FARG_Lcd_Config+1, 0
$0008	$00F0			MOVWF	STACK_0
$0009	$3001			MOVLW	1
$000A	$00F4			MOVWF	STACK_4
$000B	$0870			MOVF	STACK_0, 0
$000C	$	L_Lcd_Config_0:
$000C	$1903			BTFSC	STATUS, Z
$000D	$2812			GOTO	L_Lcd_Config_1
$000E	$0DF4			RLF	STACK_4, 1
$000F	$1074			BCF	STACK_4, 0
$0010	$3FFF			ADDLW	255
$0011	$280C			GOTO	L_Lcd_Config_0
$0012	$	L_Lcd_Config_1:
$0012	$0874			MOVF	STACK_4, 0
$0013	$00A4			MOVWF	lcd____mdb7
;lcd.ppas,121 :: 		
$0014	$0849			MOVF	FARG_Lcd_Config+2, 0
$0015	$00F0			MOVWF	STACK_0
$0016	$3001			MOVLW	1
$0017	$00F3			MOVWF	STACK_3
$0018	$0870			MOVF	STACK_0, 0
$0019	$	L_Lcd_Config_2:
$0019	$1903			BTFSC	STATUS, Z
$001A	$281F			GOTO	L_Lcd_Config_3
$001B	$0DF3			RLF	STACK_3, 1
$001C	$1073			BCF	STACK_3, 0
$001D	$3FFF			ADDLW	255
$001E	$2819			GOTO	L_Lcd_Config_2
$001F	$	L_Lcd_Config_3:
$001F	$0873			MOVF	STACK_3, 0
$0020	$00A5			MOVWF	lcd____mdb6
;lcd.ppas,122 :: 		
$0021	$084A			MOVF	FARG_Lcd_Config+3, 0
$0022	$00F0			MOVWF	STACK_0
$0023	$3001			MOVLW	1
$0024	$00F2			MOVWF	STACK_2
$0025	$0870			MOVF	STACK_0, 0
$0026	$	L_Lcd_Config_4:
$0026	$1903			BTFSC	STATUS, Z
$0027	$282C			GOTO	L_Lcd_Config_5
$0028	$0DF2			RLF	STACK_2, 1
$0029	$1072			BCF	STACK_2, 0
$002A	$3FFF			ADDLW	255
$002B	$2826			GOTO	L_Lcd_Config_4
$002C	$	L_Lcd_Config_5:
$002C	$0872			MOVF	STACK_2, 0
$002D	$00A6			MOVWF	lcd____mdb5
;lcd.ppas,123 :: 		
$002E	$084B			MOVF	FARG_Lcd_Config+4, 0
$002F	$00F0			MOVWF	STACK_0
$0030	$3001			MOVLW	1
$0031	$00F1			MOVWF	STACK_1
$0032	$0870			MOVF	STACK_0, 0
$0033	$	L_Lcd_Config_6:
$0033	$1903			BTFSC	STATUS, Z
$0034	$2839			GOTO	L_Lcd_Config_7
$0035	$0DF1			RLF	STACK_1, 1
$0036	$1071			BCF	STACK_1, 0
$0037	$3FFF			ADDLW	255
$0038	$2833			GOTO	L_Lcd_Config_6
$0039	$	L_Lcd_Config_7:
$0039	$0871			MOVF	STACK_1, 0
$003A	$00A7			MOVWF	lcd____mdb4
;lcd.ppas,124 :: 		
$003B	$084D			MOVF	FARG_Lcd_Config+6, 0
$003C	$00F0			MOVWF	STACK_0
$003D	$3001			MOVLW	1
$003E	$00A2			MOVWF	lcd____mrs
$003F	$0870			MOVF	STACK_0, 0
$0040	$	L_Lcd_Config_8:
$0040	$1903			BTFSC	STATUS, Z
$0041	$2846			GOTO	L_Lcd_Config_9
$0042	$0DA2			RLF	lcd____mrs, 1
$0043	$1022			BCF	lcd____mrs, 0
$0044	$3FFF			ADDLW	255
$0045	$2840			GOTO	L_Lcd_Config_8
$0046	$	L_Lcd_Config_9:
;lcd.ppas,125 :: 		
$0046	$084E			MOVF	FARG_Lcd_Config+7, 0
$0047	$00F0			MOVWF	STACK_0
$0048	$3001			MOVLW	1
$0049	$00A9			MOVWF	lcd____mrw
$004A	$0870			MOVF	STACK_0, 0
$004B	$	L_Lcd_Config_10:
$004B	$1903			BTFSC	STATUS, Z
$004C	$2851			GOTO	L_Lcd_Config_11
$004D	$0DA9			RLF	lcd____mrw, 1
$004E	$1029			BCF	lcd____mrw, 0
$004F	$3FFF			ADDLW	255
$0050	$284B			GOTO	L_Lcd_Config_10
$0051	$	L_Lcd_Config_11:
;lcd.ppas,126 :: 		
$0051	$084F			MOVF	FARG_Lcd_Config+8, 0
$0052	$00F0			MOVWF	STACK_0
$0053	$3001			MOVLW	1
$0054	$00A1			MOVWF	lcd____menable
$0055	$0870			MOVF	STACK_0, 0
$0056	$	L_Lcd_Config_12:
$0056	$1903			BTFSC	STATUS, Z
$0057	$285C			GOTO	L_Lcd_Config_13
$0058	$0DA1			RLF	lcd____menable, 1
$0059	$1021			BCF	lcd____menable, 0
$005A	$3FFF			ADDLW	255
$005B	$2856			GOTO	L_Lcd_Config_12
$005C	$	L_Lcd_Config_13:
;lcd.ppas,128 :: 		
$005C	$0847			MOVF	FARG_Lcd_Config, 0
$005D	$00A3			MOVWF	lcd_dataport_address
;lcd.ppas,129 :: 		
$005E	$084C			MOVF	FARG_Lcd_Config+5, 0
$005F	$00A0			MOVWF	lcd_ctrlport_address
;lcd.ppas,131 :: 		
$0060	$0847			MOVF	FARG_Lcd_Config, 0
$0061	$0084			MOVWF	FSR
;lcd.ppas,133 :: 		
$0062	$0873			MOVF	STACK_3, 0
$0063	$0474			IORWF	STACK_4, 0
$0064	$00F0			MOVWF	STACK_0
$0065	$0872			MOVF	STACK_2, 0
$0066	$04F0			IORWF	STACK_0, 1
$0067	$0871			MOVF	STACK_1, 0
$0068	$04F0			IORWF	STACK_0, 1
$0069	$09F0			COMF	STACK_0, F
$006A	$0870			MOVF	STACK_0, 0
$006B	$0580			ANDWF	INDF, 1
;lcd.ppas,134 :: 		
$006C	$	lcd_L_56:
$006C	$1784			BSF	FSR, 7
$006D	$	lcd_L_57:
;lcd.ppas,135 :: 		
$006D	$0825			MOVF	lcd____mdb6, 0
$006E	$0424			IORWF	lcd____mdb7, 0
$006F	$00F0			MOVWF	STACK_0
$0070	$0826			MOVF	lcd____mdb5, 0
$0071	$04F0			IORWF	STACK_0, 1
$0072	$0827			MOVF	lcd____mdb4, 0
$0073	$04F0			IORWF	STACK_0, 1
$0074	$09F0			COMF	STACK_0, F
$0075	$0870			MOVF	STACK_0, 0
$0076	$0580			ANDWF	INDF, 1
;lcd.ppas,136 :: 		
$0077	$1384			BCF	FSR, 7
$0078	$	lcd_L_59:
;lcd.ppas,139 :: 		
$0078	$0820			MOVF	lcd_ctrlport_address, 0
$0079	$0084			MOVWF	FSR
;lcd.ppas,141 :: 		
$007A	$0829			MOVF	lcd____mrw, 0
$007B	$0422			IORWF	lcd____mrs, 0
$007C	$00F0			MOVWF	STACK_0
$007D	$0821			MOVF	lcd____menable, 0
$007E	$04F0			IORWF	STACK_0, 1
$007F	$09F0			COMF	STACK_0, F
$0080	$0870			MOVF	STACK_0, 0
$0081	$0580			ANDWF	INDF, 1
;lcd.ppas,142 :: 		
$0082	$	lcd_L_60:
$0082	$1784			BSF	FSR, 7
$0083	$	lcd_L_61:
;lcd.ppas,143 :: 		
$0083	$0829			MOVF	lcd____mrw, 0
$0084	$0422			IORWF	lcd____mrs, 0
$0085	$00F0			MOVWF	STACK_0
$0086	$0821			MOVF	lcd____menable, 0
$0087	$04F0			IORWF	STACK_0, 1
$0088	$09F0			COMF	STACK_0, F
$0089	$0870			MOVF	STACK_0, 0
$008A	$0580			ANDWF	INDF, 1
;lcd.ppas,144 :: 		
$008B	$1384			BCF	FSR, 7
$008C	$	lcd_L_63:
;lcd.ppas,148 :: 		
$008C	$0823			MOVF	lcd_dataport_address, 0
$008D	$0084			MOVWF	FSR
;lcd.ppas,149 :: 		
$008E	$0826			MOVF	lcd____mdb5, 0
$008F	$0400			IORWF	INDF, 0
$0090	$00F0			MOVWF	STACK_0
$0091	$0827			MOVF	lcd____mdb4, 0
$0092	$0470			IORWF	STACK_0, 0
$0093	$0080			MOVWF	INDF
;lcd.ppas,151 :: 		
$0094	$0820			MOVF	lcd_ctrlport_address, 0
$0095	$0084			MOVWF	FSR
;lcd.ppas,152 :: 		
$0096	$0821			MOVF	lcd____menable, 0
$0097	$0480			IORWF	INDF, 1
;lcd.ppas,153 :: 		
$0098	$0921			COMF	lcd____menable, W
$0099	$00F0			MOVWF	STACK_0
$009A	$0870			MOVF	STACK_0, 0
$009B	$0580			ANDWF	INDF, 1
;lcd.ppas,155 :: 		
$009C	$232B			CALL	_delay_5500us
;lcd.ppas,160 :: 		
$009D	$0821			MOVF	lcd____menable, 0
$009E	$0480			IORWF	INDF, 1
;lcd.ppas,161 :: 		
$009F	$0921			COMF	lcd____menable, W
$00A0	$00F0			MOVWF	STACK_0
$00A1	$0870			MOVF	STACK_0, 0
$00A2	$0580			ANDWF	INDF, 1
;lcd.ppas,163 :: 		
$00A3	$232B			CALL	_delay_5500us
;lcd.ppas,168 :: 		
$00A4	$0821			MOVF	lcd____menable, 0
$00A5	$0480			IORWF	INDF, 1
;lcd.ppas,169 :: 		
$00A6	$0921			COMF	lcd____menable, W
$00A7	$00F0			MOVWF	STACK_0
$00A8	$0870			MOVF	STACK_0, 0
$00A9	$0580			ANDWF	INDF, 1
;lcd.ppas,171 :: 		
$00AA	$232B			CALL	_delay_5500us
;lcd.ppas,174 :: 		
$00AB	$0823			MOVF	lcd_dataport_address, 0
$00AC	$0084			MOVWF	FSR
;lcd.ppas,175 :: 		
$00AD	$0826			MOVF	lcd____mdb5, 0
$00AE	$0480			IORWF	INDF, 1
;lcd.ppas,176 :: 		
$00AF	$0927			COMF	lcd____mdb4, W
$00B0	$00F0			MOVWF	STACK_0
$00B1	$0870			MOVF	STACK_0, 0
$00B2	$0580			ANDWF	INDF, 1
;lcd.ppas,178 :: 		
$00B3	$0820			MOVF	lcd_ctrlport_address, 0
$00B4	$0084			MOVWF	FSR
;lcd.ppas,179 :: 		
$00B5	$0821			MOVF	lcd____menable, 0
$00B6	$0480			IORWF	INDF, 1
;lcd.ppas,180 :: 		
$00B7	$0921			COMF	lcd____menable, W
$00B8	$00F0			MOVWF	STACK_0
$00B9	$0870			MOVF	STACK_0, 0
$00BA	$0580			ANDWF	INDF, 1
;lcd.ppas,182 :: 		
$00BB	$232B			CALL	_delay_5500us
;lcd.ppas,187 :: 		
$00BC	$0821			MOVF	lcd____menable, 0
$00BD	$0480			IORWF	INDF, 1
;lcd.ppas,188 :: 		
$00BE	$0921			COMF	lcd____menable, W
$00BF	$00F1			MOVWF	STACK_1
$00C0	$0871			MOVF	STACK_1, 0
$00C1	$0580			ANDWF	INDF, 1
;lcd.ppas,190 :: 		
$00C2	$0823			MOVF	lcd_dataport_address, 0
$00C3	$0084			MOVWF	FSR
;lcd.ppas,191 :: 		
$00C4	$0926			COMF	lcd____mdb5, W
$00C5	$00F0			MOVWF	STACK_0
$00C6	$0870			MOVF	STACK_0, 0
$00C7	$0580			ANDWF	INDF, 1
;lcd.ppas,192 :: 		
$00C8	$0824			MOVF	lcd____mdb7, 0
$00C9	$0480			IORWF	INDF, 1
;lcd.ppas,194 :: 		
$00CA	$0820			MOVF	lcd_ctrlport_address, 0
$00CB	$0084			MOVWF	FSR
;lcd.ppas,195 :: 		
$00CC	$0821			MOVF	lcd____menable, 0
$00CD	$0480			IORWF	INDF, 1
;lcd.ppas,196 :: 		
$00CE	$0871			MOVF	STACK_1, 0
$00CF	$0580			ANDWF	INDF, 1
;lcd.ppas,198 :: 		
$00D0	$232B			CALL	_delay_5500us
;lcd.ppas,201 :: 		
$00D1	$0823			MOVF	lcd_dataport_address, 0
$00D2	$0084			MOVWF	FSR
;lcd.ppas,202 :: 		
$00D3	$0924			COMF	lcd____mdb7, W
$00D4	$00F0			MOVWF	STACK_0
$00D5	$0870			MOVF	STACK_0, 0
$00D6	$0580			ANDWF	INDF, 1
;lcd.ppas,203 :: 		
$00D7	$0827			MOVF	lcd____mdb4, 0
$00D8	$0480			IORWF	INDF, 1
;lcd.ppas,204 :: 		
$00D9	$0820			MOVF	lcd_ctrlport_address, 0
$00DA	$0084			MOVWF	FSR
;lcd.ppas,205 :: 		
$00DB	$0821			MOVF	lcd____menable, 0
$00DC	$0480			IORWF	INDF, 1
;lcd.ppas,206 :: 		
$00DD	$0921			COMF	lcd____menable, W
$00DE	$00F1			MOVWF	STACK_1
$00DF	$0871			MOVF	STACK_1, 0
$00E0	$0580			ANDWF	INDF, 1
;lcd.ppas,207 :: 		
$00E1	$0823			MOVF	lcd_dataport_address, 0
$00E2	$0084			MOVWF	FSR
;lcd.ppas,208 :: 		
$00E3	$0927			COMF	lcd____mdb4, W
$00E4	$00F0			MOVWF	STACK_0
$00E5	$0870			MOVF	STACK_0, 0
$00E6	$0580			ANDWF	INDF, 1
;lcd.ppas,209 :: 		
$00E7	$0820			MOVF	lcd_ctrlport_address, 0
$00E8	$0084			MOVWF	FSR
;lcd.ppas,210 :: 		
$00E9	$0821			MOVF	lcd____menable, 0
$00EA	$0480			IORWF	INDF, 1
;lcd.ppas,211 :: 		
$00EB	$0871			MOVF	STACK_1, 0
$00EC	$0580			ANDWF	INDF, 1
;lcd.ppas,213 :: 		
$00ED	$232B			CALL	_delay_5500us
;lcd.ppas,218 :: 		
$00EE	$0821			MOVF	lcd____menable, 0
$00EF	$0480			IORWF	INDF, 1
;lcd.ppas,219 :: 		
$00F0	$0921			COMF	lcd____menable, W
$00F1	$00F0			MOVWF	STACK_0
$00F2	$0870			MOVF	STACK_0, 0
$00F3	$0580			ANDWF	INDF, 1
;lcd.ppas,220 :: 		
$00F4	$0823			MOVF	lcd_dataport_address, 0
$00F5	$0084			MOVWF	FSR
;lcd.ppas,221 :: 		
$00F6	$0827			MOVF	lcd____mdb4, 0
$00F7	$0480			IORWF	INDF, 1
;lcd.ppas,222 :: 		
$00F8	$0820			MOVF	lcd_ctrlport_address, 0
$00F9	$0084			MOVWF	FSR
;lcd.ppas,223 :: 		
$00FA	$0821			MOVF	lcd____menable, 0
$00FB	$0480			IORWF	INDF, 1
;lcd.ppas,224 :: 		
$00FC	$0870			MOVF	STACK_0, 0
$00FD	$0580			ANDWF	INDF, 1
;lcd.ppas,226 :: 		
$00FE	$232B			CALL	_delay_5500us
;lcd.ppas,229 :: 		
$00FF	$0823			MOVF	lcd_dataport_address, 0
$0100	$0084			MOVWF	FSR
;lcd.ppas,230 :: 		
$0101	$0927			COMF	lcd____mdb4, W
$0102	$00F0			MOVWF	STACK_0
$0103	$0870			MOVF	STACK_0, 0
$0104	$0580			ANDWF	INDF, 1
;lcd.ppas,231 :: 		
$0105	$0820			MOVF	lcd_ctrlport_address, 0
$0106	$0084			MOVWF	FSR
;lcd.ppas,232 :: 		
$0107	$0821			MOVF	lcd____menable, 0
$0108	$0480			IORWF	INDF, 1
;lcd.ppas,233 :: 		
$0109	$0921			COMF	lcd____menable, W
$010A	$00F1			MOVWF	STACK_1
$010B	$0871			MOVF	STACK_1, 0
$010C	$0580			ANDWF	INDF, 1
;lcd.ppas,234 :: 		
$010D	$0823			MOVF	lcd_dataport_address, 0
$010E	$0084			MOVWF	FSR
;lcd.ppas,235 :: 		
$010F	$0827			MOVF	lcd____mdb4, 0
$0110	$0400			IORWF	INDF, 0
$0111	$00F0			MOVWF	STACK_0
$0112	$0826			MOVF	lcd____mdb5, 0
$0113	$04F0			IORWF	STACK_0, 1
$0114	$0825			MOVF	lcd____mdb6, 0
$0115	$04F0			IORWF	STACK_0, 1
$0116	$0824			MOVF	lcd____mdb7, 0
$0117	$0470			IORWF	STACK_0, 0
$0118	$0080			MOVWF	INDF
;lcd.ppas,236 :: 		
$0119	$0820			MOVF	lcd_ctrlport_address, 0
$011A	$0084			MOVWF	FSR
;lcd.ppas,237 :: 		
$011B	$0821			MOVF	lcd____menable, 0
$011C	$0480			IORWF	INDF, 1
;lcd.ppas,238 :: 		
$011D	$0871			MOVF	STACK_1, 0
$011E	$0580			ANDWF	INDF, 1
;lcd.ppas,240 :: 		
$011F	$232B			CALL	_delay_5500us
;lcd.ppas,242 :: 		
$0120	$3001			MOVLW	1
$0121	$00A8			MOVWF	lcd_lcdcmd_status
$0122	$	lcd_L_55:
;lcd.ppas,243 :: 		
$0122	$0008			RETURN
$034E	$	_lcd_chr_cp:
;lcd.ppas,97 :: 		
;lcd.ppas,98 :: 		
$034E	$1303			BCF	STATUS, RP1
$034F	$1283			BCF	STATUS, RP0
$0350	$01A8			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,99 :: 		
$0351	$0847			MOVF	FARG_Lcd_Chr_CP, 0
$0352	$00D0			MOVWF	FARG_Lcd_Cmd
$0353	$21FE			CALL	_lcd_cmd
;lcd.ppas,100 :: 		
$0354	$3001			MOVLW	1
$0355	$00A8			MOVWF	lcd_lcdcmd_status
$0356	$	lcd_L_48:
;lcd.ppas,101 :: 		
$0356	$0008			RETURN
$033D	$	_div_8x8_u:
$033D	$1303			BCF	STATUS, RP1
$033E	$1283			BCF	STATUS, RP0
;math.ppas,88 :: 		
;math.ppas,90 :: 		
$033F	$01F8			CLRF	STACK_8, F
;math.ppas,91 :: 		
$0340	$3008			MOVLW	8
;math.ppas,92 :: 		
$0341	$00FC			MOVWF	STACK_12
;math.ppas,93 :: 		
$0342	$0D70			RLF	STACK_0, W
;math.ppas,94 :: 		
$0343	$0DF8			RLF	STACK_8, F
;math.ppas,95 :: 		
$0344	$0874			MOVF	STACK_4, W
;math.ppas,96 :: 		
$0345	$02F8			SUBWF	STACK_8, F
;math.ppas,97 :: 		
$0346	$1803			BTFSC	STATUS, C
;math.ppas,98 :: 		
$0347	$2B4A			GOTO	$+3
;math.ppas,99 :: 		
$0348	$07F8			ADDWF	STACK_8, F
;math.ppas,100 :: 		
$0349	$1003			BCF	STATUS, C
;math.ppas,101 :: 		
$034A	$0DF0			RLF	STACK_0, F
;math.ppas,102 :: 		
$034B	$0BFC			DECFSZ	STACK_12, F
;math.ppas,103 :: 		
$034C	$2B42			GOTO	$-10
;math.ppas,104 :: 		
$034D	$	math_L_2:
;math.ppas,105 :: 		
$034D	$0008			RETURN
$0357	$	_init:
;Exercice3.ppas,4 :: 		begin
;Exercice3.ppas,5 :: 		TRISC:=$ff;
$0357	$30FF			MOVLW	255
$0358	$1303			BCF	STATUS, RP1
$0359	$1683			BSF	STATUS, RP0
$035A	$0087			MOVWF	TRISC
;Exercice3.ppas,6 :: 		TRISB:=$00;
$035B	$0186			CLRF	TRISB, 1
;Exercice3.ppas,7 :: 		PORTB:=$00;
$035C	$1283			BCF	STATUS, RP0
$035D	$0186			CLRF	PORTB, 1
$035E	$	Exercice3_L_0:
;Exercice3.ppas,8 :: 		end;
$035E	$0008			RETURN
$0316	$	_lcd_init:
;lcd.ppas,246 :: 		
;lcd.ppas,247 :: 		
$0316	$1303			BCF	STATUS, RP1
$0317	$1283			BCF	STATUS, RP0
$0318	$0843			MOVF	FARG_Lcd_Init, 0
$0319	$00C7			MOVWF	FARG_Lcd_Config
$031A	$3007			MOVLW	7
$031B	$00C8			MOVWF	FARG_Lcd_Config+1
$031C	$3006			MOVLW	6
$031D	$00C9			MOVWF	FARG_Lcd_Config+2
$031E	$3005			MOVLW	5
$031F	$00CA			MOVWF	FARG_Lcd_Config+3
$0320	$3004			MOVLW	4
$0321	$00CB			MOVWF	FARG_Lcd_Config+4
$0322	$0843			MOVF	FARG_Lcd_Init, 0
$0323	$00CC			MOVWF	FARG_Lcd_Config+5
$0324	$3002			MOVLW	2
$0325	$00CD			MOVWF	FARG_Lcd_Config+6
$0326	$01CE			CLRF	FARG_Lcd_Config+7, 1
$0327	$3003			MOVLW	3
$0328	$00CF			MOVWF	FARG_Lcd_Config+8
$0329	$2004			CALL	_lcd_config
$032A	$	lcd_L_64:
;lcd.ppas,248 :: 		
$032A	$0008			RETURN
$02A5	$	_lcd_out:
;lcd.ppas,252 :: 		
;lcd.ppas,254 :: 		
$02A5	$	lcd_L_68:
$02A5	$1303			BCF	STATUS, RP1
$02A6	$1283			BCF	STATUS, RP0
$02A7	$0843			MOVF	FARG_Lcd_Out, 0
$02A8	$3A01			XORLW	1
$02A9	$1D03			BTFSS	STATUS, Z
$02AA	$2AAE			GOTO	lcd_L_69
$02AB	$	lcd_L_67:
$02AB	$3080			MOVLW	128
$02AC	$00C3			MOVWF	FARG_Lcd_Out
$02AD	$2AC5			GOTO	lcd_L_66
$02AE	$	lcd_L_69:
;lcd.ppas,255 :: 		
$02AE	$	lcd_L_71:
$02AE	$0843			MOVF	FARG_Lcd_Out, 0
$02AF	$3A02			XORLW	2
$02B0	$1D03			BTFSS	STATUS, Z
$02B1	$2AB5			GOTO	lcd_L_72
$02B2	$	lcd_L_70:
$02B2	$30C0			MOVLW	192
$02B3	$00C3			MOVWF	FARG_Lcd_Out
$02B4	$2AC5			GOTO	lcd_L_66
$02B5	$	lcd_L_72:
;lcd.ppas,256 :: 		
$02B5	$	lcd_L_74:
$02B5	$0843			MOVF	FARG_Lcd_Out, 0
$02B6	$3A03			XORLW	3
$02B7	$1D03			BTFSS	STATUS, Z
$02B8	$2ABC			GOTO	lcd_L_75
$02B9	$	lcd_L_73:
$02B9	$3094			MOVLW	148
$02BA	$00C3			MOVWF	FARG_Lcd_Out
$02BB	$2AC5			GOTO	lcd_L_66
$02BC	$	lcd_L_75:
;lcd.ppas,257 :: 		
$02BC	$	lcd_L_77:
$02BC	$0843			MOVF	FARG_Lcd_Out, 0
$02BD	$3A04			XORLW	4
$02BE	$1D03			BTFSS	STATUS, Z
$02BF	$2AC3			GOTO	lcd_L_78
$02C0	$	lcd_L_76:
$02C0	$30D4			MOVLW	212
$02C1	$00C3			MOVWF	FARG_Lcd_Out
;lcd.ppas,258 :: 		
$02C2	$2AC5			GOTO	lcd_L_66
$02C3	$	lcd_L_78:
$02C3	$3080			MOVLW	128
$02C4	$00C3			MOVWF	FARG_Lcd_Out
$02C5	$	lcd_L_66:
;lcd.ppas,260 :: 		
$02C5	$0344			DECF	FARG_Lcd_Out+1, 0
$02C6	$00F0			MOVWF	STACK_0
$02C7	$0843			MOVF	FARG_Lcd_Out, 0
$02C8	$07F0			ADDWF	STACK_0, 1
$02C9	$0870			MOVF	STACK_0, 0
$02CA	$00C3			MOVWF	FARG_Lcd_Out
;lcd.ppas,261 :: 		
$02CB	$0870			MOVF	STACK_0, 0
$02CC	$00D0			MOVWF	FARG_Lcd_Cmd
$02CD	$21FE			CALL	_lcd_cmd
;lcd.ppas,262 :: 		
$02CE	$01A8			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,263 :: 		
$02CF	$01C6			CLRF	_lcd_out_local_i, 1
;lcd.ppas,264 :: 		
$02D0	$	lcd_L_80:
$02D0	$0846			MOVF	_lcd_out_local_i, 0
$02D1	$0745			ADDWF	FARG_Lcd_Out+2, 0
$02D2	$0084			MOVWF	FSR
$02D3	$0800			MOVF	INDF, 0
$02D4	$00F2			MOVWF	STACK_2
$02D5	$0872			MOVF	STACK_2, 0
$02D6	$3A00			XORLW	0
$02D7	$1903			BTFSC	STATUS, Z
$02D8	$2AE1			GOTO	lcd_L_81
;lcd.ppas,266 :: 		
$02D9	$0846			MOVF	_lcd_out_local_i, 0
$02DA	$0745			ADDWF	FARG_Lcd_Out+2, 0
$02DB	$0084			MOVWF	FSR
$02DC	$0800			MOVF	INDF, 0
$02DD	$00C7			MOVWF	FARG_Lcd_Chr_CP
$02DE	$234E			CALL	_lcd_chr_cp
;lcd.ppas,267 :: 		
$02DF	$0AC6			INCF	_lcd_out_local_i, 1
;lcd.ppas,268 :: 		
$02E0	$2AD0			GOTO	lcd_L_80
$02E1	$	lcd_L_81:
;lcd.ppas,269 :: 		
$02E1	$3001			MOVLW	1
$02E2	$00A8			MOVWF	lcd_lcdcmd_status
$02E3	$	lcd_L_65:
;lcd.ppas,270 :: 		
$02E3	$0008			RETURN
$02E4	$	_bytetostr:
;conv.ppas,8 :: 		
;conv.ppas,9 :: 		
$02E4	$3001			MOVLW	1
$02E5	$1303			BCF	STATUS, RP1
$02E6	$1283			BCF	STATUS, RP0
$02E7	$00C5			MOVWF	_bytetostr_local_len
;conv.ppas,10 :: 		
$02E8	$0843			MOVF	FARG_ByteToStr, 0
$02E9	$3C09			SUBLW	9
$02EA	$1803			BTFSC	STATUS, C
$02EB	$2AED			GOTO	conv_L_2
$02EC	$	conv_L_1:
;conv.ppas,11 :: 		
$02EC	$0AC5			INCF	_bytetostr_local_len, 1
$02ED	$	conv_L_2:
$02ED	$	conv_L_3:
;conv.ppas,12 :: 		
$02ED	$0843			MOVF	FARG_ByteToStr, 0
$02EE	$3C63			SUBLW	99
$02EF	$1803			BTFSC	STATUS, C
$02F0	$2AF2			GOTO	conv_L_5
$02F1	$	conv_L_4:
;conv.ppas,13 :: 		
$02F1	$0AC5			INCF	_bytetostr_local_len, 1
$02F2	$	conv_L_5:
$02F2	$	conv_L_6:
;conv.ppas,14 :: 		
$02F2	$0844			MOVF	FARG_ByteToStr+1, 0
$02F3	$0084			MOVWF	FSR
$02F4	$3020			MOVLW	32
$02F5	$0080			MOVWF	INDF
$02F6	$0A84			INCF	FSR, 1
$02F7	$0080			MOVWF	INDF
$02F8	$0A84			INCF	FSR, 1
$02F9	$0080			MOVWF	INDF
$02FA	$0A84			INCF	FSR, 1
$02FB	$0180			CLRF	INDF
;conv.ppas,15 :: 		
$02FC	$0384			DECF	FSR, 1
;conv.ppas,17 :: 		
$02FD	$	conv_L_9:
$02FD	$0845			MOVF	_bytetostr_local_len, 0
$02FE	$3C00			SUBLW	0
$02FF	$1803			BTFSC	STATUS, C
$0300	$2B15			GOTO	conv_L_10
;conv.ppas,19 :: 		
$0301	$300A			MOVLW	10
$0302	$00F4			MOVWF	STACK_4
$0303	$0843			MOVF	FARG_ByteToStr, 0
$0304	$00F0			MOVWF	STACK_0
$0305	$233D			CALL	_div_8x8_u
$0306	$0878			MOVF	STACK_8, 0
$0307	$00F0			MOVWF	STACK_0
$0308	$3030			MOVLW	48
$0309	$0770			ADDWF	STACK_0, 0
$030A	$0080			MOVWF	INDF
;conv.ppas,20 :: 		
;conv.ppas,21 :: 		
$030B	$0384			DECF	FSR, 1
;conv.ppas,22 :: 		
$030C	$300A			MOVLW	10
$030D	$00F4			MOVWF	STACK_4
$030E	$0843			MOVF	FARG_ByteToStr, 0
$030F	$00F0			MOVWF	STACK_0
$0310	$233D			CALL	_div_8x8_u
$0311	$0870			MOVF	STACK_0, 0
$0312	$00C3			MOVWF	FARG_ByteToStr
;conv.ppas,23 :: 		
$0313	$03C5			DECF	_bytetostr_local_len, 1
;conv.ppas,24 :: 		
$0314	$2AFD			GOTO	conv_L_9
$0315	$	conv_L_10:
$0315	$	conv_L_0:
;conv.ppas,26 :: 		
$0315	$0008			RETURN
$0123	$	_main:
;Exercice3.ppas,11 :: 		begin
;Exercice3.ppas,12 :: 		init();
$0123	$2357			CALL	_init
;Exercice3.ppas,13 :: 		Lcd_Init(PORTB);
$0124	$3006			MOVLW	PORTB
$0125	$00C3			MOVWF	FARG_Lcd_Init
$0126	$2316			CALL	_lcd_init
;Exercice3.ppas,14 :: 		Lcd_Cmd(LCD_CURSOR_OFF);
$0127	$300C			MOVLW	12
$0128	$00D0			MOVWF	FARG_Lcd_Cmd
$0129	$21FE			CALL	_lcd_cmd
;Exercice3.ppas,15 :: 		Lcd_Out(1,3,'SEM2 ISET NABEUL');
$012A	$3001			MOVLW	1
$012B	$00C3			MOVWF	FARG_Lcd_Out
$012C	$3003			MOVLW	3
$012D	$00C4			MOVWF	FARG_Lcd_Out+1
$012E	$3053			MOVLW	83
$012F	$00B0			MOVWF	?main_Local_Text+0
$0130	$3045			MOVLW	69
$0131	$00B1			MOVWF	?main_Local_Text+1
$0132	$304D			MOVLW	77
$0133	$00B2			MOVWF	?main_Local_Text+2
$0134	$3032			MOVLW	50
$0135	$00B3			MOVWF	?main_Local_Text+3
$0136	$3020			MOVLW	32
$0137	$00B4			MOVWF	?main_Local_Text+4
$0138	$3049			MOVLW	73
$0139	$00B5			MOVWF	?main_Local_Text+5
$013A	$3053			MOVLW	83
$013B	$00B6			MOVWF	?main_Local_Text+6
$013C	$3045			MOVLW	69
$013D	$00B7			MOVWF	?main_Local_Text+7
$013E	$3054			MOVLW	84
$013F	$00B8			MOVWF	?main_Local_Text+8
$0140	$3020			MOVLW	32
$0141	$00B9			MOVWF	?main_Local_Text+9
$0142	$304E			MOVLW	78
$0143	$00BA			MOVWF	?main_Local_Text+10
$0144	$3041			MOVLW	65
$0145	$00BB			MOVWF	?main_Local_Text+11
$0146	$3042			MOVLW	66
$0147	$00BC			MOVWF	?main_Local_Text+12
$0148	$3045			MOVLW	69
$0149	$00BD			MOVWF	?main_Local_Text+13
$014A	$3055			MOVLW	85
$014B	$00BE			MOVWF	?main_Local_Text+14
$014C	$304C			MOVLW	76
$014D	$00BF			MOVWF	?main_Local_Text+15
$014E	$01C0			CLRF	?main_Local_Text+16
$014F	$3030			MOVLW	?main_Local_Text
$0150	$00C5			MOVWF	FARG_Lcd_Out+2
$0151	$22A5			CALL	_lcd_out
;Exercice3.ppas,16 :: 		Lcd_Out(2,2,'TP3 ARCH ET SYST 2');
$0152	$3002			MOVLW	2
$0153	$00C3			MOVWF	FARG_Lcd_Out
$0154	$3002			MOVLW	2
$0155	$00C4			MOVWF	FARG_Lcd_Out+1
$0156	$3054			MOVLW	84
$0157	$00B0			MOVWF	?main_Local_Text+0
$0158	$3050			MOVLW	80
$0159	$00B1			MOVWF	?main_Local_Text+1
$015A	$3033			MOVLW	51
$015B	$00B2			MOVWF	?main_Local_Text+2
$015C	$3020			MOVLW	32
$015D	$00B3			MOVWF	?main_Local_Text+3
$015E	$3041			MOVLW	65
$015F	$00B4			MOVWF	?main_Local_Text+4
$0160	$3052			MOVLW	82
$0161	$00B5			MOVWF	?main_Local_Text+5
$0162	$3043			MOVLW	67
$0163	$00B6			MOVWF	?main_Local_Text+6
$0164	$3048			MOVLW	72
$0165	$00B7			MOVWF	?main_Local_Text+7
$0166	$3020			MOVLW	32
$0167	$00B8			MOVWF	?main_Local_Text+8
$0168	$3045			MOVLW	69
$0169	$00B9			MOVWF	?main_Local_Text+9
$016A	$3054			MOVLW	84
$016B	$00BA			MOVWF	?main_Local_Text+10
$016C	$3020			MOVLW	32
$016D	$00BB			MOVWF	?main_Local_Text+11
$016E	$3053			MOVLW	83
$016F	$00BC			MOVWF	?main_Local_Text+12
$0170	$3059			MOVLW	89
$0171	$00BD			MOVWF	?main_Local_Text+13
$0172	$3053			MOVLW	83
$0173	$00BE			MOVWF	?main_Local_Text+14
$0174	$3054			MOVLW	84
$0175	$00BF			MOVWF	?main_Local_Text+15
$0176	$3020			MOVLW	32
$0177	$00C0			MOVWF	?main_Local_Text+16
$0178	$3032			MOVLW	50
$0179	$00C1			MOVWF	?main_Local_Text+17
$017A	$01C2			CLRF	?main_Local_Text+18
$017B	$3030			MOVLW	?main_Local_Text
$017C	$00C5			MOVWF	FARG_Lcd_Out+2
$017D	$22A5			CALL	_lcd_out
;Exercice3.ppas,18 :: 		delay_ms(2000);
$017E	$3015			MOVLW	21
$017F	$00FC			MOVWF	STACK_12
$0180	$30FF			MOVLW	255
$0181	$00FB			MOVWF	STACK_11
$0182	$30FF			MOVLW	255
$0183	$00FA			MOVWF	STACK_10
$0184	$0BFC			DECFSZ	STACK_12, F
$0185	$2987			GOTO	$+2
$0186	$298E			GOTO	$+8
$0187	$0BFB			DECFSZ	STACK_11, F
$0188	$298A			GOTO	$+2
$0189	$298D			GOTO	$+4
$018A	$0BFA			DECFSZ	STACK_10, F
$018B	$298A			GOTO	$-1
$018C	$2987			GOTO	$-5
$018D	$2984			GOTO	$-9
$018E	$3066			MOVLW	102
$018F	$00FB			MOVWF	STACK_11
$0190	$30FF			MOVLW	255
$0191	$00FA			MOVWF	STACK_10
$0192	$0BFB			DECFSZ	STACK_11, F
$0193	$2995			GOTO	$+2
$0194	$2998			GOTO	$+4
$0195	$0BFA			DECFSZ	STACK_10, F
$0196	$2995			GOTO	$-1
$0197	$2992			GOTO	$-5
$0198	$3012			MOVLW	18
$0199	$00FA			MOVWF	STACK_10
$019A	$0BFA			DECFSZ	STACK_10, F
$019B	$299A			GOTO	$-1
$019C	$0000			NOP
$019D	$0000			NOP
;Exercice3.ppas,19 :: 		Lcd_Cmd(LCD_clear);
$019E	$3001			MOVLW	1
$019F	$00D0			MOVWF	FARG_Lcd_Cmd
$01A0	$21FE			CALL	_lcd_cmd
;Exercice3.ppas,22 :: 		i:=0;
$01A1	$01AA			CLRF	_i, 1
;Exercice3.ppas,23 :: 		Lcd_Out(1,1,'Nbr Voitures :');
$01A2	$3001			MOVLW	1
$01A3	$00C3			MOVWF	FARG_Lcd_Out
$01A4	$3001			MOVLW	1
$01A5	$00C4			MOVWF	FARG_Lcd_Out+1
$01A6	$304E			MOVLW	78
$01A7	$00B0			MOVWF	?main_Local_Text+0
$01A8	$3062			MOVLW	98
$01A9	$00B1			MOVWF	?main_Local_Text+1
$01AA	$3072			MOVLW	114
$01AB	$00B2			MOVWF	?main_Local_Text+2
$01AC	$3020			MOVLW	32
$01AD	$00B3			MOVWF	?main_Local_Text+3
$01AE	$3056			MOVLW	86
$01AF	$00B4			MOVWF	?main_Local_Text+4
$01B0	$306F			MOVLW	111
$01B1	$00B5			MOVWF	?main_Local_Text+5
$01B2	$3069			MOVLW	105
$01B3	$00B6			MOVWF	?main_Local_Text+6
$01B4	$3074			MOVLW	116
$01B5	$00B7			MOVWF	?main_Local_Text+7
$01B6	$3075			MOVLW	117
$01B7	$00B8			MOVWF	?main_Local_Text+8
$01B8	$3072			MOVLW	114
$01B9	$00B9			MOVWF	?main_Local_Text+9
$01BA	$3065			MOVLW	101
$01BB	$00BA			MOVWF	?main_Local_Text+10
$01BC	$3073			MOVLW	115
$01BD	$00BB			MOVWF	?main_Local_Text+11
$01BE	$3020			MOVLW	32
$01BF	$00BC			MOVWF	?main_Local_Text+12
$01C0	$303A			MOVLW	58
$01C1	$00BD			MOVWF	?main_Local_Text+13
$01C2	$01BE			CLRF	?main_Local_Text+14
$01C3	$3030			MOVLW	?main_Local_Text
$01C4	$00C5			MOVWF	FARG_Lcd_Out+2
$01C5	$22A5			CALL	_lcd_out
;Exercice3.ppas,24 :: 		while (true) do
$01C6	$	Exercice3_L_3:
;Exercice3.ppas,26 :: 		if(PORTC.0=1) then
$01C6	$0807			MOVF	PORTC, 0
$01C7	$00F1			MOVWF	STACK_1
$01C8	$3001			MOVLW	1
$01C9	$05F1			ANDWF	STACK_1, 1
$01CA	$0871			MOVF	STACK_1, 0
$01CB	$3A01			XORLW	1
$01CC	$1D03			BTFSS	STATUS, Z
$01CD	$29FC			GOTO	Exercice3_L_8
$01CE	$	Exercice3_L_7:
;Exercice3.ppas,28 :: 		i:=i+1;
$01CE	$0A2A			INCF	_i, 0
$01CF	$00F0			MOVWF	STACK_0
$01D0	$0870			MOVF	STACK_0, 0
$01D1	$00AA			MOVWF	_i
;Exercice3.ppas,29 :: 		ByteToStr(i , nbr);
$01D2	$0870			MOVF	STACK_0, 0
$01D3	$00C3			MOVWF	FARG_ByteToStr
$01D4	$302B			MOVLW	_nbr
$01D5	$00C4			MOVWF	FARG_ByteToStr+1
$01D6	$22E4			CALL	_bytetostr
;Exercice3.ppas,30 :: 		Lcd_Out(2,1,nbr);
$01D7	$3002			MOVLW	2
$01D8	$00C3			MOVWF	FARG_Lcd_Out
$01D9	$3001			MOVLW	1
$01DA	$00C4			MOVWF	FARG_Lcd_Out+1
$01DB	$302B			MOVLW	_nbr
$01DC	$00C5			MOVWF	FARG_Lcd_Out+2
$01DD	$22A5			CALL	_lcd_out
;Exercice3.ppas,31 :: 		delay_ms(1000);
$01DE	$300B			MOVLW	11
$01DF	$00FC			MOVWF	STACK_12
$01E0	$30FF			MOVLW	255
$01E1	$00FB			MOVWF	STACK_11
$01E2	$30FF			MOVLW	255
$01E3	$00FA			MOVWF	STACK_10
$01E4	$0BFC			DECFSZ	STACK_12, F
$01E5	$29E7			GOTO	$+2
$01E6	$29EE			GOTO	$+8
$01E7	$0BFB			DECFSZ	STACK_11, F
$01E8	$29EA			GOTO	$+2
$01E9	$29ED			GOTO	$+4
$01EA	$0BFA			DECFSZ	STACK_10, F
$01EB	$29EA			GOTO	$-1
$01EC	$29E7			GOTO	$-5
$01ED	$29E4			GOTO	$-9
$01EE	$3033			MOVLW	51
$01EF	$00FB			MOVWF	STACK_11
$01F0	$30FF			MOVLW	255
$01F1	$00FA			MOVWF	STACK_10
$01F2	$0BFB			DECFSZ	STACK_11, F
$01F3	$29F5			GOTO	$+2
$01F4	$29F8			GOTO	$+4
$01F5	$0BFA			DECFSZ	STACK_10, F
$01F6	$29F5			GOTO	$-1
$01F7	$29F2			GOTO	$-5
$01F8	$3088			MOVLW	136
$01F9	$00FA			MOVWF	STACK_10
$01FA	$0BFA			DECFSZ	STACK_10, F
$01FB	$29FA			GOTO	$-1
;Exercice3.ppas,32 :: 		end;
$01FC	$	Exercice3_L_8:
$01FC	$	Exercice3_L_9:
;Exercice3.ppas,33 :: 		end;
$01FC	$29C6			GOTO	Exercice3_L_3
;Exercice3.ppas,36 :: 		end.
$01FD	$29FD			GOTO	$
