;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 4/5/2021 4:07:52 PM
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2923			GOTO	_main
$03FD	$	_delay_1us:
;delays.ppas,11 :: 		begin
;delays.ppas,12 :: 		Delay_us(1);
$03FD	$0000			NOP
$03FE	$0000			NOP
$03FF	$	delays_L_1:
;delays.ppas,13 :: 		end;
$03FF	$0008			RETURN
$03C6	$	_delay_5500us:
;delays.ppas,41 :: 		begin
;delays.ppas,42 :: 		Delay_us(5500);
$03C6	$300F			MOVLW	15
$03C7	$1303			BCF	STATUS, RP1
$03C8	$1283			BCF	STATUS, RP0
$03C9	$00FB			MOVWF	STACK_11
$03CA	$30FF			MOVLW	255
$03CB	$00FA			MOVWF	STACK_10
$03CC	$0BFB			DECFSZ	STACK_11, F
$03CD	$2BCF			GOTO	$+2
$03CE	$2BD2			GOTO	$+4
$03CF	$0BFA			DECFSZ	STACK_10, F
$03D0	$2BCF			GOTO	$-1
$03D1	$2BCC			GOTO	$-5
$03D2	$303E			MOVLW	62
$03D3	$00FA			MOVWF	STACK_10
$03D4	$0BFA			DECFSZ	STACK_10, F
$03D5	$2BD4			GOTO	$-1
$03D6	$0000			NOP
$03D7	$	delays_L_7:
;delays.ppas,43 :: 		end;
$03D7	$0008			RETURN
$03F1	$	_delay_50us:
;delays.ppas,26 :: 		begin
;delays.ppas,27 :: 		Delay_us(50);
$03F1	$3021			MOVLW	33
$03F2	$1303			BCF	STATUS, RP1
$03F3	$1283			BCF	STATUS, RP0
$03F4	$00FA			MOVWF	STACK_10
$03F5	$0BFA			DECFSZ	STACK_10, F
$03F6	$2BF5			GOTO	$-1
$03F7	$	delays_L_4:
;delays.ppas,28 :: 		end;
$03F7	$0008			RETURN
$01D3	$	_lcd_cmd:
;lcd.ppas,19 :: 		
;lcd.ppas,20 :: 		
$01D3	$1303			BCF	STATUS, RP1
$01D4	$1283			BCF	STATUS, RP0
$01D5	$0820			MOVF	lcd_ctrlport_address, 0
$01D6	$0084			MOVWF	FSR
;lcd.ppas,22 :: 		
$01D7	$0921			COMF	lcd____menable, W
$01D8	$00F0			MOVWF	STACK_0
$01D9	$0870			MOVF	STACK_0, 0
$01DA	$0580			ANDWF	INDF, 1
;lcd.ppas,23 :: 		
$01DB	$0922			COMF	lcd____mrs, W
$01DC	$00F0			MOVWF	STACK_0
$01DD	$0870			MOVF	STACK_0, 0
$01DE	$0580			ANDWF	INDF, 1
;lcd.ppas,25 :: 		
$01DF	$0823			MOVF	lcd_dataport_address, 0
$01E0	$0084			MOVWF	FSR
;lcd.ppas,26 :: 		
$01E1	$0825			MOVF	lcd____mdb6, 0
$01E2	$0424			IORWF	lcd____mdb7, 0
$01E3	$00F0			MOVWF	STACK_0
$01E4	$0826			MOVF	lcd____mdb5, 0
$01E5	$04F0			IORWF	STACK_0, 1
$01E6	$0827			MOVF	lcd____mdb4, 0
$01E7	$04F0			IORWF	STACK_0, 1
$01E8	$09F0			COMF	STACK_0, F
$01E9	$0870			MOVF	STACK_0, 0
$01EA	$0580			ANDWF	INDF, 1
;lcd.ppas,28 :: 		
$01EB	$3000			MOVLW	0
$01EC	$1BCC			BTFSC	FARG_Lcd_Cmd, 7
$01ED	$3001			MOVLW	1
$01EE	$00F1			MOVWF	STACK_1
$01EF	$0871			MOVF	STACK_1, 0
$01F0	$3A01			XORLW	1
$01F1	$1D03			BTFSS	STATUS, Z
$01F2	$29F5			GOTO	lcd_L_2
$01F3	$	lcd_L_1:
;lcd.ppas,29 :: 		
$01F3	$0824			MOVF	lcd____mdb7, 0
$01F4	$0480			IORWF	INDF, 1
$01F5	$	lcd_L_2:
$01F5	$	lcd_L_3:
;lcd.ppas,30 :: 		
$01F5	$3000			MOVLW	0
$01F6	$1B4C			BTFSC	FARG_Lcd_Cmd, 6
$01F7	$3001			MOVLW	1
$01F8	$00F1			MOVWF	STACK_1
$01F9	$0871			MOVF	STACK_1, 0
$01FA	$3A01			XORLW	1
$01FB	$1D03			BTFSS	STATUS, Z
$01FC	$29FF			GOTO	lcd_L_5
$01FD	$	lcd_L_4:
;lcd.ppas,31 :: 		
$01FD	$0825			MOVF	lcd____mdb6, 0
$01FE	$0480			IORWF	INDF, 1
$01FF	$	lcd_L_5:
$01FF	$	lcd_L_6:
;lcd.ppas,32 :: 		
$01FF	$3000			MOVLW	0
$0200	$1ACC			BTFSC	FARG_Lcd_Cmd, 5
$0201	$3001			MOVLW	1
$0202	$00F1			MOVWF	STACK_1
$0203	$0871			MOVF	STACK_1, 0
$0204	$3A01			XORLW	1
$0205	$1D03			BTFSS	STATUS, Z
$0206	$2A09			GOTO	lcd_L_8
$0207	$	lcd_L_7:
;lcd.ppas,33 :: 		
$0207	$0826			MOVF	lcd____mdb5, 0
$0208	$0480			IORWF	INDF, 1
$0209	$	lcd_L_8:
$0209	$	lcd_L_9:
;lcd.ppas,34 :: 		
$0209	$3000			MOVLW	0
$020A	$1A4C			BTFSC	FARG_Lcd_Cmd, 4
$020B	$3001			MOVLW	1
$020C	$00F1			MOVWF	STACK_1
$020D	$0871			MOVF	STACK_1, 0
$020E	$3A01			XORLW	1
$020F	$1D03			BTFSS	STATUS, Z
$0210	$2A13			GOTO	lcd_L_11
$0211	$	lcd_L_10:
;lcd.ppas,35 :: 		
$0211	$0827			MOVF	lcd____mdb4, 0
$0212	$0480			IORWF	INDF, 1
$0213	$	lcd_L_11:
$0213	$	lcd_L_12:
;lcd.ppas,37 :: 		
$0213	$0820			MOVF	lcd_ctrlport_address, 0
$0214	$0084			MOVWF	FSR
;lcd.ppas,38 :: 		
$0215	$0828			MOVF	lcd_lcdcmd_status, 0
$0216	$3A01			XORLW	1
$0217	$1D03			BTFSS	STATUS, Z
$0218	$2A1E			GOTO	lcd_L_14
$0219	$	lcd_L_13:
;lcd.ppas,39 :: 		
$0219	$0922			COMF	lcd____mrs, W
$021A	$00F0			MOVWF	STACK_0
$021B	$0870			MOVF	STACK_0, 0
$021C	$0580			ANDWF	INDF, 1
$021D	$2A20			GOTO	lcd_L_15
;lcd.ppas,40 :: 		
$021E	$	lcd_L_14:
;lcd.ppas,41 :: 		
$021E	$0822			MOVF	lcd____mrs, 0
$021F	$0480			IORWF	INDF, 1
$0220	$	lcd_L_15:
;lcd.ppas,43 :: 		
$0220	$0821			MOVF	lcd____menable, 0
$0221	$0480			IORWF	INDF, 1
;lcd.ppas,44 :: 		
$0222	$23FD			CALL	_delay_1us
;lcd.ppas,45 :: 		
$0223	$0921			COMF	lcd____menable, W
$0224	$00F0			MOVWF	STACK_0
$0225	$0870			MOVF	STACK_0, 0
$0226	$0580			ANDWF	INDF, 1
;lcd.ppas,47 :: 		
$0227	$0922			COMF	lcd____mrs, W
$0228	$00F0			MOVWF	STACK_0
$0229	$0870			MOVF	STACK_0, 0
$022A	$0580			ANDWF	INDF, 1
;lcd.ppas,49 :: 		
$022B	$0823			MOVF	lcd_dataport_address, 0
$022C	$0084			MOVWF	FSR
;lcd.ppas,50 :: 		
$022D	$0825			MOVF	lcd____mdb6, 0
$022E	$0424			IORWF	lcd____mdb7, 0
$022F	$00F0			MOVWF	STACK_0
$0230	$0826			MOVF	lcd____mdb5, 0
$0231	$04F0			IORWF	STACK_0, 1
$0232	$0827			MOVF	lcd____mdb4, 0
$0233	$04F0			IORWF	STACK_0, 1
$0234	$09F0			COMF	STACK_0, F
$0235	$0870			MOVF	STACK_0, 0
$0236	$0580			ANDWF	INDF, 1
;lcd.ppas,52 :: 		
$0237	$3000			MOVLW	0
$0238	$19CC			BTFSC	FARG_Lcd_Cmd, 3
$0239	$3001			MOVLW	1
$023A	$00F1			MOVWF	STACK_1
$023B	$0871			MOVF	STACK_1, 0
$023C	$3A01			XORLW	1
$023D	$1D03			BTFSS	STATUS, Z
$023E	$2A41			GOTO	lcd_L_17
$023F	$	lcd_L_16:
;lcd.ppas,53 :: 		
$023F	$0824			MOVF	lcd____mdb7, 0
$0240	$0480			IORWF	INDF, 1
$0241	$	lcd_L_17:
$0241	$	lcd_L_18:
;lcd.ppas,54 :: 		
$0241	$3000			MOVLW	0
$0242	$194C			BTFSC	FARG_Lcd_Cmd, 2
$0243	$3001			MOVLW	1
$0244	$00F1			MOVWF	STACK_1
$0245	$0871			MOVF	STACK_1, 0
$0246	$3A01			XORLW	1
$0247	$1D03			BTFSS	STATUS, Z
$0248	$2A4B			GOTO	lcd_L_20
$0249	$	lcd_L_19:
;lcd.ppas,55 :: 		
$0249	$0825			MOVF	lcd____mdb6, 0
$024A	$0480			IORWF	INDF, 1
$024B	$	lcd_L_20:
$024B	$	lcd_L_21:
;lcd.ppas,56 :: 		
$024B	$3000			MOVLW	0
$024C	$18CC			BTFSC	FARG_Lcd_Cmd, 1
$024D	$3001			MOVLW	1
$024E	$00F1			MOVWF	STACK_1
$024F	$0871			MOVF	STACK_1, 0
$0250	$3A01			XORLW	1
$0251	$1D03			BTFSS	STATUS, Z
$0252	$2A55			GOTO	lcd_L_23
$0253	$	lcd_L_22:
;lcd.ppas,57 :: 		
$0253	$0826			MOVF	lcd____mdb5, 0
$0254	$0480			IORWF	INDF, 1
$0255	$	lcd_L_23:
$0255	$	lcd_L_24:
;lcd.ppas,58 :: 		
$0255	$3001			MOVLW	1
$0256	$054C			ANDWF	FARG_Lcd_Cmd, 0
$0257	$00F1			MOVWF	STACK_1
$0258	$0871			MOVF	STACK_1, 0
$0259	$3A01			XORLW	1
$025A	$1D03			BTFSS	STATUS, Z
$025B	$2A5E			GOTO	lcd_L_26
$025C	$	lcd_L_25:
;lcd.ppas,59 :: 		
$025C	$0827			MOVF	lcd____mdb4, 0
$025D	$0480			IORWF	INDF, 1
$025E	$	lcd_L_26:
$025E	$	lcd_L_27:
;lcd.ppas,61 :: 		
$025E	$0820			MOVF	lcd_ctrlport_address, 0
$025F	$0084			MOVWF	FSR
;lcd.ppas,62 :: 		
$0260	$0828			MOVF	lcd_lcdcmd_status, 0
$0261	$3A01			XORLW	1
$0262	$1D03			BTFSS	STATUS, Z
$0263	$2A69			GOTO	lcd_L_29
$0264	$	lcd_L_28:
;lcd.ppas,63 :: 		
$0264	$0922			COMF	lcd____mrs, W
$0265	$00F0			MOVWF	STACK_0
$0266	$0870			MOVF	STACK_0, 0
$0267	$0580			ANDWF	INDF, 1
$0268	$2A6B			GOTO	lcd_L_30
;lcd.ppas,64 :: 		
$0269	$	lcd_L_29:
;lcd.ppas,65 :: 		
$0269	$0822			MOVF	lcd____mrs, 0
$026A	$0480			IORWF	INDF, 1
$026B	$	lcd_L_30:
;lcd.ppas,67 :: 		
$026B	$0821			MOVF	lcd____menable, 0
$026C	$0480			IORWF	INDF, 1
;lcd.ppas,68 :: 		
$026D	$23FD			CALL	_delay_1us
;lcd.ppas,69 :: 		
$026E	$0921			COMF	lcd____menable, W
$026F	$00F0			MOVWF	STACK_0
$0270	$0870			MOVF	STACK_0, 0
$0271	$0580			ANDWF	INDF, 1
;lcd.ppas,71 :: 		
$0272	$0828			MOVF	lcd_lcdcmd_status, 0
$0273	$3A01			XORLW	1
$0274	$1D03			BTFSS	STATUS, Z
$0275	$2A78			GOTO	lcd_L_32
$0276	$	lcd_L_31:
;lcd.ppas,72 :: 		
$0276	$23C6			CALL	_delay_5500us
$0277	$2A79			GOTO	lcd_L_33
;lcd.ppas,73 :: 		
$0278	$	lcd_L_32:
;lcd.ppas,74 :: 		
$0278	$23F1			CALL	_delay_50us
$0279	$	lcd_L_33:
$0279	$	lcd_L_0:
;lcd.ppas,75 :: 		
$0279	$0008			RETURN
$03E1	$	_delay_10us:
;delays.ppas,16 :: 		begin
;delays.ppas,17 :: 		Delay_us(10);
$03E1	$3006			MOVLW	6
$03E2	$1303			BCF	STATUS, RP1
$03E3	$1283			BCF	STATUS, RP0
$03E4	$00FA			MOVWF	STACK_10
$03E5	$0BFA			DECFSZ	STACK_10, F
$03E6	$2BE5			GOTO	$-1
$03E7	$0000			NOP
$03E8	$	delays_L_2:
;delays.ppas,18 :: 		end;
$03E8	$0008			RETURN
$0004	$	_lcd_config:
;lcd.ppas,115 :: 		
;lcd.ppas,116 :: 		
$0004	$23C6			CALL	_delay_5500us
;lcd.ppas,117 :: 		
$0005	$23C6			CALL	_delay_5500us
;lcd.ppas,118 :: 		
$0006	$23C6			CALL	_delay_5500us
;lcd.ppas,120 :: 		
$0007	$0844			MOVF	FARG_Lcd_Config+1, 0
$0008	$00F0			MOVWF	STACK_0
$0009	$3001			MOVLW	1
$000A	$00F4			MOVWF	STACK_4
$000B	$0870			MOVF	STACK_0, 0
$000C	$	L_Lcd_Config_0:
$000C	$1903			BTFSC	STATUS, Z
$000D	$2812			GOTO	L_Lcd_Config_1
$000E	$0DF4			RLF	STACK_4, 1
$000F	$1074			BCF	STACK_4, 0
$0010	$3FFF			ADDLW	255
$0011	$280C			GOTO	L_Lcd_Config_0
$0012	$	L_Lcd_Config_1:
$0012	$0874			MOVF	STACK_4, 0
$0013	$00A4			MOVWF	lcd____mdb7
;lcd.ppas,121 :: 		
$0014	$0845			MOVF	FARG_Lcd_Config+2, 0
$0015	$00F0			MOVWF	STACK_0
$0016	$3001			MOVLW	1
$0017	$00F3			MOVWF	STACK_3
$0018	$0870			MOVF	STACK_0, 0
$0019	$	L_Lcd_Config_2:
$0019	$1903			BTFSC	STATUS, Z
$001A	$281F			GOTO	L_Lcd_Config_3
$001B	$0DF3			RLF	STACK_3, 1
$001C	$1073			BCF	STACK_3, 0
$001D	$3FFF			ADDLW	255
$001E	$2819			GOTO	L_Lcd_Config_2
$001F	$	L_Lcd_Config_3:
$001F	$0873			MOVF	STACK_3, 0
$0020	$00A5			MOVWF	lcd____mdb6
;lcd.ppas,122 :: 		
$0021	$0846			MOVF	FARG_Lcd_Config+3, 0
$0022	$00F0			MOVWF	STACK_0
$0023	$3001			MOVLW	1
$0024	$00F2			MOVWF	STACK_2
$0025	$0870			MOVF	STACK_0, 0
$0026	$	L_Lcd_Config_4:
$0026	$1903			BTFSC	STATUS, Z
$0027	$282C			GOTO	L_Lcd_Config_5
$0028	$0DF2			RLF	STACK_2, 1
$0029	$1072			BCF	STACK_2, 0
$002A	$3FFF			ADDLW	255
$002B	$2826			GOTO	L_Lcd_Config_4
$002C	$	L_Lcd_Config_5:
$002C	$0872			MOVF	STACK_2, 0
$002D	$00A6			MOVWF	lcd____mdb5
;lcd.ppas,123 :: 		
$002E	$0847			MOVF	FARG_Lcd_Config+4, 0
$002F	$00F0			MOVWF	STACK_0
$0030	$3001			MOVLW	1
$0031	$00F1			MOVWF	STACK_1
$0032	$0870			MOVF	STACK_0, 0
$0033	$	L_Lcd_Config_6:
$0033	$1903			BTFSC	STATUS, Z
$0034	$2839			GOTO	L_Lcd_Config_7
$0035	$0DF1			RLF	STACK_1, 1
$0036	$1071			BCF	STACK_1, 0
$0037	$3FFF			ADDLW	255
$0038	$2833			GOTO	L_Lcd_Config_6
$0039	$	L_Lcd_Config_7:
$0039	$0871			MOVF	STACK_1, 0
$003A	$00A7			MOVWF	lcd____mdb4
;lcd.ppas,124 :: 		
$003B	$0849			MOVF	FARG_Lcd_Config+6, 0
$003C	$00F0			MOVWF	STACK_0
$003D	$3001			MOVLW	1
$003E	$00A2			MOVWF	lcd____mrs
$003F	$0870			MOVF	STACK_0, 0
$0040	$	L_Lcd_Config_8:
$0040	$1903			BTFSC	STATUS, Z
$0041	$2846			GOTO	L_Lcd_Config_9
$0042	$0DA2			RLF	lcd____mrs, 1
$0043	$1022			BCF	lcd____mrs, 0
$0044	$3FFF			ADDLW	255
$0045	$2840			GOTO	L_Lcd_Config_8
$0046	$	L_Lcd_Config_9:
;lcd.ppas,125 :: 		
$0046	$084A			MOVF	FARG_Lcd_Config+7, 0
$0047	$00F0			MOVWF	STACK_0
$0048	$3001			MOVLW	1
$0049	$00A9			MOVWF	lcd____mrw
$004A	$0870			MOVF	STACK_0, 0
$004B	$	L_Lcd_Config_10:
$004B	$1903			BTFSC	STATUS, Z
$004C	$2851			GOTO	L_Lcd_Config_11
$004D	$0DA9			RLF	lcd____mrw, 1
$004E	$1029			BCF	lcd____mrw, 0
$004F	$3FFF			ADDLW	255
$0050	$284B			GOTO	L_Lcd_Config_10
$0051	$	L_Lcd_Config_11:
;lcd.ppas,126 :: 		
$0051	$084B			MOVF	FARG_Lcd_Config+8, 0
$0052	$00F0			MOVWF	STACK_0
$0053	$3001			MOVLW	1
$0054	$00A1			MOVWF	lcd____menable
$0055	$0870			MOVF	STACK_0, 0
$0056	$	L_Lcd_Config_12:
$0056	$1903			BTFSC	STATUS, Z
$0057	$285C			GOTO	L_Lcd_Config_13
$0058	$0DA1			RLF	lcd____menable, 1
$0059	$1021			BCF	lcd____menable, 0
$005A	$3FFF			ADDLW	255
$005B	$2856			GOTO	L_Lcd_Config_12
$005C	$	L_Lcd_Config_13:
;lcd.ppas,128 :: 		
$005C	$0843			MOVF	FARG_Lcd_Config, 0
$005D	$00A3			MOVWF	lcd_dataport_address
;lcd.ppas,129 :: 		
$005E	$0848			MOVF	FARG_Lcd_Config+5, 0
$005F	$00A0			MOVWF	lcd_ctrlport_address
;lcd.ppas,131 :: 		
$0060	$0843			MOVF	FARG_Lcd_Config, 0
$0061	$0084			MOVWF	FSR
;lcd.ppas,133 :: 		
$0062	$0873			MOVF	STACK_3, 0
$0063	$0474			IORWF	STACK_4, 0
$0064	$00F0			MOVWF	STACK_0
$0065	$0872			MOVF	STACK_2, 0
$0066	$04F0			IORWF	STACK_0, 1
$0067	$0871			MOVF	STACK_1, 0
$0068	$04F0			IORWF	STACK_0, 1
$0069	$09F0			COMF	STACK_0, F
$006A	$0870			MOVF	STACK_0, 0
$006B	$0580			ANDWF	INDF, 1
;lcd.ppas,134 :: 		
$006C	$	lcd_L_56:
$006C	$1784			BSF	FSR, 7
$006D	$	lcd_L_57:
;lcd.ppas,135 :: 		
$006D	$0825			MOVF	lcd____mdb6, 0
$006E	$0424			IORWF	lcd____mdb7, 0
$006F	$00F0			MOVWF	STACK_0
$0070	$0826			MOVF	lcd____mdb5, 0
$0071	$04F0			IORWF	STACK_0, 1
$0072	$0827			MOVF	lcd____mdb4, 0
$0073	$04F0			IORWF	STACK_0, 1
$0074	$09F0			COMF	STACK_0, F
$0075	$0870			MOVF	STACK_0, 0
$0076	$0580			ANDWF	INDF, 1
;lcd.ppas,136 :: 		
$0077	$1384			BCF	FSR, 7
$0078	$	lcd_L_59:
;lcd.ppas,139 :: 		
$0078	$0820			MOVF	lcd_ctrlport_address, 0
$0079	$0084			MOVWF	FSR
;lcd.ppas,141 :: 		
$007A	$0829			MOVF	lcd____mrw, 0
$007B	$0422			IORWF	lcd____mrs, 0
$007C	$00F0			MOVWF	STACK_0
$007D	$0821			MOVF	lcd____menable, 0
$007E	$04F0			IORWF	STACK_0, 1
$007F	$09F0			COMF	STACK_0, F
$0080	$0870			MOVF	STACK_0, 0
$0081	$0580			ANDWF	INDF, 1
;lcd.ppas,142 :: 		
$0082	$	lcd_L_60:
$0082	$1784			BSF	FSR, 7
$0083	$	lcd_L_61:
;lcd.ppas,143 :: 		
$0083	$0829			MOVF	lcd____mrw, 0
$0084	$0422			IORWF	lcd____mrs, 0
$0085	$00F0			MOVWF	STACK_0
$0086	$0821			MOVF	lcd____menable, 0
$0087	$04F0			IORWF	STACK_0, 1
$0088	$09F0			COMF	STACK_0, F
$0089	$0870			MOVF	STACK_0, 0
$008A	$0580			ANDWF	INDF, 1
;lcd.ppas,144 :: 		
$008B	$1384			BCF	FSR, 7
$008C	$	lcd_L_63:
;lcd.ppas,148 :: 		
$008C	$0823			MOVF	lcd_dataport_address, 0
$008D	$0084			MOVWF	FSR
;lcd.ppas,149 :: 		
$008E	$0826			MOVF	lcd____mdb5, 0
$008F	$0400			IORWF	INDF, 0
$0090	$00F0			MOVWF	STACK_0
$0091	$0827			MOVF	lcd____mdb4, 0
$0092	$0470			IORWF	STACK_0, 0
$0093	$0080			MOVWF	INDF
;lcd.ppas,151 :: 		
$0094	$0820			MOVF	lcd_ctrlport_address, 0
$0095	$0084			MOVWF	FSR
;lcd.ppas,152 :: 		
$0096	$0821			MOVF	lcd____menable, 0
$0097	$0480			IORWF	INDF, 1
;lcd.ppas,153 :: 		
$0098	$0921			COMF	lcd____menable, W
$0099	$00F0			MOVWF	STACK_0
$009A	$0870			MOVF	STACK_0, 0
$009B	$0580			ANDWF	INDF, 1
;lcd.ppas,155 :: 		
$009C	$23C6			CALL	_delay_5500us
;lcd.ppas,160 :: 		
$009D	$0821			MOVF	lcd____menable, 0
$009E	$0480			IORWF	INDF, 1
;lcd.ppas,161 :: 		
$009F	$0921			COMF	lcd____menable, W
$00A0	$00F0			MOVWF	STACK_0
$00A1	$0870			MOVF	STACK_0, 0
$00A2	$0580			ANDWF	INDF, 1
;lcd.ppas,163 :: 		
$00A3	$23C6			CALL	_delay_5500us
;lcd.ppas,168 :: 		
$00A4	$0821			MOVF	lcd____menable, 0
$00A5	$0480			IORWF	INDF, 1
;lcd.ppas,169 :: 		
$00A6	$0921			COMF	lcd____menable, W
$00A7	$00F0			MOVWF	STACK_0
$00A8	$0870			MOVF	STACK_0, 0
$00A9	$0580			ANDWF	INDF, 1
;lcd.ppas,171 :: 		
$00AA	$23C6			CALL	_delay_5500us
;lcd.ppas,174 :: 		
$00AB	$0823			MOVF	lcd_dataport_address, 0
$00AC	$0084			MOVWF	FSR
;lcd.ppas,175 :: 		
$00AD	$0826			MOVF	lcd____mdb5, 0
$00AE	$0480			IORWF	INDF, 1
;lcd.ppas,176 :: 		
$00AF	$0927			COMF	lcd____mdb4, W
$00B0	$00F0			MOVWF	STACK_0
$00B1	$0870			MOVF	STACK_0, 0
$00B2	$0580			ANDWF	INDF, 1
;lcd.ppas,178 :: 		
$00B3	$0820			MOVF	lcd_ctrlport_address, 0
$00B4	$0084			MOVWF	FSR
;lcd.ppas,179 :: 		
$00B5	$0821			MOVF	lcd____menable, 0
$00B6	$0480			IORWF	INDF, 1
;lcd.ppas,180 :: 		
$00B7	$0921			COMF	lcd____menable, W
$00B8	$00F0			MOVWF	STACK_0
$00B9	$0870			MOVF	STACK_0, 0
$00BA	$0580			ANDWF	INDF, 1
;lcd.ppas,182 :: 		
$00BB	$23C6			CALL	_delay_5500us
;lcd.ppas,187 :: 		
$00BC	$0821			MOVF	lcd____menable, 0
$00BD	$0480			IORWF	INDF, 1
;lcd.ppas,188 :: 		
$00BE	$0921			COMF	lcd____menable, W
$00BF	$00F1			MOVWF	STACK_1
$00C0	$0871			MOVF	STACK_1, 0
$00C1	$0580			ANDWF	INDF, 1
;lcd.ppas,190 :: 		
$00C2	$0823			MOVF	lcd_dataport_address, 0
$00C3	$0084			MOVWF	FSR
;lcd.ppas,191 :: 		
$00C4	$0926			COMF	lcd____mdb5, W
$00C5	$00F0			MOVWF	STACK_0
$00C6	$0870			MOVF	STACK_0, 0
$00C7	$0580			ANDWF	INDF, 1
;lcd.ppas,192 :: 		
$00C8	$0824			MOVF	lcd____mdb7, 0
$00C9	$0480			IORWF	INDF, 1
;lcd.ppas,194 :: 		
$00CA	$0820			MOVF	lcd_ctrlport_address, 0
$00CB	$0084			MOVWF	FSR
;lcd.ppas,195 :: 		
$00CC	$0821			MOVF	lcd____menable, 0
$00CD	$0480			IORWF	INDF, 1
;lcd.ppas,196 :: 		
$00CE	$0871			MOVF	STACK_1, 0
$00CF	$0580			ANDWF	INDF, 1
;lcd.ppas,198 :: 		
$00D0	$23C6			CALL	_delay_5500us
;lcd.ppas,201 :: 		
$00D1	$0823			MOVF	lcd_dataport_address, 0
$00D2	$0084			MOVWF	FSR
;lcd.ppas,202 :: 		
$00D3	$0924			COMF	lcd____mdb7, W
$00D4	$00F0			MOVWF	STACK_0
$00D5	$0870			MOVF	STACK_0, 0
$00D6	$0580			ANDWF	INDF, 1
;lcd.ppas,203 :: 		
$00D7	$0827			MOVF	lcd____mdb4, 0
$00D8	$0480			IORWF	INDF, 1
;lcd.ppas,204 :: 		
$00D9	$0820			MOVF	lcd_ctrlport_address, 0
$00DA	$0084			MOVWF	FSR
;lcd.ppas,205 :: 		
$00DB	$0821			MOVF	lcd____menable, 0
$00DC	$0480			IORWF	INDF, 1
;lcd.ppas,206 :: 		
$00DD	$0921			COMF	lcd____menable, W
$00DE	$00F1			MOVWF	STACK_1
$00DF	$0871			MOVF	STACK_1, 0
$00E0	$0580			ANDWF	INDF, 1
;lcd.ppas,207 :: 		
$00E1	$0823			MOVF	lcd_dataport_address, 0
$00E2	$0084			MOVWF	FSR
;lcd.ppas,208 :: 		
$00E3	$0927			COMF	lcd____mdb4, W
$00E4	$00F0			MOVWF	STACK_0
$00E5	$0870			MOVF	STACK_0, 0
$00E6	$0580			ANDWF	INDF, 1
;lcd.ppas,209 :: 		
$00E7	$0820			MOVF	lcd_ctrlport_address, 0
$00E8	$0084			MOVWF	FSR
;lcd.ppas,210 :: 		
$00E9	$0821			MOVF	lcd____menable, 0
$00EA	$0480			IORWF	INDF, 1
;lcd.ppas,211 :: 		
$00EB	$0871			MOVF	STACK_1, 0
$00EC	$0580			ANDWF	INDF, 1
;lcd.ppas,213 :: 		
$00ED	$23C6			CALL	_delay_5500us
;lcd.ppas,218 :: 		
$00EE	$0821			MOVF	lcd____menable, 0
$00EF	$0480			IORWF	INDF, 1
;lcd.ppas,219 :: 		
$00F0	$0921			COMF	lcd____menable, W
$00F1	$00F0			MOVWF	STACK_0
$00F2	$0870			MOVF	STACK_0, 0
$00F3	$0580			ANDWF	INDF, 1
;lcd.ppas,220 :: 		
$00F4	$0823			MOVF	lcd_dataport_address, 0
$00F5	$0084			MOVWF	FSR
;lcd.ppas,221 :: 		
$00F6	$0827			MOVF	lcd____mdb4, 0
$00F7	$0480			IORWF	INDF, 1
;lcd.ppas,222 :: 		
$00F8	$0820			MOVF	lcd_ctrlport_address, 0
$00F9	$0084			MOVWF	FSR
;lcd.ppas,223 :: 		
$00FA	$0821			MOVF	lcd____menable, 0
$00FB	$0480			IORWF	INDF, 1
;lcd.ppas,224 :: 		
$00FC	$0870			MOVF	STACK_0, 0
$00FD	$0580			ANDWF	INDF, 1
;lcd.ppas,226 :: 		
$00FE	$23C6			CALL	_delay_5500us
;lcd.ppas,229 :: 		
$00FF	$0823			MOVF	lcd_dataport_address, 0
$0100	$0084			MOVWF	FSR
;lcd.ppas,230 :: 		
$0101	$0927			COMF	lcd____mdb4, W
$0102	$00F0			MOVWF	STACK_0
$0103	$0870			MOVF	STACK_0, 0
$0104	$0580			ANDWF	INDF, 1
;lcd.ppas,231 :: 		
$0105	$0820			MOVF	lcd_ctrlport_address, 0
$0106	$0084			MOVWF	FSR
;lcd.ppas,232 :: 		
$0107	$0821			MOVF	lcd____menable, 0
$0108	$0480			IORWF	INDF, 1
;lcd.ppas,233 :: 		
$0109	$0921			COMF	lcd____menable, W
$010A	$00F1			MOVWF	STACK_1
$010B	$0871			MOVF	STACK_1, 0
$010C	$0580			ANDWF	INDF, 1
;lcd.ppas,234 :: 		
$010D	$0823			MOVF	lcd_dataport_address, 0
$010E	$0084			MOVWF	FSR
;lcd.ppas,235 :: 		
$010F	$0827			MOVF	lcd____mdb4, 0
$0110	$0400			IORWF	INDF, 0
$0111	$00F0			MOVWF	STACK_0
$0112	$0826			MOVF	lcd____mdb5, 0
$0113	$04F0			IORWF	STACK_0, 1
$0114	$0825			MOVF	lcd____mdb6, 0
$0115	$04F0			IORWF	STACK_0, 1
$0116	$0824			MOVF	lcd____mdb7, 0
$0117	$0470			IORWF	STACK_0, 0
$0118	$0080			MOVWF	INDF
;lcd.ppas,236 :: 		
$0119	$0820			MOVF	lcd_ctrlport_address, 0
$011A	$0084			MOVWF	FSR
;lcd.ppas,237 :: 		
$011B	$0821			MOVF	lcd____menable, 0
$011C	$0480			IORWF	INDF, 1
;lcd.ppas,238 :: 		
$011D	$0871			MOVF	STACK_1, 0
$011E	$0580			ANDWF	INDF, 1
;lcd.ppas,240 :: 		
$011F	$23C6			CALL	_delay_5500us
;lcd.ppas,242 :: 		
$0120	$3001			MOVLW	1
$0121	$00A8			MOVWF	lcd_lcdcmd_status
$0122	$	lcd_L_55:
;lcd.ppas,243 :: 		
$0122	$0008			RETURN
$03D8	$	_lcd_chr_cp:
;lcd.ppas,97 :: 		
;lcd.ppas,98 :: 		
$03D8	$1303			BCF	STATUS, RP1
$03D9	$1283			BCF	STATUS, RP0
$03DA	$01A8			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,99 :: 		
$03DB	$0843			MOVF	FARG_Lcd_Chr_CP, 0
$03DC	$00CC			MOVWF	FARG_Lcd_Cmd
$03DD	$21D3			CALL	_lcd_cmd
;lcd.ppas,100 :: 		
$03DE	$3001			MOVLW	1
$03DF	$00A8			MOVWF	lcd_lcdcmd_status
$03E0	$	lcd_L_48:
;lcd.ppas,101 :: 		
$03E0	$0008			RETURN
$0381	$	_keypad_read:
;keypad_16.ppas,43 :: 		
;keypad_16.ppas,44 :: 		
$0381	$1303			BCF	STATUS, RP1
$0382	$1283			BCF	STATUS, RP0
$0383	$01C3			CLRF	_keypad_read_local_result, 1
;keypad_16.ppas,45 :: 		
$0384	$3010			MOVLW	16
$0385	$00C5			MOVWF	_keypad_read_local_shifter
;keypad_16.ppas,47 :: 		
$0386	$	keypad_16_L_3:
$0386	$0845			MOVF	_keypad_read_local_shifter, 0
$0387	$3C00			SUBLW	0
$0388	$1803			BTFSC	STATUS, C
$0389	$2BAD			GOTO	keypad_16_L_4
;keypad_16.ppas,50 :: 		
$038A	$082A			MOVF	_key_pointer, 0
$038B	$0084			MOVWF	FSR
;keypad_16.ppas,51 :: 		
$038C	$30F0			MOVLW	240
$038D	$0080			MOVWF	INDF
;keypad_16.ppas,53 :: 		
$038E	$	keypad_16_L_7:
$038E	$1784			BSF	FSR, 7
$038F	$	keypad_16_L_8:
;keypad_16.ppas,54 :: 		
$038F	$0945			COMF	_keypad_read_local_shifter, W
$0390	$00F0			MOVWF	STACK_0
$0391	$30FF			MOVLW	255
$0392	$0570			ANDWF	STACK_0, 0
$0393	$0080			MOVWF	INDF
;keypad_16.ppas,55 :: 		
$0394	$23E1			CALL	_delay_10us
;keypad_16.ppas,57 :: 		
$0395	$1384			BCF	FSR, 7
$0396	$	keypad_16_L_10:
;keypad_16.ppas,58 :: 		
$0396	$300F			MOVLW	15
$0397	$0500			ANDWF	INDF, 0
$0398	$00F1			MOVWF	STACK_1
$0399	$0871			MOVF	STACK_1, 0
$039A	$00C4			MOVWF	_keypad_read_local_kdata
;keypad_16.ppas,59 :: 		
$039B	$0871			MOVF	STACK_1, 0
$039C	$3A00			XORLW	0
$039D	$1903			BTFSC	STATUS, Z
$039E	$2BA8			GOTO	keypad_16_L_12
$039F	$	keypad_16_L_11:
;keypad_16.ppas,62 :: 		
$039F	$	keypad_16_L_15:
$039F	$0844			MOVF	_keypad_read_local_kdata, 0
$03A0	$3A00			XORLW	0
$03A1	$1903			BTFSC	STATUS, Z
$03A2	$2BA7			GOTO	keypad_16_L_16
;keypad_16.ppas,64 :: 		
$03A3	$0CC4			RRF	_keypad_read_local_kdata, 1
$03A4	$13C4			BCF	_keypad_read_local_kdata, 7
;keypad_16.ppas,65 :: 		
$03A5	$0AC3			INCF	_keypad_read_local_result, 1
;keypad_16.ppas,66 :: 		
$03A6	$2B9F			GOTO	keypad_16_L_15
$03A7	$	keypad_16_L_16:
;keypad_16.ppas,68 :: 		
$03A7	$2BAE			GOTO	keypad_16_L_1
;keypad_16.ppas,69 :: 		
$03A8	$	keypad_16_L_12:
$03A8	$	keypad_16_L_13:
;keypad_16.ppas,71 :: 		
$03A8	$0DC5			RLF	_keypad_read_local_shifter, 1
$03A9	$1045			BCF	_keypad_read_local_shifter, 0
;keypad_16.ppas,72 :: 		
$03AA	$3004			MOVLW	4
$03AB	$07C3			ADDWF	_keypad_read_local_result, 1
;keypad_16.ppas,73 :: 		
$03AC	$2B86			GOTO	keypad_16_L_3
$03AD	$	keypad_16_L_4:
;keypad_16.ppas,74 :: 		
$03AD	$01C3			CLRF	_keypad_read_local_result, 1
$03AE	$	keypad_16_L_1:
;keypad_16.ppas,75 :: 		
$03AE	$0843			MOVF	_keypad_read_local_result, 0
$03AF	$00F0			MOVWF	STACK_0
$03B0	$0008			RETURN
$034F	$	_lcd_chr:
;lcd.ppas,78 :: 		
;lcd.ppas,80 :: 		
$034F	$	lcd_L_37:
$034F	$1303			BCF	STATUS, RP1
$0350	$1283			BCF	STATUS, RP0
$0351	$0843			MOVF	FARG_Lcd_Chr, 0
$0352	$3A01			XORLW	1
$0353	$1D03			BTFSS	STATUS, Z
$0354	$2B58			GOTO	lcd_L_38
$0355	$	lcd_L_36:
$0355	$3080			MOVLW	128
$0356	$00C3			MOVWF	FARG_Lcd_Chr
$0357	$2B6F			GOTO	lcd_L_35
$0358	$	lcd_L_38:
;lcd.ppas,81 :: 		
$0358	$	lcd_L_40:
$0358	$0843			MOVF	FARG_Lcd_Chr, 0
$0359	$3A02			XORLW	2
$035A	$1D03			BTFSS	STATUS, Z
$035B	$2B5F			GOTO	lcd_L_41
$035C	$	lcd_L_39:
$035C	$30C0			MOVLW	192
$035D	$00C3			MOVWF	FARG_Lcd_Chr
$035E	$2B6F			GOTO	lcd_L_35
$035F	$	lcd_L_41:
;lcd.ppas,82 :: 		
$035F	$	lcd_L_43:
$035F	$0843			MOVF	FARG_Lcd_Chr, 0
$0360	$3A03			XORLW	3
$0361	$1D03			BTFSS	STATUS, Z
$0362	$2B66			GOTO	lcd_L_44
$0363	$	lcd_L_42:
$0363	$3094			MOVLW	148
$0364	$00C3			MOVWF	FARG_Lcd_Chr
$0365	$2B6F			GOTO	lcd_L_35
$0366	$	lcd_L_44:
;lcd.ppas,83 :: 		
$0366	$	lcd_L_46:
$0366	$0843			MOVF	FARG_Lcd_Chr, 0
$0367	$3A04			XORLW	4
$0368	$1D03			BTFSS	STATUS, Z
$0369	$2B6D			GOTO	lcd_L_47
$036A	$	lcd_L_45:
$036A	$30D4			MOVLW	212
$036B	$00C3			MOVWF	FARG_Lcd_Chr
;lcd.ppas,84 :: 		
$036C	$2B6F			GOTO	lcd_L_35
$036D	$	lcd_L_47:
$036D	$3080			MOVLW	128
$036E	$00C3			MOVWF	FARG_Lcd_Chr
$036F	$	lcd_L_35:
;lcd.ppas,86 :: 		
$036F	$0844			MOVF	FARG_Lcd_Chr+1, 0
$0370	$0743			ADDWF	FARG_Lcd_Chr, 0
$0371	$00F0			MOVWF	STACK_0
$0372	$03F0			DECF	STACK_0, 1
$0373	$0870			MOVF	STACK_0, 0
$0374	$00C3			MOVWF	FARG_Lcd_Chr
;lcd.ppas,88 :: 		
$0375	$3001			MOVLW	1
$0376	$00A8			MOVWF	lcd_lcdcmd_status
;lcd.ppas,89 :: 		
$0377	$0870			MOVF	STACK_0, 0
$0378	$00CC			MOVWF	FARG_Lcd_Cmd
$0379	$21D3			CALL	_lcd_cmd
;lcd.ppas,91 :: 		
$037A	$01A8			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,92 :: 		
$037B	$0845			MOVF	FARG_Lcd_Chr+2, 0
$037C	$00CC			MOVWF	FARG_Lcd_Cmd
$037D	$21D3			CALL	_lcd_cmd
;lcd.ppas,93 :: 		
$037E	$3001			MOVLW	1
$037F	$00A8			MOVWF	lcd_lcdcmd_status
$0380	$	lcd_L_34:
;lcd.ppas,94 :: 		
$0380	$0008			RETURN
$03F8	$	_keypad_init:
;keypad_16.ppas,33 :: 		
;keypad_16.ppas,34 :: 		
$03F8	$1303			BCF	STATUS, RP1
$03F9	$1283			BCF	STATUS, RP0
$03FA	$083E			MOVF	FARG_Keypad_Init, 0
$03FB	$00AA			MOVWF	_key_pointer
$03FC	$	keypad_16_L_0:
;keypad_16.ppas,39 :: 		
$03FC	$0008			RETURN
$03E9	$	_init:
;Exercice2.ppas,7 :: 		begin
;Exercice2.ppas,8 :: 		TRISB:=$ff;
$03E9	$30FF			MOVLW	255
$03EA	$1303			BCF	STATUS, RP1
$03EB	$1683			BSF	STATUS, RP0
$03EC	$0086			MOVWF	TRISB
;Exercice2.ppas,9 :: 		TRISD:=$00;
$03ED	$0188			CLRF	TRISD, 1
;Exercice2.ppas,10 :: 		PORTD:=$00;
$03EE	$1283			BCF	STATUS, RP0
$03EF	$0188			CLRF	PORTD, 1
$03F0	$	Exercice2_L_0:
;Exercice2.ppas,11 :: 		end;
$03F0	$0008			RETURN
$03B1	$	_lcd_init:
;lcd.ppas,246 :: 		
;lcd.ppas,247 :: 		
$03B1	$1303			BCF	STATUS, RP1
$03B2	$1283			BCF	STATUS, RP0
$03B3	$083E			MOVF	FARG_Lcd_Init, 0
$03B4	$00C3			MOVWF	FARG_Lcd_Config
$03B5	$3007			MOVLW	7
$03B6	$00C4			MOVWF	FARG_Lcd_Config+1
$03B7	$3006			MOVLW	6
$03B8	$00C5			MOVWF	FARG_Lcd_Config+2
$03B9	$3005			MOVLW	5
$03BA	$00C6			MOVWF	FARG_Lcd_Config+3
$03BB	$3004			MOVLW	4
$03BC	$00C7			MOVWF	FARG_Lcd_Config+4
$03BD	$083E			MOVF	FARG_Lcd_Init, 0
$03BE	$00C8			MOVWF	FARG_Lcd_Config+5
$03BF	$3002			MOVLW	2
$03C0	$00C9			MOVWF	FARG_Lcd_Config+6
$03C1	$01CA			CLRF	FARG_Lcd_Config+7, 1
$03C2	$3003			MOVLW	3
$03C3	$00CB			MOVWF	FARG_Lcd_Config+8
$03C4	$2004			CALL	_lcd_config
$03C5	$	lcd_L_64:
;lcd.ppas,248 :: 		
$03C5	$0008			RETURN
$02CA	$	_lcd_out:
;lcd.ppas,252 :: 		
;lcd.ppas,254 :: 		
$02CA	$	lcd_L_68:
$02CA	$1303			BCF	STATUS, RP1
$02CB	$1283			BCF	STATUS, RP0
$02CC	$083E			MOVF	FARG_Lcd_Out, 0
$02CD	$3A01			XORLW	1
$02CE	$1D03			BTFSS	STATUS, Z
$02CF	$2AD3			GOTO	lcd_L_69
$02D0	$	lcd_L_67:
$02D0	$3080			MOVLW	128
$02D1	$00BE			MOVWF	FARG_Lcd_Out
$02D2	$2AEA			GOTO	lcd_L_66
$02D3	$	lcd_L_69:
;lcd.ppas,255 :: 		
$02D3	$	lcd_L_71:
$02D3	$083E			MOVF	FARG_Lcd_Out, 0
$02D4	$3A02			XORLW	2
$02D5	$1D03			BTFSS	STATUS, Z
$02D6	$2ADA			GOTO	lcd_L_72
$02D7	$	lcd_L_70:
$02D7	$30C0			MOVLW	192
$02D8	$00BE			MOVWF	FARG_Lcd_Out
$02D9	$2AEA			GOTO	lcd_L_66
$02DA	$	lcd_L_72:
;lcd.ppas,256 :: 		
$02DA	$	lcd_L_74:
$02DA	$083E			MOVF	FARG_Lcd_Out, 0
$02DB	$3A03			XORLW	3
$02DC	$1D03			BTFSS	STATUS, Z
$02DD	$2AE1			GOTO	lcd_L_75
$02DE	$	lcd_L_73:
$02DE	$3094			MOVLW	148
$02DF	$00BE			MOVWF	FARG_Lcd_Out
$02E0	$2AEA			GOTO	lcd_L_66
$02E1	$	lcd_L_75:
;lcd.ppas,257 :: 		
$02E1	$	lcd_L_77:
$02E1	$083E			MOVF	FARG_Lcd_Out, 0
$02E2	$3A04			XORLW	4
$02E3	$1D03			BTFSS	STATUS, Z
$02E4	$2AE8			GOTO	lcd_L_78
$02E5	$	lcd_L_76:
$02E5	$30D4			MOVLW	212
$02E6	$00BE			MOVWF	FARG_Lcd_Out
;lcd.ppas,258 :: 		
$02E7	$2AEA			GOTO	lcd_L_66
$02E8	$	lcd_L_78:
$02E8	$3080			MOVLW	128
$02E9	$00BE			MOVWF	FARG_Lcd_Out
$02EA	$	lcd_L_66:
;lcd.ppas,260 :: 		
$02EA	$033F			DECF	FARG_Lcd_Out+1, 0
$02EB	$00F0			MOVWF	STACK_0
$02EC	$083E			MOVF	FARG_Lcd_Out, 0
$02ED	$07F0			ADDWF	STACK_0, 1
$02EE	$0870			MOVF	STACK_0, 0
$02EF	$00BE			MOVWF	FARG_Lcd_Out
;lcd.ppas,261 :: 		
$02F0	$0870			MOVF	STACK_0, 0
$02F1	$00CC			MOVWF	FARG_Lcd_Cmd
$02F2	$21D3			CALL	_lcd_cmd
;lcd.ppas,262 :: 		
$02F3	$01A8			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,263 :: 		
$02F4	$01C1			CLRF	_lcd_out_local_i, 1
;lcd.ppas,264 :: 		
$02F5	$	lcd_L_80:
$02F5	$0841			MOVF	_lcd_out_local_i, 0
$02F6	$0740			ADDWF	FARG_Lcd_Out+2, 0
$02F7	$0084			MOVWF	FSR
$02F8	$0800			MOVF	INDF, 0
$02F9	$00F2			MOVWF	STACK_2
$02FA	$0872			MOVF	STACK_2, 0
$02FB	$3A00			XORLW	0
$02FC	$1903			BTFSC	STATUS, Z
$02FD	$2B06			GOTO	lcd_L_81
;lcd.ppas,266 :: 		
$02FE	$0841			MOVF	_lcd_out_local_i, 0
$02FF	$0740			ADDWF	FARG_Lcd_Out+2, 0
$0300	$0084			MOVWF	FSR
$0301	$0800			MOVF	INDF, 0
$0302	$00C3			MOVWF	FARG_Lcd_Chr_CP
$0303	$23D8			CALL	_lcd_chr_cp
;lcd.ppas,267 :: 		
$0304	$0AC1			INCF	_lcd_out_local_i, 1
;lcd.ppas,268 :: 		
$0305	$2AF5			GOTO	lcd_L_80
$0306	$	lcd_L_81:
;lcd.ppas,269 :: 		
$0306	$3001			MOVLW	1
$0307	$00A8			MOVWF	lcd_lcdcmd_status
$0308	$	lcd_L_65:
;lcd.ppas,270 :: 		
$0308	$0008			RETURN
$027A	$	_saisie:
;Exercice2.ppas,15 :: 		begin
;Exercice2.ppas,17 :: 		for i:=0 to 3 do
$027A	$1303			BCF	STATUS, RP1
$027B	$1283			BCF	STATUS, RP0
$027C	$01C1			CLRF	_saisie_local_i, 1
$027D	$	Exercice2_L_2:
$027D	$0841			MOVF	_saisie_local_i, 0
$027E	$3C03			SUBLW	3
$027F	$1C03			BTFSS	STATUS, C
$0280	$2AC9			GOTO	Exercice2_L_5
;Exercice2.ppas,19 :: 		kp := 0;
$0281	$01C2			CLRF	_saisie_local_kp, 1
;Exercice2.ppas,20 :: 		while kp = 0 do
$0282	$	Exercice2_L_7:
$0282	$0842			MOVF	_saisie_local_kp, 0
$0283	$3A00			XORLW	0
$0284	$1D03			BTFSS	STATUS, Z
$0285	$2A8A			GOTO	Exercice2_L_8
;Exercice2.ppas,21 :: 		kp := Keypad_Read();
$0286	$2381			CALL	_keypad_read
$0287	$0870			MOVF	STACK_0, 0
$0288	$00C2			MOVWF	_saisie_local_kp
$0289	$2A82			GOTO	Exercice2_L_7
$028A	$	Exercice2_L_8:
;Exercice2.ppas,24 :: 		if kp > 10 then
$028A	$0842			MOVF	_saisie_local_kp, 0
$028B	$3C0A			SUBLW	10
$028C	$1803			BTFSC	STATUS, C
$028D	$2A91			GOTO	Exercice2_L_12
$028E	$	Exercice2_L_11:
;Exercice2.ppas,25 :: 		kp := kp + 54
$028E	$3036			MOVLW	54
$028F	$07C2			ADDWF	_saisie_local_kp, 1
$0290	$2A93			GOTO	Exercice2_L_13
;Exercice2.ppas,26 :: 		else
$0291	$	Exercice2_L_12:
;Exercice2.ppas,27 :: 		kp := kp + 47;
$0291	$302F			MOVLW	47
$0292	$07C2			ADDWF	_saisie_local_kp, 1
$0293	$	Exercice2_L_13:
;Exercice2.ppas,28 :: 		T[i]:=kp;
$0293	$0841			MOVF	_saisie_local_i, 0
$0294	$073E			ADDWF	FARG_saisie, 0
$0295	$00F0			MOVWF	STACK_0
$0296	$0870			MOVF	STACK_0, 0
$0297	$0084			MOVWF	FSR
$0298	$0870			MOVF	STACK_0, 0
$0299	$0084			MOVWF	FSR
$029A	$0842			MOVF	_saisie_local_kp, 0
$029B	$0080			MOVWF	INDF
;Exercice2.ppas,29 :: 		Lcd_chr(l,c+i,kp);
$029C	$083F			MOVF	FARG_saisie+1, 0
$029D	$00C3			MOVWF	FARG_Lcd_Chr
$029E	$0841			MOVF	_saisie_local_i, 0
$029F	$0740			ADDWF	FARG_saisie+2, 0
$02A0	$00C4			MOVWF	FARG_Lcd_Chr+1
$02A1	$0842			MOVF	_saisie_local_kp, 0
$02A2	$00C5			MOVWF	FARG_Lcd_Chr+2
$02A3	$234F			CALL	_lcd_chr
;Exercice2.ppas,30 :: 		delay_ms(300);
$02A4	$3004			MOVLW	4
$02A5	$00FC			MOVWF	STACK_12
$02A6	$30FF			MOVLW	255
$02A7	$00FB			MOVWF	STACK_11
$02A8	$30FF			MOVLW	255
$02A9	$00FA			MOVWF	STACK_10
$02AA	$0BFC			DECFSZ	STACK_12, F
$02AB	$2AAD			GOTO	$+2
$02AC	$2AB4			GOTO	$+8
$02AD	$0BFB			DECFSZ	STACK_11, F
$02AE	$2AB0			GOTO	$+2
$02AF	$2AB3			GOTO	$+4
$02B0	$0BFA			DECFSZ	STACK_10, F
$02B1	$2AB0			GOTO	$-1
$02B2	$2AAD			GOTO	$-5
$02B3	$2AAA			GOTO	$-9
$02B4	$3010			MOVLW	16
$02B5	$00FB			MOVWF	STACK_11
$02B6	$30FF			MOVLW	255
$02B7	$00FA			MOVWF	STACK_10
$02B8	$0BFB			DECFSZ	STACK_11, F
$02B9	$2ABB			GOTO	$+2
$02BA	$2ABE			GOTO	$+4
$02BB	$0BFA			DECFSZ	STACK_10, F
$02BC	$2ABB			GOTO	$-1
$02BD	$2AB8			GOTO	$-5
$02BE	$3026			MOVLW	38
$02BF	$00FA			MOVWF	STACK_10
$02C0	$0BFA			DECFSZ	STACK_10, F
$02C1	$2AC0			GOTO	$-1
$02C2	$0000			NOP
;Exercice2.ppas,31 :: 		end;
$02C3	$0841			MOVF	_saisie_local_i, 0
$02C4	$3A03			XORLW	3
$02C5	$1903			BTFSC	STATUS, Z
$02C6	$2AC9			GOTO	Exercice2_L_5
$02C7	$	Exercice2_L_3:
$02C7	$0AC1			INCF	_saisie_local_i, 1
$02C8	$2A7D			GOTO	Exercice2_L_2
$02C9	$	Exercice2_L_5:
$02C9	$	Exercice2_L_1:
;Exercice2.ppas,33 :: 		end;
$02C9	$0008			RETURN
$0309	$	_strcmp:
;StringsLib.ppas,172 :: 		
;StringsLib.ppas,173 :: 		
$0309	$1303			BCF	STATUS, RP1
$030A	$1283			BCF	STATUS, RP0
$030B	$01C2			CLRF	_strcmp_local_i, 1
;StringsLib.ppas,174 :: 		
$030C	$083E			MOVF	FARG_strcmp, 0
$030D	$0084			MOVWF	FSR
$030E	$0800			MOVF	INDF, 0
$030F	$00C0			MOVWF	_strcmp_local_result
$0310	$01C1			CLRF	_strcmp_local_result+1
;StringsLib.ppas,175 :: 		
$0311	$083F			MOVF	FARG_strcmp+1, 0
$0312	$0084			MOVWF	FSR
$0313	$0800			MOVF	INDF, 0
$0314	$00F0			MOVWF	STACK_0
;StringsLib.ppas,176 :: 		
$0315	$3000			MOVLW	0
$0316	$00C1			MOVWF	_strcmp_local_result+1
$0317	$0870			MOVF	STACK_0, 0
$0318	$02C0			SUBWF	_strcmp_local_result, 1
$0319	$1C03			BTFSS	STATUS, C
$031A	$03C1			DECF	_strcmp_local_result+1, 1
;StringsLib.ppas,177 :: 		
$031B	$	StringsLib_L_77:
$031B	$3000			MOVLW	0
$031C	$0641			XORWF	_strcmp_local_result+1, 0
$031D	$1D03			BTFSS	STATUS, Z
$031E	$2B21			GOTO	L_strcmp_8
$031F	$3000			MOVLW	0
$0320	$0640			XORWF	_strcmp_local_result, 0
$0321	$	L_strcmp_8:
$0321	$30FF			MOVLW	255
$0322	$1D03			BTFSS	STATUS, Z
$0323	$3000			MOVLW	0
$0324	$00F3			MOVWF	STACK_3
$0325	$0842			MOVF	_strcmp_local_i, 0
$0326	$073E			ADDWF	FARG_strcmp, 0
$0327	$0084			MOVWF	FSR
$0328	$0800			MOVF	INDF, 0
$0329	$00F2			MOVWF	STACK_2
$032A	$0872			MOVF	STACK_2, 0
$032B	$3A00			XORLW	0
$032C	$30FF			MOVLW	255
$032D	$1903			BTFSC	STATUS, Z
$032E	$3000			MOVLW	0
$032F	$00F0			MOVWF	STACK_0
$0330	$0873			MOVF	STACK_3, 0
$0331	$05F0			ANDWF	STACK_0, 1
$0332	$1903			BTFSC	STATUS, Z
$0333	$2B4A			GOTO	StringsLib_L_78
;StringsLib.ppas,179 :: 		
$0334	$0A42			INCF	_strcmp_local_i, 0
$0335	$00F0			MOVWF	STACK_0
$0336	$0870			MOVF	STACK_0, 0
$0337	$00C2			MOVWF	_strcmp_local_i
;StringsLib.ppas,180 :: 		
$0338	$0870			MOVF	STACK_0, 0
$0339	$073E			ADDWF	FARG_strcmp, 0
$033A	$0084			MOVWF	FSR
$033B	$0800			MOVF	INDF, 0
$033C	$00C0			MOVWF	_strcmp_local_result
$033D	$01C1			CLRF	_strcmp_local_result+1
;StringsLib.ppas,181 :: 		
$033E	$0870			MOVF	STACK_0, 0
$033F	$073F			ADDWF	FARG_strcmp+1, 0
$0340	$0084			MOVWF	FSR
$0341	$0800			MOVF	INDF, 0
$0342	$00F0			MOVWF	STACK_0
;StringsLib.ppas,182 :: 		
$0343	$3000			MOVLW	0
$0344	$00C1			MOVWF	_strcmp_local_result+1
$0345	$0870			MOVF	STACK_0, 0
$0346	$02C0			SUBWF	_strcmp_local_result, 1
$0347	$1C03			BTFSS	STATUS, C
$0348	$03C1			DECF	_strcmp_local_result+1, 1
;StringsLib.ppas,183 :: 		
$0349	$2B1B			GOTO	StringsLib_L_77
$034A	$	StringsLib_L_78:
$034A	$	StringsLib_L_75:
;StringsLib.ppas,184 :: 		
$034A	$0840			MOVF	_strcmp_local_result, 0
$034B	$00F0			MOVWF	STACK_0
$034C	$0841			MOVF	_strcmp_local_result+1, 0
$034D	$00F1			MOVWF	STACK_0+1
$034E	$0008			RETURN
$0123	$	_main:
;Exercice2.ppas,35 :: 		begin
;Exercice2.ppas,36 :: 		Keypad_Init(PORTB);
$0123	$3006			MOVLW	PORTB
$0124	$1303			BCF	STATUS, RP1
$0125	$1283			BCF	STATUS, RP0
$0126	$00BE			MOVWF	FARG_Keypad_Init
$0127	$23F8			CALL	_keypad_init
;Exercice2.ppas,37 :: 		init();
$0128	$23E9			CALL	_init
;Exercice2.ppas,38 :: 		Lcd_init(PORTD);
$0129	$3008			MOVLW	PORTD
$012A	$00BE			MOVWF	FARG_Lcd_Init
$012B	$23B1			CALL	_lcd_init
;Exercice2.ppas,39 :: 		Lcd_Cmd(LCD_CURSOR_OFF);
$012C	$300C			MOVLW	12
$012D	$00CC			MOVWF	FARG_Lcd_Cmd
$012E	$21D3			CALL	_lcd_cmd
;Exercice2.ppas,43 :: 		while 1 do
$012F	$	Exercice2_L_16:
;Exercice2.ppas,45 :: 		Lcd_cmd(LCD_CLEAR);
$012F	$3001			MOVLW	1
$0130	$00CC			MOVWF	FARG_Lcd_Cmd
$0131	$21D3			CALL	_lcd_cmd
;Exercice2.ppas,46 :: 		Lcd_out(1,1,'Entrer code :');
$0132	$3001			MOVLW	1
$0133	$00BE			MOVWF	FARG_Lcd_Out
$0134	$3001			MOVLW	1
$0135	$00BF			MOVWF	FARG_Lcd_Out+1
$0136	$3045			MOVLW	69
$0137	$00B0			MOVWF	?main_Local_Text+0
$0138	$306E			MOVLW	110
$0139	$00B1			MOVWF	?main_Local_Text+1
$013A	$3074			MOVLW	116
$013B	$00B2			MOVWF	?main_Local_Text+2
$013C	$3072			MOVLW	114
$013D	$00B3			MOVWF	?main_Local_Text+3
$013E	$3065			MOVLW	101
$013F	$00B4			MOVWF	?main_Local_Text+4
$0140	$3072			MOVLW	114
$0141	$00B5			MOVWF	?main_Local_Text+5
$0142	$3020			MOVLW	32
$0143	$00B6			MOVWF	?main_Local_Text+6
$0144	$3063			MOVLW	99
$0145	$00B7			MOVWF	?main_Local_Text+7
$0146	$306F			MOVLW	111
$0147	$00B8			MOVWF	?main_Local_Text+8
$0148	$3064			MOVLW	100
$0149	$00B9			MOVWF	?main_Local_Text+9
$014A	$3065			MOVLW	101
$014B	$00BA			MOVWF	?main_Local_Text+10
$014C	$3020			MOVLW	32
$014D	$00BB			MOVWF	?main_Local_Text+11
$014E	$303A			MOVLW	58
$014F	$00BC			MOVWF	?main_Local_Text+12
$0150	$01BD			CLRF	?main_Local_Text+13
$0151	$3030			MOVLW	?main_Local_Text
$0152	$00C0			MOVWF	FARG_Lcd_Out+2
$0153	$22CA			CALL	_lcd_out
;Exercice2.ppas,47 :: 		saisie(T,1,15);
$0154	$302B			MOVLW	_t
$0155	$00BE			MOVWF	FARG_saisie
$0156	$3001			MOVLW	1
$0157	$00BF			MOVWF	FARG_saisie+1
$0158	$300F			MOVLW	15
$0159	$00C0			MOVWF	FARG_saisie+2
$015A	$227A			CALL	_saisie
;Exercice2.ppas,49 :: 		if (strcmp(T,'1234')=0) then
$015B	$302B			MOVLW	_t
$015C	$00BE			MOVWF	FARG_strcmp
$015D	$3031			MOVLW	49
$015E	$00B0			MOVWF	?main_Local_Text+0
$015F	$3032			MOVLW	50
$0160	$00B1			MOVWF	?main_Local_Text+1
$0161	$3033			MOVLW	51
$0162	$00B2			MOVWF	?main_Local_Text+2
$0163	$3034			MOVLW	52
$0164	$00B3			MOVWF	?main_Local_Text+3
$0165	$01B4			CLRF	?main_Local_Text+4
$0166	$3030			MOVLW	?main_Local_Text
$0167	$00BF			MOVWF	FARG_strcmp+1
$0168	$2309			CALL	_strcmp
$0169	$3000			MOVLW	0
$016A	$0671			XORWF	STACK_0+1, 0
$016B	$1D03			BTFSS	STATUS, Z
$016C	$296F			GOTO	L_main_0
$016D	$3000			MOVLW	0
$016E	$0670			XORWF	STACK_0, 0
$016F	$	L_main_0:
$016F	$1D03			BTFSS	STATUS, Z
$0170	$2990			GOTO	Exercice2_L_21
$0171	$	Exercice2_L_20:
;Exercice2.ppas,50 :: 		Lcd_out(2,5,'Code Valide')
$0171	$3002			MOVLW	2
$0172	$00BE			MOVWF	FARG_Lcd_Out
$0173	$3005			MOVLW	5
$0174	$00BF			MOVWF	FARG_Lcd_Out+1
$0175	$3043			MOVLW	67
$0176	$00B0			MOVWF	?main_Local_Text+0
$0177	$306F			MOVLW	111
$0178	$00B1			MOVWF	?main_Local_Text+1
$0179	$3064			MOVLW	100
$017A	$00B2			MOVWF	?main_Local_Text+2
$017B	$3065			MOVLW	101
$017C	$00B3			MOVWF	?main_Local_Text+3
$017D	$3020			MOVLW	32
$017E	$00B4			MOVWF	?main_Local_Text+4
$017F	$3056			MOVLW	86
$0180	$00B5			MOVWF	?main_Local_Text+5
$0181	$3061			MOVLW	97
$0182	$00B6			MOVWF	?main_Local_Text+6
$0183	$306C			MOVLW	108
$0184	$00B7			MOVWF	?main_Local_Text+7
$0185	$3069			MOVLW	105
$0186	$00B8			MOVWF	?main_Local_Text+8
$0187	$3064			MOVLW	100
$0188	$00B9			MOVWF	?main_Local_Text+9
$0189	$3065			MOVLW	101
$018A	$00BA			MOVWF	?main_Local_Text+10
$018B	$01BB			CLRF	?main_Local_Text+11
$018C	$3030			MOVLW	?main_Local_Text
$018D	$00C0			MOVWF	FARG_Lcd_Out+2
$018E	$22CA			CALL	_lcd_out
$018F	$29B2			GOTO	Exercice2_L_22
;Exercice2.ppas,51 :: 		else
$0190	$	Exercice2_L_21:
;Exercice2.ppas,52 :: 		Lcd_out(2,3,'Code Invalide');
$0190	$3002			MOVLW	2
$0191	$00BE			MOVWF	FARG_Lcd_Out
$0192	$3003			MOVLW	3
$0193	$00BF			MOVWF	FARG_Lcd_Out+1
$0194	$3043			MOVLW	67
$0195	$00B0			MOVWF	?main_Local_Text+0
$0196	$306F			MOVLW	111
$0197	$00B1			MOVWF	?main_Local_Text+1
$0198	$3064			MOVLW	100
$0199	$00B2			MOVWF	?main_Local_Text+2
$019A	$3065			MOVLW	101
$019B	$00B3			MOVWF	?main_Local_Text+3
$019C	$3020			MOVLW	32
$019D	$00B4			MOVWF	?main_Local_Text+4
$019E	$3049			MOVLW	73
$019F	$00B5			MOVWF	?main_Local_Text+5
$01A0	$306E			MOVLW	110
$01A1	$00B6			MOVWF	?main_Local_Text+6
$01A2	$3076			MOVLW	118
$01A3	$00B7			MOVWF	?main_Local_Text+7
$01A4	$3061			MOVLW	97
$01A5	$00B8			MOVWF	?main_Local_Text+8
$01A6	$306C			MOVLW	108
$01A7	$00B9			MOVWF	?main_Local_Text+9
$01A8	$3069			MOVLW	105
$01A9	$00BA			MOVWF	?main_Local_Text+10
$01AA	$3064			MOVLW	100
$01AB	$00BB			MOVWF	?main_Local_Text+11
$01AC	$3065			MOVLW	101
$01AD	$00BC			MOVWF	?main_Local_Text+12
$01AE	$01BD			CLRF	?main_Local_Text+13
$01AF	$3030			MOVLW	?main_Local_Text
$01B0	$00C0			MOVWF	FARG_Lcd_Out+2
$01B1	$22CA			CALL	_lcd_out
$01B2	$	Exercice2_L_22:
;Exercice2.ppas,53 :: 		delay_ms(500);
$01B2	$3006			MOVLW	6
$01B3	$00FC			MOVWF	STACK_12
$01B4	$30FF			MOVLW	255
$01B5	$00FB			MOVWF	STACK_11
$01B6	$30FF			MOVLW	255
$01B7	$00FA			MOVWF	STACK_10
$01B8	$0BFC			DECFSZ	STACK_12, F
$01B9	$29BB			GOTO	$+2
$01BA	$29C2			GOTO	$+8
$01BB	$0BFB			DECFSZ	STACK_11, F
$01BC	$29BE			GOTO	$+2
$01BD	$29C1			GOTO	$+4
$01BE	$0BFA			DECFSZ	STACK_10, F
$01BF	$29BE			GOTO	$-1
$01C0	$29BB			GOTO	$-5
$01C1	$29B8			GOTO	$-9
$01C2	$301A			MOVLW	26
$01C3	$00FB			MOVWF	STACK_11
$01C4	$30FF			MOVLW	255
$01C5	$00FA			MOVWF	STACK_10
$01C6	$0BFB			DECFSZ	STACK_11, F
$01C7	$29C9			GOTO	$+2
$01C8	$29CC			GOTO	$+4
$01C9	$0BFA			DECFSZ	STACK_10, F
$01CA	$29C9			GOTO	$-1
$01CB	$29C6			GOTO	$-5
$01CC	$3042			MOVLW	66
$01CD	$00FA			MOVWF	STACK_10
$01CE	$0BFA			DECFSZ	STACK_10, F
$01CF	$29CE			GOTO	$-1
$01D0	$0000			NOP
;Exercice2.ppas,56 :: 		end;
$01D1	$292F			GOTO	Exercice2_L_16
;Exercice2.ppas,57 :: 		end.
$01D2	$29D2			GOTO	$
